### ISSUE TITLE
CheckBox 的说明文字不会展示出来

### ISSUE THREAD

**Issue by Dearest** [alibaba/x-render#1000]
**1.依赖仓库的版本(Dependencies versions)**：

- react：
- form-render：
- table-render:
- antd：

**2.问题描述(Bug description)**：
CheckBox 组件的 description不会生效。
<img width="1120" alt="image" src="https://user-images.githubusercontent.com/7935414/209776358-b8ed3d02-97bc-406c-adfc-6671671e364e.png">
<img width="1049" alt="image" src="https://user-images.githubusercontent.com/7935414/209776514-aa62e2af-5fde-4676-abdc-ec1836622249.png">

**3.最小复现 demo(Reproduction demo)**：
官方文档里的表单设计器即可复现 
https://xrender.fun/generator
schema:
```json
{
  "type": "object",
  "properties": {
    "object_LoiVjg": {
      "title": "对象",
      "type": "object",
      "theme": "collapse",
      "props": {
        "style": {}
      },
      "style": {},
      "properties": {
        "checkbox_r7DE-s": {
          "title": "是否选择",
          "type": "boolean",
          "widget": "checkbox",
          "description": "说明文字",
          "disabled": false,
          "readOnly": false,
          "hidden": false
        }
      }
    }
  },
  "labelWidth": 120,
  "displayType": "column"
}
```

**Comment by lhbxs** [comment]
老的设计器已经不在迭代了，有兴趣的话，可以关注一下讨论组，关于新设计器的迭代和进展，同时也欢迎在讨论里面提想法！
