### ISSUE TITLE
表单设计器中下拉选择组件支持从服务器获取数据并保存到JSON schema中

### ISSUE THREAD

**Issue by VividKevin** [alibaba/x-render#1003]
希望表单设计器在选择下拉选择组件时支持从服务器获取数据并保存到JSON schema中
![image](https://user-images.githubusercontent.com/41005902/210691595-a862747a-b165-4a11-a587-c01d8e001f39.png)

**Comment by VividKevin** [comment]
使用
form.setSchemaByPath('select_BOO-Y6', {
enum: ['east', 'south', 'west', 'north'],
enumNames: ['东', '南', '西', '北'],
})
这样不方便，不同的表单不同的组件我都需要去服务器获取数据并对数据处理后再设置值

**Comment by lirun365** [comment]
框架目前支持这个需求么

**Comment by lhbxs** [comment]
目前不支持
