### ISSUE TITLE
《表单设计器》中新增Events可以动态获取表单配置中的值

### ISSUE THREAD

**Issue by VividKevin** [alibaba/x-render#1004]
### 期望的新功能 (describe the expected new feature)
《表单设计器》中新增Events可以动态获取表单配置中的值
### 简述一下使用场景，便于开发者更好理解新功能的必要性 (describe your scenario for us to understand the need)
现有的onSchemaChange仅能获取组件配置 schema 变化的值，无法获取表单配置变更后第一时间schema中表单配置的值，只能在导出 schema 按钮上查看。希望修改onSchemaChange在表单配置变化时也回调，或者增加新的事件，在表单配置变化时回调

**Comment by lhbxs** [comment]
老的设计器已经不在迭代了，有兴趣的话，可以关注一下讨论组，关于新设计器的迭代和进展，同时也欢迎在讨论里面提想法！
