### ISSUE TITLE
在导出schema时没有order 属性

### ISSUE THREAD

**Issue by ls-2018** [alibaba/x-render#1006]
![image](https://user-images.githubusercontent.com/38821215/211235411-9fabbc62-f484-454f-9571-4b388bd400a9.png)
![image](https://user-images.githubusercontent.com/38821215/211235421-69be3bcd-ac23-442f-8ebb-565648af0c39.png)
![image](https://user-images.githubusercontent.com/38821215/211235442-508b6325-949a-4212-892c-cfd4f1ac235a.png)
 
- react：
- form-render：
- table-render:
- antd：

**2.问题描述(Bug description)**：
在导出schema时没有order 属性
**3.最小复现 demo(Reproduction demo)**：
使用官网提供的表单设计器
 
form-render demo https://codesandbox.io/s/unruffled-flower-jl78h
table-render demo https://codesandbox.io/s/sweet-euler-bdoty
fr-generator demo https://codesandbox.io/s/s13sh

**Comment by lhbxs** [comment]
order字段不是一个必备字段：如果你需要在显示的时候按照特定的顺序展示可以通过order字段调整顺序
