### ISSUE TITLE
props 类型没有暴露出来使用起来不方便

### ISSUE THREAD

**Issue by qiphon** [alibaba/x-render#1007]
### 期望的新功能 (describe the expected new feature)
import { Table,TableRenderProps } from 'table-render';
### 简述一下使用场景，便于开发者更好理解新功能的必要性 (describe your scenario for us to understand the need)
![image](https://user-images.githubusercontent.com/24565078/211302866-8ea49f3d-c446-42c6-8061-3ca111a91568.png)

**Comment by lhbxs** [comment]
1.3.11
