### ISSUE TITLE
图片输入框控件能否直接显示图片

### ISSUE THREAD

**Issue by pccai** [alibaba/x-render#1008]
### 期望的新功能 (describe the expected new feature)
图片输入框控件能否直接显示图片，而不是一个URL地址，比如在只读模式下，直接显示img标签缩略图，类似antd的Upload的图片墙。

### 简述一下使用场景，便于开发者更好理解新功能的必要性 (describe your scenario for us to understand the need)
比如在头像显示，产品缩略图显示，表格列图片直接显示等。

**Comment by lhbxs** [comment]
1.4.8 已添加，通过 schema.imageProps 还可以设置图片组件的props

**Comment by pccai** [comment]
> 1.4.8 已添加，通过 schema.imageProps 还可以设置图片组件的props

1.14.8
