### ISSUE TITLE
2.0.0-alpha.0 antd/es/time-picker/style

### ISSUE THREAD

**Issue by ponkans** [alibaba/x-render#1011]
环境：antd5、vite 

问题：Could not resolve "antd/es/time-picker/style"

解决方案：需手动将 node_modules/form-render/es/widgets/antd/timeRange.js 跟 node_modules/form-render/es/widgets/antd/time.js 中的，import "antd/es/time-picker/style"; 移除

tips：之前支持 antd5 出现过这个问题，2.0.0-rc.0 版本解决了的，2.0.0-alpha.0 版本又出现了

**Comment by lhbxs** [comment]
2.0.0-rc.0 是临时 1.x 兼容 antd v5 的方案

2.0.0-alpha.0  alpha 是 2.x 版本 form-render 重构，目前还在测试阶段，等定了正式版会去兼容 antd V5

**Comment by ponkans** [comment]
> 2.0.0-rc.0 是临时 1.x 兼容 antd v5 的方案
> 
> 2.0.0-alpha.0 alpha 是 2.x 版本 form-render 重构，目前还在测试阶段，等定了正式版会去兼容 antd V5

好的，感谢！

**Comment by hqylss111** [comment]
是不是不能安装最新版本啊？ 要安装1.0？

**Comment by zhaoyanga** [comment]
我使用了2.0.0-rc.0版本，但是我fr-generator的配置有些输入框输入不了，选择框选择不了
