### ISSUE TITLE
search 中 dateRange 组件无法显示选中的值

### ISSUE THREAD

**Issue by qiphon** [alibaba/x-render#1012]
**1.依赖仓库的版本(Dependencies versions)**：

- react：  "react": "^18.2.0",
    "react-dom": "^18.2.0",
- table-render: "table-render": "2.0.0-rc.1",
- antd："antd": "5.1.5",

**2.问题描述(Bug description)**：
dateRange 选中的时间区间无法展示
select 选中的值点击重置无法清空

demo 
https://codesandbox.io/s/installing-and-using-an-npm-module-forked-fdtrdf?file=/src/App.js

**Comment by lhbxs** [comment]
1.0 版本不再继续增加新功能，如果需要适配 antd V5 请升级 2.x 版本
