### ISSUE TITLE
table-render 中的 Search中如何给下拉框动态赋值呢

### ISSUE THREAD

**Issue by pccai** [alibaba/x-render#1018]
### 简述一下使用场景，便于开发者更好理解新功能的必要性 (describe your scenario for us to understand the need)
查询条件中有些select的数据源是动态加载的，能不能像form-render那样直接setSchemaByPath()

**Comment by lhbxs** [comment]
const { form } = UseTable()
通过 form 实例 访问 setSchemaByPath()
