### ISSUE TITLE
【表单解释器】点击组件和拖拽组件展示的id属性不一样

### ISSUE THREAD

**Issue by kexilu** [alibaba/x-render#1019]
1.代码里注明了自定义组件的默认ID
![image](https://user-images.githubusercontent.com/52370722/215319100-4c7b8132-bb91-4c68-aa17-91cd1b3ad6ed.png)
但是通过拖拽选择组件和点击选择出来的组件，ID会有所不同，拖拽出来的组件ID固定为配置的ID，但是点击出来的组件ID会随机给
以下图一是拖拽出来的组件属性，图二是点击出来的组件睡醒，求解

图一
![image](https://user-images.githubusercontent.com/52370722/215319207-6728f4ba-78cd-4df0-bb2d-fa756ca95bd8.png)

图二
![image](https://user-images.githubusercontent.com/52370722/215319239-51e93668-4a6e-4249-a8eb-30079852dbfb.png)

**Comment by lhbxs** [comment]
确实有点小问题，那我改成统一随机吧

**Comment by lhbxs** [comment]
老的设计器已经不在迭代了，有兴趣的话，可以关注一下讨论组，关于新设计器的迭代和进展，同时也欢迎在讨论里面提想法！
