### ISSUE TITLE
nextjs中checkbox和radio的value失效

### ISSUE THREAD

**Issue by cyberbear181** [alibaba/x-render#1024]
**1.依赖仓库的版本(Dependencies versions)**：

- react："17.0.2"
- form-render："2.0.0-rc.0"
- table-render: "latest"
- antd："^5.1.7"
- next:  "12.0.4"

**2.问题描述(Bug description)**：

nextjs中checkbox和radio组件无法选中

**3.最小复现 demo(Reproduction demo)**：

![image](https://user-images.githubusercontent.com/120086676/216284358-c870c78f-25e6-4184-ba80-029e0d0f023a.png)

复现仓库 https://github.com/cyberbear181/xRender-demo.git
form-render demo https://codesandbox.io/s/unruffled-flower-jl78h
table-render demo https://codesandbox.io/s/sweet-euler-bdoty
fr-generator demo https://codesandbox.io/s/s13sh

**Comment by lhbxs** [comment]
1.0 版本不再继续增加新功能，如果需要适配 antd V5 请升级 2.x 版本
