### ISSUE TITLE
数组/对象已经被隐藏了，但数组/对象的子元素依然会被校验

### ISSUE THREAD

**Issue by 21haoxingxiu** [alibaba/x-render#1030]
**1.依赖仓库的版本(Dependencies versions)**：

- react：
- form-render：1.13.14
- table-render:
- antd：

**2.问题描述(Bug description)**：

我看这个问题还在 

**3.最小复现 demo(Reproduction demo)**：

form-render demo https://codesandbox.io/s/unruffled-flower-jl78h
table-render demo https://codesandbox.io/s/sweet-euler-bdoty
fr-generator demo https://codesandbox.io/s/s13sh

**Comment by lhbxs** [comment]
如果不校验的话，那数据提交的时候，是否要去掉？

**Comment by 21haoxingxiu** [comment]
> 如果不校验的话，那数据提交的时候，是否要去掉？

隐藏的数据，提交的时候应该要去掉

**Comment by lhbxs** [comment]
你升级下最新版看看，不会保留隐藏的数据了

**Comment by lhbxs** [comment]
看是否还会触发校验

**Comment by 21haoxingxiu** [comment]
> 看是否还会触发校验

1.14.0版本吗 昨天升级试了下 还是不行的

**Comment by 21haoxingxiu** [comment]
> 你升级下最新版看看，不会保留隐藏的数据了

提交的时候数据是隐藏的 但是还是会校验。

**Comment by lhbxs** [comment]
OK，这个我看下

**Comment by lhbxs** [comment]
我看了你的例子，隐藏了输入框，可以正常提交呢

**Comment by lhbxs** [comment]
https://user-images.githubusercontent.com/43236919/217750859-2fe22242-dbc2-4c95-8186-02e16a6fe130.mov

**Comment by lhbxs** [comment]
1.14.12
