### ISSUE TITLE
form-render支持标题样式定义

### ISSUE THREAD

**Issue by qlly0630** [alibaba/x-render#1031]
### 期望的新功能 (describe the expected new feature)
form-render支持标题样式定义
### 简述一下使用场景，便于开发者更好理解新功能的必要性 (describe your scenario for us to understand the need)
如果表单是只读状态，视觉上标题和值不太好区分
<img width="210" alt="image" src="https://user-images.githubusercontent.com/96567362/217445947-eae6b95c-ea7d-4255-93cc-2e3cace3ffda.png">

**Comment by lhbxs** [comment]
.fr-label-column 
.fr-label-title 
.no-colon

项目工程里面复写样式就好了吧
