### ISSUE TITLE
fr-generator 不支持antd5

### ISSUE THREAD

**Issue by cyberbear181** [alibaba/x-render#1037]
### 简述一下使用场景，便于开发者更好理解新功能的必要性 (describe your scenario for us to understand the need)

需要fr-generator 支持antd5

**Comment by lhbxs** [comment]
新功能指的是？

**Comment by cyberbear181** [comment]
> 新功能指的是？

感谢回复，其实我就是想了解有计划支持nextjs吗？

**Comment by imeime** [comment]
"fr-generator": "^2.8.4",
"antd": "^5.1.7",
版本兼容报错 Error: Can't resolve 'antd/es/time-picker/style'

**Comment by lhbxs** [comment]
目前 fr-generator 还没有计划支持 antd 5，fr-generator 计划重构，重构之后会考虑。依次步骤是 form-render -> table-render -> fr-generator
