### ISSUE TITLE
 mapping 配置无效，2.0.0 正式版

### ISSUE THREAD

**Issue by ychost** [alibaba/x-render#1039]
**1.依赖仓库的版本(Dependencies versions)**：

- react：18.2.0
- form-render：2.0.0
- table-render:-
- antd：5.2.1

**2.问题描述(Bug description)**：
mapping 无效

**3.最小复现 demo(Reproduction demo)**：
教程给的 Demo

**Comment by lhbxs** [comment]
感觉mapping那个配置没啥用，现在是什么功能无法实现？

**Comment by lhbxs** [comment]
外部透传的 widgets 如果和内部名字一样会覆盖内部组件，感觉这样就达到了 mapping的作用吧
