### ISSUE TITLE
validateFields传path[]无效

### ISSUE THREAD

**Issue by wangxinyu666666** [alibaba/x-render#1040]
<img width="262" alt="image" src="https://user-images.githubusercontent.com/26834996/219025577-76da9893-3744-46dc-a357-4ec44925c3a6.png">
validateFields传path，只想对某些字段进行校验，但是打印出的error仍然是全局校验结果。确认路径传的没有问题。
<img width="328" alt="image" src="https://user-images.githubusercontent.com/26834996/219025856-824cac28-053f-4b55-9e5a-0b2d2f62f70b.png">
用的form-render 2.0.0版本

**Comment by lhbxs** [comment]
import React from 'react';
import FormRender, { useForm } from 'form-render';
import { Button } from 'antd';

const schema = {
  type: 'object',
  properties: {
    input1: {
      title: '简单输入框',
      type: 'string',
      required: true,
    },
    select1: {
      title: '单选',
      type: 'string',
      required: true,
      props: {
        options: [
          { label: '早', value: 'a' },
          { label: '中', value: 'b' },
          { label: '晚', value: 'c' }
        ]
      }
    }
  }
};

export default () => {
  const form = useForm();

  const onValidateFields = () => {
    form.validateFields(['input1'])
    .then(values => {
      console.log(values, 'values');
    })
    .catch(errors => {
      console.log(errors, 'errors');
    });
  }

  return (
    <>
      <FormRender 
        form={form} 
        schema={schema} 
        displayType='row' 
      />
      <div>
        <Button onClick={onValidateFields}>validateFields Test</Button>
      </div>
    </>
  );
}

**Comment by lhbxs** [comment]
<img width="751" alt="截屏2023-02-16 下午4 19 54" src="https://user-images.githubusercontent.com/43236919/219307690-c1e6bf95-0cc0-4efc-bf62-4805f8e934dc.png">

**Comment by lhbxs** [comment]
我试了下没有问题呢

**Comment by lhbxs** [comment]
![5CD41ED1-39DC-4329-9ABB-1F36B93F3EAC](https://user-images.githubusercontent.com/43236919/219308186-c0b943d5-de59-4297-8f27-01cf384f5fbe.png)

**Comment by lhbxs** [comment]
你 antd 依赖的版本是？晒一下你的schema?

**Comment by wangxinyu666666** [comment]
> 你 antd 依赖的版本是？晒一下你的schema?

antd 4.24.6

schema = {
	"type": "object",
	"$schema": "http://json-schema.org/draft-04/schema#",
	"required": [
		"paramStr",
		"paramInt"
	],
	"properties": {
		"paramInt": {
			"type": "integer",
			"title": "策略参数2"
		},
		"paramStr": {
			"type": "string",
			"title": "策略参数1"
		}
	}
}

是不是required不应该写在外面？
