### ISSUE TITLE
2.0 版本 组件拿不到全局globalProps

### ISSUE THREAD

**Issue by gdc1998** [alibaba/x-render#1042]
**1.依赖仓库的版本(Dependencies versions)**：

- react：
- form-render：
- table-render:
- antd：

**2.问题描述(Bug description)**：

**3.最小复现 demo(Reproduction demo)**：

form-render demo https://codesandbox.io/s/unruffled-flower-jl78h
table-render demo https://codesandbox.io/s/sweet-euler-bdoty
fr-generator demo https://codesandbox.io/s/s13sh

**Comment by lhbxs** [comment]
什么场景要用到这个 globalProps ? 通过 setSchemaByPath 不行吗？

**Comment by lhbxs** [comment]
加上了，但是为了避免污染其他组件，需要自己在组件里面进行 globalProps 解构

**Comment by gdc1998** [comment]
> 什么场景要用到这个 globalProps ? 通过 setSchemaByPath 不行吗？
现在接入了很多自定义组件，自定义组件依赖全局一个状态切换，

**Comment by lhbxs** [comment]
现在直接把globalProps透传给自定义组件了，需要自行处理下
