### ISSUE TITLE
列表自定义添加动作获取schema不全

### ISSUE THREAD

**Issue by ThiefTMBadBad** [alibaba/x-render#1045]
**1.依赖仓库的版本(Dependencies versions)**：

- form-render：1.14.10
- antd：4.x

**2.问题描述(Bug description)**：
https://xrender.fun/form-render/advanced/list-display 展示的自定义 onAdd(添加)，获取到的schema不全

例如：
{"title":"配件","type":"array","widget":"list2","items":{"type":"object","properties":{}},"props":{"onAdd":"addFunc","onRemove":"removeFunc","hideMove":true},"$id":"list2_-mlhIE[]"}

properties下的数据会丢失

**3.最小复现 demo(Reproduction demo)**：
示例即可复现

**Comment by lhbxs** [comment]
父级不会保留子节点的 schma，在顶层解析的时候已经拉平了。你可以通过 getSchemaByPath 获取完整 schema
