### ISSUE TITLE
type写成其他类型时，抛错，页面空白

### ISSUE THREAD

**Issue by wangxinyu666666** [alibaba/x-render#1046]
schema = {
  type: 'object',
  displayType: 'row',
  title: 'schema中嵌入一块区域，通过widget传入用户自定义的内容',
  properties: {
    guide: {
      type: 'block1',
      widget: 'siteBlock',
    },
  },
}
<img width="473" alt="image" src="https://user-images.githubusercontent.com/26834996/220064101-44ce797a-becc-4da6-a187-afbcd5816b4f.png">
发现只有widget是自定义组件时，type写成其他类型会报错。按理说不应该抛错，应该兼容判断一下。

**Comment by lhbxs** [comment]
什么版本

**Comment by wangxinyu666666** [comment]
> 什么版本

https://github.com/alibaba/x-render/issues/1046#issuecomment-1437052451

**Comment by wangxinyu666666** [comment]
> 

1.14.14

**Comment by lhbxs** [comment]
<img width="1055" alt="截屏2023-02-23 上午11 07 03" src="https://user-images.githubusercontent.com/43236919/220849601-636eb80d-fafd-4b5f-a15c-e03e55fff298.png">

**Comment by lhbxs** [comment]
并没有报错呢

**Comment by lhbxs** [comment]
<img width="1782" alt="截屏2023-02-23 下午3 52 33" src="https://user-images.githubusercontent.com/43236919/220849756-2ffc61cd-8b4f-4707-86ca-dc6291165549.png">
