### ISSUE TITLE
formRender表单实例useForm()无法传入参数

### ISSUE THREAD

**Issue by RyzenPan** [alibaba/x-render#1048]
**1.依赖仓库的版本(Dependencies versions)**：

- react：18.2.0
- form-render：2.0.2
- table-render:
- antd：5.2.2

**2.问题描述(Bug description)**：

ts描述：
(alias) useForm(): FormInstance
import useForm

代码：
const form = **useForm**({
  logOnMount: (info) => {
    console.log('onMount', info);
  },
  logOnSubmit: (info) => {
    console.log('onSubmit', info);
  },
});

![image](https://user-images.githubusercontent.com/56830619/220501400-e83c8e61-ed73-4c2d-ba5a-c1602ef949e9.png)

**Comment by lhbxs** [comment]
这个新版里面，还没有加，我给加一下，以后通过 props 透传

**Comment by lhbxs** [comment]
有一个疑问，如果同一个页面用了两个表单，感觉日志会被覆盖掉

**Comment by lhbxs** [comment]
form-render 2.0.8-beta.2
