### ISSUE TITLE
1.14.14版本removeErrorField无效。。。

### ISSUE THREAD

**Issue by wangxinyu666666** [alibaba/x-render#1054]
1.14.14版本removeErrorField不起作用

**Comment by lhbxs** [comment]
你试试这个，可以的。

**Comment by lhbxs** [comment]
或者把你的场景说清楚一些

**Comment by Alpsli** [comment]
+1，通过 setErrorFields 的 errors 通过 removeErrorField 清不掉

**Comment by Alpsli** [comment]
![image](https://user-images.githubusercontent.com/52439609/222895719-090c9e70-c07f-402c-ac2d-710a66d7ee7c.png)
