### ISSUE TITLE
TableRender的loading状态不准确

### ISSUE THREAD

**Issue by RyzenPan** [alibaba/x-render#1055]
**1.依赖仓库的版本(Dependencies versions)**：

react：18.2.0
form-render：2.0.5
table-render: 2.0.3
antd：5.2.2

**2.问题描述(Bug description)**：
表格组件首次加载没有显示loading，点击查询等操作也没有出现loading，只有切换tab的时候才有，官网的demo也是这样的

**3.最小复现 demo(Reproduction demo)**：

form-render demo https://codesandbox.io/s/unruffled-flower-jl78h
table-render demo https://codesandbox.io/s/sweet-euler-bdoty
fr-generator demo https://codesandbox.io/s/s13sh

**Comment by lhbxs** [comment]
table-render 先装 2.0.7-beta.2
