### ISSUE TITLE
2.x版本 FormRender传入form报错

### ISSUE THREAD

**Issue by uuzpid** [alibaba/x-render#1060]
**1.依赖仓库的版本(Dependencies versions)**：

- react：17.0.2
- form-render：2.0.6 | 2.0.8
- antd：4.17.2

**2.问题描述(Bug description)**：
报错提示是antd_es_form__WEBPACK_IMPORTED_MODULE_5__.default.useFormInstance is not a function
怀疑是否是antd版本不兼容
**3.最小复现 demo(Reproduction demo)**：
const Demo = () => {
  const form = useForm();
  return (
     返回一个FormRender 传入form参数 就会报错
  );

form-render demo https://codesandbox.io/s/unruffled-flower-jl78h
table-render demo https://codesandbox.io/s/sweet-euler-bdoty
fr-generator demo https://codesandbox.io/s/s13sh

**Comment by lhbxs** [comment]
是的用到了 useFormInstance 这个 API, antd 4.20版本才有，你们项目 antd 版本也是锁定的吗？

**Comment by lhbxs** [comment]
需要升级 antd 版本到
