### ISSUE TITLE
希望有类似setValues的api  可以追加数据   而不是全表单覆盖数据

### ISSUE THREAD

**Issue by Jocelyn329** [alibaba/x-render#1064]
**希望有类似setValues的api  可以追加数据   而不是全表单覆盖数据**
场景
有时候做字段联动修改的时候 一次性会修改比较多的值 

- 如果用setValueByPath 需要循环 而且有的表格内path嵌套较深 不好拿
- 如果用setValues的话  可能造成输入过快产生覆盖行为或延迟

比如 表单项文本类A 数据 onChange，再处理新数据，然后 setValues  ，此时会对表单项A进行重置 因为输入很快 会不断走onChange 但是 处理数据再setValues 存在时间差，此时会产生覆盖行为
如果加上防抖再去做setValues又会产生延迟行为
所以 希望能有新的api 方便一次追加多条数据

**Comment by lhbxs** [comment]
你这个追加数据，我理解可以 通过 getValues 批量修改好，在 setValues吧
