### ISSUE TITLE
占位空白位空位

### ISSUE THREAD

**Issue by wahello** [alibaba/x-render#1067]
### 期望的新功能 (describe the expected new feature)
占位空白位空位
```
    input__vp7_b: {
      type: 'blank',
      width: '100%'
    },
```

### 简述一下使用场景，便于开发者更好理解新功能的必要性 (describe your scenario for us to understand the need)
主要为了排版,美观

**Comment by lhbxs** [comment]
使用版本号，效果截图

**Comment by lhbxs** [comment]
input__vp7_b: {
      type: 'void',
     "widget": "自己定义"
    },
