### ISSUE TITLE
format为dateTime时选择时间报错

### ISSUE THREAD

**Issue by The-planet** [alibaba/x-render#1071]
**1.依赖仓库的版本(Dependencies versions)**：

- react："^17.0.2",
- form-render："^2.0.11",
- table-render:"^2.0.9",
- antd："^4.18.9",

**2.问题描述(Bug description)**：
使用生成器拖拽form生成schema，在代码里选择时间报错
<img width="561" alt="image" src="https://user-images.githubusercontent.com/38370716/223398155-1fa36929-4da6-4bc5-80d1-0c310b2fe70a.png">

**3.最小复现 demo(Reproduction demo)**：
const schema = {
  type: 'object',

  properties: {
    date_srCPLa: {
      title: '时间',
      type: 'string',
      format: 'dateTime',
      required: true,
    },
  },
};
 <FormRender form={form} schema={schema} onFinish={onFinish} fieldCol={8} />

form-render demo https://codesandbox.io/s/unruffled-flower-jl78h
table-render demo https://codesandbox.io/s/sweet-euler-bdoty
fr-generator demo https://codesandbox.io/s/s13sh

**Comment by lhbxs** [comment]
是使用 form-render 报错？还是 在表单设计器里面？我看官网都是好的呢

**Comment by The-planet** [comment]
使用form-render报错

**Comment by lhbxs** [comment]
奇怪了，antd 依赖装的什么版本

**Comment by lhbxs** [comment]
你自己项目有没有装dayjs呢？

**Comment by lhbxs** [comment]
装了的化，dayjs 版本是多少？

**Comment by The-planet** [comment]
> 装了的化，dayjs 版本是多少？

antd: "^4.18.9",

自己的项目没有装dayjs，但是依赖的库有用到ahooks，ahooks依赖了dayjs。
使用yarn来管理的项目，yarn.lock里ahooks依赖dayjs@^1.9.1这个版本的。form-render的依赖是dayjs "^1.11.7"。这会有冲突吗？

**Comment by The-planet** [comment]
> > 装了的化，dayjs 版本是多少？
> 
> antd: "^4.18.9",
> 
> 自己的项目没有装dayjs，但是依赖的库有用到ahooks，ahooks依赖了dayjs。 使用yarn来管理的项目，yarn.lock里ahooks依赖dayjs@^1.9.1这个版本的。form-render的依赖是dayjs "^1.11.7"。这会有冲突吗？

ahooks,版本，"^3.3.0"

**Comment by lhbxs** [comment]
https://github.com/ant-design/ant-design/issues/26190#issuecomment-761731229
试试这个

**Comment by The-planet** [comment]
> [ant-design/ant-design#26190 (comment)](https://github.com/ant-design/ant-design/issues/26190#issuecomment-761731229) 试试这个

感谢～ 按照这个步骤已经解决了。看来确实是两个dayjs的问题
