### ISSUE TITLE
表单设计器有上传功能吗？

### ISSUE THREAD

**Issue by mac-boss** [alibaba/x-render#1072]
### 期望的新功能 (describe the expected new feature)

表单需要上传文件、图片功能，发现例子上没有这个功能

**Comment by lhbxs** [comment]
uploader: {
            title: '上传文件',
            type: 'string',
            format: 'upload',
            props: {
              action: 'https://www.mocky.io/v2/5cc8019d300000980a055e76',
            },
          },
