### ISSUE TITLE
widget的rules字段下的validator

### ISSUE THREAD

**Issue by andelio** [alibaba/x-render#1073]
Form-render下的widget的rules字段下的validator方法能不能像antd的form一样提供回调函数callback，支持自定义的message内容或者支持返回Promise?
https://zhuanlan.zhihu.com/p/69802122?utm_id=0

**Comment by lhbxs** [comment]
你使用的是1.x，还是2.x

**Comment by andelio** [comment]
2.0.11版本

**Comment by lhbxs** [comment]
2.x 是支持的吧，你看看 https://xrender.fun/form-render/advanced-validate

**Comment by andelio** [comment]
2.x支持，但是validate方式只能返回true和false，我想返回动态message信息，没有效果
![Uploading 12B5B2EA-8BF3-4151-86E0-84B31D1CF71B.png…]()

**Comment by lhbxs** [comment]
支持返回一个 { status: true/ false , message: '错误信息' }，用于动态设置 message

新版已经发布

**Comment by andelio** [comment]
按照对象的格式返回了，但是提示信息显示“messgae” is read-only
不是我定义的信息内容，是不是内部加了判断，不允许修改？
