### ISSUE TITLE
Widgets的日期的dependencies给加一下

### ISSUE THREAD

**Issue by andelio** [alibaba/x-render#1089]
日期依赖的dependencies没有响应，麻烦给加一下，业务用到了日期间的联动
![image](https://user-images.githubusercontent.com/45022165/224884753-582c3e5e-b3c9-486e-8f5f-bbccf5d852b4.jpg)

**Comment by lhbxs** [comment]
使用的是1.x 还是 2.x

**Comment by andelio** [comment]
2.x的，日期好像没有高阶函数

**Comment by lhbxs** [comment]
这个图片文件是你自己的？

**Comment by lhbxs** [comment]
什么样的联动场景，没有实现。能贴一下schema吗

**Comment by andelio** [comment]
这个是form-render的源码，我去nodemodules包里看的。我在我代码上schema的日期组件(内置)加dependencies没有效果

**Comment by lhbxs** [comment]
我看看你的schema

**Comment by andelio** [comment]
![Uploading 462AF1E4-F47F-4670-A6AF-C16FD054BC42.jpeg…]()

**Comment by andelio** [comment]
![Uploading image.jpg…]()

**Comment by andelio** [comment]
您能看到图片吗？
![Uploading image.jpg…]()

**Comment by lhbxs** [comment]
不能

**Comment by andelio** [comment]
![image](https://user-images.githubusercontent.com/45022165/224905887-bfdcacb7-2da2-4f38-b11e-f25077cf65f5.jpg)

**Comment by andelio** [comment]
大概结构是这样的，电脑不能传数据，只能拍照了，您勉强看一下，用了date组件，string:month

**Comment by lhbxs** [comment]
你要一个怎样的联动效果？

**Comment by lhbxs** [comment]
A、B 组件都是 form-render 内置组件，还是你这边自定义的组件，dependencies 准确来说会触发更新，并不是重新渲染。相关会传递 dependValue。

**Comment by andelio** [comment]
A,B组件都是form-render内置组件，自定义组件的模式是没有问题的。场景就是A组件依赖B组件，B组件的值发生变化，A组件之前判断的规则需要重新触发一下

**Comment by lhbxs** [comment]
Uploading 屏幕录制2023-03-16 上午12.51.37.mov…

**Comment by lhbxs** [comment]
你可以更新最新的包，再看看

**Comment by andelio** [comment]
好的，麻烦您了
