### ISSUE TITLE
select中的options 传入数组变量，会被解析成字符串报错

### ISSUE THREAD

**Issue by 21haoxingxiu** [alibaba/x-render#1098]
**1.依赖仓库的版本(Dependencies versions)**：

- react：
- form-render：
- table-render:
- antd：

**2.问题描述(Bug description)**：
场景:
需要动态切换select的options 使用 `{{ formData.week ? ${weekOption} : ${monthOption} }}` 报错

是否有更优雅的处理方式
**3.最小复现 demo(Reproduction demo)**：

form-render demo https://codesandbox.io/s/unruffled-flower-jl78h
table-render demo https://codesandbox.io/s/sweet-euler-bdoty
fr-generator demo https://codesandbox.io/s/s13sh

**Comment by lhbxs** [comment]
从来都不支持这种语法吧，它是函数表达事，weekOption，monthOption 是变量，获取不到的

**Comment by lhbxs** [comment]
https://xrender.fun/form-render/advanced-linkage#%E4%BF%AE%E6%94%B9%E8%A1%A8%E5%8D%95%E9%A1%B9-schema 通过这种方式结合 watch 监听 week 变化修改
