### ISSUE TITLE
x-render 1.x 的项目文档打不开了

### ISSUE THREAD

**Issue by 21haoxingxiu** [alibaba/x-render#1099]
**1.依赖仓库的版本(Dependencies versions)**：

- react：
- form-render：
- table-render:
- antd：

**2.问题描述(Bug description)**：
如题： 目前项目还是基于1.x， 希望文档能继续访问。
**3.最小复现 demo(Reproduction demo)**：

form-render demo https://codesandbox.io/s/unruffled-flower-jl78h
table-render demo https://codesandbox.io/s/sweet-euler-bdoty
fr-generator demo https://codesandbox.io/s/s13sh

**Comment by lhbxs** [comment]
国外转发的可能有点慢吧，开个加速看看

**Comment by 21haoxingxiu** [comment]
> 

开了vpn   google能正常访问， 但1.x文档还是访问不了，这对老用户不太友好啊。
