### ISSUE TITLE
设计器如何嵌入到antd5.x的项目中

### ISSUE THREAD

**Issue by qiaojianfeng** [alibaba/x-render#1102]
**1.依赖仓库的版本(Dependencies versions)**：

- react：
- form-render：
- table-render:
- antd：5.1.7
- "fr-generator：2.8.5

**2.问题描述(Bug description)**：
To install it, you can run: npm install --save antd/es/time-picker/style

ERROR in ./node_modules/.pnpm/form-render@1.14.15_antd@5.1.7/node_modules/form-render/es/widgets/antd/time.js
Module not found: Error: Can't resolve 'antd/es/time-picker/style' in 'E:\dev\Git\costrip-lib-components\node_modules\.pnpm\form-render@1.14.15_antd@5.1.7\node_modules\form-render\es\widgets\antd'
 @ ./node_modules/.pnpm/form-render@1.14.15_antd@5.1.7/node_modules/form-render/es/widgets/antd/time.js

**Comment by wjm0913** [comment]
嗯，我也遇到了！

**Comment by lhbxs** [comment]
当前设计器和 form-render 1.x 版本耦合严重。不支持 antd 5 兼容，新设置器正在规划

**Comment by wx9999** [comment]
> 当前设计器和 form-render 1.x 版本耦合严重。不支持 antd 5 兼容，新设置器正在规划
> 
> Current designer and form-render 1.0. The X version is heavily coupled. ANTD 5 compatibility is not supported and the new setup is being planned

请问大概什么时候更新出来呢

**Comment by guoqingshuai** [comment]
请问大约什么时候修复好

**Comment by jeffreyWang9983** [comment]
预计什么时候才支持antd5呢？

**Comment by ChinaGrayMan** [comment]
请问一下大概什么时候支持antd5

**Comment by beeant0512** [comment]
可以看看这个项目 支持 x-render的schema
https://xbeeant.github.io/nexus-form-engine
