### ISSUE TITLE
【form-render】中widgets文件下的html.jsx组件代码错误

### ISSUE THREAD

**Issue by yuanbaojin123** [alibaba/x-render#1106]
**问题描述(Bug description)**：
- https://xrender.fun/form-render/disaply-row#drawerlist
- form-render文档中的DrawerList示例，插入数据时，最后一项单选选择中，但是点击确认只有表格展示中显示的是早。

**问题原因(Bug reason)**：
- html.jsx是readonly时表单展示的组件，代码中发现options.find遍历时使用了item.value=value,正确应该是使用三等。

**Comment by lhbxs** [comment]
先发个 beta版，2.0.19-beta.1
