### ISSUE TITLE
使用table-render 2.x是报错Object(...) is not a function

### ISSUE THREAD

**Issue by xCCCyC** [alibaba/x-render#1109]
**1.依赖仓库的版本(Dependencies versions)**：

- react：17.0.2
- form-render：2.0.18
- table-render: 2.0.14
- antd：4.24.8

**2.问题描述(Bug description)**：
在上述环境下，使用tabel-render或者form-render报错，出现的错误都是
![image](https://user-images.githubusercontent.com/74956899/226857016-f535eaaa-ffa3-43bc-ae06-5b559d69cb10.png)
table-render使用的是文档中的”最简demo“
<img width="1348" alt="image" src="https://user-images.githubusercontent.com/74956899/226857310-51b08352-b6e5-4ba8-a136-e764405eea39.png">
form-render使用的是文档中的”使用方法“
<img width="961" alt="image" src="https://user-images.githubusercontent.com/74956899/226857442-3ab08ced-0f07-45e0-9300-056b8f7166e5.png">

**3.最小复现 demo(Reproduction demo)**：

form-render demo https://codesandbox.io/s/unruffled-flower-jl78h
table-render demo https://codesandbox.io/s/sweet-euler-bdoty
fr-generator demo https://codesandbox.io/s/s13sh

**Comment by lhbxs** [comment]
form-render 也有问题吗？

**Comment by lhbxs** [comment]
你仓库里面有弄这个zustand库吗？

**Comment by lhbxs** [comment]
"zustand": "4.1.5"， 这个好像要锁个版本

**Comment by xCCCyC** [comment]
> zustand

那我试试看
