### ISSUE TITLE
一行多列的时候 编辑区域没有全部展示

### ISSUE THREAD

**Issue by dengying918** [alibaba/x-render#1111]
表单配置一行多列的时候 编辑区域没有全部展示完全 变成了1/列数

**Comment by lhbxs** [comment]
你说的是表单设置器？

**Comment by dengying918** [comment]
是的

**Comment by dengying918** [comment]
> 你说的是表单设置器？

是的

**Comment by dengying918** [comment]
> 你说的是表单设置器？

是的，那个setting 面板展开收缩后  设计里面的内容默认就变成了一行一列

**Comment by lhbxs** [comment]
好的，我们排查下，你可以先降一个版本看看

**Comment by YoungLetter** [comment]
您好，我也同样遇到这个问题，会不会是因为预览区也是被formrender包裹导致设置一行多列的时候，预览区整个被当成一列，然后被设置成一行多列
![image](https://user-images.githubusercontent.com/62873032/229997283-44ef33e7-1c1d-46aa-ab78-bffa55ee0813.png)
![image](https://user-images.githubusercontent.com/62873032/229997406-eee59807-76ff-42fc-92ee-bbc7ea9c8041.png)
@lhbxs

**Comment by zxc-github-0201** [comment]
> 您好，我也同样遇到这个问题，会不会是因为预览区也是被formrender包裹导致设置一行多列的时候，预览区整个被当成一列，然后被设置成一行多列 ![image](https://user-images.githubusercontent.com/62873032/229997283-44ef33e7-1c1d-46aa-ab78-bffa55ee0813.png) ![image](https://user-images.githubusercontent.com/62873032/229997406-eee59807-76ff-42fc-92ee-bbc7ea9c8041.png) @lhbxs

暂时可通过引入一个样式修改文件修复，修改样式如下：
`.dnd-container > .field-wrapper {
  width: 100% !important;
}`

**Comment by lhbxs** [comment]
已修复

**Comment by jokyczq** [comment]
![image](https://user-images.githubusercontent.com/73460759/233586882-41ba58da-4871-4fab-a1e1-eb9960cdf6b7.png)

@Ihbxs 升到2.1.12版本还是会有这个问题

**Comment by jokyczq** [comment]
> 已修复

![image](https://user-images.githubusercontent.com/73460759/233587600-8a88d075-b4d7-49d6-bd1c-b61426bab362.png)


@lhbxs 大佬，升级到2.1.12还是会有这个问题

**Comment by lhbxs** [comment]
升级编辑器的版本，不是 form-render 的
