### ISSUE TITLE
如何支持进行删隔栏的支持

### ISSUE THREAD

**Issue by wenjianzhang** [alibaba/x-render#1113]
### 期望的新功能 (describe the expected new feature)

希望支持删隔栏

### 简述一下使用场景，便于开发者更好理解新功能的必要性 (describe your scenario for us to understand the need)

再编辑表单时，一般会有一行多列的情况，但并不是整个表单同时被设置的场景；

例如：

line1: 文本框
line2: 下啦框 文本框 单选框
line3: 文本框 单选框

如果已经支持，麻烦告知一下用法谢谢

**Comment by lhbxs** [comment]
升级一下最新版本，然后看下这个 https://xrender.fun/form-render/advanced-layout#span
