### ISSUE TITLE
ListSimple

### ISSUE THREAD

**Issue by zflhcc** [alibaba/x-render#1117]
ListSimple不支持编辑吗？
ListSimple新增时支持一个字段改变，去请求另外一个字段的值在渲染？
![image](https://user-images.githubusercontent.com/25218359/227879260-81be177f-06aa-422a-8b37-ba80be63f955.png)

**Comment by lhbxs** [comment]
具体是怎么操作的？

**Comment by lhbxs** [comment]
能说的是详细一点吗？具体要实现什么效果，

**Comment by zflhcc** [comment]
![image](https://user-images.githubusercontent.com/25218359/228171299-bf7b7d2c-3d62-4389-b542-526d663cf91b.png)

**Comment by lhbxs** [comment]
简单一点的方法，可以通过 watch 监听 list 的变化，然后便利 list 去请求数据，然后在更新 list 的数据

**Comment by zflhcc** [comment]
watch 监听 list 的变化, 能否获得到当前操作item的id值或者index

**Comment by zflhcc** [comment]
xRender 2.0
antd 5.x
导致这个报错了
怎么解决











LFZ\x26nbsp;\x26amp;\x26nbsp;only
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "alibaba/x-render"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年3月28日(星期二) 晚上8:13
***@***.***&gt;;
抄送:&nbsp;"LFZ &amp; ***@***.******@***.***&gt;;
主题:&nbsp;Re: [alibaba/x-render] ListSimple (Issue #1117)





 
简单一点的方法，可以通过 watch 监听 list 的变化，然后便利 list 去请求数据，然后在更新 list 的数据

**Comment by zflhcc** [comment]
这种写法报错了怎么办，导致正生成器不能用了
有什么办法可以优化吗？


LFZ&nbsp;&amp;&nbsp;only
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "alibaba/x-render"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年3月27日(星期一) 下午5:52
***@***.***&gt;;
抄送:&nbsp;"LFZ &amp; ***@***.******@***.***&gt;;
主题:&nbsp;Re: [alibaba/x-render] ListSimple (Issue #1117)





 
具体是怎么操作的？
