### ISSUE TITLE
tableList设计态能支持左右排列吗？

### ISSUE THREAD

**Issue by Shittou** [alibaba/x-render#1119]
### 期望的新功能 (describe the expected new feature)
tableList支持左右排列
### 简述一下使用场景，便于开发者更好理解新功能的必要性 (describe your scenario for us to understand the need)
产品希望所见即所得，tableList设计态也希望可以展示table的样式 左右排列，目前设计器能支持吗

**Comment by lhbxs** [comment]
左右排列？tableLlist，能截图示意下吗？没懂
