### ISSUE TITLE
TableRender中configProvider可以支持透传所有组件参数

### ISSUE THREAD

**Issue by RyzenPan** [alibaba/x-render#1123]
### 期望的新功能 (describe the expected new feature)
对于希望能定制table、分页器等组件的开发者来说，现有的部分透传参数不足够的，例如分页器只有showSizeChanger，showTotal这种显示总条数功能是比较常见的，但现在却不能透传给Pagination分页器

### 简述一下使用场景，便于开发者更好理解新功能的必要性 (describe your scenario for us to understand the need)
见上，感谢

`      configProvider={{
        pagination: {
          showSizeChanger: true,
          showTotal: (total: number) => `Total ${total} items`, // 希望能透传给Pagination
        },
      }}`

**Comment by lhbxs** [comment]
2.x 支持 props.pagination进行属性透传的
