### ISSUE TITLE
2.0.x setSchemaByPath 设置值错误

### ISSUE THREAD

**Issue by makehaha** [alibaba/x-render#1128]
**1.依赖仓库的版本(Dependencies versions)**：

- react：18.2.0
- form-render：2.1.3
- table-render:
- antd：4.24.8

**2.问题描述(Bug description)**：
通过API 对setSchemaByPath 赋值的时候，数组执行合并操作是不对的。

**3.最小复现 demo(Reproduction demo)**：
https://codesandbox.io/s/competent-snow-hh206x?file=/src/App.js
点击bug 按钮。

问题代码：
packages/form-render/src/models)/useForm.ts
错误方法：
updateSchemaByPath
错误语句：
 const result = _merge(currSchema, newSchema);

错误原因：
当要对下拉的枚举数据设置值的时候，错误的进行了合并
例如，当前下拉框数据的enum['1','2'],enumNames['女','男']
setSchemaByPath('xxx',{enum['2'],enumNames['男']}
希望设置为下拉框只有一个男。但执行后getSchema 出来是
enum['2','2'],enumNames['男','男'];界面显示也是错误的。

form-render demo https://codesandbox.io/s/unruffled-flower-jl78h
table-render demo https://codesandbox.io/s/sweet-euler-bdoty
fr-generator demo https://codesandbox.io/s/s13sh

**Comment by lhbxs** [comment]
已修复升级 2.1.6
