### ISSUE TITLE
如何自行控制渲染 schema ?

### ISSUE THREAD

**Issue by StringKe** [alibaba/x-render#1136]
### 期望的新功能 (describe the expected new feature)

提供 Field 自己传入 scheme 相关属性

### 简述一下使用场景，便于开发者更好理解新功能的必要性 (describe your scenario for us to understand the need)

https://react.formilyjs.org/api/components/schema-field

类似这样的功能，我目前需要自己来掌控布局，组件渲染，由 x-render 来多层级组件中的 输入组件（可控组件）的渲染

**Comment by StringKe** [comment]
也许可以吧 FieldItem 和 FieldItem 默认包裹一下 RenderCore 然后导出一下？

**Comment by lhbxs** [comment]
不知道你真的意图是什么，这样搞会不会越搞越复杂

**Comment by StringKe** [comment]
因为我需要通过低代码去设计表单，类似 formily designable 那样的做法

**Comment by lhbxs** [comment]
目前好像无法满足这样的需求，如果是这种 <Field schema />。可能 FormCore 的上下文就被破坏了。

**Comment by lhbxs** [comment]
目前好像无法满足这样的需求，如果是这种 '<Field schema={} />'。可能 FormCore 的上下文就被破坏了。

**Comment by lhbxs** [comment]
`<Field schema={} />
`

**Comment by StringKe** [comment]
我看了下代码，FieldItem 不本身也是调度 Context 么？，直接对外暴露 RenderCore 应该可行吧
