### ISSUE TITLE
是否可支持 列表非弹窗式编辑功能

### ISSUE THREAD

**Issue by qtzjzp** [alibaba/x-render#1140]
### 期望的新功能 (describe the expected new feature)
主要适用于 在表格列表里面，可以每一行每个字段都可以编辑的功能。

### 简述一下使用场景，便于开发者更好理解新功能的必要性 (describe your scenario for us to understand the need)
主要是在申请一些 表格时，希望能够在表格里直接定义 字段修改，每次都是弹窗的话，主页面与详情页面需要有个关联字段，需要与弹窗交互不停的处理逻辑，而且详情页面很多时候需要自动保存，如果放在列表直接编辑的话，可以最后统一保存。

**Comment by lhbxs** [comment]
tabList 不就满足需求吗
