### ISSUE TITLE
tableList 不支持 labelCol fieldCol

### ISSUE THREAD

**Issue by leshalv** [alibaba/x-render#1142]
tableList 不支持 labelCol、 fieldCol

**Comment by lhbxs** [comment]
你是指 tableList 整体布局？还是什么？截个效果图看看

**Comment by leshalv** [comment]
<img width="965" alt="image" src="https://user-images.githubusercontent.com/30397655/230842734-81a334df-fca9-4c66-b61f-3c3eb6f7c14b.png">

上图为现有 tableList 布局

下图为手动加入lable和control  ant-col-xx类样式的效果，我想应该是tableList暂未支持Form整体布局。

<img width="979" alt="image" src="https://user-images.githubusercontent.com/30397655/230842936-f413344c-7332-46f0-bda6-a6d2fe46748e.png">

**Comment by leshalv** [comment]
刚才贡献了一个PR，支持操作列的width、align、fixed 等配置，tableList 可以在支持整体样式布局后，这个表单就更好看了。

**Comment by lhbxs** [comment]
了解，我适配一下

**Comment by leshalv** [comment]
列标题也可以支持 tooltip，展示该字段提示对用户体验会很好

https://github.com/alibaba/x-render/issues/1141

**Comment by lhbxs** [comment]
升级最新版
