### ISSUE TITLE
ant design5x 关于部分过时api的警告

### ISSUE THREAD

**Issue by leshalv** [alibaba/x-render#1147]
design5x 更改了的api属性，但由于x-render组件兼容ant design4，代码中也并未根据版本来进行传递属性处理，导致使用ant design5时，控制台存在警告问题。

<img width="480" alt="image" src="https://user-images.githubusercontent.com/30397655/230877091-1e694dc0-2ee0-47e3-bae9-0fed19ad3c86.png">

**Comment by lhbxs** [comment]
更新最新版本
