### ISSUE TITLE
tableList 校验和非校验样式出现问题。

### ISSUE THREAD

**Issue by leshalv** [alibaba/x-render#1148]
<img width="573" alt="image" src="https://user-images.githubusercontent.com/30397655/230878190-a2d71074-26c1-44b2-bc7d-ec7cdaae8749.png">
<img width="457" alt="image" src="https://user-images.githubusercontent.com/30397655/230878884-10e0ec3f-74a7-46fe-885e-0f5b57d8315a.png">

**Comment by leshalv** [comment]
感觉可以参考下 ant design components 错误展示样式

<img width="724" alt="image" src="https://user-images.githubusercontent.com/30397655/230879529-8c385c67-6904-4768-9426-44f562abe770.png">

**Comment by lhbxs** [comment]
你什么版本？更新到最新版本

**Comment by leshalv** [comment]
最新版本的，使用的是ant5
