### ISSUE TITLE
type:'object' 不展示边框

### ISSUE THREAD

**Issue by leshalv** [alibaba/x-render#1150]
type:'object' 下指定一组数据，只是为了使用对象功能，并不想展示边框样式。可以支持通过透传属性关闭边框样式吗？

<img width="788" alt="image" src="https://user-images.githubusercontent.com/30397655/230890212-b9b09778-2728-4249-83f7-3b5232045756.png">

我看 BoxPanel 组件在 bordered={displayType !== 'inline'}下是可以不展示的

<img width="944" alt="image" src="https://user-images.githubusercontent.com/30397655/230889908-dfbeee8f-0a98-4dc7-9ab0-b47f649fa7dc.png">

**Comment by lhbxs** [comment]
object 里面 加一个 "widget": "card"
