### ISSUE TITLE
tableList 不为必填时，默认不展示一行null数据

### ISSUE THREAD

**Issue by leshalv** [alibaba/x-render#1151]
tableList 不为必填时，默认不展示一行null数据，本来是不必填项，展示了以后用户需要手动删除，然后才能提交。

当前样子：

<img width="618" alt="image" src="https://user-images.githubusercontent.com/30397655/230893035-1e1adf26-0a34-4c47-b11e-15668b31e4ea.png">

期望样子：
<img width="600" alt="image" src="https://user-images.githubusercontent.com/30397655/230893065-f7a755be-7fad-4e07-8de1-4be85fd872fe.png">

**Comment by lhbxs** [comment]
schema.default 默认 []
