### ISSUE TITLE
支持动态增减表单项需求

### ISSUE THREAD

**Issue by leshalv** [alibaba/x-render#1152]
###  动态增减表单项需求

<img width="602" alt="image" src="https://user-images.githubusercontent.com/30397655/230895011-c0803c38-d492-4b0d-a032-1c7b7d81d3b5.png">

可参考 https://ant.design/components/form-cn#components-form-demo-dynamic-form-item

**Comment by lhbxs** [comment]
https://xrender.fun/form-render/disaply-row#simplelist

simpleList：标签内联

**Comment by leshalv** [comment]
标签内联适用于展示每行只有 1-3 个简单控件的情况，紧凑排列，我这个需求是想只展示一个字段的动态增减

**Comment by leshalv** [comment]
对比可以看出明显区别。

![image](https://user-images.githubusercontent.com/30397655/230901767-aef7ad16-7a47-4e70-b5c7-44b255c55665.png)


<img width="935" alt="image" src="https://user-images.githubusercontent.com/30397655/230901733-413dcb41-db0e-487c-af16-0c3c39e11867.png">
