### ISSUE TITLE
checkbok 支持水平排列和垂直排列 'horizontal' | 'vertical'

### ISSUE THREAD

**Issue by leshalv** [alibaba/x-render#1153]
### checkbok 支持水平排列和垂直排列 'horizontal' | 'vertical'

如下图，这是一个垂直排列的checkbox样式

<img width="609" alt="image" src="https://user-images.githubusercontent.com/30397655/230897749-a4c02ed4-b5b6-48be-8e56-7edc773741dc.png">

**Comment by lhbxs** [comment]
direction = 'column'
