### ISSUE TITLE
SimpleList 支持字符串数组

### ISSUE THREAD

**Issue by leshalv** [alibaba/x-render#1154]
SimpleList 支持字符串数组，目前SimpleList支持对象数组，并未支持字符串数组，可参考formilyjs字符串数组

https://antd5.formilyjs.org/zh-CN/components/array-items#markup-schema-%E6%A1%88%E4%BE%8B

<img width="872" alt="image" src="https://user-images.githubusercontent.com/30397655/230902817-79a26739-a91a-4bb2-8735-8a4651d6c217.png">

![image](https://user-images.githubusercontent.com/30397655/230902953-d7d94b03-1a24-4adc-a488-5aef49e89237.png)

**Comment by lhbxs** [comment]
并不能立马支持，背后协议规则不一样。这个你可以通过写一个自定义组件来实现

**Comment by leshalv** [comment]
> 并不能立马支持，背后协议规则不一样。这个你可以通过写一个自定义组件来实现

是因为JSON协议的问题吗？

**Comment by lhbxs** [comment]
最新版本，已经支持，请看文档细则：https://xrender.fun/form-render/advanced-bind#bindroot

**Comment by rxdxxxx** [comment]
如果使用了 bind:root 之后，数据如何回显到表单里呢？
