### ISSUE TITLE
watch可以获得变化前的值

### ISSUE THREAD

**Issue by superoery** [alibaba/x-render#1155]
### 期望的新功能 (describe the expected new feature)
目前使用watch监听表单内具体字段的变化的方式如下：
```
const watch = {
  // # 为全局
  '#': val => {
    console.log('表单的时时数据为：', val);
  },
  input1: val => {
    if (val !== undefined) {
      form.onItemChange('input2', val);
    }
  },
  'object1.select2': {
    handler: val => {
      if (val === 'option1') {
        form.onItemChange('object1.input2', 'hello');
      }
    }
  }
};

```
希望可以在handler里访问字段变化前的值
```
const watch = {
  input1: (newVal,oldVal)=> {
     ...
  },

}
```

**Comment by MoYuM** [comment]
什么场景下需要用到这个功能，现有功能可以满足么？

**Comment by MoYuM** [comment]
可以尝试使用自定义组件实现，不满足校验的时候，不要调用 onChange 就行了。

**Comment by Mity1299** [comment]
> 可以尝试使用自定义组件实现，不满足校验的时候，不要调用 onChange 就行了。

好的，谢谢你的建议。但是针对自定义处理是第三方的，执行之后才知道成功还是失败，没办法通过校验判断是否会失败

**Comment by MoYuM** [comment]
没太明白你的意思，什么叫自定义处理是第三方？执行又是指的执行什么？

**Comment by Mity1299** [comment]
```
const myHandler = (param)=>{
  /**
  * 假设方法在向某个后端服务进行请求
  * 由于这个请求的执行情况不是由前端代码所控制
  * 只有执行完了才知道是否会报错
  **/
  await http.request(param);
}

const watch = {
  input1: (newVal,oldVal)=> {

    try{
      //执行自定义处理
      await myHandler(newVal)
      message.success('执行成功')
    }catch(err){
      //回退表单状态
      form.setValueByPath('input1',oldVal)
      message.success('执行失败')
    }
  },

}
```

**Comment by MoYuM** [comment]
这个和你本地校验一样的，如果失败就不要调用 onChange 就行了

**Comment by Mity1299** [comment]
我的需求是要在表单字段改变的时候，发起请求。在这个需求下，我不调用onChange怎么知道请求是否失败呢？

**Comment by MoYuM** [comment]
哦，我说的 onChange 指的是自定义组件中的 onChange。大概这样

```jsx
const MyInput = ({ value, onChange }) => {
  return (
     <Input 
       value={value}
       onChange={val => {
         // 校验成功才 onChange
         if (valiateSuccess(val)) {
           onChange(val)
         }
       }}
     />
  )
}

// 作为自定义组件使用
<FormRender widgets={{ MyInput }}>
```

**Comment by Mity1299** [comment]
好的，谢谢你的说明。
这样做确实能达到目的，但是如果我希望每个组件包括内置组件都能支持这样的操作，这种实现方式会要求我不得不覆盖所有的组件。
 为什么不可以在watch里将oldVal暴露出来呢，是出于什么考虑？这样我就可以在这里统一做这样的逻辑，而不用管他是什么组件。

> ```js
> const myHandler = (param)=>{
>   /**
>   * 假设方法在向某个后端服务进行请求
>   * 由于这个请求的执行情况不是由前端代码所控制
>   * 只有执行完了才知道是否会报错
>   **/
>   await http.request(param);
> }
> 
> const watch = {
>   input1: (newVal,oldVal)=> {
> 
>     try{
>       //执行自定义处理
>       await myHandler(newVal)
>       message.success('执行成功')
>     }catch(err){
>       //回退表单状态
>       form.setValueByPath('input1',oldVal)
>       message.success('执行失败')
>     }
>   },
> 
> }
> ```

**Comment by MoYuM** [comment]
并不是故意选择让 oldVal 不暴露出来，而是 watch 本来就拿不到 oldVal。watch 只是监听表单值的变化，和 antd form 的 onValuesChange 一样

**Comment by Mity1299** [comment]
好的，十分感谢你的及时回复！

**Comment by lhbxs** [comment]
watch 的 API  其实是 onValuesChange 的增强，你这边就完全可以自己处理，你自己建立一个 map对象，key 就是 watch 的 可以， 每次 watch 更新 通过和 map 映射的值进行对比

**Comment by superoery** [comment]
> watch 的 API 其实是 onValuesChange 的增强，你这边就完全可以自己处理，你自己建立一个 map对象，key 就是 watch 的 可以， 每次 watch 更新 通过和 map 映射的值进行对比

好的 感谢你的答复！
