### ISSUE TITLE
如何在FormRender中想要调用自定义组件中的方法？

### ISSUE THREAD

**Issue by luckyTiamo** [alibaba/x-render#1156]
### 简述一下使用场景，便于开发者更好理解新功能的必要性 (describe your scenario for us to understand the need)
父组件中配置了自定义组件，代码：
<FormRender cRef={setMyWidgetRef} form={form} widgets={{ searchInput: SearchInput }} schema={schema} onFinish={onFinish} labelAlign='left'/>

SearchInput组件中定义了clear方法
我现在想在父组件中调用SearchInput的clear方法，该如何使用呢？

**Comment by lhbxs** [comment]
你试试在父组件，创建一个 Ref 对象，然后通过 schema = { props : { xxRef: ref对象}}

或者通过动态的 setSchemaByPath('xxx', { props: {  xxRef: ref对象 }} 去设置
