### ISSUE TITLE
整体布局错乱

### ISSUE THREAD

**Issue by jokyczq** [alibaba/x-render#1160]
![image](https://user-images.githubusercontent.com/73460759/231955481-b5a776d0-d82c-4f51-a58c-66d057bb3844.png)

https://xrender.fun/generator#%E4%BB%A3%E7%A0%81%E6%BC%94%E7%A4%BA

官网整体布局链接可以查看，选择一列多行的时候，样式错乱

**Comment by MoYuM** [comment]
duplicate: https://github.com/alibaba/x-render/issues/1111
