### ISSUE TITLE
混合模式下如何使用，只渲染表单项，并不渲染 form

### ISSUE THREAD

**Issue by leshalv** [alibaba/x-render#1163]

**Comment by leshalv** [comment]
混合模式：既有正常写的表单，也有通过JSON渲染的，form-render 只生成表单项，不生成 Form ，配合表单实现混合使用

**Comment by MoYuM** [comment]
FormRender 的目的就是通过 JSON 生成表单，肯定会有 <Form> 标签的，要不怎么能算作一个表单呢？如果想和原生表单混合使用的话，可以尝试 FormRender 的自定义组件。如果需要更高层级的混用，尝试一下 antd Form 的 Form.Provider

**Comment by leshalv** [comment]
我意思是，组件是不是可以有个配置，可以不生成form元素，只生成Item

**Comment by leshalv** [comment]
https://procomponents.ant.design/components/schema-form

<img width="1095" alt="image" src="https://user-images.githubusercontent.com/30397655/232455088-3be44f7a-7005-4106-b168-a11ac828b8cd.png">

**Comment by MoYuM** [comment]
有必须这样做的场景么

**Comment by MoYuM** [comment]
我大概明白你的意思了。但 SchemaForm 有 ProForm 作为基础，FormRender 没有。目前 FormRender 的 API 和 antd Form 还是有区别的，只渲染 Item 可能会遇到很多兼容上的问题。

**Comment by leshalv** [comment]
都是基于ant，我直接用ant的Form也可以不是吗？一部分用jsx，动态配置的用form-render，反正都是Form.Item，怎么嵌无所谓不是？

**Comment by MoYuM** [comment]
如果不考虑 FormRender 本身的 API，只把 FormRender 当作 antd Form 的渲染器的话，确实可以实现。但我还是觉得这个的使用场景比较少。

**Comment by lhbxs** [comment]
你所谓的混合模式是一定不支持的，FormRender 是一个通过 JSONSchema 驱动生成表单的渲染器，其中包含了很多和 JSON 交互的 API，混合的化会使得这个体系崩溃。

但是可以换一种思路，基础字段模块完全可以是一个自定义大组件。
