### ISSUE TITLE
是否支持ant design 3.x？

### ISSUE THREAD

**Issue by GitHubOfLeon** [alibaba/x-render#1165]
1、搜索了一下issue列表，并没有此类问题，我目前有一个老项目，使用的ant design是3.x版本，引入x-render之后，会有各种组件缺失问题，想问问是否支持ant design 3.x？
2、尝试加入钉钉的开源社区群，但是二维码显示的群聊已经1000人满员了，还有分群吗？

**Comment by MoYuM** [comment]
目前没有兼容 antd3.x 的计划。
但可以尝试通过自定义组件把 antd3.x 组件覆盖内置组件来用。
@lhbxs 群确实满了，需要看下

**Comment by GitHubOfLeon** [comment]
因为现在是只要加载了FormRender就会报错，类似丢失```antd/es/date-picker/generatePicker```这种错误，所以自定义组件的方式，是需要在项目启动阶段进行什么配置吗？我在x-render的文档里好像没有找到类似的说明，希望大佬儿指点一下。

**Comment by MoYuM** [comment]
能提供个最小复现仓库么

**Comment by lhbxs** [comment]
2.x 版本 不支持 antd 3.x，如果你是老项目可以试试使用 FormRender 1.x

**Comment by lhbxs** [comment]
或者试试 2.x 的 组件按需 https://xrender.fun/form-render/advanced-slimrender
