### ISSUE TITLE
xrender 支持antd5

### ISSUE THREAD

**Issue by xiaonan132142** [alibaba/x-render#1166]
### 问题  项目umi4+antd5 报错不支持

./node_modules/fr-generator/node_modules/form-render/es/widgets/antd/time.js:2:0-35
Module not found: Error: Can't resolve 'antd/es/time-picker/style' in '/Users/mac/workspace/myapp/node_modules/fr-generator/node_modules/form-render/es/widgets/antd'

**Comment by lhbxs** [comment]
升级到2.x版本就可以使用了

**Comment by xiaonan132142** [comment]
> 

 "fr-generator": "^2.8.5", 使用的版本

**Comment by xiaonan132142** [comment]
> 

现在使用的版本  "fr-generator": "^2.8.5", 
"name": "fr-generator",
  "version": "2.8.5",
  "main": "dist/index.js",
  "module": "dist/index.esm.js",
  "typings": "dist/index.d.ts",

但是依旧会报错

**Comment by xiaonan132142** [comment]
formRender 2.0升级了antd5 
fr-generator 的依赖包没有升级formRender 的依赖

现在使用的版本 "fr-generator": "^2.8.5",
"name": "fr-generator",
"version": "2.8.5",
"main": "dist/index.js",
"module": "dist/index.esm.js",
"typings": "dist/index.d.ts",

formRender 是1.0的版本

**Comment by zhaoyanga** [comment]
升级哪个版本，我把formRender升级到2.5.6后，点击会出现input is a void element tag and must neither have `children` nor use `dangerouslySetInnerHTML`
已解决，formRender版本为2.0.0-rc.0
