### ISSUE TITLE
升级到2.x版本就可以使用了

### ISSUE THREAD

**Issue by xiaonan132142** [alibaba/x-render#1168]
升级到2.x版本就可以使用了

_Originally posted by @lhbxs in https://github.com/alibaba/x-render/issues/1166#issuecomment-1514070850_

formRender 2.0升级了antd5
fr-generator 的依赖包没有升级formRender 的依赖

现在使用的版本 "fr-generator": "^2.8.5",
"name": "fr-generator",
"version": "2.8.5",
"main": "dist/index.js",
"module": "dist/index.esm.js",
"typings": "dist/index.d.ts",

formRender 是1.0的版本 antdV4

**Comment by lhbxs** [comment]
设计器目前在重构，fr-generator 底层强依赖 formRender 是1.0 源码，无法一键升级 2.0依赖
