### ISSUE TITLE
配置化的项目使用form-render会导致XSS问题，能否提供直接禁止 “表达式” 的设置

### ISSUE THREAD

**Issue by lqzerogg** [alibaba/x-render#1172]
### 期望的新功能 (describe the expected new feature)
配置化的项目使用form-render会导致XSS问题，能否提供直接禁止 “表达式” 的设置
### 简述一下使用场景，便于开发者更好理解新功能的必要性 (describe your scenario for us to understand the need)
配置化的项目，由于配置都是由运营输入或者拖拽完成的，输入不可控，表达式 的功能会导致XSS的问题

**Comment by lhbxs** [comment]
那禁用了，表达式不起作用，岂不是功能都无法实现

**Comment by lqzerogg** [comment]
表达式是指 图片的这个功能。因为这部分是用户可控的，容易有XSS。其他功能正常就行了
![image](https://user-images.githubusercontent.com/5119347/233525591-d6d37fbe-e956-4c1f-9aea-8c7ecd5f6712.png)

**Comment by lhbxs** [comment]
那不处理，hidden 是 true 还是 false 呢？ 我理解你正则匹一下， 然后替换？

**Comment by lqzerogg** [comment]
是可以遍历处理，但是每个开发者都实现一遍还是比较重复嘛。可以的话，库中提供一个功能直接禁用是最好了

**Comment by lhbxs** [comment]
globalConfig={{
  mustacheDisabled: true,
}}

2.1.16-beta.1，你可以试试

不做解析，但可能会带来一下副作用，比如 disabled:"{{}}" ，disabled 会直接生效
