### ISSUE TITLE
中间过程报错

### ISSUE THREAD

**Issue by wangxinyu666666** [alibaba/x-render#1177]
schema={
    "$schema": "[https://json-schema.org/draft/2020-12/schema"](https://json-schema.org/draft/2020-12/schema),
    "title": "Feeds 策略配置",
    "type": "object"
}
报错如下
<img width="1427" alt="image" src="https://user-images.githubusercontent.com/26834996/233559808-774b4e53-0384-473e-b43a-ff66b4e46bcd.png">
<img width="964" alt="image" src="https://user-images.githubusercontent.com/26834996/233559849-398b9c3f-1571-4465-a4cd-42fde9f24de3.png">

formrender版本2.1.12

**Comment by lhbxs** [comment]
schema 格式不对吧

**Comment by wangxinyu666666** [comment]
应该兼容一下，schema如果没有写properties，不应该页面崩溃吧？

**Comment by lhbxs** [comment]
恩，我判断一下

**Comment by wangxinyu666666** [comment]
好的，谢谢。

**Comment by lhbxs** [comment]
但是出错的原因还是由于你的格式不对哈

**Comment by lhbxs** [comment]
不是很懂你的意思，我是只要保证页面不崩溃就行是吗？因为如果 properties  不传的话，什么也显示不出来

**Comment by lhbxs** [comment]
2.1.13-beta.2
