### ISSUE TITLE
onValuesChange没有监听到数据变化

### ISSUE THREAD

**Issue by wangxinyu666666** [alibaba/x-render#1179]
<FormRender
                form={strategyForm}
                schema={schema}
                watch={watch}
                widgets={widgets}
                onValuesChange=(value, formData) => {
                              console.log(value);
                }
                readOnly={readOnly}
 />

onValuesChange没有打印出来任何东西
formrender版本2.1.12

**Comment by lhbxs** [comment]
请使用 watch = {
  "#": () => {
  }
}

onValuesChange 不对外暴露
