### ISSUE TITLE
画布按钮

### ISSUE THREAD

**Issue by xiaonan132142** [alibaba/x-render#1181]
### 请问现在是否支持？是否支持拖拽上传组件并未在渲染器中看到

![L1VzZXJzL21hYy9MaWJyYXJ5L0NvbnRhaW5lcnMvNVpTTDJDSlUyVC5jb20uZGluZ3RhbGsubWFjL0RhdGEvTGlicmFyeS9BcHBsaWNhdGlvbiBTdXBwb3J0L0RpbmdUYWxrTWFjLzE1NzE1NjEyNl92Mi9JbWFnZUZpbGVzLzE2ODIyMjEyNTc2ODVfRTFERUE3Q0QtNDFDNy00RTRGLTlERTgtOTYyODMwRDg3NkFFLnBuZw==](https://user-images.githubusercontent.com/19482277/233818583-5c111f1b-d7b0-4960-a942-7dd9fbc52610.png)

**Comment by lhbxs** [comment]
后面会推出新的搭建器来配合 2.x 使用，所以这个就不迭代新功能啦，

左侧组件可以自定义配置，设计器没有全部内置
