### ISSUE TITLE
升级到2.x之后，以前的schema不兼容了

### ISSUE THREAD

**Issue by wangxinyu666666** [alibaba/x-render#1183]
以前业务上schema如下：
{
    "$schema": "[https://json-schema.org/draft/2020-12/schema"](https://json-schema.org/draft/2020-12/schema),
    "title": "Feeds 策略配置",
    "type": "object",
    "widget": "StrategyEditor",
    "readOnlyWidget": "StrategyEditor",
    "props": {}
}
在1.14.14版本中，上面的schema是可以正常渲染出表单的，但是升级到2.x版本后，就不能渲染了。辛苦看一下，因为这个已经上到正式环境了，我这没有太好的办法修改。

**Comment by MoYuM** [comment]
报的什么错

**Comment by wangxinyu666666** [comment]
> 报的什么错

没有报错，就是没有渲染出来表单

**Comment by MoYuM** [comment]
本地环境下也没有报错么

**Comment by wangxinyu666666** [comment]
> 本地环境下也没有报错么

没有报错，用的2.1.13-beta.2这个版本

**Comment by lhbxs** [comment]
你的 schema 贴出来看看

**Comment by lhbxs** [comment]
然后新老对比，截图看看

**Comment by wangxinyu666666** [comment]
schema={
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "title": "Feeds 策略配置",
  "type": "object",
  "widget": "StrategyEditor",
  "readOnlyWidget": "StrategyEditor",
  "props": {}
}
新版本：
<img width="1084" alt="image" src="https://user-images.githubusercontent.com/26834996/233825751-170fe5e9-f2ca-44d0-bfce-845748df827b.png">
旧版本：
<img width="1076" alt="image" src="https://user-images.githubusercontent.com/26834996/233825819-38f33919-1bc0-490e-89e9-1e6b1b48e03b.png">


> 然后新老对比，截图看看

schema={
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "title": "Feeds 策略配置",
  "type": "object",
  "widget": "StrategyEditor",
  "readOnlyWidget": "StrategyEditor",
  "props": {}
}
新版本：
<img width="1084" alt="image" src="https://user-images.githubusercontent.com/26834996/233825751-170fe5e9-f2ca-44d0-bfce-845748df827b.png">
旧版本：
<img width="1076" alt="image" src="https://user-images.githubusercontent.com/26834996/233825819-38f33919-1bc0-490e-89e9-1e6b1b48e03b.png">

**Comment by lhbxs** [comment]
把 type 改成 any 试试

**Comment by wangxinyu666666** [comment]
> 把 type 改成 any 试试
右侧还是渲染不出来
<img width="1115" alt="image" src="https://user-images.githubusercontent.com/26834996/233825994-0bace3a6-429c-4bb5-859c-4b3ad8f97dde.png">

**Comment by lhbxs** [comment]
你这个 左侧的 schema 是最顶层的 schema 吗？

**Comment by wangxinyu666666** [comment]
> 你这个 左侧的 schema 是最顶层的 schema 吗？

是的

**Comment by lhbxs** [comment]
截图看下 <FormRender /> 的传参

**Comment by wangxinyu666666** [comment]
> 截图看下 的传参

是哪里的传参？

**Comment by lhbxs** [comment]
看看 <FormRender /> 这边标签的代码

**Comment by lhbxs** [comment]
"<FormRender />"

**Comment by lhbxs** [comment]
"<<FormRender />>"

**Comment by lhbxs** [comment]
<img width="245" alt="截屏2023-04-23 下午3 30 21" src="https://user-images.githubusercontent.com/43236919/233826212-5525c6ab-45f7-4b79-abb0-f48583d9ae9f.png">

**Comment by wangxinyu666666** [comment]
> <img alt="截屏2023-04-23 下午3 30 21" width="245" src="https://user-images.githubusercontent.com/43236919/233826212-5525c6ab-45f7-4b79-abb0-f48583d9ae9f.png">

<img width="768" alt="image" src="https://user-images.githubusercontent.com/26834996/233826262-99b60387-8ca9-4416-9bf7-643d7a09c6e5.png">
<img width="181" alt="image" src="https://user-images.githubusercontent.com/26834996/233826286-9274a029-56a7-4d83-a73c-29a8b1135a00.png">

**Comment by lhbxs** [comment]
感觉哪里不对，标准 schema 格式 不应该是下面这样的吗？

export default {
  type: 'object',
  properties: {
   "xxx": {
      title: '策略配置',
      type: 'any',
       .....

    },
};

**Comment by wangxinyu666666** [comment]
> 感觉哪里不对，标准 schema 格式 不应该是下面这样的吗？
> 
> { type: 'object', properties: { "xxx": { title: '策略配置', type: 'any', .....
> 
> ```
> },
> ```
> 
> };

我理解你说的标准模式，但是我上面的schema是想在根节点就渲染自定义组件，而且在1.14.14版本是可以正常渲染的，然后在新版本就渲染不出来。

**Comment by lhbxs** [comment]
你按照我说的套一层试试，看看

**Comment by wangxinyu666666** [comment]
> 你按照我说的套一层试试，看看

套一层肯定是可以的，但是之前的schema已经上生产了，在套一层的话，values的格式就变了，会多一层，所以不能多套一层，多套一层会改很多东西，可不可以在formrender里改一下？formrender升级了按理也需要兼容之前的schema呀

**Comment by lhbxs** [comment]
我理解数据只是从 data => xxx.data 吧，至于 data 里面的格式并不会改变

**Comment by lhbxs** [comment]
还有一个就是，我有点没 get 到点，你这个是一个顶层 schema 然后顶层 schema 对应的是一个自定义组件？那 form-render 起到了什么作用？

**Comment by wangxinyu666666** [comment]
> 我理解数据只是从 data => xxx.data 吧，至于 data 里面的格式并不会改变


是的，如果变成xxx.data，需要我这里改一下，以及客户那里的接口再改一下，而且需要兼容已有的数据。

**Comment by wangxinyu666666** [comment]
> 还有一个就是，我有点没 get 到点，你这个是一个顶层 schema 然后顶层 schema 对应的是一个自定义组件？那 form-render 起到了什么作用？

我上面写的schema只是一种使用情况，其他大多数的使用情况都是按照你们的标准来的。我的点是在于，既然之前这种schema是可以正常渲染出来的，那么版本升级之后也得兼容之前的schema吧？

**Comment by lhbxs** [comment]
底层渲染器换了，你这种非标准好像不适用新的渲染器

**Comment by wangxinyu666666** [comment]
> 底层渲染器换了，你这种非标准好像不适用新的渲染器

实在不行的话，那我改一下代码逻辑吧，这种根节点就是自定义组件的，就不使用formrender了。

**Comment by lhbxs** [comment]
恩，或者是判断一下是根组件这种情况，回填数据套一层、提交数据解套
