### ISSUE TITLE
fr-generator Switch设置默认选中切换错误

### ISSUE THREAD

**Issue by Now-Sprouting** [alibaba/x-render#1185]
**1.依赖仓库的版本(Dependencies versions)**：

- react：18.2.0
- fr-generator：2.8.5
- antd：4.24.9

**2.问题描述(Bug description)**：
fr-generator Switch组件设置默认选中切换组件错误提示，如下
![image](https://user-images.githubusercontent.com/64894484/233828673-6755ee4d-8b8d-4302-8fba-1b06ba045945.png)

**3.最小复现 demo(Reproduction demo)**：
1、使用代码
import Generator from 'fr-generator';

import './App.css'
import 'antd/dist/antd.css';

function App() {
  return (
    <div style={{ height: '80vh' }}>
      <Generator/>
    </div>
  );
}

export default App;

2、导入json
{
  "type": "object",
  "displayType": "column",
  "labelWidth": 120,
  "properties": {
    "appName__8Tymc": {
      "title": "应用中文名称appName(示例)",
      "type": "object",
      "displayType": "column",
      "props": {
        "style": {}
      },
      "theme": "collapse",
      "style": {},
      "properties": {
        "switch_Q68zMH": {
          "title": "是否展示",
          "type": "boolean",
          "widget": "switch",
          "displayType": "column",
          "default": true
        },
        "input_RcIqmG": {
          "title": "表头展示别名",
          "type": "string",
          "displayType": "column",
          "props": {}
        }
      }
    }
  }
}

3、切换两次 《是否展示》 与 《表头展示别名》后组件卡死，无法再次切换

**Comment by lhbxs** [comment]
试试 2.8.6

**Comment by Now-Sprouting** [comment]
2.8.6 也不行呢

**Comment by lhbxs** [comment]
1.0 设计器 已停止维护
