### ISSUE TITLE
表单里数字类型输入框最小值限制失效

### ISSUE THREAD

**Issue by superoery** [alibaba/x-render#1186]
已搜索issue

**1.依赖仓库的版本(Dependencies versions)**：

- react：18.2.0
- form-render：2.1.12
- table-render: 无
- antd：5.4.4

**2.问题描述(Bug description)**：
数字类型输入框最小值限制失效
![image](https://user-images.githubusercontent.com/41116724/233833863-420854a7-dea1-4e21-8c10-8dd052ce2a62.png)
最大值正常生效
![image](https://user-images.githubusercontent.com/41116724/233833944-a6b9d991-240f-4604-8535-12eb50262b11.png)

**3.最小复现 demo(Reproduction demo)**：
https://codesandbox.io/s/funny-tharp-jdcego?file=/schema/simple.ts

表单描述符为：
```
{
  type: "object",
  properties: {
    input: {
      title: "数字输入框",
      type: "number",
      min: 0,
      max: 5
    }
  }
}
```

**Comment by lhbxs** [comment]
已经修复，更新版本
