### ISSUE TITLE
FormRender提供定义className的配置

### ISSUE THREAD

**Issue by superoery** [alibaba/x-render#1191]
### 期望的新功能 (describe the expected new feature)
FormRender：
增加配置：为表单内的任意组件自定义className
### 简述一下使用场景，便于开发者更好理解新功能的必要性 (describe your scenario for us to understand the need)
使用场景：
需要更改表单内某组件的样式

根据现有的API，目前可行的方法似乎是自定义组件，并接收内联样式或className
对于需要修改任意组件的情况，这种方式要求用户覆盖所有内置组件，实现起来很麻烦

个人觉得优化的方案是
1. 为组件添加className，那么就可以通过导入自定义的样式文件，高自由度地修改表单的样式
2. 或者是否可以提供对已注册的所有组件使用[HOC](https://legacy.reactjs.org/docs/higher-order-components.html)的hook，方便用户对所有组件进行任意处理

**Comment by MoYuM** [comment]
不需要自定义组件也可以传 className

**Comment by superoery** [comment]
好的 已找到

**Comment by lhbxs** [comment]
这个新版有调整， 上面的配置 className 会命中到 Form.Item 容器上，要想给控件本身例如 input 自身 配置 className 需要配置 

{
  type: 'string',
  title: 'input',
  props: { className: 'xxx' }
}

**Comment by superoery** [comment]
> 这个新版有调整， 上面的配置 className 会命中到 Form.Item 容器上，要想给控件本身例如 input 自身 配置 className 需要配置
> 
> { type: 'string', title: 'input', props: { className: 'xxx' } }
好的 谢谢你的补充！
