### ISSUE TITLE
下载fr-generator包引入react项目，启动会有debugger

### ISSUE THREAD

**Issue by liyuyu0929** [alibaba/x-render#1192]
**1.依赖仓库的版本(Dependencies versions)**：

- react：
- form-render：
- table-render:
- antd：

**2.问题描述(Bug description)**：

**3.最小复现 demo(Reproduction demo)**：

form-render demo https://codesandbox.io/s/unruffled-flower-jl78h
table-render demo https://codesandbox.io/s/sweet-euler-bdoty
fr-generator demo https://codesandbox.io/s/s13sh

**Comment by liyuyu0929** [comment]
引入demo，样式丢失

**Comment by lhbxs** [comment]
我今天发了新的版本 2.8.7 不会有 debugger
