### ISSUE TITLE
Tabs组件问题

### ISSUE THREAD

**Issue by tianxinli** [alibaba/x-render#1193]
![image](https://user-images.githubusercontent.com/15724574/234501711-b4fe9f06-a672-49f0-9023-c2749716d733.png)
Tabs组件 没指定type值报的错，是ES类型转换的问题导致的吗

**Comment by lhbxs** [comment]
type: 'object' 加上

**Comment by lhbxs** [comment]
或者把你的 schema 贴出看下

**Comment by lhbxs** [comment]
还有说下用的什么版本？

**Comment by tianxinli** [comment]
> type: 'object' 加上

![image](https://user-images.githubusercontent.com/15724574/234733303-35b9144e-31dc-4a79-aff5-7d99f265e690.png)
我在源码里面加上这个就不会报错

**Comment by lhbxs** [comment]
你这个是啥？fr-generator?

**Comment by tianxinli** [comment]
> fr-generator

^-^ 额 是的，

**Comment by lhbxs** [comment]
10 设计器 已停止维护
