### ISSUE TITLE
https://xrender.fun/form-render/advanced/widget   这个文档更新的链接发一发呗，都看不了了

### ISSUE THREAD

**Issue by liyuyu0929** [alibaba/x-render#1194]
**1.依赖仓库的版本(Dependencies versions)**：

- react：
- form-render：
- table-render:
- antd：

**2.问题描述(Bug description)**：

**3.最小复现 demo(Reproduction demo)**：

form-render demo https://codesandbox.io/s/unruffled-flower-jl78h
table-render demo https://codesandbox.io/s/sweet-euler-bdoty
fr-generator demo https://codesandbox.io/s/s13sh

**Comment by lhbxs** [comment]
最近有点忙，是这个https://xrender.fun/form-render/advanced-widget
