### ISSUE TITLE
表单设计器报错

### ISSUE THREAD

**Issue by West121** [alibaba/x-render#1206]
sandbox打开示例报错，本地antd pro v6打开也是同样的报错
![image](https://user-images.githubusercontent.com/29170680/236360140-c434b6ae-e713-43ed-bc25-d5355c3d6eda.png)

**Comment by West121** [comment]
版本是这个："@xrenders/schema-builder": "1.0.0-alpha.1",

**Comment by lhbxs** [comment]
看下是那个 js 资源没有加载出来

**Comment by West121** [comment]
没看出来，地址是这个：https://codesandbox.io/s/6e9jo3

**Comment by West121** [comment]
https://static.cloudflareinsights.com/beacon.min.js/v52afc6f149f6479b8c77fa569edb01181681764108816
https://www.googletagmanager.com/gtm.js?id=GTM-T3L6RFK
![38daf7c43b49735546b638145f7f9b7](https://user-images.githubusercontent.com/29170680/236366212-195f5a9d-65a2-43b1-bb75-9347b63f7c1a.png)

**Comment by lhbxs** [comment]
需要 配置 externals: {
   
    react: 'React',
    'react-dom': 'ReactDOM',
   
  }

**Comment by West121** [comment]
> 



> 需要 配置 externals: {
> 
> ```
> react: 'React',
> 'react-dom': 'ReactDOM',
> ```
> 
> }

请问下在哪个文件配置啊？

**Comment by 13353634242** [comment]
请问解决了嘛
<img width="447" alt="image" src="https://user-images.githubusercontent.com/37133731/236718610-f5ad44ef-fda4-4ce2-97a0-7168e7e8bf7f.png">
我这边配置了这个 依旧有以上报错

**Comment by wx9999** [comment]
请问解决了嘛 
<img width="325" alt="image" src="https://user-images.githubusercontent.com/42061047/236718940-cd9a0d33-6445-4624-93e9-b8a149781fae.png">
我配置了这个 依然会报错
