### ISSUE TITLE
[Feature]渲染层根据结构自动生成最外层menu，支持快速索引功能

### ISSUE THREAD

**Issue by karzanOnline** [alibaba/x-render#121]
**Is your feature request related to a problem? Please describe.**
在实际业务中，使用的 formRender 展示将超出当前屏幕很多。对用户体感很差，无法一眼看到当前的结构。

同时用户修改时 期望可以快速所引导目标位置。

**Describe the solution you'd like**
FR 的生成页面，左侧可以生成一个 menu 菜单，点击 menuItem 后 content 可以滚动到对应位置。

**Describe alternatives you've considered**
`getContainerMenuList() ` 解析 schema 获取第一层的keys ，相当于获取左侧的 menu。
`setMenuTable()` 做一个映射表，左侧的menu和生成在右侧的 dom 节点，做映射关系。
当 `menu` `onClick` 的时候去触发滚动到指定dom的操作(根据这个映射表)

**Additional context**
![](https://img.alicdn.com/tfs/TB1WP_zOAL0gK0jSZFtXXXQCXXa-818-1274.png)

**Comment by FateRiddle** [comment]
挺好的，等空了可以支持。我理解对于一个长的表单这样能够快速滚动到需要填写的块，还是挺好的。

**Comment by aited** [comment]
fr-generator 支持tabs组件吗？

**Comment by tw93** [comment]
看了下半年都没有支持，交互方式需要再想一想，先关闭了
