### ISSUE TITLE
TableRender无法改变表格默认显示条数

### ISSUE THREAD

**Issue by RyzenPan** [alibaba/x-render#1210]
**1.依赖仓库的版本(Dependencies versions)**：

- react：
- form-render：2.1.14
- table-render: 2.0.14
- antd：^5.4.6

**2.问题描述(Bug description)**：
往TableRender传入pagination: { pageSize: 20 }，仅能改变分页器默认选中的每页显示数，但request吐出来的pageSize不准确，并且内部切换也不准确了

**3.最小复现 demo(Reproduction demo)**：
已在3群中反馈
![image](https://user-images.githubusercontent.com/56830619/236436476-0ab9c873-e1e2-44cb-8d18-8373389459ea.png)

form-render demo https://codesandbox.io/s/unruffled-flower-jl78h
table-render demo https://codesandbox.io/s/sweet-euler-bdoty
fr-generator demo https://codesandbox.io/s/s13sh

**Comment by lhbxs** [comment]
奇怪了，你是点击查询的时候，还是切页查询的时候，我没有复现，你试试这个 2.0.15-beta.2

**Comment by RyzenPan** [comment]
> 奇怪了，你是点击查询的时候，还是切页查询的时候，我没有复现，你试试这个 2.0.15-beta.2

我刚刚更新了2.0.15正式版，还是一样，传入pageSize或defaultPageSize是20，还是不能默认加载20条

**Comment by lhbxs** [comment]
#1258 
已修复，更新最新版本

**Comment by RyzenPan** [comment]
> #1258 已修复，更新最新版本

还是会存在一点问题，指定pageSize后生效，但切换条数时select未变化，表格数据数量已变更，已在3群反馈！！感谢大佬们的辛勤付出
