### ISSUE TITLE
antd 升级到5.x报错了

### ISSUE THREAD

**Issue by zflhcc** [alibaba/x-render#1216]
xRender 2.0
antd 5.x
导致这个报错了
怎么解决

![image](https://user-images.githubusercontent.com/25218359/236733385-ca73e903-5c39-4912-bd44-8c7bf0abeb3a.png

**Comment by MoYuM** [comment]
试试删掉缓存文件 .umi nodemodals 这些

**Comment by zflhcc** [comment]
![image](https://user-images.githubusercontent.com/25218359/236761671-d81fab52-4412-4611-9fed-b7e92c978605.png)
还是不行，不知道什么情况

![image](https://user-images.githubusercontent.com/25218359/236761977-b500a846-7cc8-46d5-9828-9bdf6a118274.png)
看看工程里面还有这个引用

**Comment by zflhcc** [comment]
主要是我这边还是用的之前的fr-generator导致报错了，你们能否修复一下

**Comment by MoYuM** [comment]
fr-generator 不支持 antd5.x

**Comment by lhbxs** [comment]
fr-generator 强依赖 1.x 的 form-render 的 源码，而 form-render 2.0 进行了源码整体重构，所以 fr-generator 无法支持 antd 5.x 
fr-generator 后面也不再继续维护了

**Comment by zflhcc** [comment]
fr-generator自己改造是否能支持antd5.x , 有什么好建议吗？
SchemaBuilder 现在好像还不支持自定义组件。

**Comment by maple5233** [comment]
```
resolve: {
        alias: {
          'antd/es/time-picker/style': path.resolve(__dirname, 'empty.js'),
        },
      },
```
一个work arround, empty.js建在根目录，啥内容都没就行
