### ISSUE TITLE
schema type类型问题

### ISSUE THREAD

**Issue by tianxinli** [alibaba/x-render#1219]
![image](https://user-images.githubusercontent.com/15724574/236784639-722d34d0-556d-4ac4-be51-21769e64e172.png)
这里的类型，通过配置参数，返回值会存在string和array类型，怎么解决值类型报错的问题
![image](https://user-images.githubusercontent.com/15724574/236784997-94d4dd37-8ab9-45c8-970f-9a89e771b5b0.png)

**Comment by MoYuM** [comment]
这个报错是因为 companyList 的 value 类型不是 string, 看你的截图这应该是个多选吧，那把 string 改成 array 应该就可以了。
跟下面没关系

**Comment by tianxinli** [comment]
> type 字段会做为校验的基础字段，多选的时候 type: 'array'
我的companyList组件，可以通过右侧配置项设置，值存在string和array两种类型
