### ISSUE TITLE
form.setValueByPath是undefined

### ISSUE THREAD

**Issue by Yuanyating** [alibaba/x-render#1220]
**1.依赖仓库的版本(Dependencies versions)**：

- react：17.0.2
- form-render：2.0.0
- table-render:
- antd：4.19.3

**2.问题描述(Bug description)**：
项目中form-render由1.x升级为2.x，项目中的form.setValueByPath失效，打印form发现setValueByPath为undefined

**3.最小复现 demo(Reproduction demo)**：
![截屏2023-05-09 下午6 43 58](https://github.com/alibaba/x-render/assets/43534983/e1377e0c-1d7f-4b54-921f-3212eb0d5eeb)

form-render demo https://codesandbox.io/s/unruffled-flower-jl78h
table-render demo https://codesandbox.io/s/sweet-euler-bdoty
fr-generator demo https://codesandbox.io/s/s13sh

**Comment by lhbxs** [comment]
装 2.x 最新版本

**Comment by Yuanyating** [comment]
> 装 2.x 最新版本

您好 我重新安装了form-render@^2.1.12 ，setValueByPath属性不再是undefined了，但是使用时仍然存在问题，我换成setValues能够解决这个问题，但是系统中多处使用该方法，并且该方法为重要方法，希望能够修复！
![截屏2023-05-10 下午4 33 29](https://github.com/alibaba/x-render/assets/43534983/bf9a169f-8041-4913-bcfe-9404ea35fe81)
