### ISSUE TITLE
DrawerList组件的编辑功能不生效

### ISSUE THREAD

**Issue by EdisonVan** [alibaba/x-render#1230]
**1.依赖仓库的版本(Dependencies versions)**：

- react：^17.x
- form-render：^2.1.19
- table-render: 无
- antd：^5.4.0

**2.问题描述(Bug description)**：
编辑任意一行，弹出Drawer后，编辑内容点击确定；确定后，数据没有更新；DrawerList组件内部函数抛错  TypeError: form.setFieldValue is not a function

**3.最小复现 demo(Reproduction demo)**：
<img width="1072" alt="image" src="https://github.com/alibaba/x-render/assets/38999461/42e9fb77-3ae4-474b-892b-731faeeae220">
<img width="363" alt="image" src="https://github.com/alibaba/x-render/assets/38999461/7ab0d02e-850d-4bcc-a0eb-7c59e2293fe3">
<img width="593" alt="image" src="https://github.com/alibaba/x-render/assets/38999461/4faa26ed-6b52-446b-bcc6-419634e5c448">

**Comment by lhbxs** [comment]
已解决，更新依赖 2.1.21

**Comment by EdisonVan** [comment]
编辑后表单内的数据未及时更新，需要再点一下 编辑 或 新增一行 表单数据才是最新的
<img width="378" alt="image" src="https://github.com/alibaba/x-render/assets/38999461/caf04500-2613-45d2-b05c-4ac4a127a5c1">
<img width="591" alt="image" src="https://github.com/alibaba/x-render/assets/38999461/96dc9ded-4a3a-4445-b49e-def1070511a9">


> 已解决，更新依赖 2.1.21
