### ISSUE TITLE
DrawerList组件编辑后表单内的数据未及时更新，需要再点一下 编辑 或 新增一行 表单数据才是最新的

### ISSUE THREAD

**Issue by EdisonVan** [alibaba/x-render#1235]
编辑后表单内的数据未及时更新，需要再点一下 编辑 或 新增一行 表单数据才是最新的
<img width="378" alt="image" src="https://github.com/alibaba/x-render/assets/38999461/caf04500-2613-45d2-b05c-4ac4a127a5c1">
<img width="591" alt="image" src="https://github.com/alibaba/x-render/assets/38999461/96dc9ded-4a3a-4445-b49e-def1070511a9">

> 已解决，更新依赖 2.1.21

_Originally posted by @EdisonVan in https://github.com/alibaba/x-render/issues/1230#issuecomment-1552774713_

**Comment by lhbxs** [comment]
是的，因为要确定新增的数据和编辑的数据，是否合规，Drawer 关闭之后不会在做校验了。保障数据的准确性

**Comment by lhbxs** [comment]
我可能理解你的意思了，https://xrender.fun/form-render/display-row#drawerlist 你看下是否能复写，然后升级到最新再看看
