### ISSUE TITLE
SimpleList 组件在 FormSlimRender中无法渲染，在DrawerList里内嵌SimpleList能正常展示

### ISSUE THREAD

**Issue by EdisonVan** [alibaba/x-render#1237]
**1.依赖仓库的版本(Dependencies versions)**：

- react：^17.x
- form-render：2.1.21
- table-render: 无
- antd：5.4.0

**2.问题描述(Bug description)**：
- SimpleList 组件在 FormSlimRender中无法渲染
<img width="415" alt="image" src="https://github.com/alibaba/x-render/assets/38999461/387c8e83-3fc7-4e07-afa9-409bf19b8a2b">

- SimpleList在DrawerList里内嵌SimpleList能正常展示
<img width="655" alt="image" src="https://github.com/alibaba/x-render/assets/38999461/106738fc-1d65-4fb8-a722-a8f481f7c64a">

**Comment by MoYuM** [comment]
可以提供下你的 schema 么

**Comment by EdisonVan** [comment]
> 可以提供下你的 schema 么

{
    "title": "solvents",
    "type": "array",
    "widget": "cardList",
    "items": {
        "type": "object",
        "title": "Solvent",
        "column": 3,
        "properties": {
            "solvent_name": {
                "title": "Solvent Name",
                "type": "string",
                "width": 120,
                "required": true
            },
            "solvent_quantity": {
                "title": "Solvent Quantity",
                "default": -1,
                "type": "number",
                "width": 120
            },
            "solvent_unit": {
                "title": "Solvent Unit",
                "default": "ml",
                "type": "string",
                "width": 120
            },
            "concentration": {
                "title": "Concentration",
                "type": "number",
                "width": 120
            },
            "concentration_unit": {
                "title": "Concentration Unit",
                "default": "%",
                "type": "string",
                "width": 120
            }
        }
    }
}

**Comment by MoYuM** [comment]
从 form-render 引入 Collapse 然后注册进 widgets 中就可以了

**Comment by EdisonVan** [comment]
你是指改为如下格式吗？
{
    type: 'object',
    column: 1,
    displayType: 'row',
    widget: 'collapse',
    properties: {
      solvents: {
        title: 'solvents',
        type: 'array',
        widget: 'cardList',
        items: {
          type: 'object',
          title: 'Solvent',
          column: 3,
          properties: {
            solvent_name: {
              title: 'Solvent Name',
              type: 'string',
              width: 120,
              required: true
            },
            solvent_quantity: {
              title: 'Solvent Quantity',
              default: -1,
              type: 'number',
              width: 120
            },
            solvent_unit: {
              title: 'Solvent Unit',
              default: 'ml',
              type: 'string',
              width: 120
            },
            concentration: {
              title: 'Concentration',
              type: 'number',
              width: 120
            },
            concentration_unit: {
              title: 'Concentration Unit',
              default: '%',
              type: 'string',
              width: 120
            }
          }
        }
      }
    }
  }
