### ISSUE TITLE
从 form-render 引入 Collapse后，SimpleList 组件在 FormSlimRender中按需加载仍无法渲染

### ISSUE THREAD

**Issue by EdisonVan** [alibaba/x-render#1239]
从 form-render 引入 Collapse 然后注册进 widgets 中就可以了

_Originally posted by @MoYuM in https://github.com/alibaba/x-render/issues/1237#issuecomment-1554248193_

你是指改为如下格式吗？
{
type: 'object',
column: 1,
displayType: 'row',
widget: 'collapse',
properties: {
solvents: {
title: 'solvents',
type: 'array',
widget: 'cardList',
items: {
type: 'object',
title: 'Solvent',
column: 3,
properties: {
solvent_name: {
title: 'Solvent Name',
type: 'string',
width: 120,
required: true
},
solvent_quantity: {
title: 'Solvent Quantity',
default: -1,
type: 'number',
width: 120
},
solvent_unit: {
title: 'Solvent Unit',
default: 'ml',
type: 'string',
width: 120
},
concentration: {
title: 'Concentration',
type: 'number',
width: 120
},
concentration_unit: {
title: 'Concentration Unit',
default: '%',
type: 'string',
width: 120
}
}
}
}
}
}

**Comment by EdisonVan** [comment]
<img width="442" alt="image" src="https://github.com/alibaba/x-render/assets/38999461/e2049e7c-702b-46c4-bfd6-75ff065027b2">
Collapse 有注入的，还是不行

**Comment by MoYuM** [comment]
首先 schema 中不用写 widget: "collapse"。
然后我看你用的是 cardList ，但你引入的是 simpleList，要改为引入 CardList

**Comment by EdisonVan** [comment]
> simpleList

好的，谢谢；
