### ISSUE TITLE
@xrenders/schema-builder: Support `schema` and `onSchemaChange` props

### ISSUE THREAD

**Issue by wangleng-shopee** [alibaba/x-render#1241]
Currently the new `@xrenders/schema-builder` only supports import and export of the schema through the buttons.

Would hope that it will support `schema` and `onSchemaChange` props (similar to `fr-generator`'s `defaultValue` and `onSchemaChange` props) so that the schema can be injected and extracted through props, rather than through user actions.

**Comment by lhbxs** [comment]
这两个api 后面会暴露，目前 设计器还没有正式发布，敬请其他，如果有其他方面的诉求，也可以在讨论组里面提建议
