### ISSUE TITLE
无法获取到设置了hidden:true的值

### ISSUE THREAD

**Issue by lisisi1997** [alibaba/x-render#1247]
**1.依赖仓库的版本(Dependencies versions)**：

- react：17.0.0
- form-render：2.1.24
- table-render:
- antd：4.21.0

**2.问题描述(Bug description)**：
const onFinish = async (value: any) => {
    console.log('finish', value);
}

value的值为：basic_auth_password: "123"

**3.出现问题的 schema demo(Reproduction schema demo)**：
```js
const schema ={
  "title": "authentication.basic",
  "description": "Basic认证参数",
  "type": "object",
  "properties": {
    "basic_auth_username": {
      "title": "账号",
      "type": "string",
      "extra": "",
      "required": true,
      "hidden": true,
      "default": "admin"
    },
    "basic_auth_password": {
      "title": "密码",
      "type": "string",
      "extra": "",
      "required": true
    }
  }
}
```

**4.最小复现 demo(Reproduction demo)**：
https://codesandbox.io/s/heuristic-neco-clgmpw

form-render demo https://codesandbox.io/s/unruffled-flower-jl78h
table-render demo https://codesandbox.io/s/sweet-euler-bdoty
fr-generator demo https://codesandbox.io/s/s13sh

**Comment by lhbxs** [comment]
你的意思是 basic_auth_username 配置的 default 值希望获取到，这种情况确实无法获取到，除非初始的时候给 form setValues 设置值，这样即使输入控件被隐藏了也可以获取到值

**Comment by lisisi1997** [comment]
您好 很高兴收到您的来信 我会尽快回复  谢谢！

**Comment by lhbxs** [comment]
还有一个配置方式我没有暴露出来，你可以试试，配置 visible: true 这种配置方式，值会被搜集，样式上是隐藏了

**Comment by lisisi1997** [comment]
> 还有一个配置方式我没有暴露出来，你可以试试，配置 visible: false 这种配置方式，值会被搜集，样式上是隐藏了

谢谢。 使用visible能符合要求

**Comment by Deja-vuuu** [comment]
> > 还有一个配置方式我没有暴露出来，你可以试试，配置 visible: false 这种配置方式，值会被搜集，样式上是隐藏了
> 
> 谢谢。 使用visible能符合要求

没办法隐藏对象?

**Comment by lisisi1997** [comment]
您好 很高兴收到您的来信 我会尽快回复  谢谢！
