### ISSUE TITLE
type: array 的字段加 className 不生效

### ISSUE THREAD

**Issue by mzl980425** [alibaba/x-render#1250]
**1.依赖仓库的版本(Dependencies versions)**：

- react：18.2.6
- form-render：2.1.25
- table-render:
- antd：5.5.1

**2.问题描述(Bug description)**：

给 "type": "array" 的表单项加 className 不生效

**3.出现问题的 schema demo(Reproduction schema demo)**：
```js
const schema = {
  "className": "class-1",
  "type": "object",
  "properties": {
    "list": {
      "className": "class-2",
      "title": "对象数组",
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "input1": {
            "title": "简单输入框",
            "type": "string"
          }
        }
      }
    }
  }
}

```

**4.最小复现 demo(Reproduction demo)**：

去 playground: https://xrender.fun/playground 随便找一个 "type": "array" 的加一个 className 即可复现

**Comment by lhbxs** [comment]
试试 2.1.26-beta.2
