### ISSUE TITLE
> 装 2.x 最新版本

### ISSUE THREAD

**Issue by Yuanyating** [alibaba/x-render#1252]
> 装 2.x 最新版本

您好 我重新安装了form-render@^2.1.12 ，setValueByPath属性不再是undefined了，但是使用时仍然存在问题，我换成setValues能够解决这个问题，但是系统中多处使用该方法，并且该方法为重要方法，希望能够修复！
![截屏2023-05-10 下午4 33 29](https://github.com/alibaba/x-render/assets/43534983/bf9a169f-8041-4913-bcfe-9404ea35fe81)

_Originally posted by @Yuanyating in https://github.com/alibaba/x-render/issues/1220#issuecomment-1541579019_

**Comment by lhbxs** [comment]
setFieldValue 不提供对外使用，请使用 setValueByPath
