### ISSUE TITLE
2.1.6为什么去除 setSchemaByPath 属性合并，只对 schema.props 进行简单合并

### ISSUE THREAD

**Issue by zxuera** [alibaba/x-render#1253]
### 对于业务复杂的表单配置，用了大量的setSchame和 setSchemaByPath 的属性合并，升级后setSchema会报错，
<img width="1042" alt="image" src="https://github.com/alibaba/x-render/assets/75372357/1ce4b12c-90e7-4ca5-9544-1d911dc6914a">
比如我想在原schema上增加一个属性或者修改一个原有属性，应该如何高效实现呢？

**Comment by lhbxs** [comment]
你的 schema 属性层级会嵌套很深吗？

**Comment by lhbxs** [comment]
具体是要做什么操作？

**Comment by lhbxs** [comment]
都到 path 级别了， setSchemaByPath  schema 还很大？

**Comment by lhbxs** [comment]
用 setSchema 报什么错？有用 2.x. 最新版试试吗？

**Comment by lhbxs** [comment]
1.x 本身是没有深度合并的能力的吧，我记得。然后 2.x 后面也和 1.x 保持了一致

**Comment by lhbxs** [comment]
最好能贴个 setSchema 的示例出来

**Comment by zxuera** [comment]
<img width="1460" alt="image" src="https://github.com/alibaba/x-render/assets/75372357/e6498c68-7125-49ef-acb1-6e5bc8112a92">
新增报错
<img width="1152" alt="image" src="https://github.com/alibaba/x-render/assets/75372357/b5a12380-f58b-4451-84f9-535cd1decd71">修改报错

**Comment by lhbxs** [comment]
form.setSchema 在什么函数里面调用的？

**Comment by zxuera** [comment]
onMount

**Comment by lhbxs** [comment]
你这种代码在1.0 跑是没有问题的是吧，我理解 ContractCode 最起码对应一个输入控件的，原 schema 都没有 ContractCode

然后 直接 设置 ContractCode : { hidden : true } 你这种事什么场景逻辑，2.0 可能没考虑到这一块，

说白了 2.0 的 schema 修改目标都是要对应到组件上的

**Comment by zxuera** [comment]
1.0没有问题哈，不同的业务场景可以需要ContractCode，可能需要展示，也可能需要hidden，也可能完全不需要，所以原 schema上没有这个属性，这个能和1.0保持一致吗？setSchema 会和原schema合并。没有就新增，有就修改

**Comment by lhbxs** [comment]
经过验证，对你所说的上述问题，无法复现
