### ISSUE TITLE
"enums": { 	"true": "是", 	"false": "否" }这种语法在最新的playground中，不兼容了

### ISSUE THREAD

**Issue by DanteLzp** [alibaba/x-render#1255]
教程案例
![image](https://github.com/alibaba/x-render/assets/26007934/63da78cf-5338-4831-bce3-a32e8091d86b)
历史代码案例
![Uploading image.png…]()

**Comment by lhbxs** [comment]
这种语法 2.x 不再兼容，合并使用请使用 props.options = [{ label: '', value: ''}]
