### ISSUE TITLE
getValues 方法使用时会获取到非schema中的数据

### ISSUE THREAD

**Issue by Now-Sprouting** [alibaba/x-render#1259]
**1.依赖仓库的版本(Dependencies versions)**：

- react：18.2.0
- form-render：2.0.13
- antd：5.2.1

**2.问题描述(Bug description)**：
form-render getValues 方法使用时会获取到非schema中的数据，在获取前会有setValues 操作（多层级时会出现）

**3.出现问题的 schema demo(Reproduction schema demo)**：
```js
const schema = {
  "type": "object",
  "displayType": "column",
  "properties": {
    "list_oh3g9h": {
      "title": "数组",
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "object_ZVRT0A": {
            "title": "对象",
            "type": "object",
            "displayType": "column",
            "props": {
              "style": {}
            },
            "properties": {
              "object_E_bikT": {
                "title": "对象",
                "type": "object",
                "properties": {
                  "name1": {
                    "title": "单行文本",
                    "type": "string",
                    "displayType": "column",
                    "props": {}
                  }
                }
              }
            }
          }
        }
      },
      "displayType": "column",
      "props": {}
    }
  }
}
```

**4.最小复现 demo(Reproduction demo)**：
1、先根据查询数据执行set操作 setValues({
  "list_oh3g9h": [
    {
      "object_ZVRT0A": {
        "object_E_bikT": {
          "name1": "a",
          "name2": "a",
        }
      }
    }
  ]
})

2、再通过getValues获取数据时发现schema中未存在的 name2 也会被提交上来。
3、期望：getValues只获取schema中存在的数据。

form-render demo https://codesandbox.io/s/unruffled-flower-jl78h
table-render demo https://codesandbox.io/s/sweet-euler-bdoty
fr-generator demo https://codesandbox.io/s/s13sh

**Comment by lhbxs** [comment]
List 场景还没有办法剥离，请确保 setValues 数据的准确性

**Comment by Now-Sprouting** [comment]
好的感谢

**Comment by Now-Sprouting** [comment]
> List 场景还没有办法剥离，请确保 setValues 数据的准确性

getValues 中的 nameList?: Path[] 入参也不支持List数组么
