### ISSUE TITLE
datePicker时间组件传入defaultValue默认值，不选时间提交时会返回多一个T的时间格式

### ISSUE THREAD

**Issue by RyzenPan** [alibaba/x-render#1263]
**1.依赖仓库的版本(Dependencies versions)**：

- react：^18.2.0
- form-render：2.1.28
- table-render: 2.0.18
- antd：^5.5.2

**2.问题描述(Bug description)**：

![image](https://github.com/alibaba/x-render/assets/56830619/8e57b1f9-6f6a-41dc-9ab2-8cc5b90550b1)
datePicker时间组件传入defaultValue默认值，不选时间提交时会返回多一个T的时间格式
**3.出现问题的 schema demo(Reproduction schema demo)**：
```js
const schema = {
  // ...
}
```

**4.最小复现 demo(Reproduction demo)**：

loginEffectTime: {
      title: '生效时间',
      type: 'string',
      defaultValue: dayjs().format('YYYY-MM-DD HH:mm:ss'),
      props: {
        showTime: { format: 'HH:mm:ss' },
        format: 'YYYY-MM-DD HH:mm:ss',
        placeholder: '请选择日期',
      },
      widget: 'datePicker',
    }
form-render demo https://codesandbox.io/s/unruffled-flower-jl78h
table-render demo https://codesandbox.io/s/sweet-euler-bdoty
fr-generator demo https://codesandbox.io/s/s13sh

**Comment by lhbxs** [comment]
我尝试了下并不能复现

**Comment by lhbxs** [comment]
![xxx](https://github.com/alibaba/x-render/assets/43236919/0bc08a85-8a0f-45ec-b8b1-7db4a58b15bf)

**Comment by RyzenPan** [comment]
> ![xxx](https://user-images.githubusercontent.com/43236919/242144973-0bc08a85-8a0f-45ec-b8b1-7db4a58b15bf.png)

很神奇，今天试了确实不会有了[捂眼][捂眼]
