### ISSUE TITLE
form-render 校验能力的一些疑问

### ISSUE THREAD

**Issue by iSozL** [alibaba/x-render#1274]
### 期望的新功能 (describe the expected new feature)
请问有没有办法能够做到不渲染 form 使用校验能力。
### 简述一下使用场景，便于开发者更好理解新功能的必要性 (describe your scenario for us to understand the need)
目前的话看起来每次校验都需要渲染一次 form 视图，比较耗时，不知道有没有办法能够做到只实例化 form，直接使用校验能力

**Comment by lhbxs** [comment]
2.x 版本？

**Comment by iSozL** [comment]
> 2.x 版本？

1.x

**Comment by iSozL** [comment]
> 2.x 版本？

1.x 似乎必须要渲染视图，我直接使用 setSchema 这些好像不能直接挂不到 schema 树上

**Comment by lhbxs** [comment]
1.x 无论在校验还是 changeValue 都会导致表单视图权限更新，这也是为什么后面有 2.x 的原因。可以尝试升级到 2.x
