### ISSUE TITLE
Next is not defined

### ISSUE THREAD

**Issue by linyufei123** [alibaba/x-render#1275]
- react："^18.2.0"
- antd："^5.2.2"

**2.JsonSchema 生成器报错：

**3 pro-cli 初始化的脚手架，引入schema-builder 后 X报Next is not defined 
![image](https://github.com/alibaba/x-render/assets/51406160/60619884-5358-4358-bb78-cf5a83a5678b)

```js
import React from 'react';

import SchemaBuilder from '@xrenders/schema-builder';

const Demo = () => {
  return (
    <div style={{ height: '80vh' }}>
      <SchemaBuilder importBtn={true} exportBtn={true} pubBtn={false} />
    </div>
  );
};

export default Demo;
```

**Comment by lhbxs** [comment]
项目需要配置
externals: {
  "react": "React",
  "react-dom": "ReactDOM",
}
注意：externals 之后需要在 html 里面引入 React、ReactDOM cdn 资源

**Comment by shiningstarts** [comment]
> 项目需要配置 externals: { "react": "React", "react-dom": "ReactDOM", } 注意：externals 之后需要在 html 里面引入 React、ReactDOM cdn 资源

请问 antd pro 这个要怎么加
