### ISSUE TITLE
嵌套的object类型添加className不生效

### ISSUE THREAD

**Issue by lisisi1997** [alibaba/x-render#1285]
**1.依赖仓库的版本(Dependencies versions)**：

- react：17.0.0
- form-render：2.2.2
- table-render:
- antd：4.22.8

**2.问题描述(Bug description)**：
给嵌套的object类型添加 className不生效
**3.出现问题的 schema demo(Reproduction schema demo)**：
```js
const schema = {
  // ...
"type": "object",
"title":"schema表单",
"properties":{
 "Switches": {
            "title": "采集开关123",
            "type": "object",
            "className": "custom-class",
            "properties": {
                "Extra_status_metrics": {
                    "title": "extra_status_metrics",
                    "type": "boolean",
                    "default": false
                },
                "Extra_innodb_metrics": {
                    "title": "extra_innodb_metrics",
                    "type": "boolean",
                    "default": false
                }
         }
}
}
}
```

**4.最小复现 demo(Reproduction demo)**：
  本地验证不生效， 同段代码在playground中添加className生效， 是form-render或者antd的版本不同吗？

form-render demo https://codesandbox.io/s/unruffled-flower-jl78h
table-render demo https://codesandbox.io/s/sweet-euler-bdoty
fr-generator demo https://codesandbox.io/s/s13sh

**Comment by lisisi1997** [comment]
升级到2.2.3解决问题。

**Comment by lhbxs** [comment]
![925743D8-7ACB-421D-A869-89D71A520E9A](https://github.com/alibaba/x-render/assets/43236919/bdd8ede1-bcb6-4edf-8f91-74062274ab94)

**Comment by lisisi1997** [comment]
您好 很高兴收到您的来信 我会尽快回复  谢谢！
