### ISSUE TITLE
nextjs13和xrender中formRender的最小实践

### ISSUE THREAD

**Issue by xiaomingyu-git** [alibaba/x-render#1299]
nextjs13和xrender中formRender的最小实践

next.config.js 中加入配置 transpilePackages: ['form-render'],
页面中引用
const FormRenderwithoutssr = dynamic(() => import('../pages/schema/formRender'), { ssr: false, });

form-render 本身不支持ssr
参考demo 
https://github.com/xiaomingyu-git/nextjs13-with-formrender

**Comment by wty-gogo** [comment]
补充一下，如果使用nextjs时启用了appdir，组件会在dynamic执行时报Uncaught Error: NEXT_DYNAMIC_NO_SSR_CODE。
解决这个错误需要在 FormRenderwithoutssr 外层包裹Suspense
