### ISSUE TITLE
tableList每组可以显示不同操作，希望支持

### ISSUE THREAD

**Issue by aiyuezhicheng** [alibaba/x-render#1304]
form-render 希望支持tableList（及其他数组类型的）组件中，可以每一组控制删除、赋值、移动操作。比如图片中第一行不显示“复制”，第二行不显示“删除”，最好能在脚本里自己控制
![image](https://github.com/alibaba/x-render/assets/37925989/28561984-3fc7-442c-9c4a-2ad471747946)

**Comment by lhbxs** [comment]
欢迎提 pr，或者你试着看下 tableList 的代码，看是否能自定义一个 tableList 这样会更灵活
