### ISSUE TITLE
form-render2.2.3版本的函数联动不起作用，实时修改值，没有触发函数表单式没有任何效果

### ISSUE THREAD

**Issue by aiyuezhicheng** [alibaba/x-render#1305]
**1.依赖仓库的版本(Dependencies versions)**：

- react：17.0.2
- form-render：2.2.3
- fr-generator: 2.8.9
- antd：

**2.问题描述(Bug description)**：
表单联动的函数表达式，根据表单某属性值是否等于某个值时，将该属性更改为必填、显示、隐藏，实时修改不起作用了。

但在旧版本的表单自定义和官网https://xrender.fun/playground 上相同schema有效果，可以必填、显示、隐藏。
![image](https://github.com/alibaba/x-render/assets/37925989/69c93918-3b1b-4009-919e-c50b4ce5192b)
![image](https://github.com/alibaba/x-render/assets/37925989/2e6b64f5-ecbc-43b9-9d0e-4d2a21b75081)
![image](https://github.com/alibaba/x-render/assets/37925989/0b026b04-4fb3-461a-b33c-cdb43d4a493a)

**3.出现问题的 schema demo(Reproduction schema demo)**：
{
                "type": "object",
                "labelWidth": 120,
                "displayType": "row",
                "globalScript": "",
                "properties": {
                  "number_t3m4VM": {
                    "bindPropertyName": "数值",
                    "title": "数值",
                    "type": "number",
                    "default": "",
                    "disabled": "{{ formData['string_EbT2ND'] === '3' }}",
                    "required": "{{ formData['string_EbT2ND'] === '1' }}",
                    "hidden": "{{ formData['string_EbT2ND'] === '2' }}",
                    "props": {}
                  },
                  "string_EbT2ND": {
                    "bindPropertyName": "字符串",
                    "title": "字符串",
                    "type": "string",
                    "default": "",
                    "disabled": false,
                    "requiredConfig": {},
                    "disabledConfig": {},
                    "hiddenConfig": {},
                    "props": {}
                  },
                }
              }

**4.最小复现 demo(Reproduction demo)**：
const form = useForm();
<FormRender
            form={form}
            schema={{
                "type": "object",
                "labelWidth": 120,
                "displayType": "row",
                "globalScript": "",
                "properties": {
                  "number_t3m4VM": {
                    "bindPropertyName": "数值",
                    "title": "数值",
                    "type": "number",
                    "default": "",
                    "disabled": "{{ formData['string_EbT2ND'] === '3' }}",
                    "required": "{{ formData['string_EbT2ND'] === '1' }}",
                    "hidden": "{{ formData['string_EbT2ND'] === '2' }}",
                    "props": {}
                  },
                  "string_EbT2ND": {
                    "bindPropertyName": "字符串",
                    "title": "字符串",
                    "type": "string",
                    "default": "",
                    "disabled": false,
                    "requiredConfig": {},
                    "disabledConfig": {},
                    "hiddenConfig": {},
                    "props": {}
                  },
                }
              }}
        />

**Comment by lhbxs** [comment]
确实有点问题，可以先改成 {{ formData.string_EbT2ND === '3' }} 这种格式

**Comment by aiyuezhicheng** [comment]
最新版2.2.9还是不能用[]的格式，有的id组件时中文，就监听不到触发不了了

**Comment by aiyuezhicheng** [comment]
@lhbxs
