### ISSUE TITLE
form-render如何获取隐藏属性值

### ISSUE THREAD

**Issue by aiyuezhicheng** [alibaba/x-render#1306]
1.依赖仓库的版本(Dependencies versions)：

form-render：2.2.3

2.问题描述(Bug description)：
如何在表单提交时获取所有值？
看了之前隐藏的问题，用visible:false,，可以把简单类型（数值、字符串等）值直接隐藏并能获取，但是复杂结构（像对象、表格列表等）如何设置visible，如何获取隐藏的值？

const onFinish = async (value: any) => {
console.log('finish', value);
}

3.出现问题的 schema demo(Reproduction schema demo)：
`const schema ={
                "type": "object",
                "labelWidth": 120,
                "displayType": "row",
                "globalScript": "",
                "properties": {
                    "number_t3m4VM": {
                        "title": "数值",
                        "type": "number",
                    },
                    "string_EbT2ND": {
                        "title": "字符串",
                        "type": "string",
                        "default": "",
                        "disabled": false,
                        "hidden": true
                    },
                    "list2_K-iD1c": {
                        "title": "数组",
                        "type": "array",  
                       "hidden": true,
                        "widget": "tableList",
                        "items": {
                            "type": "object",
                            "properties": {
                                "input_SFBbiU": {
                                    "title": "输入框",
                                    "type": "string",
                                }
                            }
                        },
                    }
                }
            }`

4.最小复现 demo(Reproduction demo)：

**Comment by aiyuezhicheng** [comment]
有直接获取所有值包含隐藏的方法么？

**Comment by lhbxs** [comment]
getValues(true)
