### ISSUE TITLE
form-render 1.*版本  列表  给某条数据中的某个字段 通过shema加属性  要怎么做 或者有没有建议方案

### ISSUE THREAD

**Issue by Jocelyn329** [alibaba/x-render#1309]
### 简述一下使用场景，便于开发者更好理解新功能的必要性 (describe your scenario for us to understand the need)

情景：
列表有1 2 3.........条数据   字段分别为ABC  我需要对第1条数据的某个字段做单独的属性处理  要怎么做呢  
目前setSchemaByPath的话 整个列都会加上该属性

**Comment by lhbxs** [comment]
目前好像不能单独处理，不过如果是依赖同级某个数据字段可以用函数表达式 {{ rootValue.xx }}

**Comment by Jocelyn329** [comment]
rootvalue 是当前行数据？


---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2023年06月20日 20:34 |
| 收件人 | alibaba/x-render ***@***.***> |
| 抄送人 | jocelyn ***@***.***>,
Author ***@***.***> |
| 主题 | Re: [alibaba/x-render] form-render 1.*版本 列表 给某条数据中的某个字段 通过shema加属性 要怎么做 或者有没有建议方案 (Issue #1309) |

目前好像不能单独处理，不过如果是依赖同级某个数据字段可以用函数表达式 {{ rootValue.xx }}
