### ISSUE TITLE
searchForm支持searchWrapper配置

### ISSUE THREAD

**Issue by songdy** [alibaba/x-render#1313]
### 期望的新功能 (describe the expected new feature)
tableRender的searchForm提供searchWrapper配置，可扩展查询表单功能。类似tableRender的tableWrapper。
### 简述一下使用场景，便于开发者更好理解新功能的必要性 (describe your scenario for us to understand the need)
比如我们在查询表单下展示当前所筛选的条件，如下图：
![image](https://github.com/alibaba/x-render/assets/8369801/73bd52f0-74bc-484c-adca-4963de1f8fb3)

**Comment by lhbxs** [comment]
可以试试这个 https://xrender.fun/table-render/custom-table

**Comment by RyzenPan** [comment]
> 可以试试这个 https://xrender.fun/table-render/custom-table

我们是想自定义搜索表单区域，上面这个demo是自定义表格的哈~
