### ISSUE TITLE
部分属性是不是没了，但文档还有示例

### ISSUE THREAD

**Issue by LiMao00** [alibaba/x-render#1314]
**1.依赖仓库的版本(Dependencies versions)**：

- form-render：2.2.5

**2.问题描述(Bug description)**：
![image](https://github.com/alibaba/x-render/assets/99939885/0db5018f-57d4-4746-99bb-d2be5e7791cd)
部分属性是不是没了，但文档还有示例

**Comment by lhbxs** [comment]
是的，我更新一下文档，像这种复杂的配置，直接配置自定义模式 footer={() => (
        <Button>自定义</Button>
      )}
