### ISSUE TITLE
form-render 增加支持加载后事件

### ISSUE THREAD

**Issue by aiyuezhicheng** [alibaba/x-render#1315]
form-render 能不能增加一个是加载后事件，这样可以方便在加载完schema之后，有其他操作

**Comment by lhbxs** [comment]
https://xrender.fun/form-render/advaced-example#%E4%B8%8B%E6%8B%89%E9%80%89%E9%A1%B9%E5%BC%82%E6%AD%A5%E5%8A%A0%E8%BD%BD

**Comment by lhbxs** [comment]
多看看官方文档

**Comment by is-tongben** [comment]
> 多看看官方文档

这个写法有问题啊，现在用的1.x版本 setSchemaByPath 报错找不到，升级到2.x就没问题了，看了升级文档在2.x修复了
