### ISSUE TITLE
form-render 表格列表tableList的列设置hidden：true,在表格中还会显示出来

### ISSUE THREAD

**Issue by aiyuezhicheng** [alibaba/x-render#1316]
**1.依赖仓库的版本(Dependencies versions)**：

- form-render：2.1.29

**2.问题描述(Bug description)**：
表格列表的列设置hidden：true,在表格中还会显示出来。如果不用hidden设置隐藏，还可以用什么方法去设置？用actionColumnProps好像也不行

**3.出现问题的 schema demo(Reproduction schema demo)**：
```js
const schema = 
  {
  type: 'object',
  displayType: 'row',
  properties: {
    list: {
      title: '两层数组-有隐藏属性',
      type: 'array',
      widget: 'tableList',
      items: {
        type: 'object',
        properties: {
          input1: {
            title: '简单输入框',
            type: 'string',
            hidden: true,
          },
        },
      },
    },
  },
}

```
![image](https://github.com/alibaba/x-render/assets/37925989/6d6ea4c0-776c-4e50-a034-eb056f973502)

**Comment by lhbxs** [comment]
先更新本地版本道 2.2.9 看看是否有问题
