### ISSUE TITLE
能否升级`form-render`中的`color-picker`组件为`antd`的组件?

### ISSUE THREAD

**Issue by ilovelll** [alibaba/x-render#1317]
### 能否升级`form-render`中的`color-picker`组件为`antd`的组件?
目前项目的依赖的版本太旧, 需要依赖React16, 可否直接使用antd内置的color-picker呢?
https://ant.design/components/color-picker-cn
![QQ截图20230626115531](https://github.com/alibaba/x-render/assets/5793799/846ef603-c903-4aa0-9a48-4aba155763bf)

**Comment by lhbxs** [comment]
你如果不想用内置的 picker 组件，完全可以通过 widgets = {{ Color: antdColor }} 进行覆盖
