### ISSUE TITLE
form-render 2.2.9表格列表tableList的列设置hidden：true,在表格中还会显示出来

### ISSUE THREAD

**Issue by aiyuezhicheng** [alibaba/x-render#1320]
1.依赖仓库的版本(Dependencies versions)：

form-render：2.2.9
2.问题描述(Bug description)：
表格列表的列设置hidden：true,在表格中还会显示出来。如果不用hidden设置隐藏，还可以用什么方法去设置？用actionColumnProps好像也不行

3.出现问题的 schema demo(Reproduction schema demo)：
```js
const schema = 
  {
  "type": "object",
  "labelWidth": 120,
  "displayType": "row",
  "globalScript": "",
  "properties": {
    "tableList_dYubm5": {
      "title": "数组",
      "type": "array",
      "widget": "tableList",
      "items": {
        "type": "object",
        "properties": {
          "input_KVVOvh": {
            "title": "输入框-隐藏",
            "type": "string",
            "hidden": true,
          },
          "input_wGLGdL": {
            "title": "输入框-必填",
            "type": "string",
            "required": true,
          },
          "input_mY-1Xy": {
            "title": "输入框",
            "type": "string",
          }
        }
      },
    }
  }
```
![image](https://github.com/alibaba/x-render/assets/37925989/ffed0993-7ffa-4798-8b82-5b1ce5cc62b4)

**Comment by lhbxs** [comment]
tableList 为什么有隐藏的逻辑，难道你要做联动隐藏吗？

**Comment by aiyuezhicheng** [comment]
对， 想要表格中一列默认隐藏，通过一行中其他属性值判断再赋给这个隐藏属性值;而且如果设置一列为隐藏，正常的话应该不显示，现在列头会显示出来。


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "alibaba/x-render"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年6月27日(星期二) 上午10:56
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [alibaba/x-render] form-render 2.2.9表格列表tableList的列设置hidden：true,在表格中还会显示出来 (Issue #1320)





 
tableList 为什么有隐藏的逻辑，难道你要做联动隐藏吗？
