### ISSUE TITLE
咨询：多级深层嵌条Object对象中的 联动

### ISSUE THREAD

**Issue by xyy7260** [alibaba/x-render#1323]
### 简述一下使用场景，便于开发者更好理解新功能的必要性 (describe your scenario for us to understand the need)
多级深层嵌条Object对象中的 联动， 比如我要在嵌套中控制显示： 我觉得有点麻烦
  "hidden": "{{ formData.xxx.xxx.xxx.xxx.xxx.xxx.xxx  }}"
因为我们所有表单都是用过Excel 生成的， 所以觉得 watch 并不太需要，并且在网上没看到有好的方式控制联动

**Comment by xyy7260** [comment]
偷个懒看看有没有好的方式， 没有的话 只能 自己个函数 去 处理 欠条层级关系联动了

**Comment by lhbxs** [comment]
没有，或者有好的方式，可以提 pr
