### ISSUE TITLE
table-render内置工具栏表格筛选传入指定的columnsSettingValue，首次点击会丢失传入的筛选结果

### ISSUE THREAD

**Issue by RyzenPan** [alibaba/x-render#1325]
**1.依赖仓库的版本(Dependencies versions)**：

- react：^18.2.0
- form-render：^2.2.9
- table-render: ^2.0.19
- antd：^5.6.3

**2.问题描述(Bug description)**：
![image](https://github.com/alibaba/x-render/assets/56830619/e68c8dc6-c112-40b0-9e83-774461c0f2a6)
之前提的丢失结果问题已经修复，但现在发现还会有一个小问题，麻烦大佬们看看
table-render内置工具栏表格筛选传入指定的columnsSettingValue，首次点击会丢失传入的筛选结果
需求是希望我传入columnsSettingValue指定了显示的列，然后点击齿轮时依然是我传入指定显示的列数据，因为需要保存用户上次勾选的显示结果，所以需要解决这个问题，谢谢各位大佬了。

**3.出现问题的 schema demo(Reproduction schema demo)**：
```js
const schema = {
  // ...
}
```

**4.最小复现 demo(Reproduction demo)**：

form-render demo https://codesandbox.io/s/unruffled-flower-jl78h
table-render demo https://codesandbox.io/s/sweet-euler-bdoty
fr-generator demo https://codesandbox.io/s/s13sh

**Comment by lhbxs** [comment]
欢迎提 pr

**Comment by RyzenPan** [comment]
好的，已经提了

**Comment by RyzenPan** [comment]
请问什么时候合代码？

**Comment by lhbxs** [comment]
已经修复
