### ISSUE TITLE
SchemaBuilder上创建一个下拉框的JSonSchema拿到FRMobile上功能缺失

### ISSUE THREAD

**Issue by supermanklk** [alibaba/x-render#1326]
在pc的SchemaBuilder上创建一个下拉框，JSonSchema拿到FRMobile上展示有问题。

SchemaBuilder下拿到的对象是如下 

SchemaBuilder导出
`'fr-lfc4': {
      'title': '下拉单选',
      'type': 'string',
      'props': {
        'options': [
          {
            'label': 'A',
            'value': 'A',
          },
          {
            'label': 'B',
            'value': 'B',
          },
        ],
        'placeholder': '请选择',
      },
      'widget': 'select',
    },`

import FormRender, { useForm } from 'form-render-mobile'，

在 FormRender 功能有问题，如图。

<img width="477" alt="image" src="https://github.com/alibaba/x-render/assets/28639384/dd574d24-7f5e-46b1-80e0-7796f7ac8ba6">

解决该问题：必须手动将 fr-lfc4 对象字段值改了才行 ，如下：

有问题的
`'fr-lfc4': {
      'title': '下拉单选',
      'type': 'string',
      'props': {
        'options': [
          {
            'label': 'A',
            'value': 'A',
          },
          {
            'label': 'B',
            'value': 'B',
          },
        ],
        'placeholder': '请选择',
      },
      'widget': 'select',
    },`

手动修改的（没问题）
`'fr-lfc4': {
      'title': '下拉单选',
      'type': 'array',
      'props': {
        'options': [
          {
            'label': 'A',
            'value': 'A',
          },
          {
            'label': 'B',
            'value': 'B',
          },
        ],
        'placeholder': '请选择',
      },
      'widget': 'cascader',
    },
`
<img width="421" alt="image" src="https://github.com/alibaba/x-render/assets/28639384/8a7a4546-7c6d-482b-9e9c-5046242ddb96">

请问必须手动处理还是功能缺陷？

**Comment by supermanklk** [comment]
与组件维护者钉钉群内交流，2023-07-03：

<img width="618" alt="image" src="https://github.com/alibaba/x-render/assets/28639384/23db1f7e-bdc7-43ee-beca-7ac340576774">

**Comment by lhbxs** [comment]
目前 PC 的组件 和 Mobile 的组件不是互通的，所以需要分开搭建，

SchemaBuilder 还未发布正式版本，等正式发布之后，会建设 mobile 场景可视化搭建
