### ISSUE TITLE
列表类型的组件互相嵌套，能否通过rootValue的形式控制内部列表的显示和隐藏？

### ISSUE THREAD

**Issue by GoRolo** [alibaba/x-render#1329]
**开发过程中包版本为："form-render": "^2.2.9",**
**发现的问题如截图所示**
1. 序号1的组件可以正常通过rootValue显示或者隐藏
2. 序号2的组件为一个列表，这时发现不能通过rootValue控制显示和隐藏
![image](https://github.com/alibaba/x-render/assets/16891232/16e22eb3-9dbe-4b40-96a9-6273a07186ec)
**schema如下**
`const schema = {
  type: 'object',
  properties: {
    'fr-8z7n': {
      title: '基础配置',
      description: '活动基础信息配置区域',
      column: 1,
      type: 'object',
      widget: 'card',
      properties: {
        'fr-hh6h': {
          title: '网页标题',
          type: 'string',
          required: true,
          widget: 'input',
        },
        'fr-advs': {
          title: '背景主题色',
          required: true,
          widget: 'color',
        },
        'fr-fjsf': {
          title: '头图',
          required: true,
          widget: 'imageInput',
        },
        'fr-45x': {
          title: '我的奖品图标',
          required: true,
          widget: 'imageInput',
        },
        'fr-jnnj': {
          title: '我的奖品跳转链接',
          default: 'https://m.xiwang.com/628f7e716e9a5e391a75b625.html',
          props: {
            addonText: '测试链接',
          },
          required: true,
          maxWidth: '340px',
          widget: 'urlInput',
        },
        'fr-efre': {
          title: '地址填写页跳转链接',
          default: 'https://m.xiwang.com/628f76c703c284521a3e0c40.html',
          props: {
            addonText: '测试链接',
          },
          required: true,
          widget: 'urlInput',
        },
        'fr-iry6': {
          title: '活动规则图标',
          widget: 'imageInput',
        },
        'fr-dv6h': {
          title: '活动规则跳转链接',
          default: '',
          props: {
            addonText: '测试链接',
          },
          widget: 'urlInput',
        },
        'fr-aa1e': {
          title: '分享卡片',
          required: true,
          widget: 'imageInput',
        },
        'fr-bnaz': {
          title: '分享标题',
          type: 'string',
          required: true,
          widget: 'input',
        },
        'fr-ak9t': {
          title: '分享描述',
          type: 'string',
          required: true,
          widget: 'input',
        },
        'fr-8b66': {
          title: '分享链接',
          props: {
            addonText: '测试链接',
          },
          required: true,
          widget: 'urlInput',
        },
        'fr-1o83': {
          title: '分享海报',
          required: true,
          widget: 'imageInput',
        },
        'fr-5532': {
          title: '抽奖开始日期',
          type: 'string',
          props: {
            placeholder: '请选择日期',
          },
          required: true,
          maxWidth: '340px',
          widget: 'datePicker',
        },
        'fr-f76f': {
          title: '抽奖开始时间',
          type: 'string',
          format: 'time',
          props: {
            placeholder: '请选择时间',
          },
          required: true,
          maxWidth: '340px',
          widget: 'timePicker',
        },
        'fr-g2nh': {
          title: '抽奖结束日期',
          type: 'string',
          props: {
            placeholder: '请选择日期',
          },
          required: true,
          maxWidth: '340px',
          widget: 'datePicker',
        },
        'fr-51n0': {
          title: '抽奖结束时间',
          type: 'string',
          format: 'time',
          props: {
            placeholder: '请选择时间',
          },
          required: true,
          maxWidth: '340px',
          widget: 'timePicker',
        },
      },
    },
    rulesConfig: {
      title: '任务配置',
      column: 1,
      type: 'object',
      widget: 'card',
      maxWidth: '340px',
      properties: {
        isShowTaskModule: {
          title: '是否展示任务模块',
          default: true,
          type: 'boolean',
          required: true,
          widget: 'switch',
        },
        'fr-2b9x': {
          title: '任务模块标题图片',
          required: true,
          maxWidth: '340px',
          widget: 'imageInput',
          hidden: '{{formData.rulesConfig.isShowTaskModule === false}}',
        },
        list: {
          title: '可以增加抽奖的行为',
          type: 'array',
          hidden: '{{formData.rulesConfig.isShowTaskModule === false}}',
          items: {
            title: '抽奖行为',
            column: 1,
            type: 'object',
            widget: 'lineTitle',
            properties: {
              ruleType: {
                title: '行为类型',
                type: 'string',
                props: {
                  options: [
                    {
                      label: '分享',
                      value: 'A',
                    },
                    {
                      label: '购课',
                      value: 'B',
                    },
                  ],
                  placeholder: '请选择',
                },
                widget: 'select',
              },
              'fr-jj3b': {
                title: '行为描述',
                type: 'string',
                widget: 'input',
                hidden: '{{rootValue.ruleType === "B"}}',
              },
              shareChannel: {
                title: '分享渠道',
                type: 'array',
                hidden: '{{rootValue.ruleType === "B"}}',
                items: {
                  title: '渠道',
                  description: '',
                  column: 1,
                  type: 'object',
                  widget: 'lineTitle',
                  properties: {
                    shareChannel: {
                      title: '分享渠道',
                      type: 'string',
                      props: {
                        options: [
                          {
                            label: '微信好友',
                            value: 'A',
                          },
                          {
                            label: '朋友圈',
                            value: 'B',
                          },
                        ],
                        placeholder: '请选择',
                      },
                      widget: 'select',
                    },
                    shareChannelType: {
                      title: '分享类型',
                      type: 'string',
                      props: {
                        options: [
                          {
                            label: '小程序',
                            value: 'D',
                          },
                          {
                            label: '微信卡片',
                            value: 'C',
                          },
                        ],
                        placeholder: '请选择',
                      },
                      widget: 'select',
                    },
                    xcxId: {
                      title: '小程序ID',
                      type: 'string',
                      widget: 'input',
                      // hidden: '{{rootValue.shareChannelType !== "C"}}',
                    },
                    shareIcon: {
                      title: '分享缩略图',
                      widget: 'imageInput',
                      // hidden: '{{rootValue.shareChannelType !== "D"}}',
                    },
                  },
                },
              },
            },
          },
          widget: 'cardList',
          labelCol: {
            span: 4,
          },
          wrapperCol: {
            span: 6,
          },
        },
      },
    },
  },
  displayType: 'row',
  maxWidth: '340px',
};`

**Comment by lhbxs** [comment]
怎么注释了一些代码

**Comment by GoRolo** [comment]
这有影响吗？我打开也不行的

**Comment by GoRolo** [comment]
> 怎么注释了一些代码

没影响吧，我打开也不行呀，而且我注视的这里也发现问题了，这里是一个列表，通过rootValue控制不同选项展示不同的组件，但发现点击新增一条之后，上一条的状态被清除了

**Comment by lhbxs** [comment]
你把多余的 schema 去掉，比如基础配置，因为发到我这边就是没有格式的字符串了。我直接贴进去会报错的

**Comment by GoRolo** [comment]
> 你把多余的 schema 去掉，比如基础配置，因为发到我这边就是没有格式的字符串了。我直接贴进去会报错的

稍等

**Comment by GoRolo** [comment]
`
{
   "type": "object",
   "properties": {
      "rulesConfig": {
         "title": "任务配置",
         "column": 1,
         "type": "object",
         "widget": "card",
         "maxWidth": "340px",
         "properties": {
            "isShowTaskModule": {
               "title": "是否展示任务模块",
               "default": true,
               "type": "boolean",
               "required": true,
               "widget": "switch"
            },
            "fr-2b9x": {
               "title": "任务模块标题图片",
               "required": true,
               "maxWidth": "340px",
               "widget": "imageInput",
               "hidden": "{{formData.rulesConfig.isShowTaskModule === false}}"
            },
            "list": {
               "title": "可以增加抽奖的行为",
               "type": "array",
               "hidden": "{{formData.rulesConfig.isShowTaskModule === false}}",
               "items": {
                  "title": "抽奖行为",
                  "column": 1,
                  "type": "object",
                  "widget": "lineTitle",
                  "properties": {
                     "ruleType": {
                        "title": "行为类型",
                        "type": "string",
                        "props": {
                           "options": [
                              {
                                 "label": "分享",
                                 "value": "A"
                              },
                              {
                                 "label": "购课",
                                 "value": "B"
                              }
                           ],
                           "placeholder": "请选择"
                        },
                        "widget": "select"
                     },
                     "fr-jj3b": {
                        "title": "行为描述",
                        "type": "string",
                        "widget": "input",
                        "hidden": "{{rootValue.ruleType === \"B\"}}"
                     },
                     "shareChannel": {
                        "title": "分享渠道",
                        "type": "array",
                        "hidden": "{{rootValue.ruleType === \"B\"}}",
                        "items": {
                           "title": "渠道",
                           "description": "",
                           "column": 1,
                           "type": "object",
                           "widget": "lineTitle",
                           "properties": {
                              "shareChannel": {
                                 "title": "分享渠道",
                                 "type": "string",
                                 "props": {
                                    "options": [
                                       {
                                          "label": "微信好友",
                                          "value": "A"
                                       },
                                       {
                                          "label": "朋友圈",
                                          "value": "B"
                                       }
                                    ],
                                    "placeholder": "请选择"
                                 },
                                 "widget": "select"
                              },
                              "shareChannelType": {
                                 "title": "分享类型",
                                 "type": "string",
                                 "props": {
                                    "options": [
                                       {
                                          "label": "小程序",
                                          "value": "D"
                                       },
                                       {
                                          "label": "微信卡片",
                                          "value": "C"
                                       }
                                    ],
                                    "placeholder": "请选择"
                                 },
                                 "widget": "select"
                              },
                              "xcxId": {
                                 "title": "小程序ID",
                                 "type": "string",
                                 "widget": "input",
                                 "hidden": "{{rootValue.shareChannelType !== \"C\"}}"
                              },
                              "shareIcon": {
                                 "title": "分享缩略图",
                                 "widget": "imageInput",
                                 "hidden": "{{rootValue.shareChannelType !== \"D\"}}"
                              }
                           }
                        }
                     }
                  }
               },
               "widget": "cardList",
               "labelCol": {
                  "span": 4
               },
               "wrapperCol": {
                  "span": 6
               }
            }
         }
      }
   },
   "displayType": "row",
   "maxWidth": "340px"
}
`

**Comment by GoRolo** [comment]
> 你把多余的 schema 去掉，比如基础配置，因为发到我这边就是没有格式的字符串了。我直接贴进去会报错的

用这个吧，我发现把下面这段代码贴在官网的playground中测试是可以的，但是放在我本地通过formRender渲染就会有我描述的问题

`{
   "type": "object",
   "properties": {
      "rulesConfig": {
         "title": "任务配置",
         "column": 1,
         "type": "object",
         "widget": "card",
         "maxWidth": "340px",
         "properties": {
            "isShowTaskModule": {
               "title": "是否展示任务模块",
               "default": true,
               "type": "boolean",
               "required": true,
               "widget": "switch"
            },
            "fr-2b9x": {
               "title": "任务模块标题图片",
               "required": true,
               "maxWidth": "340px",
               "widget": "imageInput",
               "hidden": "{{formData.rulesConfig.isShowTaskModule === false}}"
            },
            "list": {
               "title": "可以增加抽奖的行为",
               "type": "array",
               "hidden": "{{formData.rulesConfig.isShowTaskModule === false}}",
               "items": {
                  "title": "抽奖行为",
                  "column": 1,
                  "type": "object",
                  "widget": "lineTitle",
                  "properties": {
                     "ruleType": {
                        "title": "行为类型",
                        "type": "string",
                        "props": {
                           "options": [
                              {
                                 "label": "分享",
                                 "value": "A"
                              },
                              {
                                 "label": "购课",
                                 "value": "B"
                              }
                           ],
                           "placeholder": "请选择"
                        },
                        "widget": "select"
                     },
                     "fr-jj3b": {
                        "title": "行为描述",
                        "type": "string",
                        "widget": "input",
                        "hidden": "{{rootValue.ruleType === \"B\"}}"
                     },
                     "shareChannel": {
                        "title": "分享渠道",
                        "type": "array",
                        "hidden": "{{rootValue.ruleType === \"B\"}}",
                        "items": {
                           "title": "渠道",
                           "description": "",
                           "column": 1,
                           "type": "object",
                           "widget": "lineTitle",
                           "properties": {
                              "shareChannel": {
                                 "title": "分享渠道",
                                 "type": "string",
                                 "props": {
                                    "options": [
                                       {
                                          "label": "微信好友",
                                          "value": "A"
                                       },
                                       {
                                          "label": "朋友圈",
                                          "value": "B"
                                       }
                                    ],
                                    "placeholder": "请选择"
                                 },
                                 "widget": "select"
                              },
                              "shareChannelType": {
                                 "title": "分享类型",
                                 "type": "string",
                                 "props": {
                                    "options": [
                                       {
                                          "label": "小程序",
                                          "value": "D"
                                       },
                                       {
                                          "label": "微信卡片",
                                          "value": "C"
                                       }
                                    ],
                                    "placeholder": "请选择"
                                 },
                                 "widget": "select"
                              },
                              "xcxId": {
                                 "title": "小程序ID",
                                 "type": "string",
                                 "widget": "input",
                                 "hidden": "{{rootValue.shareChannelType !== \"C\"}}"
                              },
                              "shareIcon": {
                                 "title": "分享缩略图",
                                 "widget": "imageInput",
                                 "hidden": "{{rootValue.shareChannelType !== \"D\"}}"
                              }
                           }
                        }
                     }
                  }
               },
               "widget": "cardList",
               "labelCol": {
                  "span": 4
               },
               "wrapperCol": {
                  "span": 6
               }
            }
         }
      }
   },
   "displayType": "row",
   "maxWidth": "340px"
}`

**Comment by lhbxs** [comment]
FormRender 和 antd 的版本，还有 React 的

**Comment by GoRolo** [comment]
> FormRender 和 antd 的版本，还有 React 的

"antd": "^4.24.1",
"form-render": "^2.2.9",
"@umijs/max": "^4.0.28",
**umi依赖的react版本为**
"devDependencies": {
    "react": "18.1.0",
    "react-dom": "18.1.0"
  },

**Comment by GoRolo** [comment]
> FormRender 和 antd 的版本，还有 React 的

看起来我的版本是满足条件的，你这边有推荐使用的版本吗？

**Comment by GoRolo** [comment]
> 2.2.11
已经升级了，但发现没生效，还是原来的问题

**Comment by GoRolo** [comment]
> form-render 升级到 2.2.11，问题已修复

已经升级了，但发现没生效，还是原来的问题

**Comment by lhbxs** [comment]
恩，我调试的时候把外部的list hidden 条件屏蔽了导致不触发，升级到 2.2.12
