### ISSUE TITLE
getValues 传入PathList异常

### ISSUE THREAD

**Issue by Now-Sprouting** [alibaba/x-render#1335]
**1.依赖仓库的版本(Dependencies versions)**：

- react：
- form-render：
- table-render:
- antd：

**2.问题描述(Bug description)**：
getValues(['name'])中传 PathList 报错，看了下源码 getFieldName 这个函数应该有问题
**3.出现问题的 schema demo(Reproduction schema demo)**：
任意schema
```
**4.最小复现 demo(Reproduction demo)**：
https://codesandbox.io/s/elegant-ardinghelli-fl7c4t?file=/App.jsx

**Comment by lhbxs** [comment]
获取某个控件的值，请使用 form.getValueByPath('obj.boxes')
