### ISSUE TITLE
设计器报错 Component Not Found

### ISSUE THREAD

**Issue by YangZhanZhi** [alibaba/x-render#1343]
**1.依赖仓库的版本(Dependencies versions)**：

- react："^17.0.0"
- form-render："^2.2.13"
- table-render:
- antd："^4.20.0"
- xrenders/schema-builder: "^1.0.0-alpha.5"

**2.问题描述(Bug description)**：
在edge浏览器中出现（谷歌和火狐测试没有出现）
首次加载SchemaBuilder正常
切换页面后回来，大概率出现FormRender Component Not Found
![企业微信截图_16895862025911](https://github.com/alibaba/x-render/assets/138113805/4b7fbd69-2b3d-4c3a-8a0e-8c817e4ab3c5)
![企业微信截图_16895862372448](https://github.com/alibaba/x-render/assets/138113805/7c8b025b-7720-466a-81d5-8e28ded5fd9d)
出现报错后，使用F5刷新继续会报错，需要“清除缓存并进行硬刷新”才能重新使用

**3.出现问题的 schema demo(Reproduction schema demo)**：
```js
  <SchemaBuilder
      importBtn={true}
      exportBtn={true}
      pubBtn={false}
   />

```

**Comment by ziyingjing** [comment]
设计器2.0啥时候发正式版？现在官方提供的demo都报错https://codesandbox.io/s/wzfzr2?file=/App.tsx

**Comment by Hokkaii** [comment]
设计器2.0啥时候发正式版？现在官方提供的demo都报错https://codesandbox.io/s/wzfzr2?file=/App.tsx

**Comment by lhbxs** [comment]
大概 930 会有正式版，是不是 edge的 IE 模式，设计器底层依赖的是阿里低代码引擎，尽量使用 chrome

**Comment by lovekobe24** [comment]
在谷歌浏览器也出现了上述错误 react18.2.0,  antd5.9.0

**Comment by laogui** [comment]
schema-builder的源代码不开源？里面都是内嵌的iframe

**Comment by wangqiangstar** [comment]
这个问题解决了吗

**Comment by wangqiangstar** [comment]
在哪个版本可以解决一下这个报错呢，很期待

**Comment by freesaber** [comment]
这个问题咋解决啊，项目不维护了么，蛋疼啊。
vite 5.x
react 18.x
antd 5.20.x

**Comment by jinmuyano** [comment]
偶发.问题解决了吗
