### ISSUE TITLE
schema-builder": Props Types Error 

### ISSUE THREAD

**Issue by ruoduan-hub** [alibaba/x-render#1347]
**1.依赖仓库的版本(Dependencies versions)**：👇🏻

- "@xrenders/schema-builder": "^1.0.0-alpha.5"
- react：18.0.0
- form-render："^2.2.13"
- table-render: X
- antd：^5.7.0"

**2.问题描述(Bug description)**：

SchemaBuilder 的 Props 👇🏻

```js
interface IProps {
    widgets: any;
    settings: any;
}
declare const Design: (props: IProps) => JSX.Element;
export default Design;

```

- 和文档描述的 `<SchemaBuilder importBtn={true} exportBtn={true} pubBtn={false} /> ` 不符，且 Button 的 `onClick` 方法并不会生效，要怎么拿到 schema data 呢 ？

**Comment by Hokkaii** [comment]
同问

**Comment by feifei128** [comment]
同文

**Comment by feifei128** [comment]
同问～～

**Comment by lhbxs** [comment]
pubBtn={{ text: '确认',  onClick: (schema) => {console.log(schema}}，这样就可以拿到吧
