### ISSUE TITLE
schema-builder iframe 中 的#app 样式 "100vh" 会导致长表单被切断无法下拉

### ISSUE THREAD

**Issue by ruoduan-hub** [alibaba/x-render#1350]
1.依赖仓库的版本(Dependencies versions)：👇🏻

"@xrenders/schema-builder": "^1.0.0-alpha.5"
react：18.0.0
form-render："^2.2.13"
table-render: X
antd：^5.7.0"

- react：
- form-render：
- table-render:
- antd：

**2.问题描述(Bug description)**：

schema-builder iframe 中 的#app 样式 "100vh" 会导致长表单被切断无法下拉

**4.最小复现 demo(Reproduction demo)**：

 - https://xrender.fun/schema-builder( 文档 demo 就有这个问题 )

- 手动在 `#app` 添加 overflow-y: auto 可以蹩脚的暂时解决

**Comment by lhbxs** [comment]
更新版本 1.0.0-alpha.6
