### ISSUE TITLE
father-build更新

### ISSUE THREAD

**Issue by jangdelong** [alibaba/x-render#1356]
### 期望的新功能 (describe the expected new feature)
father-build为什么还没更新到father 4.x版本
### 简述一下使用场景，便于开发者更好理解新功能的必要性 (describe your scenario for us to understand the need)
father-build 1.17.2版本太老了

**Comment by lhbxs** [comment]
目前这块有什么问题吗？并没有去持续更新

**Comment by jangdelong** [comment]
问题不大。只是最近借鉴了你们xrender的这个monorepo脚手架，发现father build版本比较低，可能会存在一些隐患，比如，alias问题，不支持esbuild等。所以，建议你们升级。

**Comment by lhbxs** [comment]
好的。后面空了升级一版
