### ISSUE TITLE
国际化不支持繁体和日文是否可以修改或者自定义 label 、description、extra这些标签和提示呢？

### ISSUE THREAD

**Issue by xyy7260** [alibaba/x-render#1357]
### 简述一下使用场景，便于开发者更好理解新功能的必要性 (describe your scenario for us to understand the need)
我看了一下 国际化仅支持 英文和中文。 但是不支持繁体、日文等这些， 所以我想把i18加入在其中只能自己定义的方式解决。

array 数组中 新增一条这个按钮是否也可以一起自定义？ 我想改成icon ， 上下移 删除是否同样也可以改成icon

**Comment by xyy7260** [comment]
目前在自定义组件中 找到  [description 和label 的widget](https://xrender.fun/form-render/advanced-widget#labelwidget)  ，但是没有找到 extra 、tooItip 的定义方式。

**Comment by xyy7260** [comment]
想到一个解决方案就 ，  更改 extra 、tooItip  在json 中名字随便替换一个单词。 然后在 自定义组件中（input ,select...） 手写一个  extra 、tooItip  。 这样会很麻烦就是 你需要把所有组件手写一次

**Comment by lhbxs** [comment]
https://xrender.fun/form-render/api-props

ListOperate 这个属性配置，可以把操作改成 icon 模式

**Comment by lhbxs** [comment]
国际化成面，你完全可以把 schema 翻译好在传进去来吧，没懂你这块。
