### ISSUE TITLE
Demo 无法运行

### ISSUE THREAD

**Issue by wahello** [alibaba/x-render#1359]

**Comment by lhbxs** [comment]
这个需要在项目工程里面做工程改造的，
externals: {
  "react": "React",
  "react-dom": "ReactDOM",
}

**Comment by wahello** [comment]
package.json吗?

**Comment by wahello** [comment]
@lhbxs  SchemaBuilder 的官方[demo](https://codesandbox.io/p/sandbox/suspicious-babycat-wzfzr2) 报错, 无法运行.   

```
externals: {
"react": "React",
"react-dom": "ReactDOM",
}
```
这个加在哪个文件里?
