### ISSUE TITLE
列表组件 cardList 能否支持标题配置变量，折叠状态时展示具体 items 的某个属性内容

### ISSUE THREAD

**Issue by Ariel-Cheng** [alibaba/x-render#1362]
### 期望的新功能 (describe the expected new feature)
- 列表组件 cardList 新增 titleKey 配置。
- 只有当 type array，widget 为 cardList ，  items.type 为 object 时生效。
- 生效后卡片的标题跟随对象 key 的内容变化

### 简述一下使用场景，便于开发者更好理解新功能的必要性 (describe your scenario for us to understand the need)
- 当使用 cardList 配置大量数据时，能够通过指定 titleKey  ，实现折叠状态下快速找到具体的数据位置，同时多条数据下的数据上移、下移等操作也会更加方便。 
![image](https://github.com/alibaba/x-render/assets/16719388/5a06861c-75cd-4a30-b527-7d0d159b7fef)

**Comment by lhbxs** [comment]
欢迎提 pr
