### ISSUE TITLE
表单后面跟随固定宽度的文本该如何实现

### ISSUE THREAD

**Issue by 21haoxingxiu** [alibaba/x-render#1364]
### 期望的新功能 (describe the expected new feature)
固定宽度的文本
### 简述一下使用场景，便于开发者更好理解新功能的必要性 (describe your scenario for us to understand the need)
场景是表单后面跟段文本，文本是固定宽度的，现在v2版本好像没有看到width熟悉了，现在是怎么解决的呢

**Comment by lhbxs** [comment]
截个效果图看看

**Comment by lhbxs** [comment]
看看相关的属性，看能不能实现 https://xrender.fun/form-render/advanced-layout
