### ISSUE TITLE
schema里增加了description后，必填文案，没取label，用的是name

### ISSUE THREAD

**Issue by JbSun** [alibaba/x-render#1370]
**1.依赖仓库的版本(Dependencies versions)**：

- react：17.0.2
- form-render：2.2.13
- table-render:
- [antd：](https://4x-ant-design.antgroup.com/components/form-cn/#API)

**2.问题描述(Bug description)**：
在schema中设置了description后，必填文案改变了。没取label，用的是name
![image](https://github.com/alibaba/x-render/assets/31204110/e07b2eb8-1e78-414b-b405-8065957822f9)

![image](https://github.com/alibaba/x-render/assets/31204110/644b8bfe-ff87-400a-990f-e710fa6c326e)

**3.出现问题的 schema demo(Reproduction schema demo)**：
```js
const schema = {
  type: 'object',
  properties: {
    floorGoods: {
      title: '货架兜底货品',
      type: 'number',
      required: true,
      description: '未命中货品池货品或打分模型匹配分数失败，推荐该货品'
    },
  },
}
```

**4.最小复现 demo(Reproduction demo)**：

form-render demo https://codesandbox.io/s/unruffled-flower-jl78h
table-render demo https://codesandbox.io/s/sweet-euler-bdoty
fr-generator demo https://codesandbox.io/s/s13sh

**Comment by MoYuM** [comment]
建议自定义 rules 解决
