### ISSUE TITLE
FormRender添加form时报错

### ISSUE THREAD

**Issue by Hxtst** [alibaba/x-render#1371]
**1.依赖仓库的版本(Dependencies versions)**：

- react：18.2.0
- form-render：2.2.14
- antd：5.8.4

**2.问题描述(Bug description)**：
FormRender 添加form时提示 ：类型“FormInstance<any>”缺少类型“FormInstance”的以下属性: setSchemaByPath, getHiddenValues, setSchema, getSchema 及其他 16 项
**3.出现问题的 schema demo(Reproduction schema demo)**：
```js
import FormRender from 'form-render';
import { useForm } from 'antd/lib/form/Form';
const [formMaterial] = useForm();
<FormRender 
                        form={formMaterial} 
                        schema={schema} 
                        maxWidth={360} 
                        footer={false}
                        />
```

**4.最小复现 demo(Reproduction demo)**：

<img width="957" alt="image" src="https://github.com/alibaba/x-render/assets/64404409/f419e622-cec0-4caf-b896-34e4e4b63a09">

**Comment by lhbxs** [comment]
请使用 form-render 导出的 useForm
