### ISSUE TITLE
提交数据时，能否获得重复添加item的id呢？

### ISSUE THREAD

**Issue by xyy7260** [alibaba/x-render#1372]
### 期望的新功能 (describe the expected new feature)
<img width="1790" alt="image" src="https://github.com/alibaba/x-render/assets/23183393/2ea88738-edc9-4212-a755-b7c3aa1d9170">

### 简述一下使用场景，便于开发者更好理解新功能的必要性 (describe your scenario for us to understand the need)

因为我们需要给每一个重复添加的数据做一些特殊的事情， 所以需要一个ID 做对应的匹配显示， 谢谢！

**Comment by lhbxs** [comment]
item ID 从哪里来，不是很清楚你的需求

**Comment by xyy7260** [comment]
methods={methods} 方法中 可以解决这个问题
