### ISSUE TITLE
removeHiddenData 在重复添加中无效

### ISSUE THREAD

**Issue by xyy7260** [alibaba/x-render#1377]
**1.依赖仓库的版本(Dependencies versions)**：

- react："^18.2.0",
- form-render： "^2.2.14",
- antd："^5.6.4",

**2.问题描述(Bug description)**：

 removeHiddenData 设置true 

在重复添加里 ：  [仍可以获取隐藏的数据 （codesandbox）](https://codesandbox.io/s/vibrant-shape-37m2wn?file=/App.jsx)

在普通情况下   ：  [去掉已经被隐藏的元素的数据（codesandbox）](https://codesandbox.io/s/twilight-rgb-6ld5vr?file=/package.json:87-96)

console的触发事件 onFinish  在codesandbox 中可以查看 

**3.出现问题的 schema demo(Reproduction schema demo)**：
我放在codesandbox中查看schema

麻烦你们了 谢谢

**4.最小复现 demo(Reproduction demo)**：

**Comment by xyy7260** [comment]
[在额外的问个问题，我提到的这个也在开发中也常见  ](https://github.com/alibaba/x-render/issues/1375)

**Comment by lhbxs** [comment]
已修复 #1388
