### ISSUE TITLE
form-render的 TabList自定义组件 支持配置 activeKey

### ISSUE THREAD

**Issue by jerryYuX** [alibaba/x-render#1390]
1.依赖仓库的版本(Dependencies versions)：
react：16.14.0
form-render：2.2.15
antd：4.24.1
2.问题描述(Bug description)：
目前只有在添加、点击tab和删除tab(通过删除按钮)时，才会更新 activeKey，希望能由开发中在代码中自行控制当前activeKey，满足需要手动控制当前激活tab的场景。

**Comment by lhbxs** [comment]
更新到最新版本，通过 form.setSchemaBypath('list', { props: { activeKey: '2'}})
