### ISSUE TITLE
schemaBuilder的defaultValue有值时，在某些情况下会出现找不到组件的问题；左侧的组件容器不能滚动

### ISSUE THREAD

**Issue by GeekChen-stack** [alibaba/x-render#1395]
defaultValue有值时，在某些情况下会出现找不到组件：
<img width="889" alt="component-not-found-bug" src="https://github.com/alibaba/x-render/assets/120497519/62adb422-a764-47a6-9946-120d1f44a706">

左侧的组件容器不能滚动：
![schemaBuilder-scroll-bug](https://github.com/alibaba/x-render/assets/120497519/f8b59f9e-7f52-4be8-91c6-739d833b98c4)

**Comment by lhbxs** [comment]
最新版本，已修复
