### ISSUE TITLE
期望 type 为 object 的自定义 widget 里能够拿到当前的 path

### ISSUE THREAD

**Issue by Chechengyi** [alibaba/x-render#1397]
### 期望的新功能 (describe the expected new feature)

期望在 type 为 object 的自定义 widget 里能够拿到当前的 path

form-render: 2.2.14

<img width="736" alt="image" src="https://github.com/alibaba/x-render/assets/30520052/f9d0533c-1762-432a-a53d-195bf1597cb4">

看起来这里设置了 path = undefined， 导致 object 的 widget 中是没有办法拿到当前的 path

### 简述一下使用场景，便于开发者更好理解新功能的必要性 (describe your scenario for us to understand the need)

我们的业务中有如下的使用场景：

schema:
```
{
  type: 'object',
  properties: {
    input: {
      title: '输入框',
      type: 'string',
      widget: 'input'
    },
    testObject: {
      type: 'object',
      title: '测试object',
      widget: 'CustomObjectWidget',
      props: {
        setPath: 'testObject'
      },
      properties: {
        input_1: {
          title: '输入框',
          type: 'string',
          widget: 'input'
        },
         input_2: {
          title: '输入框',
          type: 'string',
          widget: 'input'
        },
         input_3: {
          title: '输入框',
          type: 'string',
          widget: 'input'
        },
      }
    }
  }
}
```
我写了一个 type 为 object 的自定义 widget: CustomObjectWidget, 我在这里面增加了一个按钮功能，即点击一下就可以将 input_1、input_2、input_3 的值全都设置成空字符串，我打算调用 `props.addons.setValueByPath` 方法去实现。

但是我发现在 CustomObjectWidget 组件里我根本获取不到当前 path

顺便也提一嘴，因为 ant deisgn 依赖的 rc-field-form 的原因， setFiledValue 无法触发 onValuesChange，导致在 xrende 中 setValueByPath 也无法触发 watch。 type 为 object 的 widget 里并没有接收到 onChange 方法，导致 在 object 的 widget 里做的操作无法触发 watch 方法， 想问下这里的设计思路是啥，为啥在 object 的 widget 里不提供 onChange 方法？

**Comment by lhbxs** [comment]
props.addons.dataPath 获取这个肯能会更准确一些

**Comment by lhbxs** [comment]
另外 setValueByPath 沿用了 antd setFieldsValue 的设计思路，防止在 change 事件中调用 setFieldsValue 导致的循环问题。

**Comment by Chechengyi** [comment]
> props.addons.dataPath 获取这个肯能会更准确一些

```js
{
  type: 'object',
  properties: {
    input: {
      title: '输入框',
      type: 'string',
      widget: 'input'
    },
    testObject: {
      type: 'object',
      title: '测试object',
      widget: 'subInline',
      props: {
        setPath: 'testObject'
      },
      properties: {
        input_1: {
          title: '输入框',
          type: 'string',
          widget: 'input'
        },
      }
    }
  }
}
```

然后到 boxSubInline 里面去打断点
<img width="1433" alt="image" src="https://github.com/alibaba/x-render/assets/30520052/c66f9c7c-5113-4816-82f5-ad3d0084c2c4">

`dataPath` 也取不到正确的值，期望这里应该是: `'testObject'` 吧？

**Comment by Chechengyi** [comment]
> 另外 setValueByPath 沿用了 antd setFieldsValue 的设计思路，防止在 change 事件中调用 setFieldsValue 导致的循环问题。

能理解 setValueByPath 为何不能触发 watch， 问题是现在 object 的 widget props 没有接受到 onChange 方法， 所以只能使用 setValueByPath 方法去设置值，但是这个 setValueByPath 无法触发 watch， 所以当 object 的自定义 widget 修改表单 data 的时候，像我们业务中这种实时根据表单输出的 data 去渲染UI的就没办法在 watch 中监听到了，只能在 object 的自定义 widget 中手动去同步。

**Comment by lhbxs** [comment]
我已经发了新版本，你再看一下，props.addons.dataPath
