### ISSUE TITLE
Object 和array的title 如何修改或者把国际化添加进去呢

### ISSUE THREAD

**Issue by xyy7260** [alibaba/x-render#1413]
<img width="702" alt="image" src="https://github.com/alibaba/x-render/assets/23183393/3551e599-9f36-45e0-92ec-9c42ff5526cf">

因为我们产品要国际化所以 要把i18加入进去。
```

   "items": {
        "type": "object",
        "properties": {
          "xh_yy_zt": {
            "param": "xh_yy_zt",
            "title": "xh_yy_zt",     
            "type": "object",
            "labelWidget": "CustomLabel",   // 这里 
            "descWidget": "CustomDesc",
             .......
```

**Comment by lhbxs** [comment]
你这里不是已经自定义 labelWidget 吗

**Comment by xyy7260** [comment]
@lhbxs  labelWidget 不能获取到 Object 和array的信息。

**Comment by xyy7260** [comment]
```
import { I18n } from '@/components/i18';

const styles = {
  color: '#00000073',
  lineHeight: '22px',
  marginLeft: '5px',
  fontWeight: '400',
  fontSize: '14px',
};
const CustomLabel = (props: any) => {
  const { schema } = props;
 console.log(props) // 不能获取到 Object 和array 信息
  return (
    <div>
      {I18n(schema.title)}
      {schema.description ? <span style={styles}>{`(${I18n(schema.description)})`}</span> : null}
    </div>
  );
};

export default CustomLabel;

```

**Comment by RGaius** [comment]
> ```
> import { I18n } from '@/components/i18';
> 
> const styles = {
>   color: '#00000073',
>   lineHeight: '22px',
>   marginLeft: '5px',
>   fontWeight: '400',
>   fontSize: '14px',
> };
> const CustomLabel = (props: any) => {
>   const { schema } = props;
>  console.log(props) // 不能获取到 Object 和array 信息
>   return (
>     <div>
>       {I18n(schema.title)}
>       {schema.description ? <span style={styles}>{`(${I18n(schema.description)})`}</span> : null}
>     </div>
>   );
> };
> 
> export default CustomLabel;
> ```

建议自己实现tableList吧，框架层面没有适配

**Comment by xyy7260** [comment]
只能自己用Object 和 array widget了
