### ISSUE TITLE
Found some files needed to be formarted

### ISSUE THREAD

**Issue by KazooTTT** [alibaba/x-render#1415]
After I run the script `yarn format` to prettier codes, there are so many changes.
Should I just commit the part of files that I want to modify or commit this pr below directly? 
[style: run yarn format](https://github.com/KazooTTT/x-render/commit/8238bb5defd3d4676b66b4ac69302929e09f827b)
![image](https://github.com/alibaba/x-render/assets/31075337/14ff3222-5067-4cd5-a596-a72b5bda1ff1)

**Comment by lhbxs** [comment]
Only the modified part is submitted
