### ISSUE TITLE
table columns defaultSortOrder属性不生效

### ISSUE THREAD

**Issue by yp94** [alibaba/x-render#1417]
**1.依赖仓库的版本(Dependencies versions)**：

- react：18.2.0
- form-render：2.1.24
- table-render: 2.0.15
- antd：5.5.1

**2.问题描述(Bug description)**：table defaultSortOrder不生效

**3.出现问题的 schema demo(Reproduction schema demo)**：
![image](https://github.com/alibaba/x-render/assets/28262260/c7462ce4-ff28-433e-b866-e3381532022f)
![image](https://github.com/alibaba/x-render/assets/28262260/958c0510-f8a5-4d32-a6f4-9ee7ee19105c)

**Comment by lhbxs** [comment]
已修复，更新最新版本
