### ISSUE TITLE
自定义labelWidget 能否在props中返回额外的参数信息呢？

### ISSUE THREAD

**Issue by xyy7260** [alibaba/x-render#1427]
请问一下，
要做一些特定的功能 labelWidget  需要获取 当前表单的 value 或者 返回参数全路径。（包括重复添加的的那些）

不过目前labelwidget 只返回了schema 。

能否支持呢。

如果不支持的话就直接关闭issues 谢谢

**Comment by lhbxs** [comment]
更新版本，支持访问 addons，对象包含 值路径 dataPath，schema 路径 schemaPath，一级 form 的操作方法

**Comment by xyy7260** [comment]
@lhbxs  哈哈哈太感谢了！
