### ISSUE TITLE
有很多个Collapse，渲染起来很卡

### ISSUE THREAD

**Issue by LittleZhaoLearnsFromTheFront** [alibaba/x-render#1432]
关于Collapse的源代码为
`<Collapse
      className='fr-obj-collapse'
      style={style}
      bordered={bordered}
      ghost={ghost}
      activeKey={[activeKey]}
      expandIcon={renderExpandIcon}
      onChange={() => setActiveKey(activeKey ? '' : 'single')}
    >
      <Panel key='single' header={collapseHeader} forceRender={true}>
        {children}
      </Panel>
    </Collapse>`

其中forceRender={true} 将所有Collapse中的内容一起渲染，如果Collapse多了渲染起来就会很卡

**Comment by lhbxs** [comment]
可能还是要提供一个 demo，我这边试了每一个 collapse 30 input、然后 list 长度 10，还是直出的

**Comment by xyy7260** [comment]
@lhbxs   
演示步骤 
1、在多选框中选择一个， 在子级多选框中又选择一个下拉框的然去测试，  输入 日期选择 等等 会卡。
表单大约有1000多个，并且很多表单都是在隐藏状态下。按道理网页渲染的前面只有十几个，为啥会变卡呢。

2、把所有选择框都选择此时会变得很卡。
 表单全部大约有1000多一个
<img width="758" alt="image" src="https://github.com/alibaba/x-render/assets/23183393/b228400f-54be-4daf-a17d-d1520efc2e9b">

 [codesandbox  演示代码在这里](https://codesandbox.io/s/da-liang-biao-dan-shu-ju-ce-shi-6n83p5?file=/components/CustomSelect.jsx)  
[预览网页在这里](https://6n83p5.csb.app/)
 谢谢respect！

**Comment by lhbxs** [comment]
同类型问题 https://github.com/alibaba/x-render/issues/1393
