### ISSUE TITLE
cardList的hideDelete判断错误

### ISSUE THREAD

**Issue by WebSealinda** [alibaba/x-render#1435]
表单初始化的时候cardList数组的长度为2，我设置了max=4， min=1, 按照道理cardList渲染出来应该有删除按钮，因为我max=4，数据的长度为2。再次点击复制按钮，或者新增按钮的 时候，删除按钮又出来了
<img width="1062" alt="image" src="https://github.com/alibaba/x-render/assets/29306863/c3cae997-9ff7-4556-a0cf-6d36a3ac2543">

![image](https://github.com/alibaba/x-render/assets/29306863/6c295903-d644-4e3e-b8cf-0d76c65d7383)

**Comment by lhbxs** [comment]
这个延续了 1.x 的逻辑，超过了 max 才会出现删除按钮

**Comment by WebSealinda** [comment]
> 这个延续了 1.x 的逻辑，超过了 max 才会出现删除按钮
这样是不是不太合适，用户新增了2条数据，现在只想要1条，还不让删了。而且这个问题只是刚渲染的时候，当点击上移或者下移其他按钮的时候，这个删除按钮又出现了，是不是哪里的依赖有问题

**Comment by lhbxs** [comment]
更新到最新版本，已修复
