### ISSUE TITLE
schemaBuilder构建表单，设置表单的属性例如禁用/隐藏/只读等属性不生效

### ISSUE THREAD

**Issue by cscbeyond** [alibaba/x-render#1437]
这是逻辑部分
![image](https://github.com/alibaba/x-render/assets/27284565/d5e6b35a-6a7d-450a-9368-4c85eb402ab6)
  这是预览效果
![image](https://github.com/alibaba/x-render/assets/27284565/3cd6da73-13b2-4308-917c-d8196e4a92ed)

似乎是对{{进行了编码导致的问题，请大佬抽空修复一下

**Comment by lhbxs** [comment]
分开写，个写个的。这个弹窗里面填只读属性的表达式值，例如： "{{ formData.number == 1 }}"
