### ISSUE TITLE
removeHiddenData 属性在 form-render-mobile 中无效

### ISSUE THREAD

**Issue by tplwang** [alibaba/x-render#1438]
**1.依赖仓库的版本(Dependencies versions)**：

- form-render-mobile：1.0.14

**2.问题描述(Bug description)**：
诉求类似于 #1423，但是 ` removeHiddenData` 在 `form-render-mobile` 中依旧无效
看到最近有 `removeHiddenData ` 相关的更新
- #1410
- https://github.com/alibaba/x-render/pull/1403/commits/138bac5943ce45cfd413847722d369ab15b2b46c

但是仅更新了 `form-render` 的逻辑，没有同步更新 `form-render-mobile`

**Comment by lhbxs** [comment]
更新最新版本，已修复

**Comment by tplwang** [comment]
似乎还是有问题
form-render-mobile demo: https://codesandbox.io/s/rough-sunset-j72636
