### ISSUE TITLE
当表单很多时候，网页会出现卡顿效果

### ISSUE THREAD

**Issue by xyy7260** [alibaba/x-render#1445]
演示步骤 
1、在多选框中选择一个， 在子级多选框中又选择一个下拉框的然去测试，  输入 日期选择 等等 会卡。
表单大约有1000多个，并且很多表单都是在隐藏状态下。按道理网页渲染的前面只有十几个，为啥会变卡呢。

2、把所有选择框都选择此时会变得很卡。

<img width="758" alt="image" src="https://github.com/alibaba/x-render/assets/23183393/b228400f-54be-4daf-a17d-d1520efc2e9b">

 [codesandbox  演示代码在这里](https://codesandbox.io/s/da-liang-biao-dan-shu-ju-ce-shi-6n83p5?file=/components/CustomSelect.jsx)  
[预览网页在这里](https://6n83p5.csb.app/)

 谢谢respect！

**Comment by lhbxs** [comment]
建议把 hidden 配置到某个大模块上面，去进行联动，你这个1000 多个控件，你每输入一次，函数表达式就会执行一次，你现在隐藏的颗粒度太细了，肯定卡。去控制某个 object 是不是显示，而不是去控制 object 里面的每一项。

**Comment by youngjuning** [comment]
hidden 函数表达式多的话导致的卡顿吗？
