### ISSUE TITLE
表单编辑器能否支持编程能力

### ISSUE THREAD

**Issue by liuyangzuo** [alibaba/x-render#1446]
以 Select 组件为例，要实现 Select 的列表数据是发送异步请求获取的，新版的 SchemaBuilder 也只能用自定义组件实现吗，能否支持在属性面板配置接口，或者开放一个编程能力？

**Comment by lhbxs** [comment]
你指的是在线编程？

**Comment by liuyangzuo** [comment]
> 你指的是在线编程？

不是，写代码，发请求等等。

**Comment by liuyangzuo** [comment]
> 你指的是在线编程？

下拉列表的 options 不通过右边的属性面板配置死，通过发送请求获取

**Comment by cscbeyond** [comment]
我也很期待这个能力

**Comment by liuyangzuo** [comment]
> 我也很期待这个能力

但是，感觉 xrender的 定位比较简洁，感觉不会支持。。还没发布的 schemabuild 我看没有这个能力的支持

**Comment by lhbxs** [comment]
可以关注这个 pr:https://github.com/alibaba/x-render/pull/1461，开源正在筹划中
