### ISSUE TITLE
SchemaBuilder 什么添加自定义组件

### ISSUE THREAD

**Issue by lusida** [alibaba/x-render#1449]
SchemaBuilder 什么添加自定义组件？

**Comment by yuzai** [comment]
同问，schemaBuilder 什么时候可以支持自定义组件？

**Comment by liuyangzuo** [comment]
@tw93 什么时候能开源，并且支持自定义组件呢

**Comment by lhbxs** [comment]
可以关注这个 pull，https://github.com/alibaba/x-render/pull/1461，已经在筹划开源了。
