### ISSUE TITLE
scrollToFirstError wrapForm.scrollToField is not a function

### ISSUE THREAD

**Issue by xyy7260** [alibaba/x-render#1451]
**1.依赖仓库的版本(Dependencies versions)**：

   "antd": "^5.6.4",
    "form-render": "2.3.6",
    "react": "^18.2.0",
    "react-dom": "^18.2.0"

**2.问题描述(Bug description)**：
当我点击提交时候没有滚动到必填的地方

在表单属性中使用scrollToFirstError 报错 wrapForm.scrollToField is not a function
 

**3.出现问题的 schema demo(Reproduction schema demo)**：
 在codesandbox中

**4.最小复现 demo(Reproduction demo)**：

[form-render demo ](https://codesandbox.io/p/sandbox/cocky-architecture-gh6695?file=%2FApp.jsx%3A107%2C1)

**Comment by lhbxs** [comment]
XRender 的 form 虽然底层继承了 Antd 。但是 XRender 有 path 的概念和 Antd filed.name 所有不同。所以为了 防止 API 混用，所以在 API 上有自己独立的一套。

**Comment by xyy7260** [comment]
<img width="638" alt="image" src="https://github.com/alibaba/x-render/assets/23183393/98e0ba6c-2809-4a0b-b9c4-c81395b3f2c1">
把props 属性传递到  自定组件最外层中就可以 滚动到错误地方了 
scrollToField
