### ISSUE TITLE
type 为 `object` 类型自定义组件没有接收到 `value` 与 `onChange` 属性

### ISSUE THREAD

**Issue by mov-78** [alibaba/x-render#1453]
**1.依赖仓库的版本(Dependencies versions)**：

- react：18.2.0
- form-render：2.3.6
- antd：5.11.1

**2.问题描述(Bug description)**：

在为 `type` 为 `object` 的字段注册自定义组件时，自定义组件没有接收到 `value` 与 `onChange` props。

**3.最小复现 demo(Reproduction demo)**：

[demo](https://codesandbox.io/p/sandbox/dank-rgb-k95rsz?file=%2FApp.tsx&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clqncb0gp00063b6mllonx6az%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clqncb0go00023b6mewmm7ehg%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clqncb0go00033b6mlsg9q86p%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clqncb0go00053b6m5bm0oehm%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B64.82249287380151%252C35.17750712619849%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clqncb0go00023b6mewmm7ehg%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clqncb0go00013b6mgy88oyqc%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Findex.tsx%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522id%2522%253A%2522clqncgwzf005o3b6mde3lbfr4%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A7%252C%2522startColumn%2522%253A18%252C%2522endLineNumber%2522%253A7%252C%2522endColumn%2522%253A18%257D%255D%252C%2522filepath%2522%253A%2522%252FApp.tsx%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522id%2522%253A%2522clqncb0go00023b6mewmm7ehg%2522%252C%2522activeTabId%2522%253A%2522clqncgwzf005o3b6mde3lbfr4%2522%257D%252C%2522clqncb0go00053b6m5bm0oehm%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clqncb0go00043b6m2grfp9qm%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522id%2522%253A%2522clqncb0go00053b6m5bm0oehm%2522%252C%2522activeTabId%2522%253A%2522clqncb0go00043b6m2grfp9qm%2522%257D%252C%2522clqncb0go00033b6mlsg9q86p%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522clqncb0go00033b6mlsg9q86p%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

`object` 类型的自定义组件接收不到 `value` 与 `onChange` 属性：

<img width="625" alt="image" src="https://github.com/alibaba/x-render/assets/523893/b8451e80-ea5e-4f95-8b0f-325a2bc225e2">

而其他非对象类型，例如 `string` 则可以接受到：

<img width="628" alt="image" src="https://github.com/alibaba/x-render/assets/523893/397a6344-acd4-4654-961f-249ed394c25d">

**Comment by lhbxs** [comment]
2.x 对于你这样的结构会视为容器组件进行递归渲染

  if (schema?.properties && schema?.widgetType !== 'field') {
    child = RenderCore({ schema, parentPath: path, rootPath })
  }
  
  
  schema 增加一个 widgetType：'field'
