### ISSUE TITLE
table-render里在打包的时候会多打一个form-render

### ISSUE THREAD

**Issue by jackqiu0123** [alibaba/x-render#1454]
**1.依赖仓库的版本(Dependencies versions)**：

- react：18.2.0
- form-render：2.3.7
- table-render:2.1.3
- antd：5.9.0

**2.问题描述(Bug description)**：
打包之后table-render下多了一个form-render
打开node_modules里查看后发现table-render下有一个2.3.0的form-render
![image](https://github.com/alibaba/x-render/assets/5487754/600e6a03-ae6d-4f04-9e7f-09dd90e4c54e)
![image](https://github.com/alibaba/x-render/assets/5487754/af2d1937-ca37-421e-a1ff-c41d3bc04ee4)

**3.出现问题的 schema demo(Reproduction schema demo)**：
```js
const schema = {
  // ...
}
```

**4.最小复现 demo(Reproduction demo)**：

form-render demo https://codesandbox.io/s/unruffled-flower-jl78h
table-render demo https://codesandbox.io/s/sweet-euler-bdoty
fr-generator demo https://codesandbox.io/s/s13sh

**Comment by lhbxs** [comment]
配置这个试试，应该能统一成一个， "resolutions": {
    "form-render": "1.14.17"
  },
