### ISSUE TITLE
getSchemaFullPath 方法问题

### ISSUE THREAD

**Issue by k-w-wang** [alibaba/x-render#1458]
![image](https://github.com/alibaba/x-render/assets/91463246/a5331747-8017-4a1c-bbfd-b71d5c74fb03)

第149行代码
result = key + '.properties';

应该要判断一下是不是forEach最后一个item, 如果是的话不应该继续加 .properties

现象： getSchemaByPath 多层结构 如 getSchemaByPath( 'a.b' );  获取到的结果不对

**Comment by lhbxs** [comment]
是的，你发现的是对的。 #1460
