### ISSUE TITLE
Ant 5.x DatePicker控件无法渲染

### ISSUE THREAD

**Issue by whsqjss** [alibaba/x-render#1459]
**1.依赖仓库的版本(Dependencies versions)**：

- react：18.2.0
- form-render：2.0.0-rc.0
- antd：5.2.2

**2.问题描述(Bug description)**：
DatePicker组件无法渲染
**3.出现问题的 schema demo(Reproduction schema demo)**：
```js
const schema = {
	"type": "object",
	"properties": {
		"calibrationDate": {
			"type": "string", 
			"props": {"placeholder": "请选择日期"}, 
			"title": "校准日期", 
			"widget": "datePicker", 
			"required": true
			}
	}
}
```
![image](https://github.com/alibaba/x-render/assets/35548533/23e5a94e-8df7-4117-955e-bb7b95dd54eb)

**4.最小复现 demo(Reproduction demo)**：

**Comment by lhbxs** [comment]
这种临时太的 XRender 1.0 兼容 antd 5.x 的版本很早就不维护了。建议是通过自定义组件方式替换掉内部 DatePicker，或者是考虑升级 2.x
