### ISSUE TITLE
TS2339: Property validateMessages does not exist on type

### ISSUE THREAD

**Issue by finnMasurat** [alibaba/x-render#1462]
**1.依赖仓库的版本(Dependencies versions)**：
- form-render：2.3.8

**2.问题描述(Bug description)**：
Hello everyone,
this package is part of pdfme, which i am trying to use in my application.
Typscript is throwing an error due to a possible undefined property.
Place: form-render/lib/types.d.ts:290:
validateMessages?: ConfigProviderProps['form']['validateMessages'];

I can see that validateMessages is defined as following inside the ConfigProviderProps:
`form?: ComponentStyleConfig & {
        validateMessages?: ValidateMessages;
        requiredMark?: RequiredMark;
        colon?: boolean;
        scrollToFirstError?: Options | boolean;
    };
`
The error i am receiving is the following:
`TS2339: Property validateMessages does not exist on type`
`FRProps.validateMessages?: any`

Thank you very much for your help!

**Comment by lhbxs** [comment]
已修复
