### ISSUE TITLE
FormRender使用description导致rules校验时提示语从title变成key了

### ISSUE THREAD

**Issue by RyzenPan** [alibaba/x-render#1463]
**1.依赖仓库的版本(Dependencies versions)**：

- react：^18.2.0
- form-render：2.3.7
- table-render:
- antd：^5.12.5

**2.问题描述(Bug description)**：

**3.出现问题的 schema demo(Reproduction schema demo)**：
```js
const schema = {
  type: 'object',
  displayType: 'column',
  properties: {
    key: {
      title: '测试校验',
      type: 'number',
      description: '有描述时',
      min: 1,
    },

    key2: {
      title: '测试校验(无描述)',
      type: 'number',
      min: 1,
    },
}
}
```

**4.最小复现 demo(Reproduction demo)**：
![image](https://github.com/alibaba/x-render/assets/56830619/0e4f6673-d7bd-4e28-a36c-59c4de41a126)

form-render demo https://codesandbox.io/s/unruffled-flower-jl78h
table-render demo https://codesandbox.io/s/sweet-euler-bdoty
fr-generator demo https://codesandbox.io/s/s13sh

**Comment by lhbxs** [comment]
这个好像是 antd 组件本身的问题， Form.Item 的 title 如果是字符串是正常的，如果是一个 JSX 它好像就会提示 key


目前没有太优雅的办法去解，你可以把 min 这种简易的写法或者是其他校验，按照校验配置完整写全 rules: [{ min: 1, message: ''}]，这样就能正常显示了。
