### ISSUE TITLE
 tableList：标签内联组件，内容多余展示lable

### ISSUE THREAD

**Issue by leshalv** [alibaba/x-render#1469]
最新版本，使用官网JSON规则即可复现。

<img width="1654" alt="image" src="https://github.com/alibaba/x-render/assets/30397655/7a27f5e6-9111-4f65-abad-3128b69d355c">

**Comment by lhbxs** [comment]
官网是没有问题的，https://xrender.fun/form-render/display-row#tablelist

**Comment by leshalv** [comment]
> 官网是没有问题的，https://xrender.fun/form-render/display-row#tablelist

官网没有，本地用最新的版本就会有这个问题。

**Comment by liangchaofei** [comment]
> > 官网是没有问题的，https://xrender.fun/form-render/display-row#tablelist
> 
> 官网没有，本地用最新的版本就会有这个问题。

提供一个复现链接吧

**Comment by leshalv** [comment]
很奇怪，我创建一个示例是正常的，但是在实际使用中是不行的，版本号是最新的，依赖工具是pnpm，控制台也没有错误

<img width="1284" alt="image" src="https://github.com/alibaba/x-render/assets/30397655/ea5b6b51-8ed5-4f01-a788-9256b99166d0">

**Comment by leshalv** [comment]
找到问题了，因为自定义ant prefixCls 前缀导致的 https://github.com/alibaba/x-render/issues/1146

**Comment by leshalv** [comment]
less 文件可以引入变量来处理，兼容ant5，应该使用官方推荐的css in js

<img width="792" alt="image" src="https://github.com/alibaba/x-render/assets/30397655/18f2f98a-399f-4d25-ba11-8aa8f9eea74d">
