### ISSUE TITLE
希望提供0.X版本渐进式迁移1.0版本或者2.0版本的迁移指南

### ISSUE THREAD

**Issue by XinLi96** [alibaba/x-render#1472]
### 期望的新功能 (describe the expected new feature)
希望提供0.X版本渐进式迁移1.0版本或者2.0版本的迁移指南
### 简述一下使用场景，便于开发者更好理解新功能的必要性 (describe your scenario for us to understand the need)
旧项目中有使用0.8的落后版本，希望渐进式迁移成最新的版本

**Comment by lhbxs** [comment]
结合这两个文档吧
https://1.xrender.fun/form-render/migrate

https://xrender.fun/form-render/migrate
