### ISSUE TITLE
tableList下很多列的时候字段显示不全

### ISSUE THREAD

**Issue by africa1207** [alibaba/x-render#1473]
**1.依赖仓库的版本(Dependencies versions)**：

- react：
- form-render：
- table-render:
- antd：

**2.问题描述(Bug description)**：
背景：
在官网的playground使用
问题：
当定义一个列表选择tableList并设置了很多列的时候，比如其中某个列是下拉框，选项的label特别长，由于宽度很小选中后导致label显示不全，如图
![image](https://github.com/alibaba/x-render/assets/21698755/7d7d2be7-ee0b-47ea-9718-6c9bb5635cf7)
解决方案：1. 该列宽度自动跟随内容变化；
                  2. 列的label可以手动拖动改变宽度；

**Comment by lhbxs** [comment]
如果表格列比较多的话：
首先建议使用 DrawerList，而不是 TableList

如果飞要使用 TableList，建议给 TableList 足够大的宽度，然后滚动表格
