### ISSUE TITLE
Schema 传入JSX会报错

### ISSUE THREAD

**Issue by MoYuM** [alibaba/x-render#1484]
**1.依赖仓库的版本(Dependencies versions)**：

- react：17
- form-render：2.4.0

**2.问题描述(Bug description)**：
如果schema中传入jsx的话，页面直接报错

**3.出现问题的 schema demo(Reproduction schema demo)**：
```js
const schema = {
        type: 'object',
      properties: {
        type: {
          title: '联系人',
          type: 'string',
          props: {
            options: [
{label: <div>123</div>, key: 1}
]
          },
        },
  }
}
```

**4.最小复现 demo(Reproduction demo)**：

[demo](https://codesandbox.io/p/sandbox/hopeful-shirley-lyxyzm?file=%2Fpackage.json%3A9%2C5&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clsww3f9v00063b6f8fazmwg0%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clsww3f9v00023b6fmym0vzsa%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clsww3f9v00033b6fmm4xi63b%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clsww3f9v00053b6fesraq1ta%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clsww3f9v00023b6fmym0vzsa%2522%253A%257B%2522id%2522%253A%2522clsww3f9v00023b6fmym0vzsa%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clswwhkk300023b6ebwadt98t%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A9%252C%2522startColumn%2522%253A5%252C%2522endLineNumber%2522%253A9%252C%2522endColumn%2522%253A5%257D%255D%252C%2522filepath%2522%253A%2522%252Fpackage.json%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522activeTabId%2522%253A%2522clswwhkk300023b6ebwadt98t%2522%257D%252C%2522clsww3f9v00053b6fesraq1ta%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clsww3f9v00043b6fd8lu7xf5%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522id%2522%253A%2522clsww3f9v00053b6fesraq1ta%2522%252C%2522activeTabId%2522%253A%2522clsww3f9v00043b6fd8lu7xf5%2522%257D%252C%2522clsww3f9v00033b6fmm4xi63b%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522clsww3f9v00033b6fmm4xi63b%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

**Comment by MoYuM** [comment]
具体报错位置是这里
![image](https://github.com/alibaba/x-render/assets/64450989/137618dc-c83b-4be8-9ace-f4405e0bb1e6)

**Comment by lhbxs** [comment]
schema 不支持这种 JSX 的配置，schema 推荐的是保持 JSON 的方式，这样保证了远程配置的一致性。你这种更倾向自定义一个 widget。
