### ISSUE TITLE
内网使用连接超时

### ISSUE THREAD

**Issue by weskerjiang** [alibaba/x-render#1485]
先在互联网环境把包下载好，运行没问题，然后切换到离线，也没问题，但是开发一段时间后，提示连接超时，这个如何解决

**Comment by lhbxs** [comment]
内网你只的是？公司自己的内网？你用了 XR 的什么产品？提示链接超时？

**Comment by weskerjiang** [comment]
> 内网你只的是？公司自己的内网？你用了 XR 的什么产品？提示链接超时？

 你好，内网就是内部局域网，与互联网物理隔离
我们使用了form-render和对应的可视化编辑器SchemaBuilder
SchemaBuilder在内网使用一段时间后，会出现连接超时的问题，就是IFrame里的页面无法访问了，导致我们无法编辑表单。在重新连接互联网后，又可以使用了，但是过一段时间就会导致无法使用（连接超时）

**Comment by lhbxs** [comment]
明白你的意思了。SchemaBuilder 有些资源是通过 CDN 资源访问的。所以在内部局域网目前无法单独使用。
