### ISSUE TITLE
DrawList 支持配置不渲染下层嵌套对象

### ISSUE THREAD

**Issue by chenqien** [alibaba/x-render#1486]
### 期望的新功能 (describe the expected new feature)
DrawList 支持配置不渲染下层嵌套对象

### 简述一下使用场景，便于开发者更好理解新功能的必要性 (describe your scenario for us to understand the need)
如下图以及对应的 schema，
1，2.0 版本中默认渲染了下层的对象，导致配置内容较多时页面极其卡顿。
2，本身 DrawList 样式用于复杂的表单配置，在上层全部渲染，交互也很混乱。

恳请考虑～～  远不如 1.0 版本中 默认不渲染内嵌对象。

<img width="1734" alt="image" src="https://github.com/alibaba/x-render/assets/32092235/663985bd-cd2e-4969-8a9a-675ba75fc49a">

{
      "type":"object",
      "title":"质检报告配置类目维度",
      "properties":{
        "zzConfigList":{
          "type":"array",
          "title":"配置信息",
          "required":true,
          "rules":[
            {
              "required":true,
              "message":"必填"
            }
          ],
          "widget":"drawerList",
          "items":{
            "type":"object",
            "widget":"lineTitle",
            "properties":{
              "cateId":{
                "type":"string",

                "title":"末级类目ID",
                "required":true,
                "width":"50%",
                "rules":[
                  {
                    "message":"长度超限，请确认",
                    "max":11
                  },
                  {
                    "message":"只允许填写数字",
                    "pattern":"^[0-9]+$"
                  },
                  {
                    "required":true,
                    "message":"[末级类目ID]必填"
                  }
                ],
                "default":""
              },
              "configs":{
                "type":"array",
                "title":"二级项",
                "required":false,
                "widget":"drawerList",
                "items":{
                  "widget":"lineTitle",
                  "type":"object",
                  "properties":{
                    "firstId":{
                      "type":"string",

                      "title":"一级质检项ID",
                      "required":true,
                      "width":"50%",
                      "rules":[
                        {
                          "message":"长度超限，请确认",
                          "max":11
                        },
                        {
                          "message":"只允许填写数字",
                          "pattern":"^[0-9]+$"
                        },
                        {
                          "required":true,
                          "message":"[一级质检项ID]必填"
                        }
                      ],
                      "default":""
                    },

                  }
                }
              }
            }
          }
        }
      },
      "displayType":"row"
    }

**Comment by lhbxs** [comment]
你这个渲染好像不对，我用你的 schema 复现不了

**Comment by lhbxs** [comment]
<img width="1697" alt="截屏2024-02-28 上午11 06 07" src="https://github.com/alibaba/x-render/assets/43236919/dff04071-2e94-42a9-919f-1e8f09e4169b">

**Comment by lhbxs** [comment]
你当前按照的 form-render是什么版本？

**Comment by chenqien** [comment]
@lhbxs 
最新版本：2.4.2

可能我没把问题说清楚....

期望的是：
1，在以下页面正常填写嵌套的数据，并点击确定之后，
<img width="815" alt="企业微信截图_ada5c18b-72aa-499c-94cc-19ff35e6c73b" src="https://github.com/alibaba/x-render/assets/32092235/2af2b558-03b0-4967-8c48-55794c040d8c">

2，在上层不渲染下一层的对象类型的数据，例如下图的红色框部分，不展示内容 以一个横杆“-”代替，在 1.X 版本中是这样的
<img width="1695" alt="企业微信截图_df3de50c-4d5f-4770-b732-e64ddacb9bdd" src="https://github.com/alibaba/x-render/assets/32092235/82ab1139-66b9-4e61-80ca-83612e472642">

**Comment by lhbxs** [comment]
没懂

**Comment by lhbxs** [comment]
大概懂你的意思了。我给列增加了一个 columnHidden 属性配置，配置之后就不会在表格里面显示

**Comment by lhbxs** [comment]
#1505
