### ISSUE TITLE
collapse组件是否可以支持一个属性控制其默认展开或者折叠

### ISSUE THREAD

**Issue by Chengyunlai** [alibaba/x-render#1489]
### 期望的新功能 (describe the expected new feature)
期待增加一个属性控制collapse组件初始时是展开还是折叠

### 简述一下使用场景，便于开发者更好理解新功能的必要性 (describe your scenario for us to understand the need)
复杂表单中可能有很多个需要折叠的内容，默认展开页面容易过长，期待加一个属性控制其初始时是展开还是折叠

**Comment by lhbxs** [comment]
传 collapsed： false
