### ISSUE TITLE
table如何自定义分页，或者如何修改他的属性和样式？

### ISSUE THREAD

**Issue by zqj-0922** [alibaba/x-render#1491]
![image](https://github.com/alibaba/x-render/assets/131839656/77e2e413-9ab1-41ec-ac3e-e8f0acba85ef)

**Comment by zqj-0922** [comment]
@lhbxs

**Comment by lhbxs** [comment]
<TableRender pagination={} />

**Comment by lhbxs** [comment]
<TableRender pagination={} />

**Comment by lhbxs** [comment]
<TableRender pagination={} />

**Comment by lhbxs** [comment]
<TableRender pagination={} />

**Comment by lhbxs** [comment]
pagination={}

**Comment by lhbxs** [comment]
![Uploading 截屏2024-03-22 上午10.32.33.png…]()

**Comment by lhbxs** [comment]
<img width="533" alt="截屏2024-03-22 上午10 32 33" src="https://github.com/alibaba/x-render/assets/43236919/76226b3d-1369-4ae0-a135-3bf6387b0b29">
