### ISSUE TITLE
FormRender配置disabled: true后仍然校验该表单项

### ISSUE THREAD

**Issue by RyzenPan** [alibaba/x-render#1493]
**1.依赖仓库的版本(Dependencies versions)**：

- react：18.2.0
- form-render：2.3.7
- table-render:
- antd：5.12.5

**2.问题描述(Bug description)**：
FormRender配置disabled: true后仍然校验该表单项
![image](https://github.com/alibaba/x-render/assets/56830619/10d4e566-0414-475d-8ee4-751f919b8a86)

**3.出现问题的 schema demo(Reproduction schema demo)**：
```js
const schema = {
  // ...
}
```

**4.最小复现 demo(Reproduction demo)**：

form-render demo https://codesandbox.io/s/unruffled-flower-jl78h
table-render demo https://codesandbox.io/s/sweet-euler-bdoty
fr-generator demo https://codesandbox.io/s/s13sh

**Comment by lhbxs** [comment]
配置 disable = true，然后还校验也没毛病哇。你这个都 disabled 了，为什么没有数据呢？
