### ISSUE TITLE
fr-generator点击导入导出按钮弹出框没有生效

### ISSUE THREAD

**Issue by nirvanaborn** [alibaba/x-render#1497]
**1.依赖仓库的版本(Dependencies versions)**：

- react：17.0.2
- form-render：
- table-render:
- antd：4.19.2

**2.问题描述(Bug description)**：表单设计器v-1版本中，点击导入导出按钮弹窗没有生效，官方文档里面的demo也都打不开

**3.出现问题的 schema demo(Reproduction schema demo)**：
```js
const schema = {
  // ...
}
```

**4.最小复现 demo(Reproduction demo)**：

form-render demo https://codesandbox.io/s/unruffled-flower-jl78h
table-render demo https://codesandbox.io/s/sweet-euler-bdoty
fr-generator demo https://codesandbox.io/s/s13sh

**Comment by lhbxs** [comment]
https://1.xrender.fun/generator

没有复现出来。
