### ISSUE TITLE
displayType 不是 column 的情况下出现 hideLabel 字符串

### ISSUE THREAD

**Issue by ylfeng250** [alibaba/x-render#1499]
**1.依赖仓库的版本(Dependencies versions)**：

- react：18
- form-render：2.4.2
- table-render:
- antd：5

**2.问题描述(Bug description)**：
![image](https://github.com/alibaba/x-render/assets/26338012/dc5758e0-3299-4efb-855a-d8e8844d9e52)
![image](https://github.com/alibaba/x-render/assets/26338012/3390d463-30ab-4d6c-9eee-38e51cfd8d48)

https://github.com/alibaba/x-render/blob/0c1c20c3c7600900567c76dba2cff5679a6e7556/packages/form-render/src/form-core/index.tsx#L234
这个位置 判断不是 column ，就设置label的操作我没有看懂，导致生产环境下这个 表单的 action 区域出现一个 hideLabel

```
<Form.Item
              label={ displayType !== 'column' ?  'hideLabel' : null}
              labelCol={operlabelCol}
              className='fr-hide-label'
            >
               {isFunction(footer) ? (
                <Space>{footer(actionBtns)}</Space>
              ) : (
                <Space>{actionBtns}</Space>
              )}
            </Form.Item>
```

能不能优化一下

**Comment by lhbxs** [comment]
你是不是配置了 prefixCls，导致隐藏的 css 不生效了，你可以找到那块的 css 然后复写下样式。
