### ISSUE TITLE
time类型报invalideDate

### ISSUE THREAD

**Issue by oxygen-xx** [alibaba/x-render#1506]
**1.依赖仓库的版本(Dependencies versions)**：

- react：18
- form-render：2.4.4
- antd：5.15.3

**2.问题描述(Bug description)**：

"time": {
  "title": "时间选择",
  "type": "string",
  "format": "time"
}

不能正常显示 time类型， date, dateTime都是可以的。

**Comment by lhbxs** [comment]
2.x 建议使用申明，可以看看这个用力。

https://xrender.fun/form-render/display-row

date1: {
      title: '日期选择',
      type: 'string',
      widget: 'datePicker'
    },
    dateRange1: {
      title: '日期范围',
      type: 'range',
      widget: 'dateRange'
    },
    time1: {
      title: '时间选择',
      type: 'string',
      widget: 'timePicker'
    },
    timeRange1: {
      title: '时间范围',
      type: 'range',
      widget: 'timeRange'
    },
