### ISSUE TITLE
drawerList edit 表单数值填充异常

### ISSUE THREAD

**Issue by tiancheng91** [alibaba/x-render#1508]
**1.依赖仓库的版本(Dependencies versions)**：

- react：18.2.0
- form-render：2.4.4
- table-render:  --
- antd：5.15.4

**2.问题描述(Bug description)**：
drawerList 组件, 行编辑时, 表单数据始终只填充最后一行

**3.出现问题的 schema demo(Reproduction schema demo)**：
```js
const schema = {
  // ...
}
```

**4.最小复现 demo(Reproduction demo)**：
https://codesandbox.io/p/sandbox/festive-kirch-7m4jr2

![image](https://github.com/alibaba/x-render/assets/1658770/c72a228b-7fc4-45eb-ace4-64e269646f3a)

**Comment by lhbxs** [comment]
请更新最新版本
