### ISSUE TITLE
hideAdd为true, 复制按钮出现了。如果hideAdd为false，添加和复制按钮都没有了。 hideCopy不起任何作用。

### ISSUE THREAD

**Issue by oxygen-xx** [alibaba/x-render#1510]
**1.依赖仓库的版本(Dependencies versions)**：

- react：
- form-render：2.4.4
- table-render:
- antd：5.16

**2.问题描述(Bug description)**：
hideAdd为true, 复制按钮出现了。如果hideAdd为false，添加和复制按钮都没有了。 hideCopy不起任何作用。

**3.出现问题的 schema demo(Reproduction schema demo)**：
```js
const schema = {
  // ...
}
```

**4.最小复现 demo(Reproduction demo)**：

form-render demo https://codesandbox.io/s/unruffled-flower-jl78h
table-render demo https://codesandbox.io/s/sweet-euler-bdoty
fr-generator demo https://codesandbox.io/s/s13sh

**Comment by lhbxs** [comment]
无法复现，请提供 demo 示例
