### ISSUE TITLE
Docs Typo: Correct misspelling 'defalut' to 'default

### ISSUE THREAD

**Issue by gitgundam** [alibaba/x-render#1515]
**1.依赖仓库的版本(Dependencies versions)**：

- react：
- form-render：2.x
**2.问题描述(Bug description)**：

Description: I noticed a typo in your code/documentation where the word "defalut" is misspelled as "default". This issue is to request correction of the typo to ensure accuracy and consistency.

**3.出现问题的 schema demo(Reproduction schema demo)**：

link https://xrender.fun/form-render/advanced-linkage 

修改表单项的协议（schema）
form.setSchemaByPath：指定路径对 schema 进行修改 (不允许通过此 API 修改 value、defalut)。[path 路径详见](https://xrender.fun/form-render/advanced-path)。

**Comment by lhbxs** [comment]
已订正。
