### ISSUE TITLE
自定义组件的input或者别的表单，如何更合理的触发校验？

### ISSUE THREAD

**Issue by zqj-0922** [alibaba/x-render#1518]
![image](https://github.com/alibaba/x-render/assets/131839656/48a32f22-135d-4f0b-9e69-ffd163003fee)
![image](https://github.com/alibaba/x-render/assets/131839656/64835f2e-3c65-4936-9720-25d886b175b2)
![image](https://github.com/alibaba/x-render/assets/131839656/cfc0c2b2-b666-4d68-9ab3-5c8cedf6a389)

**Comment by lhbxs** [comment]
自定义组件，你可以把 props 解构剩余的属性 { xx1, xxx, ...retProps } = props; <Input {...retProps} />
