### ISSUE TITLE
schema未匹配到展示组件

### ISSUE THREAD

**Issue by blockmood** [alibaba/x-render#1519]
**1.依赖仓库的版本(Dependencies versions)**：

- react：
- form-render：
- table-render:
- antd：

**2.问题描述(Bug description)**：

**3.出现问题的 schema demo(Reproduction schema demo)**：
```js
const schema = {
  // ...
[1.json](https://github.com/alibaba/x-render/files/15124432/1.json)

}
```

**4.最小复现 demo(Reproduction demo)**：

```
import { useEffect, useRef, useState } from "react";
import { schema } from './1'
import Form, { useForm } from 'form-render';


function App() {

  const form = useForm();
  

  return (
    <div className="App1">
      <Form
        form={form}
        schema={schema}
        onFinish={formData => console.log(JSON.stringify(formData, null, 2))}
        footer
      />
    </div>
  );
}

export default App;

```
form-render demo https://codesandbox.io/s/unruffled-flower-jl78h
table-render demo https://codesandbox.io/s/sweet-euler-bdoty
fr-generator demo https://codesandbox.io/s/s13sh

帮忙看看是什么问题，谢谢。

**Comment by blockmood** [comment]
![1714097593592](https://github.com/alibaba/x-render/assets/22879524/9ae65597-13e1-4786-82f6-d68cd36739ed)

**Comment by blockmood** [comment]
@lhbxs

**Comment by lhbxs** [comment]
这两个 "language_tag": {
                        "$ref": "#/$defs/language_tag"
                    },
                    "marketplace_id": {
                        "$ref": "#/$defs/marketplace_id"
                    },  没有办法判断使用哪个输入空见，需指定 widget: '' 字段。
