### ISSUE TITLE
Docs 需要补充: TableRender 里的 Search 组件 api 有些不全, 允许传入 ...rest 参数进行透传给 FormRender 但是文档没写

### ISSUE THREAD

**Issue by hacker0limbo** [alibaba/x-render#1520]
**1.依赖仓库的版本(Dependencies versions)**：

- react：16.x
- form-render：1.x
- table-render: 1.x
- antd：4.x

**2.问题描述(Bug description)**：

`TableRender` 里的 `Search` 组件是允许传入多余的参数, 最终会透传给 `FormRender`, 例如可以传 `widgets` 等. 但是文档里似乎没写, 不管是 1.x 的文档还是 2.x 的文档 `TableRender` 的 [api](https://xrender.fun/table-render/api) 里我都没找到相关说明, 反而是 [ChartRender 里的 api](https://1.xrender.fun/chart-render#search) 提到了...这个是否可以修复一下? 对于新用户还是会造成一些困扰的

**3.出现问题的 schema demo(Reproduction schema demo)**：
```js
const schema = {
  // ...
}
```

**4.最小复现 demo(Reproduction demo)**：暂无

form-render demo https://codesandbox.io/s/unruffled-flower-jl78h
table-render demo https://codesandbox.io/s/sweet-euler-bdoty
fr-generator demo https://codesandbox.io/s/s13sh

**Comment by lhbxs** [comment]
好的，我补充一下
