### ISSUE TITLE
希望FormRender支持形如 {type: array,  items: { type: string;  format: 'text' } }的schema

### ISSUE THREAD

**Issue by DontTellAnyone1** [alibaba/x-render#1524]
### 目前只有添加了enum才能正常渲染。但是有很多场景是允许用户自定义数组中的每一项。
<img width="897" alt="image" src="https://github.com/alibaba/x-render/assets/132656156/d9d18483-1de6-4cfa-9243-8101a253f43d">

**Comment by lhbxs** [comment]
<img width="858" alt="截屏2024-07-15 下午8 24 53" src="https://github.com/user-attachments/assets/a3a6b234-d31b-4422-8036-5765086278a8">

这种？
