### ISSUE TITLE
[bug] form-render preserve=false, tablist 组件删除中间的数据会导致下方数据被清空！

### ISSUE THREAD

**Issue by blinkcat** [alibaba/x-render#1526]
使用官方的实例，[https://xrender.fun/form-render/display-row#tablelist%E6%A0%87%E7%AD%BE%E6%8D%A2%E8%A1%8C](https://xrender.fun/form-render/display-row#tablelist%E6%A0%87%E7%AD%BE%E6%8D%A2%E8%A1%8C)。

```tsx
export default () => {
  const form = useForm();
  return <FormRender preserve={false} schema={schema} form={form} />;
};
```
在FormRender上加上preserve属性。删除第二条数据

![screenshot-20240604-154001](https://github.com/alibaba/x-render/assets/7824959/8bcbbdc5-9162-4956-aab7-625a94f7c564)

结果变成这样了，第三条数据的值没了。

![screenshot-20240604-154143](https://github.com/alibaba/x-render/assets/7824959/1cf2a879-a98a-488e-acaa-765e77423d94)

期望的正常结果是，第二条数据被删除，第三条的数据保留。

[可复现的demo](https://codesandbox.io/p/sandbox/recursing-waterfall-gjy9fm?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clwzxtrg700063b6mjbby8qvu%2522%252C%2522sizes%2522%253A%255B100%252C0%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clwzxtrg700023b6m1bao6b53%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clwzxtrg700033b6mow1pn2pj%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clwzxtrg700053b6m1joeccxm%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clwzxtrg700023b6m1bao6b53%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clwzxtrg600013b6mi56y2uvf%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Findex.html%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522id%2522%253A%2522clwzxv6rt00023b6lfkcdz5s8%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A10%252C%2522startColumn%2522%253A1%252C%2522endLineNumber%2522%253A36%252C%2522endColumn%2522%253A9%257D%255D%252C%2522filepath%2522%253A%2522%252FApp.tsx%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522id%2522%253A%2522clwzxtrg700023b6m1bao6b53%2522%252C%2522activeTabId%2522%253A%2522clwzxv6rt00023b6lfkcdz5s8%2522%257D%252C%2522clwzxtrg700053b6m1joeccxm%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clwzxtrg700043b6mvlvl40zy%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522id%2522%253A%2522clwzxtrg700053b6m1joeccxm%2522%252C%2522activeTabId%2522%253A%2522clwzxtrg700043b6mvlvl40zy%2522%257D%252C%2522clwzxtrg700033b6mow1pn2pj%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522clwzxtrg700033b6mow1pn2pj%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Afalse%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

**Comment by lhbxs** [comment]
当前版本无法复现。
