### ISSUE TITLE
ones插件平台 无法识别less  ones平台不能自己配置webpack

### ISSUE THREAD

**Issue by panghongye** [alibaba/x-render#1533]
**1.依赖仓库的版本(Dependencies versions)**：

- react：17.0.2
- form-render：2.4.4
- table-render:
- antd：^4

**2.问题描述(Bug description)**：
在ones插件平台上使用出现如下问题，ones平台没有配置webpack的地方

Compiled with problems:X

ERROR in ../node_modules/antd/es/button/style/index.less 1:0

Module parse failed: Unexpected character '@' (1:0)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
> @root-entry-name: default;
| 
| @import './index-pure.less';
**3.出现问题的 schema demo(Reproduction schema demo)**：
```js
const schema = {
  // ...
}
```

**4.最小复现 demo(Reproduction demo)**：Nextjs上

form-render demo https://codesandbox.io/s/unruffled-flower-jl78h
table-render demo https://codesandbox.io/s/sweet-euler-bdoty
fr-generator demo https://codesandbox.io/s/s13sh

**Comment by Hemyhcy** [comment]
可以看下是否有webpack.config.js文件
