### ISSUE TITLE
antd升级版本到5.17.x之后，日期时间选择范围点击确认后无法回显在表单上

### ISSUE THREAD

**Issue by Liu-0114** [alibaba/x-render#1536]
**1.依赖仓库的版本(Dependencies versions)**：

- react：18.3.1
- form-render：2.4.4
- table-render:
- antd：5.18.1

**2.问题描述(Bug description)**：antd升级版本到5.17.x之后，日期时间选择范围选择两个之后再点击确认后无法回显在表单上

**3.出现问题的 schema demo(Reproduction schema demo)**：
```js
const schema = {
    type: 'object',
    properties: {
      dateRange1: {
        title: '日期范围',
        type: 'range',
        widget: 'dateRange',
        format: 'dateTime'
      },
}
```

**4.最小复现 demo(Reproduction demo)**：
```tsx
import React from 'react';
import FormRender, { useForm } from 'form-render';

export default () => {
  const form = useForm();
  const schema = {
    type: 'object',
    properties: {
      dateRange1: {
        title: '日期范围',
        type: 'range',
        widget: 'dateRange',
        format: 'dateTime'
      },
    }
  };
  const onFinish = (formData) => {
    console.log('formData:', formData);
  };

  return (
    <FormRender 
      form={form} 
      schema={schema} 
      onFinish={onFinish} 
      maxWidth={360} 
      footer={true}
    />
  );
}
```

form-render demo https://codesandbox.io/s/unruffled-flower-jl78h
table-render demo https://codesandbox.io/s/sweet-euler-bdoty
fr-generator demo https://codesandbox.io/s/s13sh

**Comment by Hemyhcy** [comment]
版本号改为
react：18.3.1
form-render：2.4.4
table-render:
antd：5.18.1
后无法复现这个问题，就可以看看是不是其他的原因导致的：
<img width="415" alt="截屏2024-07-29 16 11 32" src="https://github.com/user-attachments/assets/3b2ece4c-ee38-4176-9859-cd7f67292a1b">
