### ISSUE TITLE
复杂嵌套列表DrawerList样式优化

### ISSUE THREAD

**Issue by hanhant98** [alibaba/x-render#1538]
### 期望的新功能 (describe the expected new feature)

1、希望2.x版本DrawerList展示样式可以跟1.x展示样式保持一样
2、2.x版本DrawerList编辑时点击蒙层会自动关闭，导致输入数据丢失问题优化

### 简述一下使用场景，便于开发者更好理解新功能的必要性 (describe your scenario for us to understand the need)
1、当嵌套列表元素较多时，页面展示爆炸，阅读体感下降。个人更倾向选择DrawerList就是希望于能够折叠隐藏复杂对象
<img width="1436" alt="image" src="https://github.com/user-attachments/assets/72b088cf-83ea-4d07-8faa-16c33c38324a">
2、编辑列表输入内容，点击蒙层会自动关闭，导致数据丢失，当数据量较多时比较搞心态
<img width="780" alt="image" src="https://github.com/user-attachments/assets/dd9cb1d1-cd51-4731-866b-2a78ccf277bc">

**Comment by lhbxs** [comment]
已发布
