### ISSUE TITLE
FormLIst 数据返回为空 有bug

### ISSUE THREAD

**Issue by Flcwl** [alibaba/x-render#1540]
![image](https://github.com/user-attachments/assets/5dc5c6f6-2d0d-426a-b51e-667bf3ef48a9)

**Comment by Flcwl** [comment]
因为 lodash 的 get 没有处理 null 的情况
<img width="861" alt="image" src="https://github.com/user-attachments/assets/c1c22923-e124-45b4-9d65-7d5768b27e91">

**Comment by Hemyhcy** [comment]
已修复
