### ISSUE TITLE
Support disabling alpha channel in the color picker

### ISSUE THREAD

**Issue by peteward** [alibaba/x-render#1544]
### 期望的新功能 (describe the expected new feature)
Hi 👋 
The [pdfme](https://github.com/pdfme/pdfme/) project, which uses `form-render` has a requirement to disable alpha channel from the color picker UI. This is supported by `rc-color-picker` and also [the suggested future alternative](https://github.com/alibaba/x-render/issues/1496), `@rc-component/color-picker`

### 简述一下使用场景，便于开发者更好理解新功能的必要性 (describe your scenario for us to understand the need)

This would allow you to change the color picker from:
![Screenshot 2024-08-14 at 16 08 07](https://github.com/user-attachments/assets/dccd04f8-1201-4a8a-be8c-fdd22aa06383)

to:

![Screenshot 2024-08-14 at 16 08 41](https://github.com/user-attachments/assets/1c1c9948-be9f-46e1-9b3e-54241109670d)

This can be achieved using the `enableAlpha` prop.

**Comment by lhbxs** [comment]
Thank you for submitting the issue, which has been merged
