### ISSUE TITLE
在 SimpleList 文件中，onCopy 方法当前返回的是复制操作的目标数据，而没有提供关于被复制项的索引信息

### ISSUE THREAD

**Issue by ajun568** [alibaba/x-render#1549]
### 期望的新功能 (describe the expected new feature)

- 在 SimpleList 文件中，onCopy 方法当前返回的是复制操作的目标数据，而没有提供关于被复制项的索引信息

- 希望修改 onCopy 方法的回传值，增加被复制项的索引

### 简述一下使用场景，便于开发者更好理解新功能的必要性 (describe your scenario for us to understand the need)

在某些场景下，我们需要在独立维护的数据中包含额外的信息，并且在进行复制操作时需要将这些额外的信息一并复制过去。获取被复制项的索引信息可以帮助我们在后续处理中正确地处理这些额外信息。

**Comment by ajun568** [comment]
此外，onMove 中返回的应为 from 而不是 form

**Comment by lhbxs** [comment]
#1554

**Comment by lhbxs** [comment]
已发布新版本支持
