### ISSUE TITLE
高级正则在 Safari 浏览器会解析error，导致页面挂掉。需要尽快代码回滚

### ISSUE THREAD

**Issue by Flcwl** [alibaba/x-render#1552]
https://github.com/alibaba/x-render/commit/fc900d427d0fdd65c068dc838a40f478a12fd210

**Comment by Flcwl** [comment]
<img width="1190" alt="image" src="https://github.com/user-attachments/assets/53683ae2-4b3a-4945-9505-6f25369f3ef4">

**Comment by lhbxs** [comment]
你修复，请更新版本
