### ISSUE TITLE
想了很久，决定把表单设计器，重新设计一下。

### ISSUE THREAD

**Issue by chenyajun-create** [alibaba/x-render#1564]
想了很久，决定把表单设计器，重新设计一下。

表单设计器将分三部走

第一阶段，支持内置组件拖拉拽生成协议

第二阶段，支持自定义组件接入

第三阶段，纳入表格场景，支持拖拉拽生成表格

大家有什么想法和建议欢迎一起讨论

_Originally posted by @lhbxs in https://github.com/alibaba/x-render/discussions/1110_

**Comment by beeant0512** [comment]
可以看看这个项目 支持 x-render的schema
https://xbeeant.github.io/nexus-form-engine
