### ISSUE TITLE
select组件 自定义渲染label报错

### ISSUE THREAD

**Issue by YUANC0NG** [alibaba/x-render#1568]
**1.依赖仓库的版本(Dependencies versions)**：

- react：17-18
- "form-render": "^2.4.8",
- "umi": "^4.3.14"
- "antd": "^5.20.2",

**2.问题描述(Bug description)**：
options里label包含div自定义渲染就会报错 原生是正常的 options: [{ label: <div>1</div>, value: '1' }], 

**3.出现问题的 schema demo(Reproduction schema demo)**：
```js
const schema = {
                     type: 'object',
			displayType: 'row',
			labelAlign: 'left',
			readOnly,
			properties: {	
                     test: {
					title: '测试标题',
					type: 'string',
					required: true,
					props: {
						allowClear: true,
						options: [{ label: <div>1</div>, value: '1' }],
					},
				},
			},
}
```

**4.最小复现 demo(Reproduction demo)**：

form-render demo https://codesandbox.io/s/unruffled-flower-jl78h
table-render demo https://codesandbox.io/s/sweet-euler-bdoty
fr-generator demo https://codesandbox.io/s/s13sh

**Comment by Hemyhcy** [comment]
上面schema少了 widget:"select",加上之后可以正常使用，不会报错。
```tsx
const schema = {
  type: 'object',
  displayType: 'row',
  labelAlign: 'left',
  properties: {
    test: {
      title: '测试标题',
      type: 'string',
      required: true,
      widget:"select",
      props: {
        allowClear: true,
        options: [{ label: <div>测试</div>, value: '1' }],
      },
    },
  },
}
```
效果展示：
<img width="362" alt="截屏2024-09-29 17 27 56" src="https://github.com/user-attachments/assets/a6654f51-2405-49ee-9e5f-9137cd049c06">
