### ISSUE TITLE
[BUG] number类型默认值设置为"", 导致不必要的提示

### ISSUE THREAD

**Issue by kala888** [alibaba/x-render#287]
**1.依赖仓库的版本**：
 "@ant-design/icons": "^4.6.2",
    "@ant-design/pro-layout": "^6.5.0",
    "@form-render/rich-text": "^1.0.1",
    "@material-ui/core": "^4.11.3",
    "@material-ui/icons": "^4.11.2",
    "@rjsf/antd": "^2.5.1",
    "@rjsf/core": "^2.5.1",
    "@rjsf/material-ui": "^2.5.1",
    "@umijs/preset-react": "1.x",
    "antd": "^4.14.1",
    "dayjs": "^1.10.4",
    "form-render": "^0.10.5",
    "lodash": "^4.17.21",
    "react-json-view": "^1.21.3",
    "umi": "^3.4.6"

**2.问题描述**：
```
    age: {
        title: '年龄',
        type: 'number',
      },

```

类型是number，未设置默认值，FR源码中默认设置为""，并触发校验“请填写数字”（红色提示）
空表单，某些number字段业务上应该是允许为空且没有默认值。

建议修改，number默认值为null

![image](https://user-images.githubusercontent.com/1215976/113116512-1999bc80-9240-11eb-9d15-61b4cb4228c5.png)

**Comment by FateRiddle** [comment]
升级1.0后，问题解决了哈。现在不触碰的数字框的初始值是undefined。
