### ISSUE TITLE
[BUG]当 descIcon 显示时，悬浮的描述控件会被遮盖

### ISSUE THREAD

**Issue by seasonyuu** [alibaba/x-render#291]
**1.依赖仓库的版本**：
- react：17.0.1
- form-render：0.10.5
- antd：4.14.0
- funsion（如果用的是fusion）：

**2.问题描述**：

配置 `showDescIcon` 为 `true`，而后当 `description` 文本较长时，会分为多行，此时顶部就会被遮盖了。

**3.最小复现demo**：

https://codesandbox.io/s/zidingyizujian-forked-42lw4

**Comment by seasonyuu** [comment]
附带 codesandbox 了，请不要未经验证直接否认 Bug

**Comment by FateRiddle** [comment]
(。・＿・。)ﾉI’m sorry~ 在1.0版本已经修复了。

表单设计上的建议是，description不要写太长，用户不会认真看；而且尽量用label一行展示的模式，而不要把description收起到icon上，用户不会去点。

**Comment by seasonyuu** [comment]
感谢响应~~~
