### ISSUE TITLE
[BUG]无法与Ant Design黑暗模式适配

### ISSUE THREAD

**Issue by myonlylonely** [alibaba/x-render#296]
**1.依赖仓库的版本**：
- form-render：0.10.5
- antd：4.15.0

**2.问题描述**：
如果通过umi3的配置来开启Ant Design的黑暗主题模式 (https://ant.design/docs/react/customize-theme-cn#使用暗黑主题和紧凑主题), 则Form-Render的主题无法生效。

```javascript
// .umirc.ts or config/config.ts
export default {
  antd: {
    dark: true, // 开启暗色主题
  },
},
```

**Comment by FateRiddle** [comment]
因为form-render除了表单元素，剩下部分并不是antd。这块这么配置生效是因为umi选择集成了antd的umi插件。
1.0版本我dark了一下，每个元素都变了。外部的用一下样式覆盖吧~
我们会在下周的版本加个dark模式的props，用于配置。

**Comment by siyi98** [comment]
> 因为form-render除了表单元素，剩下部分并不是antd。这块这么配置生效是因为umi选择集成了antd的umi插件。 1.0版本我dark了一下，每个元素都变了。外部的用一下样式覆盖吧~ 我们会在下周的版本加个dark模式的props，用于配置。

@myonlylonely 解决参考于此
