### ISSUE TITLE
[BUG] rules 字段无法生效

### ISSUE THREAD

**Issue by alvin0216** [alibaba/x-render#305]
**1.依赖仓库的版本**：
- react：17+
- form-render：1.0.2

**2.问题描述**：

校验无法生效

**3.最小复现demo**：

```json
{
    "type": "object",
    "properties": {
      "pageTitle": {
        "type": "string",
        "title": "页面名称",
        "minLength": 0,
        "maxLength": 10,
        "rules": [
          {
            "required": true,
            "message": "请输入页面名称"
          }
        ]
      }
    }
  },
```
![image](https://user-images.githubusercontent.com/34113677/114831303-ceff6f00-9dff-11eb-95db-f2049d0516e3.png)

---

问题 2：props 字段是否是 AntdFormItem 的 props， 多个校验或者参数同时存在时，以哪个参数为主

**Comment by FateRiddle** [comment]
已经fix。v1.0.5
