### ISSUE TITLE
[BUG]多选下拉框传入的值为null时，下拉框组件中会多一个为空的tag

### ISSUE THREAD

**Issue by flycatrix** [alibaba/x-render#307]
**1.依赖仓库的版本**：
- react：16+
- form-render：1.0.2
- antd：4.x

**2.问题描述**：
多选下拉框传入的值为null时，下拉框组件中会多一个为空的tag

![image](https://user-images.githubusercontent.com/23756954/114840651-9b294700-9e09-11eb-8b11-cb4e54cf2e72.png)

**Comment by FateRiddle** [comment]
v1.0.5 已经fix
