### ISSUE TITLE
[BUG] title文本超长后自动换行,会导致设置的描述信息错位

### ISSUE THREAD

**Issue by ShmilyXI** [alibaba/x-render#308]
**1.依赖仓库的版本**：
- react：17+
- form-render：1.0.2
- antd：4.14.0

**2.问题描述**：
 title文本超长后自动换行,会导致设置的描述信息错位;

**3.最小复现demo**：
```jsx
{
  "schema": {
    "type": "object",
    "properties": {
      "string": {
        "title": "字符串123123123",
        "type": "string",
         "description": "提示信息"
      }
    }
  }
}
```
![xwfPZg](https://cdn.jsdelivr.net/gh/ShmilyXI/Gallerys@master/BokeImage/images/xwfPZg.png)

**Comment by FateRiddle** [comment]
问题了解了，谢谢issue。

布局上：title稍微超长了一点，用labelWidth来调整一下。真的很长，建议使用默认的 displayType: column 展示方式。这是官方设计上的推荐哈。
