### ISSUE TITLE
[BUG]API文档文字错误 https://x-render.gitee.io/tools/generator/#events

### ISSUE THREAD

**Issue by yanchangyou** [alibaba/x-render#314]
**1.依赖仓库的版本**：
- react：
- form-render：
- antd：
- funsion（如果用的是fusion）：

**2.问题描述**：
文档位置：https://x-render.gitee.io/tools/generator/#events
拼写错误：onSchameChange -> onSchemaChange

**3.最小复现demo**：

https://codesandbox.io/s/form-renderjichudemo-f55oy

**Comment by F-loat** [comment]
已更正
