### ISSUE TITLE
[Feature]能自定义mapping能自定义widget字段

### ISSUE THREAD

**Issue by baiheinet** [alibaba/x-render#316]
### 期望的新功能
自定义mapping能自定义widget字段
### 为什么（简述一下使用场景）
比如 array: 'list', 怎么能全局设置成  widget: 'list2' ，就是能全局配置一下 而不是 一个一个去改对应的Schema

**Comment by F-loat** [comment]
这个其实能把 list 组件直接拆成 list1 和 list2 两个组件的话就可以了

**Comment by baiheinet** [comment]
> 这个其实能把 list 组件直接拆成 list1 和 list2 两个组件的话就可以了

你的意思是如果分开 就可以 mapping={{array: 'list2'}} 了

**Comment by FateRiddle** [comment]
该咋说，list的展示要根据不同的数据情况选择不同的展示才是最佳实践，写死并不是推荐的。这里的情况是仅仅多写一个widget，感觉还好吧？更复杂的schema未来会开放一个api简化到只需要写一个widget字段替代。

这块等有更多同类诉求后考虑开放哈。目前容许我们观望一下。

**Comment by baiheinet** [comment]
> 该咋说，list的展示要根据不同的数据情况选择不同的展示才是最佳实践，写死并不是推荐的。这里的情况是仅仅多写一个widget，感觉还好吧？更复杂的schema未来会开放一个api简化到只需要写一个widget字段替代。
> 
> 这块等有更多同类诉求后考虑开放哈。目前容许我们观望一下。

那要这么说 最牛逼的话是根据字段 只能选择显示模式
