### ISSUE TITLE
[Feature] 自定义组件为对象类型时，label展示希望能够与普通 label 相同，而不默认是对象的 label 展示

### ISSUE THREAD

**Issue by godismygirl** [alibaba/x-render#319]
在使用自定义组件时，返回值为object
导致在书写相应 schema时，类似 
schema = {
  type: 'object',
  properties: {
    inputType: {
       title: 'xxx',
       type: 'object',
       widget: 'customWidget',
       },
    }
}
 这会导致该行的样式自动换行，与普通form item不同
 schema type中的object 是与表单样式绑定的，能否不要与样式绑定

**Comment by FateRiddle** [comment]
v1.1.3 修复
