### ISSUE TITLE
我运行源码后，出现一个错误，无法解决

### ISSUE THREAD

**Issue by zhoujun5201314** [alibaba/x-render#321]
请问下，这个如何解决呢？
![1619054926340_FD70230D-B2CC-4d42-A9F6-8524BF884E30](https://user-images.githubusercontent.com/24538118/115642435-8e4aad00-a34d-11eb-98ea-38b41ec48be2.png)

**Comment by XYSynnek** [comment]
源码中的`import nanoid` 替换成 `import { nanoid }`

**Comment by F-loat** [comment]
Fixed ca41adb9c1ee3c8cee8d41e4db7795bfb05eb67b
