### ISSUE TITLE
[BUG]表单description展示被遮盖

### ISSUE THREAD

**Issue by flycatrix** [alibaba/x-render#323]
**1.依赖仓库的版本**：
- react：17.x
- form-render：1.x
- antd：4.x

**2.问题描述**：

表单description展示被遮盖
![image](https://user-images.githubusercontent.com/23756954/115646215-55620680-a354-11eb-9acc-14b24f1e0fd7.png)

**3.最小复现demo**：

https://codesandbox.io/s/form-renderjichudemo-f55oy

**Comment by flycatrix** [comment]
问题的原因是同时使用了未升级的table-render，导致部分样式沿用了0.8版本的form-render样式。可通过升级table-render解决。

**Comment by FateRiddle** [comment]
嗯嗯，是新老form-render同时引入造成的。我把样式覆盖做的彻底一点，避免这类情况发生吧。
