### ISSUE TITLE
[BUG]我在win10创建新的项目，但是没显示antd的css

### ISSUE THREAD

**Issue by caimingyi484** [alibaba/x-render#325]
执行命令如下：
create-react-app mytest;
cd mytest;
npn i antd --save;
npm i form-render --save;
npm run start;
访问http://localhost:3000，页面可以显示，就是没有css，这是为什么？

**Comment by caimingyi484** [comment]
版本号如下
`-- react@17.0.2
`-- antd@4.15.2
`-- form-render@1.1.1

import代码如下
import React from 'react';
import { Button } from 'antd';
import FormRender, { useForm } from 'form-render';

const schema = {....

**Comment by FateRiddle** [comment]
加个
```
import 'antd/dist/antd.css'
```
一般引入的项目本身都是antd，css在项目本身就处理过了。

**Comment by caimingyi484** [comment]
好的，谢谢了
