### ISSUE TITLE
[BUG] JsonSchema不正确，FormRender渲染时页面crash

### ISSUE THREAD

**Issue by jsyt** [alibaba/x-render#326]
**1.依赖仓库的版本**：
- react：^16.4.1
- form-render：^1.x
- antd：
- funsion（如果用的是fusion）：

**2.问题描述**：
JsonSchema 不正确，FormRender 渲染时，页面直接crash了，这个地方Form-Render能直接兜住报错吗？我看0.x版本是有兜住错误的，或者提供一个校验 FormRender JsonSchema的工具也行。

**Comment by FateRiddle** [comment]
@jsyt 嗯嗯，这儿肯定要兜。问一下，不正确是不正确到什么程度？直接语法错误完全不是一个JSON？

**Comment by FateRiddle** [comment]
问题主要集中在如果schema无法匹配到任何组件的时候会crash，已经修复了。而且还加上了UI的错误提示
