### ISSUE TITLE
[BUG] 使用 type html 时报错

### ISSUE THREAD

**Issue by Tanviw** [alibaba/x-render#327]
**1.依赖仓库的版本**：
- react：
- form-render： 1.1
- antd：
- funsion（如果用的是fusion）：

**2.问题描述**：
当 type 为 html 时，必须要自定义validator ，如图：
![image](https://user-images.githubusercontent.com/22901710/115692709-cd9aed00-a391-11eb-9c3b-7a10c8e2ff3a.png)
![image](https://user-images.githubusercontent.com/22901710/115692746-d5f32800-a391-11eb-9988-998f9d41f87a.png)

**3.最小复现demo**：

https://codesandbox.io/s/form-renderjichudemo-f55oy

**Comment by FateRiddle** [comment]
谢谢issue，v1.1.3 已经修复
