### ISSUE TITLE
能否提供动态改变search api的能力？[Feature]

### ISSUE THREAD

**Issue by godismygirl** [alibaba/x-render#336]
### 期望的新功能
试想一个常见页面场景，左侧树，点击树查询并展示table render

能否提供动态改变search api的能力？
或者在useTable 中开放run 方法

### 为什么（简述一下使用场景）
目前我是用setTable({search: newParams})
然后再hook tableState.search 手动请求，但这样会重复渲染，也不美观

**Comment by FateRiddle** [comment]
@godismygirl 有多个仓库，下次开发记得打个标，方便维护者识别哈~

**Comment by siyi98** [comment]
如开源答疑群里所说，使用`refresh({})`即可进行主动传参
