### ISSUE TITLE
[BUG]表单验证有问题

### ISSUE THREAD

**Issue by btea** [alibaba/x-render#337]
**1.依赖仓库的版本**：
- react：
- form-render：
- antd：
- funsion（如果用的是fusion）：

**2.问题描述**：
输入框表单验证提示有问题，如下所示

**3.最小复现demo**：

https://user-images.githubusercontent.com/24516654/116021306-860aae80-a67a-11eb-82f4-80cee6fe36fd.mp4

(不知道什么原因，视频在线看好像是一片空白，下载看是可以的。)

**Comment by Turkyden** [comment]
> (不知道什么原因，视频在线看好像是一片空白，下载看是可以的。)

这个功能是 github 的吧？

**Comment by btea** [comment]
> > (不知道什么原因，视频在线看好像是一片空白，下载看是可以的。)
> 
> 这个功能是 github 的吧？

播放视频是github的功能，视频内容是我说的表单验证的问题。

**Comment by FateRiddle** [comment]
谢谢，厉害，这个操作被你发现了。已经fix了。v1.2.0
