### ISSUE TITLE
[BUG]希望能优先解决下： 设置了一行三列，某个字段 hidden后还是占位在那，影响体验

### ISSUE THREAD

**Issue by Tanviw** [alibaba/x-render#339]
**1.依赖仓库的版本**：
- react：
- form-render：
- antd：
- funsion（如果用的是fusion）：

**2.问题描述**：
如图：
![image](https://user-images.githubusercontent.com/22901710/116048677-fc71d580-a6a7-11eb-95ca-56d5f41cf5a0.png)

**3.最小复现demo**：

https://codesandbox.io/s/form-renderjichudemo-f55oy

**Comment by FateRiddle** [comment]
已经解决了 v1.2.0 谢谢issue。
