### ISSUE TITLE
[Feature] 表单监听watch在首次渲染时会触发

### ISSUE THREAD

**Issue by lx544690189** [alibaba/x-render#340]
### 期望的新功能
类似vue提供一个immediate=true/false选项，最好默认初始化不触发
### 为什么（简述一下使用场景）

场景：
外部需要维护表单值formData，通过`form.setValues(formData)`设置表单初始值，并且实时监听表单的值。表单组件渲染后会先触发watch，将外部维护的表单值formData置为{}。目前只能判断是否首次触发watch来解决。

**Comment by FateRiddle** [comment]
1.2.0 解了。谢谢这个issue。immediate也加了。和vue的api相同的使用方式
