### ISSUE TITLE
[Feature]减小包体积

### ISSUE THREAD

**Issue by suanmei** [alibaba/x-render#341]
### 期望的新功能
减小包体积

### 为什么（简述一下使用场景）
现在的form-render压缩后还有1M。

### 突破点
moment.js 换成 dayjs
lodash 换成 lodash-es

**Comment by FateRiddle** [comment]
嗯，moment会进行替换。lodash这个问题，感觉开发的大多数中后台项目都明着或者暗着（依赖包的依赖包）引用了lodash，这块改成lodash-es反而会给不少的项目增加体积。

**Comment by suanmei** [comment]
那是他们项目本身的问题。form-render 换成 lodash-es 后和 lodash 有关的代码会很少，相关代码体积小，即使旧有项目使用lodash也无所谓。而且lodash-es取代lodash也是趋势
