### ISSUE TITLE
[BUG]本地无法启动generator ，spec.type must be defined

### ISSUE THREAD

**Issue by abattle** [alibaba/x-render#352]
spec.type must be defined
invariant
./src/index.ts:28
  25 |   );
  26 | } else {
  27 |   let argIndex = 0;
  28 |   error = new Error(| ^ 
  29 |     format.replace(/%s/g, function() {
  30 |       return args[argIndex++];
  31 |     })

**Comment by F-loat** [comment]
重新安装依赖后还有问题的话请提供下复现步骤及运行环境
