### ISSUE TITLE
[BUG]在 onMount 中调用 form.setValues 无法设置表单值

### ISSUE THREAD

**Issue by chenyinkai** [alibaba/x-render#354]
**1.依赖仓库的版本**：
- react：16.13.1
- form-render：1.3.0
- antd：4.5.4
- funsion（如果用的是fusion）：

**2.问题描述**：

在 `onMount` 中调用 `form.setValues` 无法设置表单值

期望：在 `FormRender` 渲染完成后直接设置表单值

**3.最小复现demo**：

https://codesandbox.io/s/flamboyant-hugle-3d2h4?file=/App.jsx:934-941

**Comment by FateRiddle** [comment]
最新版已经fix了。谢谢issue哈！
