### ISSUE TITLE
[BUG] 文档无法加载

### ISSUE THREAD

**Issue by simplast** [alibaba/x-render#355]
https://x-render.gitee.io/form-render 转圈圈
https://x-render.gitee.io/form-render/schema/schema 转圈圈

**Comment by simplast** [comment]
另外我想加钉钉群，发现README.md里面的群二维码只显示一半

**Comment by F-loat** [comment]
清除缓存后再刷新下，群二维码应该是网络问题，可以试下直接搜索群号 23185578
