### ISSUE TITLE
[Feature]form-render 支持自定义 readonly 模式下的组件

### ISSUE THREAD

**Issue by Tanviw** [alibaba/x-render#357]
### 期望的新功能
希望能够支持配置在 readonly 模式下，字段使用自定义的组件。如 schema 配置 readOnlyWidget，则该字段在 readOnly 时使用配置的组件，并能够将 form 的 readOnly 属性传递给自定义组件。
### 为什么（简述一下使用场景）

某些自定义组件，无法简单使用 value 值展示。

**Comment by FateRiddle** [comment]
谢谢建议，已经添加了 readOnlyWidget 字段
