### ISSUE TITLE
[BUG]选中对象层时会清空表单

### ISSUE THREAD

**Issue by chenyinkai** [alibaba/x-render#359]
**1.依赖仓库的版本**：
- react：
- form-render：
- fr-generator: 2.0.0
- antd：
- funsion（如果用的是fusion）：

**2.问题描述**：

1. 进入 [demo](https://codesandbox.io/s/nostalgic-jones-ydn3r?file=/App.jsx), 选择左侧 模版-复杂模版样式
2. 选中 <简单输入框> 表单或 <对象> 中任一表单
3. 再选择 <对象> 层，会发现 <对象> 中的表单都被清空了

没有找到 `fr-generator` 仓库地址，所以就在这里提 `issue` 了

**3.最小复现demo**：

https://codesandbox.io/s/nostalgic-jones-ydn3r?file=/App.jsx

**Comment by F-loat** [comment]
已修复 fr-generator@2.0.1
