### ISSUE TITLE
[Feature] 增加全局disable所有控件功能

### ISSUE THREAD

**Issue by simplast** [alibaba/x-render#362]
### 期望的新功能
0x可以通过uiSchema的“ui:readOnly”设置全部组件禁用
1x只能通过外层设置readOnly，但是效果是纯文本，非禁用效果

**Comment by QiannanXu** [comment]
同意，尤其boolean相关的组件，✔和✘实在太任性了

**Comment by FateRiddle** [comment]
谢谢issue，新版本已经提供了 disabled 的全局开关
