### ISSUE TITLE
[Feature] 希望tableList可以暴露更多配置选项

### ISSUE THREAD

**Issue by QiannanXu** [alibaba/x-render#363]
### 为什么（简述一下使用场景）

比如支持配置不显示翻页

**Comment by FateRiddle** [comment]
@QiannanXu 目前默认的是单页不显示，多页了会显示。请问一下是什么具体场景，以上的默认展示会出现问题？

**Comment by QiannanXu** [comment]
@FateRiddle 产品需求，tableList多条数据需要在同一页展示，如果数据项过大，支持虚拟列表滚动加载
