### ISSUE TITLE
[Feature] 希望可以暴露Core组件

### ISSUE THREAD

**Issue by QiannanXu** [alibaba/x-render#364]
### 期望的新功能

项目需要高度自定义复杂object或者array的显示，希望可以暴露类似于0.x版本的 props.getSubField 的函数或者组件(Core)

**Comment by FateRiddle** [comment]
object的话，可以通过widget来自定义组件。list这边有点烦，因为list的展示本身会影响到children的展示方式，但接下来也会想办法暴露出来。
是老用户呀，请问是我们的钉钉群里的哪位小伙伴呀，可以找我聊具体诉求哦

Core 本身暂时不打算暴露，不过我们可以具体聊一下，如果诉求合理完全可以考虑哈。
