### ISSUE TITLE
[Feature]希望array类型可以增加配置项，能够隐藏“复制”、“新增”、“删除”功能

### ISSUE THREAD

**Issue by xuemin-li** [alibaba/x-render#369]
### 为什么（简述一下使用场景）

A平台调用B平台的数据，A是一个搭建平台，只是在已有B平台数据基础上补充额外的素材。数组长度还是B平台的。感恩，点赞👍🏻

**Comment by FateRiddle** [comment]
已提供了 hideDelete / hideAdd 的 api

**Comment by xuemin-li** [comment]
在schame里增加hideAdd或者hideDelete后，新增或删除按钮仍然存在。群里提问，加default后，还是没隐藏。下图为sschema书写片段
![image](https://user-images.githubusercontent.com/5096093/118632765-52e3b700-b803-11eb-9d1f-0d108a4fd5ba.png)
