### ISSUE TITLE
[Feature] 希望默认的组件中提供 （服务端数据下拉框）

### ISSUE THREAD

**Issue by jiangby123** [alibaba/x-render#371]
### 为什么（简述一下使用场景）

填写表单时，不可能所有的数据都是固定不变的，有些选项希望从服务端拿到，然后渲染在下拉框中 ，给用户去选择

**Comment by FateRiddle** [comment]
可以在 onMount 中使用 form.setSchemaByPath 来实现，见文档：
https://x-render.gitee.io/form-render/advanced/form-methods#%E4%BE%8B-4%EF%BC%9A%E6%9C%8D%E5%8A%A1%E7%AB%AF%E5%8A%A0%E8%BD%BD%E9%80%89%E6%8B%A9%E6%A1%86%E7%9A%84%E9%80%89%E9%A1%B9

**Comment by jiangby123** [comment]
> 可以在 onMount 中使用 form.setSchemaByPath 来实现，见文档：
> https://x-render.gitee.io/form-render/advanced/form-methods#%E4%BE%8B-4%EF%BC%9A%E6%9C%8D%E5%8A%A1%E7%AB%AF%E5%8A%A0%E8%BD%BD%E9%80%89%E6%8B%A9%E6%A1%86%E7%9A%84%E9%80%89%E9%A1%B9

收到，感谢～

**Comment by jiangby123** [comment]
> 可以在 onMount 中使用 form.setSchemaByPath 来实现，见文档：
> https://x-render.gitee.io/form-render/advanced/form-methods#%E4%BE%8B-4%EF%BC%9A%E6%9C%8D%E5%8A%A1%E7%AB%AF%E5%8A%A0%E8%BD%BD%E9%80%89%E6%8B%A9%E6%A1%86%E7%9A%84%E9%80%89%E9%A1%B9

不好意思，关于我的使用场景 还有一个疑问：
我的表单需要填写的项，都是后端传过来的，按照这个方式，我如何指定当前后端传过来的表单中。有无需要服务端进行渲染的表单项呢？如果表单项是写死的。用setSchemaByPath 是没问题的，关键我的表单是管理后台动态设置的
