### ISSUE TITLE
[BUG] x-render设置column无效

### ISSUE THREAD

**Issue by ShmilyXI** [alibaba/x-render#374]
**1.依赖仓库的版本**：
- react：16.12.0
- form-render：1.3.2
- antd：4.16.0
- funsion（如果用的是fusion）：

**2.问题描述**：
设置表单排列方式为一行三个以后,渲染出来的表单还是一行一个
通过官网的schema编辑器设置也是如此 切换到x-render展示就会无效

**3.最小复现demo**：
```json
{
  "type": "object",
  "properties": {
    "input_xvkZGJ": {
      "title": "输入框",
      "type": "string"
    },
    "input_sOPczi": {
      "title": "输入框",
      "required": false,
      "type": "string"
    },
    "input_oWwHo8": {
      "title": "输入框",
      "type": "string"
    }
  },
  "column": 3,
  "displayType": "row",
  "showDescIcon": true
}
```

**Comment by F-loat** [comment]
已修复 https://github.com/alibaba/x-render/commit/8cba8413a38947ebadf22cb76147058a74bc449e
