### ISSUE TITLE
[BUG] form-render dateRange 组件清空值后，没有触发必填校验规则

### ISSUE THREAD

**Issue by Tanviw** [alibaba/x-render#375]
**1.依赖仓库的版本**：
- react：
- form-render：1.3
- antd：
- funsion（如果用的是fusion）：

**2.问题描述**：
如 demo 所示，dateRange 组件，设置了 required 属性，在选择日期后点击清空按钮，没有提示必填
**3.最小复现demo**：

https://codesandbox.io/s/cool-leftpad-424rp?file=/App.jsx:582-605

**Comment by FateRiddle** [comment]
谢谢issue！已经fix了。
