### ISSUE TITLE
为什么不设计成显式选择想要的组件？

### ISSUE THREAD

**Issue by MoYuM** [alibaba/x-render#377]
对用户来讲，目前想选一个表单组件有三种方式

1. 不显式的指明组件类型
  比如 基础的 input， select
  ```
  "string": {
      "title": "字符串",
      "type": "string",
      "required": true
    },
  ```
2. 指明 `format` 
  比如 textarea
 ```
  "textarea": {
          "title": "简单文本编辑框",
          "type": "string",
          "format": "textarea"
        },
  ```
3. 指明 `widget`
  比如 radio
 ```
 "select": {
      "title": "单选",
      "type": "string",
      "enum": [
        "a",
        "b",
        "c"
      ],
      "enumNames": [
        "选项1",
        "选项2",
        "选项3"
      ],
      "widget": "radio"
    }
  ```

那为何不统一一个属性出来，专门用来指明我希望使用什么组件呢？

(而且感觉 `type` 这个属性有些无用)

这样代码内部判断起来也更方便，文档也能更清楚明白，用起来自然就更方便

**Comment by F-loat** [comment]
widget 就是这个属性，其他的逻辑都是在没有设置 widget 属性时合理推断 widget 的依据，type 对表单数据的初始化是很有意义的，而且表单的产物最终还是表单数据，有 type 字段也更加直观，其实 format 感觉相对作用不大，合入 rule 中反而理解成本更低

**Comment by MoYuM** [comment]
format 如果合的话，我也建议跟 widget 合到一起，不写 widget 即自动推断类型。
这个我觉的挺自然的，一旦再有第三种方式就感觉有点奇怪了。

**Comment by FateRiddle** [comment]
见常见问题 https://x-render.gitee.io/form-render/faq
