### ISSUE TITLE
[Feature]table-render中Search无法引用自定义的组件

### ISSUE THREAD

**Issue by maohui66661** [alibaba/x-render#378]
### 为什么（简述一下使用场景）
目前table-reander中的Search接受schema作为入参，来渲染表格上方的表单。但实际情况是，Search中经常会带有自定义组件。
且根据form-render官网上关于【高级用法->自定义组件->最佳实践】中提及的”针对一个项目中心化一个 Form 组件，并一次性将所有需要的自定义组件注入其中“。希望这个带有自定义组件的Form表单可以和table-render中的Search结合起来。

**Comment by siyi98** [comment]
`Search`组件是可以透传`FormRender`所有参数的，可以给个复现demo吗
