### ISSUE TITLE
[Feature] 自定义组件的校验

### ISSUE THREAD

**Issue by alvin0216** [alibaba/x-render#379]
![image](https://user-images.githubusercontent.com/34113677/118473914-13eb2e00-b73d-11eb-9414-7688b60701d2.png)

如图，validator 的方式可以配置，但是 function 的形式不利于后端存储，那么如何解决呢？字符串是无法生效的，

自定义组件是否可以内部校验，抛错？

谢谢🙏

**Comment by FateRiddle** [comment]
考虑用 "function(rule, value) { ... }" 字符串来支持。
这个方案会在下个版本推出。当然现在你也可以直接在外部这么处理一下哈。

**Comment by F-loat** [comment]
这里能直接用现在表达式的解析逻辑支持下吗

**Comment by alvin0216** [comment]
> 这里能直接用现在表达式的解析逻辑支持下吗

不能，业务复杂的情况下，应该还是要内部支持校验的。

目前实现的方案是 

```js
<FormRender 
   widgets={
       comA: props => <comA  {...props} customValidate={customValidate} />
   }
 />
```

**Comment by charleylla** [comment]
业务组件如果校验很复杂，可以考虑在 `onChange` 的时候进行校验，然后通过 `setErrors` 方法来更新错误信息。另外一种方式是为业务组件提供注册校验器的能力，使用方式可能如下面这样，具体我们需要再讨论一下。

```
function A({ form }) {
    useEffect(() => {
        form.addValidator([antd form 的自定义 validator])
    }, [])
}
```

**Comment by siyi98** [comment]
问题移步至discussion：https://github.com/alibaba/x-render/discussions/700
