### ISSUE TITLE
[BUG] Schema 編輯器無法修改欄位 ID

### ISSUE THREAD

**Issue by KuanYinChen-Houzz** [alibaba/x-render#381]
**1.依赖仓库的版本**：
- react：16.8.0
- form-render：x
- antd：4.15.5
- fr-generator: 2.0.2

**2.问题描述**：

在 v2.0.2 版本無法修改 ID, 降級至 v2.0.0 可以修改

<img width="1020" alt="截圖 2021-05-18 上午12 42 30" src="https://user-images.githubusercontent.com/76982730/118525585-eec4e280-b771-11eb-95c4-3d4e74938cf9.png">

**3.最小复现demo**：

v2.0.2: https://codesandbox.io/s/prod-cache-rizbk
v2.0.0: https://codesandbox.io/s/happy-kepler-ql0o6

**Comment by F-loat** [comment]
fr-generator 更新到 2.0.3 就好了
