### ISSUE TITLE
[BUG] schema编辑器时间控件选择日期后再切换控件回来,无法切换时间

### ISSUE THREAD

**Issue by ShmilyXI** [alibaba/x-render#382]
**1.依赖仓库的版本**：
- react：16.12.0
- form-render：1.3.3
- antd：4.x
- funsion（如果用的是fusion）：

**2.问题描述**：
schema编辑器时间控件选择日期后再切换控件回来,无法切换时间以及年月
步骤:
1. 创建一个时间控件并选择一个时间
2. 点击编辑器空白处
3. 再次点击已设值的时间控件
4. 切换日期或切换年月,控件闪烁无变化

**3.最小复现demo**：
{
  "type": "object",
  "properties": {
    "date_fXXPvi": {
      "title": "日期选择",
      "type": "string",
      "format": "date"
    }
  },
  "displayType": "row"
}

**Comment by F-loat** [comment]
官网上好像没有复现，不过编辑和预览交互是有点不一致

https://x-render.gitee.io/tools/generator/playground
