### ISSUE TITLE
[BUG] form-render 对象数组的 item 设置 required 数组属性不生效

### ISSUE THREAD

**Issue by Tanviw** [alibaba/x-render#383]
**1.依赖仓库的版本**：
- react：
- form-render：
- antd：
- funsion（如果用的是fusion）：

**2.问题描述**：
items 的 properties 里设置每一项的 required 属性可以，但在 properties 同级设置 required 数组不生效，如图所示
![image](https://user-images.githubusercontent.com/22901710/118617415-32acfb80-b7f5-11eb-8fc2-cde0ce6e5a79.png)

**3.最小复现demo**：

https://codesandbox.io/s/form-renderjichudemo-f55oy

**Comment by FateRiddle** [comment]
在上层用数组required的方式已经不推荐（原因就是你提的这个issue），请在需要被required的元素内声明required：true
https://x-render.gitee.io/form-render/schema/schema#%E5%9F%BA%E7%A1%80%E5%B1%9E%E6%80%A7
