### ISSUE TITLE
[BUG]form-render type: range 组件默认必填了

### ISSUE THREAD

**Issue by Tanviw** [alibaba/x-render#385]
**1.依赖仓库的版本**：
- react：
- form-render：
- antd：
- funsion（如果用的是fusion）：

**2.问题描述**：
类型为 range 的组件，没有设置 required 属性，在选择后清除，也校验为必填了，如 demo 所示
**3.最小复现demo**：

https://codesandbox.io/s/inspiring-bush-0dzsb?file=/App.jsx

**Comment by FateRiddle** [comment]
1.4.0 已经fix。谢谢issue

**Comment by Tanviw** [comment]
![image](https://user-images.githubusercontent.com/22901710/119615164-ad979700-be31-11eb-9196-df89eb59c288.png)
这个问题实际上是type 为 range 时，必填应该根据是否配置了 required 属性来判断。
如果 required, 那清空了也会提示必填，否则清空不提示。另外默认情况下，是非必填属性。
看这里的实现是默认必填了，所以没有解决问题呢😂麻烦大佬再看一下~~

**Comment by Tanviw** [comment]
https://codesandbox.io/s/inspiring-golick-831gs?file=/App.jsx
另外还麻烦看下这个例子，在选择日期点击清空后，再次选择日期会提示 “日期的类型不是date”，貌似和这个 issue 类似 #400

**Comment by FateRiddle** [comment]
抱歉，1.4.3 这次真的fixed了。

**Comment by Tanviw** [comment]
使用了 onMount setValues 后，还是出现了日期必填呢 https://codesandbox.io/s/practical-ellis-ibuw6?file=/App.jsx

**Comment by Mrtaochen** [comment]
确实还存在这个问题
