### ISSUE TITLE
[BUG]多选框设置default值后，无法取消选择

### ISSUE THREAD

**Issue by likepearl** [alibaba/x-render#388]
**1.依赖仓库的版本**：
- form-render：1.3.3

**2.问题描述**：
当给多选框设置默认值后，取消选择框的所有选中，录入表单其他项时，多选框又被设置了默认值

**3.最小复现demo**：
示例中不选择任何城市，再输入框输入的时候，选择框又被赋上默认值

https://codesandbox.io/s/recursing-rain-t1g8n?file=/src/pages/index.tsx

**Comment by FateRiddle** [comment]
1.4.0 fixed.
