### ISSUE TITLE
[BUG] 旧schema转换失败！ TypeError: Cannot read property 'rules' of undefined

### ISSUE THREAD

**Issue by jiangby123** [alibaba/x-render#390]
**1.依赖仓库的版本**：
- react：17.0.0
- form-render：1.3.2
- antd：4.8.6
- funsion（如果用的是fusion）：

**2.问题描述**：
fr-generator": "2.0.3", fr-generator升级到2.0.3后 form-render渲染时有上面的报错，但貌似不影响功能
**3.最小复现demo**：

https://codesandbox.io/s/form-renderjichudemo-f55oy

**Comment by F-loat** [comment]
复现 demo 里没看到有这个报错，有问题的 schema 贴一下吧

**Comment by jiangby123** [comment]
> 复现 demo 里没看到有这个报错，有问题的 schema 贴一下吧

{
                    "type":"object",
                    "column":2,
                    "properties":{
                        "hostname":{
                            "enum":[
                                "127.0.0.1"
                            ],
                            "type":"array",
                            "items":{
                                "type":"string"
                            },
                            "title":"选择目标机器",
                            "hidden":false,
                            "widget":"multiSelect",
                            "disabled":false,
                            "readOnly":false,
                            "required":false,
                            "enumNames":[
                                "test-node-1"
                            ],
                            "description":""
                        },
                        "asyncSelect_q6SCp2":{
                            "api":"http://www.baidu.com",
                            "type":"string",
                            "title":"服务端下拉选框",
                            "hidden":false,
                            "widget":"NewWidget",
                            "disabled":false,
                            "readOnly":false,
                            "required":false
                        },
                        "multiSelect__hkYpx":{
                            "enum":[
                                "A",
                                "B",
                                "C",
                                "D"
                            ],
                            "type":"array",
                            "items":{
                                "type":"string"
                            },
                            "title":"多选",
                            "widget":"multiSelect",
                            "enumNames":[
                                "杭州",
                                "武汉",
                                "湖州",
                                "贵阳"
                            ],
                            "description":"下拉多选"
                        }
                    },
                    "displayType":"row"
                },

**Comment by F-loat** [comment]
fr-generator 更新到 2.1.0 试下，我这边还是没有复现这个问题

**Comment by FateRiddle** [comment]
先关了，如果还有问题打开哈。

**Comment by sirzxj** [comment]
![image](https://user-images.githubusercontent.com/1269254/208331958-1b785f89-8f52-45db-b36d-21b7ba8e27cc.png)我也
碰到了

**Comment by fanfan7426** [comment]
> ![image](https://user-images.githubusercontent.com/1269254/208331958-1b785f89-8f52-45db-b36d-21b7ba8e27cc.png)我也 碰到了

+1
