### ISSUE TITLE
[Feature]希望addons里能返回其兄弟schema，而不是它自己的schema

### ISSUE THREAD

**Issue by xuemin-li** [alibaba/x-render#392]
### 为什么（简述一下使用场景）

如果兄弟是两个三可列枚举的，通过addons.setValue赋值即可，但兄弟最多可能有二十几项，希望通过一个函数遍历并赋值。
Thanks♪(･ω･)ﾉ    希望form-render越来越好！！

**Comment by FateRiddle** [comment]
这类场景现在已经不建议从addons里面去干了，而是通过watch。watch一个值，然后写触发后的callback。
你说的对多个值的修改，确实，这个口子这周的版本会开。
