### ISSUE TITLE
[BUG] schema 顶层如果有自定义 title 这个key，渲染时整个容器会变成折叠式的卡片

### ISSUE THREAD

**Issue by BeanWei** [alibaba/x-render#394]
**1.依赖仓库的版本**：
"react": "^17.0.2",
"antd": "^4.15.6",
"form-render": "^1.3.4",
"fr-generator": "^2.0.3",

**2.问题描述**：
rt。
![image](https://user-images.githubusercontent.com/33516660/119215272-4612dc00-baff-11eb-8a86-b48b4142aa7c.png)

**3.最小复现demo**：
```json
{
  "title": "文件",
  "type": "object",
  "properties": {
    "string": {
      "title": "字符串",
      "type": "string",
      "required": true
    },
    "select": {
      "title": "单选",
      "type": "string",
      "enum": [
        "a",
        "b",
        "c"
      ],
      "enumNames": [
        "选项1",
        "选项2",
        "选项3"
      ],
      "widget": "radio"
    }
  }
}
```

**Comment by F-loat** [comment]
这个应该不算 bug 吧，title 本身是 object 组件的一个属性，应该避免用做自定义属性的

**Comment by FateRiddle** [comment]
就别写title了呗。有title的object就会渲染成卡片。
