### ISSUE TITLE
[BUG]  array中非string类型要求必填时校验会报【xx必填的类型不是xxx】的错误

### ISSUE THREAD

**Issue by jiyeking** [alibaba/x-render#400]
**1.依赖仓库的版本**：
- react：17.0.2
- form-render：1.3.4
- antd：4.15.6
- funsion（如果用的是fusion）：

**2.问题描述**：

array类型的字段中`非string`类型的有必填校验时会产生校验【xx必填的类型不是xxx】的错误，通过跟踪代码，发现使用的校验依赖包中 `async-validator`对 `array`类型的校验是不支持传入数组形式的 rules，而在本项目的 `getDescriptorFromSchema`方法中处理单个的逻辑部分的代码返回的 result 是 `array`类型，如：
```json
[
    {
        "type": "number"
    },
    {
        "required": true
    }
]
```
 通过查阅跟踪`async-validator`源码，发现对 `array`类型的校验时假如传入的是数组rules会遍历校验，但是在校验每条时会获取 `type`，获取不到`type`就会取默认的类型` string` 导致了`非 string` 类型出现校验错误的提示。

建议：能否把上方的 `array`组装成 `object` 方式？因为我简单试了下 `object` 方式的校验是没有问题的，而且对于重复的条目是不是也会去重以及提高校验效率？
感谢：这个项目节省了我很多组装页面的工作，继续支持～

**3.最小复现demo**：

在下方链接的demo中，因为现在默认就有一个子条目。需要在排序中填入数字然后再点击按钮进行触发
https://codesandbox.io/s/keen-engelbart-37b3x?file=/App.jsx

**Comment by FateRiddle** [comment]
有兴趣pr一波么？https://github.com/alibaba/x-render/blob/master/CONTRIBUTING.md

**Comment by jiyeking** [comment]
好的

**Comment by FateRiddle** [comment]
你的那个提交有点问题，我comment了，我用一个简单的方式解决了。1.4.0 版本。
谢谢支持！
