### ISSUE TITLE
[BUG] 编辑器格式配置不生效

### ISSUE THREAD

**Issue by xuemin-li** [alibaba/x-render#408]
**1.依赖仓库的版本**：
- react：16.13.1
- form-render：1.3.3
- antd：4.0.4
- funsion（如果用的是fusion）：

**2.问题描述**：
![image](https://user-images.githubusercontent.com/5096093/119479403-2b509980-bd83-11eb-9301-d6728a0132c7.png)
https://x-render.gitee.io/tools/generator/ 如链接，选择了“日期时间”不生效，显示的仍然是日期。

**3.最小复现demo**：

https://codesandbox.io/s/form-renderjichudemo-f55oy

**Comment by xuemin-li** [comment]
同理内置组件中设置dateTime也无效
thanks ^_^

**Comment by F-loat** [comment]
2.1.1 已修复
