### ISSUE TITLE
希望设计器新增字段类型

### ISSUE THREAD

**Issue by where16** [alibaba/x-render#413]
希望设计器 上能新增 输入框或者选择框的字段类型，当前默认都是String类型，如果是数字的话，页面存储or读取的时候需要手动转换（后台存储的是整形）。如果是嵌套多层的表单，更难转换
![image](https://user-images.githubusercontent.com/4919880/119678436-169eff00-be72-11eb-9481-30c86fb0dd13.png)

**Comment by moling1234** [comment]
自己手动实现一下 type 类型可选就行了
