### ISSUE TITLE
[BUG] The above error occurred in the <App> component:

### ISSUE THREAD

**Issue by jiangby123** [alibaba/x-render#416]
Uncaught TypeError: Cannot read property 'column' of undefined
The above error occurred in the <App> component:

**1.依赖仓库的版本**：
- react：^17.0.0
- form-render："1.4.2"
- antd："^4.8.6"

**2.问题描述**：
![image](https://user-images.githubusercontent.com/47846791/119806782-1b68bf00-bf15-11eb-8ca7-c1b70b559762.png)

 form-render 升级至大于1.3.2 就会有这个问题，目前使用1.3.2版本是没有问题的，但是组件无法更新了就
**3.最小复现demo**：

https://codesandbox.io/s/form-renderjichudemo-f55oy

**Comment by FateRiddle** [comment]
有代码么？我这边并没有出现。

**Comment by jiangby123** [comment]
<FormRender readOnly form={form} schema={schema}/>


数据是这样set进去的：
    const form = useForm();
    const [schema, setSchema] = useState<string[]>();

只要版本大于1.3.2，就会报错导致页面空白

**Comment by jiangby123** [comment]
<FormRender readOnly form={form} schema={schema}/>
                <Divider />
                <Row justify="center">

**Comment by jiangby123** [comment]
form_structrue:

**Comment by jiangby123** [comment]
"fr-generator": "2.1.2",
        "form-render": "1.4.4"
刚才看到form又有新版本，更新了下，现在页面渲染则没有上面的报错和空白页面了，1.3.3-1.4.3版本。试过很多都有上面的问题

**Comment by FateRiddle** [comment]
谢谢反馈。1.4上面的有几个版本是有点问题。。惭愧。现在都好了。
