### ISSUE TITLE
[Performance]form render会做性能优化？输入控件发生输入操作，都只会更新它自身，而不会整树更新

### ISSUE THREAD

**Issue by Crystal2030** [alibaba/x-render#422]

**Comment by FateRiddle** [comment]
性能优化已经做了不少了。普通表单没有之间的关联关系，form-render要考虑到表达式的问题，但在最底层的组件渲染那层做了强判断避免重复渲染了。
而且对性能问题的优化可以在实际场景中出现了性能问题后再讨论。这里总是有权衡的。
如果你有什么优化建议或者优化pr，欢迎反馈和贡献哈！
