### ISSUE TITLE
[BUG]list类型submit后，能够获取errors，但表单项没有标红

### ISSUE THREAD

**Issue by xuemin-li** [alibaba/x-render#423]
**1.依赖仓库的版本**：
- react：17.0.2
- form-render：1.4.4
- antd：4.16.0

**2.问题描述**：
初始表单项有必填项时，针对新增的list item，直接提交不触发标红校验，只有在点击任意一个表单项时，才会标红。
![image](https://user-images.githubusercontent.com/5096093/120139282-b8c03d80-c20a-11eb-92fd-1b686e5d244b.png)
如下图有error，但未标红：
![image](https://user-images.githubusercontent.com/5096093/120140057-4bada780-c20c-11eb-91d6-bb7aff8958b0.png)
输入值时才会标红：
![image](https://user-images.githubusercontent.com/5096093/120140083-59632d00-c20c-11eb-941f-81886f1b1266.png)

 **希望没有任何输入，不操作表单项时，直接submit也可以标红。**
^_^   感谢 

**3.最小复现demo**：

https://codesandbox.io/s/form-renderjichudemo-f55oy

**Comment by FateRiddle** [comment]
这个是正常的。会有这种情况：list不是必填的，但是一旦你填了一项就一定要填完。如果强制校验这类场景就没法支持了。

数据的角度：你可以打开debug=true的props看一眼formData就明白了。没有触碰时，list结构是空的，所以不做下层的校验。

解决方案：这里可以在list这侧加上 min: 1 ，来强制必须要填一项。就ok了。
