### ISSUE TITLE
[BUG]git下载文件，无法正常运行，但是form-render v1.4.0下载就没问题

### ISSUE THREAD

**Issue by zhoujun5201314** [alibaba/x-render#425]
![image](https://user-images.githubusercontent.com/24538118/120288677-116b0580-c2f3-11eb-8fbe-6c1bc1992fda.png)
这个问题的产生，是在
![image](https://user-images.githubusercontent.com/24538118/120288747-234ca880-c2f3-11eb-843d-e1f49e42cfb5.png)
这个地方git的时候产生的。
但是我在
![image](https://user-images.githubusercontent.com/24538118/120288818-36f80f00-c2f3-11eb-8a3e-b9a20899d088.png)
这里下载就没问题。

**Comment by zhoujun5201314** [comment]
补充下：就是在npm start的时候产生的。

**Comment by FateRiddle** [comment]
npm 跟新了。顶层彻底重装一遍，详见 contributing.md
