### ISSUE TITLE
[BUG] form-render range 组件问题

### ISSUE THREAD

**Issue by Tanviw** [alibaba/x-render#427]
**1.依赖仓库的版本**：
- react：
- form-render：1.4.4
- antd：

**2.问题描述**：
如 demo 所示，type 为 range 时,
1.没有设置 required，使用了 onMount setValues 后，还是出现了日期必填校验
2.如果设置 required，在提交时也没有校验日期必填

range 类型的必填校验没有和配置对应起来

**3.最小复现demo**：

https://codesandbox.io/s/practical-ellis-ibuw6?file=/App.jsx

**Comment by Tanviw** [comment]
同时对于 range 设置 disabled: true，没有生效

**Comment by FateRiddle** [comment]
已经修复哈。版本1.5.2

**Comment by Tanviw** [comment]
1.5.2版本，没有解决提交时对 range 的必填校验啊 https://codesandbox.io/s/agitated-bird-pmht1?file=/App.jsx

**Comment by FateRiddle** [comment]
1.5.4 fix了。这个问题也是吐血了。谢谢反馈。
