### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by moling1234** [alibaba/x-render#428]
**1.依赖仓库的版本**：
- react：16.9.0
- form-render：2.1.2
- antd：4.16.1

**2.问题描述**：
schema 编辑器，转formily报错

**3.最小复现demo**：
https://codesandbox.io/s/jm1xs

**Comment by F-loat** [comment]
已修复 4af4d69dd9505eb5cfc7595e8ab4e913efaed8b6
