### ISSUE TITLE
[Feature] 优化 form-render 体积，底层依赖的antd，使用 dayjs 替换掉 momentjs

### ISSUE THREAD

**Issue by FateRiddle** [alibaba/x-render#429]
### 期望的新功能

目前moment的部分占了 400k 左右的大小，一旦使用了 date 类组件就会被打入包

![image](https://user-images.githubusercontent.com/12005259/120968090-ff79de80-c79a-11eb-83d4-4a4b9339a695.png)

需要优化 form-render 体积，底层依赖的antd，使用 dayjs 替换掉 momentjs

**Comment by tw93** [comment]
自己的需求不要写到issue
