### ISSUE TITLE
form-render通过props透传自定义属性失败

### ISSUE THREAD

**Issue by oppcxx** [alibaba/x-render#434]
schema
![image](https://user-images.githubusercontent.com/71963553/121452250-b069be80-c9d1-11eb-903a-886db38b06ca.png)
渲染结果
![image](https://user-images.githubusercontent.com/71963553/121452351-e0b15d00-c9d1-11eb-92ea-3377f044a6ee.png)

**Comment by FateRiddle** [comment]
defaultValue 应该是数组，这里直接写一个字符串传入的就是字符串了，所以会无效。这类表达式建议直接使用js object来写（就可以随便写js的语法了）。或者通过 setSchema 的方式在加载后传入。
