### ISSUE TITLE
[BUG] table-render 里面的参数命名冲突

### ISSUE THREAD

**Issue by androidvm** [alibaba/x-render#436]
table-render 中 index.tsx 里面有一个函数 basicSearch 做了一个数组的判断，
```
if (Array.isArray(api)) {
  _params = { ..._params, tab };
}
```
其实这里的api是参数，不是闭包里面的那个，所以这个判断一直都是false。
只需要把参数里面api改一下名字就好了。

**然后提一个建议：** 分页信息应该作为一个单独的参数传给api，这样可以防止因为表单名字冲突引起的bug，特别是这种bug很难发现。

**Comment by FateRiddle** [comment]
fixed
