### ISSUE TITLE
[BUG]fr-generator 高级组件-颜色选择点击后页面白屏

### ISSUE THREAD

**Issue by jeezliu** [alibaba/x-render#439]
**1.依赖仓库的版本**：
- form-render：1.5.2

**2.问题描述**：
使用 schema 编辑器 fr-generator，选择高级组件-颜色选择点击后页面白屏

**3.最小复现demo**：

https://x-render.gitee.io/tools/generator/

**Comment by F-loat** [comment]
fr-generator@2.4.5 已修复
