### ISSUE TITLE
[Feature] formRender 支持 modal

### ISSUE THREAD

**Issue by lmnsg** [alibaba/x-render#443]
### 期望的新功能
通用的 modal 能力,  类似于 { type: 'string', title: "输入框"， modal: true } 这样。加个modal，一个正常展示的数据就变成modal 展示了

### 为什么（简述一下使用场景）
![image](https://user-images.githubusercontent.com/10400425/122187809-f89d4b00-cec1-11eb-8745-ffc37cadf360.png)

**Comment by tw93** [comment]
一个自定义组件可搞定：https://x-render.gitee.io/form-render/advanced/widget
