### ISSUE TITLE
[BUG]单选框optionType设置为button,选项和title在垂直方向上没有居中

### ISSUE THREAD

**Issue by hello-world-csx** [alibaba/x-render#445]
**1.依赖仓库的版本**：
- react：16.9.0
- form-render：1.5.2
- antd：4.16.3

**2.问题描述**：
      单选框optionType设置为button,选项和title不垂直居中
**3、schame
{
  "type": "object",
  "properties": {
    "select": {
      "title": "单选",
      "type": "string",
      "enum": [
        "a",
        "b",
        "c"
      ],
      "enumNames": [
        "选项1",
        "选项2",
        "选项3"
      ],
      "widget": "radio",
      "displayType":"row"
    },
    "select2": {
      "title": "单选2",
      "type": "string",
      "displayType":"row",
      "enum": [
        "a",
        "b",
        "c"
      ],
      "enumNames": [
        "选项1",
        "选项2",
        "选项3"
      ],
      "props":{
        "optionType":"button"
      },
      "widget": "radio"
    }
  }
}
**截图
![image](https://user-images.githubusercontent.com/85184285/122900240-16195b80-d37f-11eb-90e3-77c89c2b6b80.png)

**Comment by FateRiddle** [comment]
1.6.2 版本修复
