### ISSUE TITLE
[Feature]是否考虑追加table表格布局方式

### ISSUE THREAD

**Issue by lovewinders** [alibaba/x-render#446]
### 期望的新功能
期望未来支持常见表格单元格合并这种布局方式

### 为什么（简述一下使用场景）

例如如下图这种常见的单元格表格方式布局
![1624359136422](https://user-images.githubusercontent.com/22837419/122912571-0acc2d00-d38b-11eb-952a-b75644e1281c.jpg)

**Comment by tw93** [comment]
form-render的底层其实是针对antd的一个上层实现，此类的布局改动很大，同时大部分人用不到，抱歉官方暂无计划，有兴趣，你可以基于fr搞一个
