### ISSUE TITLE
[BUG] 添加行数和form.getValues拿到的不一致

### ISSUE THREAD

**Issue by Crystal2030** [alibaba/x-render#448]
**1.依赖仓库的版本**：
- react：16.14
- form-render：1.5.6
- antd：4.14.1

**2.问题描述**：
添加行数和form.getValues拿到的不一致

**3.最小复现demo**：
https://codesandbox.io/s/brave-bash-x20n7?file=/demo/display.js
![image](https://user-images.githubusercontent.com/6970454/123223228-4be74d00-d503-11eb-9e7d-ed2dc3a356ea.png)

**Comment by FateRiddle** [comment]
我说两个点
1. form.getValues 建议在 onMount 或者 click事件里使用，而不是直接在函数组件体内
2. 没有填写任何数据的item，是不会生成数据的，只有你真正填写了哪怕一个input之后，那一行的数据才会生成
