### ISSUE TITLE
[BUG]渲染样式bug

### ISSUE THREAD

**Issue by Copyes** [alibaba/x-render#449]
**1.依赖仓库的版本**：
- react：16.3
- form-render：1.x
- antd：

**2.问题描述**：
![image](https://user-images.githubusercontent.com/10307282/123232112-6a514680-d50b-11eb-82ea-ce7e4f96908e.png)
![image](https://user-images.githubusercontent.com/10307282/123232149-73421800-d50b-11eb-9eb9-948147709172.png)

![image](https://user-images.githubusercontent.com/10307282/123232193-7dfcad00-d50b-11eb-9e2e-3a23767cdb6f.png)

设置整体一行二列后，列表布局组件也会一行二列，布局组件上设置了width：calc(50%)；

**3.最小复现demo**：
fr-generator预览即可实现

**Comment by FateRiddle** [comment]
不太理解这为什么是bug？1行两列不是50%么？
