### ISSUE TITLE
[BUG]object的schema，hidden与required同时存在，hidden为true时，仍然校验字段必填。

### ISSUE THREAD

**Issue by xuemin-li** [alibaba/x-render#451]
**如题，希望对象属性的hidden为true时，就不要校验了，目前现象是还会校验**

**1.依赖仓库的版本**：
- react：16.13.1
- form-render：1.5.5
- antd：4.0.4

**Comment by FateRiddle** [comment]
@xuemin-li 发一个可复现的schema？

**Comment by xuemin-li** [comment]
> @xuemin-li 发一个可复现的schema？

const STEPONE = {
  "type": "object",
  "properties": {
    "asacTips": {
      "title": "命中安全后的提示文案",
      "type": "string",
      "default": "亲，投票过于频繁请明天再来",
      "required": true,
      "hidden": '{{formData.asacCheckFlag === 0}}',
    },
    "gainTicketType": {
      "title": "投票模式",
      "type": "number",
      "default": 2,
      "description": "该项保存后不支持修改",
      "enum": [
        1,
        2,
      ],
      "enumNames": [
        "不得票即可投模式(适用于话题选择、点赞类活动)",
        "先得票再投票模式(推荐)"
      ],
      "widget": "radio",
      "required": true,
    },
    "ticketRule": {
      "type": "object",
      "title": "投票策略",
      "properties": {
        "hasFreeTicket": {
          "title": "基础票设置（到访即得）",
          "type": "number",
          "default": 2,
          "enum": [
            1,
            2,
          ],
          "enumNames": [
            "有基础票",
            "无基础票"
          ],
          "hidden": '{{formData.gainTicketType === 1}}',
          "widget": "radio"
        },
        "giveTicketType": {
          "title": "基础票赠送策略",
          "type": "number",
          "default": 2,
          "enum": [
            1,
            2,
          ],
          "enumNames": [
            "每天可得",
            "活动期只得一次"
          ],
          "hidden": '{{rootValue.hasFreeTicket === 2}}',
          "widget": "radio"
        },
        "giveTicketCount": {
          "title": "非会员用户基础票",
          "placeholder": "请输入票数",
          "hidden": '{{rootValue.hasFreeTicket === 2}}',
          "default": 0,
          "required": true,
          "type": "number"
        }
      }
    }
  }
}
如上，选择了hasFreeTicket为2，giveTicketCount不显示，但仍校验。
另外：本身hidden状态的字段，给它设置的默认值，在提交时还是有，希望没有~~，可以用上面的giveTicketCount字段验证。
感谢

**Comment by FateRiddle** [comment]
1.6.3 版本已经修复
