### ISSUE TITLE
[Feature] list类型可以扩展下新增按钮自定义&可以选择新增父子节点

### ISSUE THREAD

**Issue by liu9856866814** [alibaba/x-render#454]
### 自定义内容模板使用
如 内容中可以有列表，列表中可能有文字和图片等嵌套，不希望使用 widget: 'list3'的弹窗形式；
希望可以查看formRender表单的schema结构
![image](https://user-images.githubusercontent.com/16934376/123787939-00bba880-d90e-11eb-9659-5e3c785e4b18.png)

**Comment by liu9856866814** [comment]
const schema = {
  type: 'object',
  properties: {
    listName2: {
      title: '对象数组',
      description: '对象数组嵌套功能',
      type: 'array',
      widget: 'list1',
      items: {
        type: 'object',
        properties: {
          input1: {
            title: '简单输入框',
            type: 'string',
            required: true,
          },
          input2: {
            title: '简单输入框2',
            type: 'string',
          },
          input3: {
            title: '简单输入框3',
            type: 'string',
          },
          select1: {
            title: '单选',
            type: 'string',
            enum: ['a', 'b', 'c'],
            enumNames: ['早', '中', '晚'],
            widget: 'select',
          },
          listName2: {
            title: '对象数组',
            description: '对象数组嵌套功能',
            type: 'array',
            widget: 'list0',
            items: {
              type: 'object',
              properties: {
                input1: {
                  title: '简单输入框',
                  type: 'string',
                  required: true,
                },
                input2: {
                  title: '简单输入框2',
                  type: 'string',
                },
                input3: {
                  title: '简单输入框3',
                  type: 'string',
                },
                select1: {
                  title: '单选',
                  type: 'string',
                  enum: ['a', 'b', 'c'],
                  enumNames: ['早', '中', '晚'],
                  widget: 'select',
                },
              },
            },
          },
        },
      },
    },
  },
};
### 期望嵌套的内容可以放在第二行与第一层结构缩进两字符左右展示
![image](https://user-images.githubusercontent.com/16934376/123926044-15577980-d9be-11eb-93a4-44d2375410f5.png)

目前使用 widget: list0 - list3 展示效果都不理想，期望可以尽快优化下，谢谢

**Comment by FateRiddle** [comment]
我的看法是，新增节点这个需求
1. 太重了，不如直接去操作form.setSchema修改schema。
2. 而且不怎么用户友好，要新增一个节点必然要定义这个表单对应的key值、title等，这些并不太合适暴露给用户

重要的是我也没有看到具体使用场景，如果有后续讨论欢迎打开
