### ISSUE TITLE
[BUG]项目启动不了？

### ISSUE THREAD

**Issue by wheelo** [alibaba/x-render#456]
**1.依赖仓库的版本**：
- react：^16.12.0
- form-render：1.5.2
- antd：^4.x

**2.问题描述**：
项目拉取到本地，master分支
yarn安装完依赖完成
项目启动`npm start`或`yarn start`

![image](https://user-images.githubusercontent.com/3896369/123922619-cc51f600-d9ba-11eb-8d50-8676f27d3199.png)

**Comment by F-loat** [comment]
切下 dev 分支，master 分支有个依赖版本不匹配

**Comment by wheelo** [comment]
> 切下 dev 分支，master 分支有个依赖版本不匹配

你好，切换到dev分支后一样的错误信息😭

**Comment by F-loat** [comment]
重新安装下依赖
