### ISSUE TITLE
[BUG]fr-generator类型声明文件 ExtraButton & ControlButton 与文档描述不符

### ISSUE THREAD

**Issue by DevanXU** [alibaba/x-render#460]
**1.依赖仓库的版本**：
- react：17.0.2
- form-render：1.5.6
- antd：4.16.6
- fr-generator: 2.4.3

**2.问题描述**：
fr-generator/index.d.ts 中 ExtraButton & ControlButton的 onClick 定义与[文档描述](https://x-render.gitee.io/tools/generator#events)不符

```
export interface ExtraButton {
  /** 按钮文案 */
  text: string;
  /** 点击回调 */
  onClick?: () => void;
  [key: string]: any;
}

export interface ControlButton {
  /** 按钮文案 */
  text?: string;
  /** 点击回调 */
  onClick?: () => void;
}
```

**3.最小复现demo**：

**Comment by F-loat** [comment]
这个为什么不符了

**Comment by DevanXU** [comment]
ExtraButton & ControlButton都是错的。不好意思，我贴的ControlButton代码是本地改过的（已经改成原始的了），你可以看下你本地的。

**Comment by F-loat** [comment]
fr-generator@2.4.5 已修复
