### ISSUE TITLE
[Feature]fr-generator的controlButton可以自定义（包括默认buttons）

### ISSUE THREAD

**Issue by DevanXU** [alibaba/x-render#461]
### 期望的新功能
<Generator controlButtons={} ... />中，controlButtons可以：
- 根据选择的组件显示允许操作的button，目前的做法是所有的button菜单都一样，例如：用户新增未保存的组件允许删除，用户已保存的组件不允许删除。
- 默认的button显示的是图标，自定义的button显示的是文案（文本），应该要保存一致。

**Comment by F-loat** [comment]
> 用户新增未保存的组件允许删除，用户已保存的组件不允许删除。

这个可以传函数来控制，文档里没写，可以用下看看，有什么建议也可以讨论下。图标的支持我考虑下怎么处理，直接传图标组件进来应该可以。

**Comment by DevanXU** [comment]
选择组件没有函数触发，没法定位是哪个组件。有个onSchemaChange，不过不适用这里的场景。

**Comment by F-loat** [comment]
不是的，是 controlButton 本身可以是一个函数，使用上大概像下面这样 https://github.com/alibaba/x-render/blob/master/tools/schema-generator/src/components/Canvas/core/Wrapper.jsx#L217

``` jsx
<Generator controlButtons={[true, true, (schema) => schema.type === 'string' ? { text: '字符串' } : false]} />
```

**Comment by DevanXU** [comment]
> 不是的，是 controlButton 本身可以是一个函数，使用上大概像下面这样 https://github.com/alibaba/x-render/blob/master/tools/schema-generator/src/components/Canvas/core/Wrapper.jsx#L217
> 
> ```js
> <Generator controlButtons={[true, true, (schema) => schema.type === 'string' ? { text: '字符串' } : false]} />
> ```

OK，这是可以的。"schema"会自动插入`$id`这个字段，这个可以用来确定被选中的组件。BTW，`$id`的命名规则是在Generator里的`id`前加`#/`吗？为什么不保持一致呢？

**Comment by DevanXU** [comment]
> > 用户新增未保存的组件允许删除，用户已保存的组件不允许删除。
> 
> 这个可以传函数来控制，文档里没写，可以用下看看，有什么建议也可以讨论下。图标的支持我考虑下怎么处理，直接传图标组件进来应该可以。

图标的支持还要考虑tooltip，有时候图标很难让用户一目了然，需要tooltip信息辅助。

**Comment by F-loat** [comment]
v2.5.2 已支持，可以用 children 属性代替 text 属性，传入 `<Tooltip />` 这样（其实 text 属性也一样可以--）

**Comment by YangsonHung** [comment]
把源码魔改就行了 https://github.com/YangsonHung/fr-generator-hyx
