### ISSUE TITLE
[BUG] schema className 配置在运行时可以正确携带class,设计时无法携带该class

### ISSUE THREAD

**Issue by killdada** [alibaba/x-render#462]
**1.依赖仓库的版本**：
- react：17.*
-  form-render: "^1.5.6",
 - fr-generator: "^2.4.3",
- antd：4.16.6

**2.问题描述**：

className运行时正常显示class，设计时class缺失

![image](https://user-images.githubusercontent.com/16487810/124252978-20dfa780-db5a-11eb-96d2-e83f53a17768.png)
![image](https://user-images.githubusercontent.com/16487810/124252996-263cf200-db5a-11eb-93b2-1a65e508b50f.png)

**3.最小复现demo**：

https://codesandbox.io/s/sweet-haze-79wss?file=/App.jsx

随便再官网fr-generator 配置一个 className 即可测试

**Comment by killdada** [comment]
![image](https://user-images.githubusercontent.com/16487810/124898252-9a234280-e011-11eb-8fcb-64b4b9e3a75e.png)

![image](https://user-images.githubusercontent.com/16487810/124899009-47965600-e012-11eb-94b6-0dc928e994f3.png)


目前想到的折中自己处理方式，统一对这种类型全部定义为string类型，使用的时候自行转换下也可以处理

**Comment by F-loat** [comment]
fr-generator@2.4.5 已修复
