### ISSUE TITLE
[BUG]组件在readOnly模式下的layout无法控制

### ISSUE THREAD

**Issue by DevanXU** [alibaba/x-render#464]
**1.依赖仓库的版本**：
- react：17.0.2
- form-render：1.5.6
- antd：4.16.6
- fr-generator: 2.4.3

**2.问题描述**：
组件在readOnly模式下的样式无法控制，e.g. 默认的html显示组件间距有问题（同一组件的标签和内容间距太大，相邻组件间距太小），而且无法调整。采用自定义组件的话，组件间的间距也无法调整。

**3.最小复现demo**：

https://codesandbox.io/s/formrender-demo-0poys?file=/App.jsx

**Comment by DevanXU** [comment]
any update?

**Comment by lovesly** [comment]
试试 readOnlyWidget ？

**Comment by DevanXU** [comment]
> 试试 readOnlyWidget ？

readOnlyWidget是自定义组件的显示，不同组件之间呢？组件和标签之间呢？

**Comment by FateRiddle** [comment]
我看你特意使用了displayType: column, row的情况展示是不是更雅观点？
![image](https://user-images.githubusercontent.com/12005259/127988682-2ec84056-71fa-482f-9612-2e22c5d12d55.png)

竖排的间距确实有点问题，这个我们会解决。如果还有其他定制样式需求，建议用万能的css样式覆盖哈。
