### ISSUE TITLE
[BUG]form-render 提交时 removeHiddenData 的逻辑 bug

### ISSUE THREAD

**Issue by Tanviw** [alibaba/x-render#467]
**1.依赖仓库的版本**：
- react：
- form-render：1.5.8-beta.1
- antd：

**2.问题描述**：
如 demo 所示，在字段为对象类型时，其下面的属性 hidden 表达式为 "{{rootValue.a !== '2'}}"，在页面控制显示隐藏的逻辑是对的，但是提交时存在 bug。
在该例子中，不管选了”是“或者”否“， RelationshipOtherCN 总是**不被提交**。
如果表达式换成"{{rootValue.a === '1'}}"，不管选了”是“或者”否“， RelationshipOtherCN 总是**会被提交**。

但是把表达式的 rootValue 换成 formData.test，则上述两种写法，提交的逻辑都是正确的。

**3.最小复现demo**：

https://codesandbox.io/s/cocky-meninsky-889mz?file=/App.jsx

**Comment by FateRiddle** [comment]
看来是 rootValue 这块的逻辑有点问题，谢谢反馈。

**Comment by FateRiddle** [comment]
1.6.3 版本已经修复。
