### ISSUE TITLE
[Feature]

### ISSUE THREAD

**Issue by anticcc** [alibaba/x-render#471]
### form-render 产出的 schema 无法通过校验

![image](https://user-images.githubusercontent.com/51567189/125410095-25744d80-e3ef-11eb-994f-475bcac26b07.png)

测试schema

`{
    "$schema": "https://json-schema.org/draft/2019-09/schema",
    "$id": "https://json-schema.org/draft/2019-09/schema",
    "type":"object",
    "properties": {
    "image1": {
      "widget": "PicturePicker",
      "type": "string",
      "title": "图片选择器1",
      "required": true,
      "props": {
        "size": 200,
        "fixHeight": "200",
        "mime": "png",
        "fixWidth": "200"
      }
    },
    "buttonWord": {
      "min": 3,
      "max": 5,
      "type": "string",
      "title": "按钮文案",
      "required": true
    },
    "cardTheme": {
      "min": 5,
      "max": 10,
      "description": "",
      "type": "string",
      "title": "主题描述",
      "required": true
    }
  }
}
`

[https://www.jsonschemavalidator.net/](校验网址 https://www.jsonschemavalidator.net/)

**Comment by tw93** [comment]
可以理解是为了方便使用，用了jsonschema的一个超级，原始规范required是放外面的，但是我们觉得不是很友好，当然也支持
