### ISSUE TITLE
[BUG] title如果设置为ReatNode会不显示

### ISSUE THREAD

**Issue by Crystal2030** [alibaba/x-render#472]
**1.依赖仓库的版本**：
- react：16.8
- form-render：1.5.8
- antd：4.x

**2.问题描述**：
 title如果设置为ReatNode会不显示，甚至title稍微多写几个字就显示不完整
 
![image](https://user-images.githubusercontent.com/6970454/126098714-0051c625-cf10-468a-99a7-fb72835388ee.png)

**3.最小复现demo**：
https://codesandbox.io/s/cool-galileo-whlw2?file=/App.jsx

**Comment by FateRiddle** [comment]
需要用html string 哦
https://codesandbox.io/s/strange-bohr-9h4u3
