### ISSUE TITLE
[Feature] watch 是否支持字段列表监听，或者函数表达式？

### ISSUE THREAD

**Issue by killdada** [alibaba/x-render#473]
### 为什么（简述一下使用场景）

![image](https://user-images.githubusercontent.com/16487810/126114452-4ad1cdf5-a786-4eea-a34c-a1f0ce30c701.png)

基于我们以前的表单联动交互处理，我新增了一个类型于这样的配置弹窗处理，然后想要在watch的时候进行处理，watch现在除了全局的 # ，其他的都是单个的字段的监听，有没有办法提供一种对 字段列表的监听，比如 字段1 || 字段2 || 字段3 只要里面的一个字段改变就触发联动函数。 目前是自己折中处理优化了下，不过比较麻烦点

**Comment by tw93** [comment]
从 vue watch 的角度不是很好实现，先用折中方案试试，或者一起用你这个场景直接到源码里面去，好不好支持

**Comment by web-linda** [comment]
现在就是列表监听啊。列表里面的字段没法监听吧
