### ISSUE TITLE
vscode 版本: 1.58.2 - FormRender generator设计器无效[BUG]

### ISSUE THREAD

**Issue by sephirothwzc** [alibaba/x-render#476]
感谢制作组！

FormRender generator - v1.0.5
Visual Studio Code - 版本: 1.58.2
提交: c3f126316369cd610563c75b1b1725e0679adfb3
日期: 2021-07-14T22:10:12.490Z (5 天前)
Electron: 12.0.13
Chrome: 89.0.4389.128
Node.js: 14.16.0
V8: 8.9.255.25-electron.0
OS: Darwin arm64 20.3.0

问题没有右键 没有右上角图标，无法设计json文件。

系统：
macos big sur
11.2.3
m1 
arm 版本vscode
谢谢 🙏

**Comment by F-loat** [comment]
旧版本的 vscode 可以吗，vscode 某个版本开始加了工作区安全机制，不信任的工作区目前还没有设配

**Comment by F-loat** [comment]
没有复现这个问题，可以尝试下信任打开的文件，还有问题的话可以再反馈
