### ISSUE TITLE
[BUG]父节点设置hidden后，提交时子节点仍然参与了require校验

### ISSUE THREAD

**Issue by yoyogis** [alibaba/x-render#484]
父节点通过setSchema设置hidden后，提交时子节点仍然参与了require校验。父节点和子节点此时已经隐藏，不应该再参与校验。
如： https://codesandbox.io/s/brave-goldstine-kyp4h?file=/App.jsx

**Comment by FateRiddle** [comment]
1.6.3版本修复。这个问题隐藏比较深，做了个小的重构。
