### ISSUE TITLE
[BUG] Parameter has a name but no type.

### ISSUE THREAD

**Issue by oMaten** [alibaba/x-render#486]
**1.依赖仓库的版本**：
- react：17
- form-render：1.5.8
- antd：4

**2.问题描述**：

引用 form-render 后 tsc 构建会检测到类型异常，注意：需要 tsconfig.json 开启严格模式后 `compilerOptions.strict: true`

```
node_modules/form-render/lib/index.d.ts:49:15 - error TS7051: Parameter has a name but no type. Did you mean 'arg0: any'?
49   syncStuff: (any) => void;
```

**3.最小复现demo**：

非 UI 逻辑问题无法在 scb 上复现，可以直接对 `index.d.ts` 进行修复

**Comment by F-loat** [comment]
dev 分支修复了哈
