### ISSUE TITLE
[Feature]

### ISSUE THREAD

**Issue by xiaoCue** [alibaba/x-render#489]
### 期望的新功能 (describe the expected new feature)
希望列表的展示可以自定义 新增一行 的显示和隐藏
### 简述一下使用场景，便于开发者更好理解新功能的必要性 (describe your scenario for us to understand the need)
有时候希望展示固定数量的list,不需要新增一行、复制、删除的按钮
![image](https://user-images.githubusercontent.com/50943211/128448104-d5e3a395-0c71-4104-9814-5c215fbba8a1.png)

**Comment by FateRiddle** [comment]
见 https://x-render.gitee.io/form-render/schema/props
