### ISSUE TITLE
[BUG] 通过setSchema给字段设置rules，不生效

### ISSUE THREAD

**Issue by Crystal2030** [alibaba/x-render#491]
**1.依赖仓库的版本(Dependencies versions)**：

- react：16.14
- form-render：1.6.0
- antd：4.14.1

**2.问题描述(Bug description)**：
通过setSchema给字段设置rules，不生效（在特定场景下，需要在接口请求完之后，给某个字段设置特殊的rules规则）

**3.最小复现demo(Reproduction demo)**：
https://codesandbox.io/s/priceless-maxwell-4tvsl?file=/App.jsx

**Comment by FateRiddle** [comment]
1.6.3版本已经修复
