### ISSUE TITLE
[BUG]表单联动无法识别复杂表达式

### ISSUE THREAD

**Issue by moling1234** [alibaba/x-render#494]
1.依赖仓库的版本(Dependencies versions)**：

- react：17.x
- form-render：^1.5.6
- antd：4.16.0

**2.问题描述(Bug description)**：
- form-render 表单联动无法识别  "{{formData.select1.some(t=>['a'].indexOf(t) > -1)}}" 这样复杂的语句

**3.最小复现demo(Reproduction demo)**：
https://codesandbox.io/s/infallible-gareth-y2530?file=/App.jsx

![image](https://user-images.githubusercontent.com/32126933/129166542-ecf4a11a-caff-45fe-9b56-1c09758cd2da.png)

**Comment by jeezliu** [comment]
@tw93 大佬好，请问README里面的那个贡献者贡献记录视频是怎么做的？太cool了！

**Comment by FateRiddle** [comment]
1.6.3 版本修复

**Comment by moling1234** [comment]
@FateRiddle 未修复，最小复现demo可复现此bug
