### ISSUE TITLE
[BUG] `schema.dependences` 设置无效

### ISSUE THREAD

**Issue by oMaten** [alibaba/x-render#497]
**1.依赖仓库的版本(Dependencies versions)**：

- react：16.8
- form-render：16.8
- antd：4.6.0

**2.问题描述(Bug description)**：

根据文档所述 https://x-render.gitee.io/form-render/schema/schema#dependencies
定义字段的 `dependences` 属性，依赖的字段值发生变化后，被依赖字段的 widget 并没有重新渲染。同时，我在 x-render 项目中通过 `dependences` 关键字并没有搜索到相关代码。

```json
{
  "type": "object",
  "properties": {
    "string": {
      "title": "字符串",
      "type": "string",
      "widget": "customInput",
     "dependences": ["select"]
    },
    "select": {
      "title": "单选",
      "type": "string",
      "enum": [
        "a",
        "b",
        "c"
      ],
      "enumNames": [
        "选项1",
        "选项2",
        "选项3"
      ],
      "widget": "radio"
    }
  }
}
```

**3.最小复现demo(Reproduction demo)**：

**Comment by oMaten** [comment]
从 `1.5.8` 升级至 `1.6.2` 后该问题解决，是否可以在文档上标识功能依赖的最低版本

**Comment by FateRiddle** [comment]
好的，谢谢建议
