### ISSUE TITLE
[BUG]custom widget 不能对对象进行onChange操作，错误的memo了对象

### ISSUE THREAD

**Issue by makmav** [alibaba/x-render#498]
**1.依赖仓库的版本(Dependencies versions)**：

- react：v 17.0
- form-render：v 1.6.2
- antd：4.16.11

**2.问题描述(Bug description)**：
custom widget 不能对对象进行操作，错误的memo了对象。

**3.最小复现demo(Reproduction demo)**：

https://codesandbox.io/s/blissful-microservice-3s3os?file=/App.jsx

**Comment by FateRiddle** [comment]
https://codesandbox.io/s/fervent-taussig-q1ch7

你那样写，相当于在state上改了一圈，然后重新setState(改过的State)。问题在于还是被当做同一个对象。

**Comment by makmav** [comment]
> https://codesandbox.io/s/fervent-taussig-q1ch7
> 
> 你那样写，相当于在state上改了一圈，然后重新setState(改过的State)。问题在于还是被当做同一个对象。
😭 不是这个问题，不过解决了，用的是V0.0.1的包，。。不是最新的
