### ISSUE TITLE
[Feature]关于表单联动及表单分组

### ISSUE THREAD

**Issue by guomingzhi** [alibaba/x-render#499]
表单联动：是否支持上一个表单修改后，调用接口获取下一个表单的数据，例如获取options
表单分组：有时候一整块表单需要进行分组，每组外会有一个box进行包裹，而目前通过schema级联所产生的样式并不能满足我们的样式要求，是否能够支持下自定义包裹的box，这种场景常出现在且或的条件表单中

**Comment by minuux** [comment]
可以添加一个名字为 `map`的`widget`到`widgets`配置中，覆盖现有的 <https://github.com/alibaba/x-render/blob/master/packages/form-render/src/widgets/antd/map.js>

**Comment by FateRiddle** [comment]
如上同学所说哈，可以自己覆盖一个object组件。
