### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by videring** [alibaba/x-render#501]
**1.依赖仓库的版本(Dependencies versions)**：

- react：
- form-render：
- antd：

**2.问题描述(Bug description)**：
setSchemaByPath('某id', {hidden:true})执行后，没有作用到全局。

**3.最小复现demo(Reproduction demo)**：
- 配置另个组件，id分别是select_123，input_123；
- 通过setSchemaByPath(‘input_123’, {hidden: true})成功实现input_123对应组件的隐藏
- 当用getSchemaByPath('input_123')，能获取到schema中hidden为true，但是getSchemaByPath('#')获取的相应组件schema中hidden没有设置。

**Comment by FateRiddle** [comment]
如果说的是 1.6.3版本的setSchemaByPath无效的问题，已经修复
下次提issue的时候建议版本填写一下，同时这个描述对于解决者来说太难理解了，希望抱着大家一起来解决问题的心态提问哦，issue中有codesandbox的demo，可以留一个复现demo，便于解决者第一时间明白和修复问题。谢谢！
