### ISSUE TITLE
[BUG]Schema中widget为time时，配置的format:"HH:mm"未生效

### ISSUE THREAD

**Issue by JiquanWang99** [alibaba/x-render#505]
**1.依赖仓库的版本(Dependencies versions)**：

- react：>=16.8.0
- form-render：1.6.3
- antd：

**2.问题描述(Bug description)**：
schema中配置了widget为time时，format:"HH:mm"未生效。

**3.最小复现demo(Reproduction demo)**：
复现demo查看下面链接
https://codesandbox.io/s/compassionate-meninsky-n0hof?file=/App.jsx

form-render demo https://codesandbox.io/s/unruffled-flower-jl78h
table-render demo https://codesandbox.io/s/sweet-euler-bdoty
fr-generator demo https://codesandbox.io/s/s13sh

**Comment by tw93** [comment]
已经在dev版本修复，近期将现有issue bug解决完成再发布

**Comment by siyi98** [comment]
@JiquanWang99 form-render@1.8.5版本已经修复~
