### ISSUE TITLE
[Feature] 拖动点击一个组件到面板的时候，组件的新生成的id，能不能自定义？

### ISSUE THREAD

**Issue by killdada** [alibaba/x-render#507]
### 期望的新功能 (describe the expected new feature)
 拖动点击一个组件到面板的时候，组件的新生成的id，能不能自定义？现在的id 都是组件type加随机唯一id生成的

### 简述一下使用场景，便于开发者更好理解新功能的必要性 (describe your scenario for us to understand the need)

![image](https://user-images.githubusercontent.com/16487810/129993800-530079fd-7863-4db7-afc0-636dd877819d.png)
 
我们是基于原来的老系统进行重构的，后端想保留原来的字段id， f1 f2 f3 f4 f5 这样自动递增的id。沟通后发现，这样的id只是为了后续定位问题，直接f+数字的这样比较好写 sql查询语句。原来的随机id还是偏长需要手动复制写sql查询， （随便可以每一个组件都手动更改下id 为 f + 数字的形式解决，不过每一个都改比较麻烦）

**Comment by FateRiddle** [comment]
当然是可以的。
![image](https://user-images.githubusercontent.com/12005259/129996533-0d90950f-8c20-43f6-95f9-d05f5ae233cc.png)

**Comment by killdada** [comment]
可能我上面描述的有点错误，我知道用户可以手动更新这个id，（但是因为我们的这个id和以前的流程业务的强绑定关系，如果id可以改变那么会带来一连串的问题，因此目前我是直接把这个该id的可改变性直接设置为了disabled），所以我想要的时候再创建的时候生成的那个直接支持我们自定义的方法，然后我自己来生成递增的id

**Comment by killdada** [comment]
刚想了下，好像我可以在新增的时候，因为每次新增都会触发选中的组件节点改变，我应该可以试着监听选中节点的改变，然后如果这个组件id不是以 f开头，我直接自动把id改下，我先试下

**Comment by killdada** [comment]
自己自定义额外封装了idInput组件，测试新增和编辑的时候都能够按预期 f1 , f2, f3,f4这样递增。但是复制组件的时候有点问题

![image](https://user-images.githubusercontent.com/16487810/130050981-cb9009ce-e5ef-43a4-b0f3-c7aa578da20e.png)

断点看的时候复制的时候实际设置了如截图1标识的 form-render的随机id，但是马上渲染又变成了之前当前选中节点的f3, 导致新增的本应该是f4节点没有进断点截图 2位置 ，没有想到办法处理这种情况。可以提供demo，或者是能不能直接在源头上支持自定义生成id？这样我也不需要这样处理了
