### ISSUE TITLE
fr-generator点击左侧新增组件报错

### ISSUE THREAD

**Issue by lyhper** [alibaba/x-render#513]
2.5.6版本出现的问题，2.5.4版本正常

![image](https://user-images.githubusercontent.com/13343726/130173025-0d873c65-f435-4a0c-b8af-8ceb4b7603c2.png)

**Comment by F-loat** [comment]
2.5.7 已修复

**Comment by pengxiaocui** [comment]
点击左侧组件，新增不了呢；第一次点击Schema编辑器里的默认组件，这个组件就会消失。请问下这个是什么问题呢
