### ISSUE TITLE
[Feature] 希望能够将内置组件暴露出来

### ISSUE THREAD

**Issue by mdzxy** [alibaba/x-render#514]
### 示例
`<div className='form'>
        <Input placeholder='请输入标题' />
        <div>
          使用内置组件，如表格列表...
        </div>
        <Upload action='upload/file' name='file'>
          <Button icon={<UploadOutlined />}>点击上传</Button>
        </Upload>
        <Input.TextArea placeholder='请输入事由' />
      </div>`

**Comment by tw93** [comment]
试试 'form-render/lib/antd/upload' 或者'form-render/es/antd/upload'
