### ISSUE TITLE
[BUG]  数组对象行监听bug

### ISSUE THREAD

**Issue by Crystal2030** [alibaba/x-render#515]
**1.依赖仓库的版本(Dependencies versions)**：

- react：16.8
- form-render：1.6.3
- antd：4.x

**2.问题描述(Bug description)**：
1.6.3及以上不支持监听行上的rootValue值，1.6.3以下都可以支持的

**3.最小复现demo(Reproduction demo)**：
https://codesandbox.io/s/intelligent-fog-r1llt?file=/App.jsx
![image](https://user-images.githubusercontent.com/6970454/130224209-9417ef9a-9076-4fd3-a830-9259ce228a35.png)

![image](https://user-images.githubusercontent.com/6970454/130224422-3178614b-cd45-4f45-bf49-b3f438b59b3d.png)

**Comment by FateRiddle** [comment]
https://codesandbox.io/s/awesome-noyce-dtr1f
数组中的问题，建议用dependencies 和 dependValues 来实现。

watch的用法和lodash.get类似，get数组中的一项时，path是a[1].b, 而不是a.b。
碰到数组的情况rootValue目前确实会无效，所以建议使用dependencies
