### ISSUE TITLE
[Feature] 抽离 antd

### ISSUE THREAD

**Issue by oMaten** [alibaba/x-render#516]
### 期望的新功能

根据[文档中 QA 的解释](https://x-render.gitee.io/form-render/faq#3%E3%80%81formrender-10-%E6%98%AF%E5%90%A6%E5%B0%86-antd-%E4%BD%9C%E4%B8%BA%E4%BA%86%E5%BC%BA%E4%BE%9D%E8%B5%96%EF%BC%8C%E8%BF%98%E6%9C%89%E6%B2%A1%E6%9C%89%E4%BF%9D%E7%95%99%E5%8E%9F%E5%85%88%E7%BA%AF%E7%B2%B9%E7%9A%84%E8%A1%A8%E5%8D%95%E6%A0%B8%E5%BF%83%E5%8C%85%EF%BC%8C%E7%84%B6%E5%90%8E%E9%80%9A%E8%BF%87%E8%87%AA%E5%AE%9A%E4%B9%89%E7%BB%84%E4%BB%B6%E6%B3%A8%E5%86%8C%E7%AC%AC%E4%B8%89%E6%96%B9%E7%BB%84%E4%BB%B6%E5%BA%93%E7%9A%84%E8%83%BD%E5%8A%9B%EF%BC%9F)，虽然将 antd 作为 `peerDependence` 声明，但是 form-render 的代码依然主动声明 `import ... from 'antd'`，本质上仍然强依赖了 antd，否则无法在项目中 bundle form-render。希望可以对 form-render 单独抽象一层（目前源码中对 antd 的依赖分散在 core、widgets 等文件中）作为基础库类的依赖注入，以避免安装不必要的 antd 依赖。

#### 默认使用
默认使用场景仍然保持现状
```js
import FormRender, { useForm } from 'form-render';
```

#### 依赖注入的模式

```jsx
import createFormRender from 'form-render/implement';
// （可选引用）如果本身需要部分内置组件时，可以引入进行集成，如果完全不需要，也可以不引入
import internalWidgets from 'form-render/widgets';
import widgets from './all-my-custom-widgets';
// `createFormRender` 本身不包含基础样式库的依赖，所有 antd 的依赖都在这一层进行注入
const MyCustomFormRender = createFormRender(widgets, { Provider, ...anythingElse });
render(<MyCustomFormRender />);
```

通过这种方式在基于 form-render 进行二次封装（自定义的组件库）时，可以完全拜托 antd 的依赖，避免不必要的 bundle 成本。

**Comment by oMaten** [comment]
目前为止只能通过对 `form-render` 的 bundle 来重新 resolve 部分对 antd 的依赖。
比如，以我使用的 `esbuild` 为例，通过插件 API 在 resolve 以及 load 阶段对部分文件进行替换以达到彻底移除 antd 依赖的目的。
但是这么做会带来后续升级的不稳定。
```js
const path = require("path");
const NodeModulesPath = path.resolve(__dirname, "..", "node_modules");

const EmptyConfigProviderJS = `
  export default function Provider(props) {
    return props.children
  };
`;

const resolverPlugin = {
  name: "form-render-extract",
  setup(build) {
    // 对所有 widgets 进行替换
    build.onResolve({ filter: /^\.\/widgets\/antd$/ }, (args) => {
      return { path: require.resolve("../path-to-my-own-widgets/") };
    });
   // 对 core/RenderChildren 进行替换（实现了自定义列表的交互）
    build.onResolve({ filter: /^\.\/RenderChildren\/RenderList$/ }, (args) => {
      return { path: require.resolve("../path-to-my-custom-list") };
    });
    // 对 index 中的 Provider 进行替换
    build.onLoad({ filter: /antd/ }, async (args) => {
      const p = path.relative(NodeModulesPath, args.path);
      if (p === "antd/lib/locale/zh_CN.js") {
        return { contents: "", loader: "js" };
      } else if (p === "antd/es/config-provider/style/index.js") {
        return { contents: "", loader: "js" };
      } else if (p === "antd/es/config-provider/index.js") {
        return {
          // Provider 替换
          contents: EmptyConfigProviderJS,
          loader: "js",
        };
      }
    });
  },
};
```

**Comment by siyi98** [comment]
@oMaten 这个我们内部会讨论一下。
