### ISSUE TITLE
[BUG] fr-generator最新版本 globalSetting、schema数据没有填充

### ISSUE THREAD

**Issue by killdada** [alibaba/x-render#517]
**1.依赖仓库的版本(Dependencies versions)**：

- react：
- form-render：
- antd：

**2.问题描述(Bug description)**：

schema对应的formName等没有填充数据

![image](https://user-images.githubusercontent.com/16487810/130721157-e311e003-ad82-4b0a-81f8-7cfa3340788e.png)

以前的旧版本正常

**3.最小复现demo(Reproduction demo)**：

https://codesandbox.io/s/dazzling-brook-7xelu?file=/App.jsx

**Comment by F-loat** [comment]
2.5.8 已修复
