### ISSUE TITLE
[BUG] 表单 formData 值中属性为 array 时，当其中有 0，‘’ 时会被 filter 掉

### ISSUE THREAD

**Issue by moling1234** [alibaba/x-render#519]
**1.依赖仓库的版本(Dependencies versions)**：

- react：17.x
- form-render：1.6.7-beta.1
- antd：4.x

**2.问题描述(Bug description)**：
表单 formData 中属性为 array 时，当其中有 0，‘’ 时会被 filter 掉

**3.最小复现demo(Reproduction demo)**：
https://codesandbox.io/s/exciting-mestorf-jok2h?file=/App.jsx

![217A1930-35D9-4AAA-9CF9-6444816BD999](https://user-images.githubusercontent.com/32126933/130895968-71f9563b-6fc2-48aa-8379-647ef4459a9b.png)

**Comment by FateRiddle** [comment]
已经修复，谢谢issue。
