### ISSUE TITLE
[BUG] list2表格列表组件，分页删除项错误

### ISSUE THREAD

**Issue by auyo18** [alibaba/x-render#522]
**1.依赖仓库的版本(Dependencies versions)**：

- react：17.x
- form-render：1.6.8
- antd：4.x

**2.问题描述(Bug description)**：
删除第2页以后的数据，实际删除的是第1页的数据

**3.最小复现demo(Reproduction demo)**：
https://codesandbox.io/s/buy2j

**Comment by tw93** [comment]
已修复，可以升级FormRender到1.9.1的版本
