### ISSUE TITLE
[Feature]form-render 提供自定义组件对象属性整体注入

### ISSUE THREAD

**Issue by elesheepcn** [alibaba/x-render#524]
### 期望的新功能 
form-render 提供自定义组件对象属性注入
### 简述一下使用场景 
公司内部多个场景使用  有很多自定义组件 整体放置在npm库中 
希望可以直接传入schema 和自定义组件整体对象 在form-render内部匹配 
目前已在外部实现匹配 希望能实现在内部
外部实现demo  https://codesandbox.io/s/billowing-hooks-foj16?file=/App.jsx
引用库地址随便写的 所以有报错

**Comment by FateRiddle** [comment]
没看懂，demo似乎和你的议题无关？
