### ISSUE TITLE
[BUG]form-render当对象为list  修改schema属性时  提示找不到元素

### ISSUE THREAD

**Issue by elesheepcn** [alibaba/x-render#525]
**1.依赖仓库的版本(Dependencies versions)**：
- react：17.0.2
- form-render：1.6.7
- antd：4.16.11

**2.问题描述(Bug description)**：
当对象为list  修改schema属性时  提示找不到元素

**3.最小复现demo(Reproduction demo)**：
https://codesandbox.io/s/billowing-hooks-foj16?file=/App.jsx

**Comment by FateRiddle** [comment]
https://codesandbox.io/s/blue-thunder-snmtu?file=/App.jsx

list的path需要在后面加一个'[]'。这是form-render设计上的一个规则。类似于lodash的get，如果get一个list里的东西，会是

get(data, 'a[1].b[2].c')
