### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by videring** [alibaba/x-render#529]
**1.依赖仓库的版本(Dependencies versions)**：

- react：16.14.0
- form-render：16.8
- antd：4.10.0

**2.问题描述(Bug description)**：
步骤：
1.通过form-render生成表单，既有内置的组件如input组件，也有自定义组件，自定义组件按照form-render自定义组件的规范书写组件
2.在自定义组件中通过addons.getValue()只能拿到初始化时的数据。当更改表单中其他组件的值，自定义组件无法通过addons.getValue拿到最新的值。

**Comment by videring** [comment]
说下临时解决办法吧。
我的自定义组件是一个按钮，点击会触发onClick方法，在onClick中执行一些逻辑，同时也不会触发onChange方法。
临时解决办法就是在onClick方法中执行onChange(new Date().valueOf())，强制form-render/es/core/RenderField/ExtendedWidget.js的areEqual方法返回false。

**Comment by FateRiddle** [comment]
见 issue https://github.com/alibaba/x-render/issues/534
