### ISSUE TITLE
[BUG]动态设置required，form.submit必输校验未提示

### ISSUE THREAD

**Issue by Crystal2030** [alibaba/x-render#530]
**1.依赖仓库的版本(Dependencies versions)**：

- react：16.8.x
- form-render：1.6.2
- antd：4.x

**2.问题描述(Bug description)**：

**3.最小复现demo(Reproduction demo)**：
https://codesandbox.io/s/zealous-sky-31f2o?file=/App.jsx:1026-1035 
![image](https://user-images.githubusercontent.com/6970454/131850841-5df8ae0b-37a9-4576-8456-e0f284192c44.png)

**Comment by FateRiddle** [comment]
升级到最新版，这个问题之前已经解了。
