### ISSUE TITLE
[Feature] 与其他低代码前端平台的对接

### ISSUE THREAD

**Issue by william-lg** [alibaba/x-render#531]
## 背景  
1、我们项目组使用xrender来作为前端展示，但是业务上需要借助于另一个审批平台，该审批平台使用乐高搭建的  
2、乐高的自定义表单设计跟xrender不一样，一是嵌入不进去，二是如果使用格式化文本展示的话，xrender也没有提供相应的接口，只能自己后台手动解析和转换  

## 期望的新功能 (describe the expected new feature)
个人感觉还是低代码跨平台的对接，格式化文本是一个比较常见的想法和展示方式，希望维护者能够给出这样场景下的一种解决方式吧

**Comment by FateRiddle** [comment]
没咋用过乐高，能具体说明下 “格式化文本” 是啥么

**Comment by FateRiddle** [comment]
> key为组件的title，value为输入的值

看完问号更多了。
你要的是这个吗？这个有啥用？是一份简报吗？这点信息是完全没法还原表单吧。
其次比如选项类的，光看个value很可能也没有意义吧？除了选项其他不少情况也是。
最后，如果你真的只要这个，写个入参是formData和schema的函数就行。

**Comment by william-lg** [comment]
第一点，我们项目用xrender做页面，但是要通过别的平台审批（就是类似xrender的平台），审批者需要了解要审批的大致内容。第二点，我需要的就是一份简报，我不需要整个的表单。我说的文本化是一种展示形式，或者说有没有别的更优雅的形式能够解决我的问题。
第三点，我可以基于schema+formData来做，我现在也是这么做的，但是囿于表单联动处理会比较麻烦。
我本意不是说能不能做成文本化，我是想框架能不能提供更为优雅的解决问题的方式。如果维护者觉得这不重要，那我就只能自己处理。

**Comment by wangqiangstar** [comment]
有考虑对接lowcode-engine吗？现在是用iframe嵌套在lowcode-engine上，但是这样就割裂成两个视图了，不方便操作
