### ISSUE TITLE
下拉框组件搜索问题

### ISSUE THREAD

**Issue by wanxiangxin** [alibaba/x-render#532]
**1.依赖仓库的版本(Dependencies versions)**：

- react：>=16.8.0
- form-render：1.6.2
- antd：4.x

**2.问题描述(Bug description)**：
使用下拉选择控件，并且支持搜索，搜索不出来(确实是有的)
![image](https://user-images.githubusercontent.com/35825365/132649701-8bded0c6-1705-4745-ac3e-ac1fce27ee93.png)
![image](https://user-images.githubusercontent.com/35825365/132649751-4a0046ec-eb05-40b9-903c-0f8551f99917.png)

**3.最小复现demo(Reproduction demo)**：

```{
  "type": "object",
  "properties": {
    "select": {
      "title": "带搜索的单选框",
      "type": "string",
      "enum": [
        "a",
        "b",
        "c"
      ],
      "enumNames": [
        "jack",
        "steve",
        "david"
      ],
      "widget": "select",
      "props": {
        "filterOption": true,
        "showSearch": true,
        "optionFilterProp": "children"
      }
    }
  }
}

**Comment by FateRiddle** [comment]
"optionFilterProp": "children" 改成 "optionFilterProp": "label"

说到底是个透传，只要antd的demo能跑通，同样的props在form-render也能跑通

谢谢提醒已经更正。

**Comment by wanxiangxin** [comment]
谢谢，问题解决

**Comment by lifegit** [comment]
请教一下，如果数据源来自接口呢？
