### ISSUE TITLE
[Feature] enum 和 enumNames 的合并

### ISSUE THREAD

**Issue by wwyx778** [alibaba/x-render#533]
### 期望的新功能 (describe the expected new feature)
`{"enum":[{"label":"上海","value":"SH"},{"label":"北京","value":"BJ"}]}`
### 简述一下使用场景，便于开发者更好理解新功能的必要性 (describe your scenario for us to understand the need)
有一些动态 set 或 update enum 的场景，且后端返回数据大概率也是类似这种格式。后面会考虑兼容这种方式吗？

**Comment by FateRiddle** [comment]
说一个技巧：
{
   props: [{"label":"上海","value":"SH"},{"label":"北京","value":"BJ"}],
   widget: 'select'
}

就行了。
