### ISSUE TITLE
[BUG]自定义组件的addons.getValue()和addons.formData获取的值不是最新

### ISSUE THREAD

**Issue by xuemin-li** [alibaba/x-render#534]
**1.依赖仓库的版本(Dependencies versions)**：

- react：最新
- form-render： 最新
- antd： 最新

**2.问题描述(Bug description)**：
如题，自定义组件通过addons.getValue()和addons.formData获取整个表单的值，初次是正确的，多次修改表单某一个项后，通过getValue()或者formData获取不到最新的值。
或者说在独立打包成npm包的自定义组件里，怎么获取到表单最新的值呢？

**Comment by FateRiddle** [comment]
一个表单元素不应该由于用户在填另一个input而一直重新渲染。这个是出于性能上的正常考虑。所以自定义组件没有渲染的情况下，数据是不会更新的

使用一下 dependencies 注明你的依赖元素可以解决这个问题。https://x-render.gitee.io/form-render/schema/schema#dependencies
