### ISSUE TITLE
[Feature]希望开放createWidget函数

### ISSUE THREAD

**Issue by xuemin-li** [alibaba/x-render#535]
### 期望的新功能 (describe the expected new feature)
自定义组件里想实时获取整个表单的值，目前看只有watch支持，想通过使用createWidget函数将实时表单值传递下去。
### 简述一下使用场景，便于开发者更好理解新功能的必要性 (describe your scenario for us to understand the need)
使用场景是视频类表单的场景，一个视频节目搜索框，一个视频封面素材选择框（包含素材列表）。选了某个视频，需要实时更新成对应视频的素材列表，方便运营从当前列表当中选择某一个素材图。

**Comment by FateRiddle** [comment]
createWidget 现在就是开放的，但是不是你说的用法。
可以在schema中注明 dependencies 说明本组件对于某几个 formData 的依赖，并在自定义组件里用 dependValues 取到对于的值的时时数据。这个做法比较推荐。
