### ISSUE TITLE
[BUG] form-render使用出现闪现问题

### ISSUE THREAD

**Issue by furfur-jiang** [alibaba/x-render#538]
**1.问题描述(Bug description)**：
master：form-render使用出现闪现问题

**2.最小复现demo(Reproduction demo)**：
进入官网https://x-render.gitee.io/tools/generator/playground/ 页面，任意点击一个组件，出现闪动后消失。

2021/9/7拉取schema-generator最新master分支代码出现类似问题，使用dev分支无此问题。

**Comment by F-loat** [comment]
已修复
