### ISSUE TITLE
[Feature] 项目中也使用rem单位，和x-render的rem单位冲突

### ISSUE THREAD

**Issue by liqupan** [alibaba/x-render#540]
### 期望的新功能 (describe the expected new feature)

项目中也使用rem单位，和x-render的rem单位冲突，怎么解决呀~

比如现在项目中使用的font-size = 100px

**Comment by liqupan** [comment]
好像没有什么更好的解决办法，我们吧源码拉下来将rem全部修改成em，发布到私服自己用了🥺🥺🥺🥺🥺

**Comment by FateRiddle** [comment]
我没听懂，从你的问题“具体怎么冲突了，表现是啥”，到你的解法“发布到私服”。。
我先关了
