### ISSUE TITLE
[BUG] form-render schema 设置异常

### ISSUE THREAD

**Issue by mianmabb1** [alibaba/x-render#541]
### 问题一
如以下视频所示：当设置 props 的 `allowClear` 属性以及 `default` 时，会出现如下现象

https://user-images.githubusercontent.com/49062532/133547546-217efc59-155c-4dee-b9cb-6455543b2ed8.mov

### 问题二
`array` 会过滤掉值为 `false` 的选项
![image](https://user-images.githubusercontent.com/49062532/133560580-b25a7e70-b7d2-4926-b260-199510bc1b2c.png)

### 问题三
数字类型不支持设置 antd 组件 props 的 `addon`
![image](https://user-images.githubusercontent.com/49062532/133561401-72d3b14a-1989-4d70-8929-63052f7ebf6f.png)

## 最小复现demo(Reproduction demo)：
form-render demo https://codesandbox.io/s/ecstatic-bohr-e5wvq

**Comment by FateRiddle** [comment]
问题一
default的逻辑是，如果表单有值用值，如果没有值（undefined），用default。这个不太好解，在用法上可以考虑一下是否需要一个单项去清空？

问题二
fix 了

问题三
数字的addonBefore是4.17.x 版本antd才添加上的功能，确保使用的项目里antd的版本比这个大，就能用。
