### ISSUE TITLE
[BUG]自定义组件props只传递函数时会被删除props

### ISSUE THREAD

**Issue by rquanx** [alibaba/x-render#543]
**1.依赖仓库的版本(Dependencies versions)**：

- form-render：1.6.2

**2.问题描述(Bug description)**：

自定义组件props只传递函数时会被删除props
![image](https://user-images.githubusercontent.com/36622981/133733243-73437fa7-39a8-4b91-819b-3142012cdbdd.png)

**Comment by hi-heshuai** [comment]
一样的问题

**Comment by FateRiddle** [comment]
谢谢issue，已经修复
