### ISSUE TITLE
[BUG] fr-generator 点击左侧组件，新增不了呢；第一次点击Schema编辑器里的默认组件，这个组件就会消失。请问下这个是什么问题呢

### ISSUE THREAD

**Issue by pengxiaocui** [alibaba/x-render#544]
**1.依赖仓库的版本(Dependencies versions)**：

- react：
- form-render：
- antd：

**2.问题描述(Bug description)**：

**3.最小复现demo(Reproduction demo)**：

form-render demo https://codesandbox.io/s/unruffled-flower-jl78h
table-render demo https://codesandbox.io/s/sweet-euler-bdoty
fr-generator demo https://codesandbox.io/s/s13sh

**Comment by F-loat** [comment]
最新版应该修复了，更新下看看
