### ISSUE TITLE
list下的max: {{rootValue.xxx}}不生效[BUG]

### ISSUE THREAD

**Issue by xuemin-li** [alibaba/x-render#547]
**1.依赖仓库的版本(Dependencies versions)**：

- react：最新
- form-render：最新
- antd：最新

看了下1.6.2版本及以下好使，求问最新版本能修复下这个问题吗

**2.问题描述(Bug description)**：
list下的rootValue设置不生效，rootValue返回{}
**3.最小复现demo(Reproduction demo)**：

下面是可复现的schema，外层可以，list里面的不生效
const testSchema = {
  "type": "object",
  "description": "配置",
  "properties": {
    "showTitle": {
      "type": "boolean",
      "title": "【1】是否显示标题"
    },
    "titleColor": {
      "type": "string",
      "title": "【联动】标题颜色",
      "x-componentType": "color",
      "hidden": "{{!(rootValue.showTitle)}}",
    },
    "list": {
      "type": "array",
      "title": "坑位列表",
      "items": {
        "type": "object",
        "title": "坑位内容",
        "properties": {
          "showTitle": {
            "type": "boolean",
            "title": "是否显示标题"
          },
          "titleColor": {
            "type": "string",
            "title": "【联动】标题颜色",
            "hidden": "{{rootValue.showTitle}}"
          }
        }
      }
    }
  }
}

辛苦大佬看看

**Comment by FateRiddle** [comment]
1.6.12 已经修复了哈
