### ISSUE TITLE
[BUG]同时拖出两个日期组件时，一个类型选择时间，一个类型选择日期，时间组件属性面板消失

### ISSUE THREAD

**Issue by Zhengyang550** [alibaba/x-render#565]
**1.依赖仓库的版本(Dependencies versions)**：

- react：
- form-render：
- antd：

**2.问题描述(Bug description)**：
同时拖出两个日期组件时，一个类型选择时间，一个类型选择日期，时间组件属性面板消失
![image](https://user-images.githubusercontent.com/52303982/134624656-225dba19-66d0-4310-8017-b3d25f11ed88.png)

**3.最小复现demo(Reproduction demo)**：
dmeo地址：https://x-render.gitee.io/tools/generator/playground
json-schema：
{
  "type": "object",
  "properties": {
    "date_B9s87E": {
      "title": "日期选择sssssssssssssssssssssssssssssssssssssssssss",
      "type": "string",
      "format": "time"
    },
    "date_xisKoY": {
      "title": "日期选择",
      "type": "string",
      "format": "date"
    }
  },
  "labelWidth": 120,
  "displayType": "row"
}

**Comment by F-loat** [comment]
已修复，发版前可以先通过自定义 settings 处理

``` js
{
  text: '日期选择',
  name: 'date',
  schema: {
    title: '日期选择',
    type: 'string',
    format: 'date',
    widget: 'date',
  },
  setting: {
    format: {
      title: '格式',
      type: 'string',
      enum: ['dateTime', 'date', 'time'],
      enumNames: ['日期时间', '日期', '时间'],
    },
  },
},
```
