### ISSUE TITLE
[BUG] 输入16位以上的number，离开光标数字自动发生改变

### ISSUE THREAD

**Issue by Crystal2030** [alibaba/x-render#566]
**1.依赖仓库的版本(Dependencies versions)**：

- react：16.8.0
- form-render：1.6.9
- antd：4.x

**2.问题描述(Bug description)**：
输入16位以上的number，离开光标数字自动发生改变，期望返回输入的原值

**3.最小复现demo(Reproduction demo)**：
https://codesandbox.io/s/wonderful-wood-kyupi

![image](https://user-images.githubusercontent.com/6970454/134768923-fcec5f01-61a3-409e-8715-0ab39a3c3fea.png)
![image](https://user-images.githubusercontent.com/6970454/134768936-c83c894b-148d-4b52-9295-d91bbb660995.png)

**Comment by FateRiddle** [comment]
这个是js的机制，浮点数超过范围了吧。可以去浏览器的console
