### ISSUE TITLE
[Feature] 开放 style className 参数

### ISSUE THREAD

**Issue by mzl980425** [alibaba/x-render#567]
### 期望的新功能 (describe the expected new feature)
开放 style className 参数，直接挂到FR最外层容器上

### 简述一下使用场景，便于开发者更好理解新功能的必要性 (describe your scenario for us to understand the need)
通过外层包个 div 的方法来写这两个参数太粗暴了，而且很没必要。
并且通过传入不同的 className ，可以实现不同项目内对 FR 的样式多重定制。

**Comment by FateRiddle** [comment]
v1.6.12 已经开放了 className、style和 id。供君选用
