### ISSUE TITLE
[Feature]标题后面的说明文字支持直接展示或者问号图标

### ISSUE THREAD

**Issue by qiu-caiping** [alibaba/x-render#568]
### 简述一下使用场景，便于开发者更好理解新功能的必要性 (describe your scenario for us to understand the need)

![image](https://user-images.githubusercontent.com/48647498/135047819-4821a4c7-2042-432f-a81a-b1931f21ff42.png)
因项目目前表单涉及到联动，一行可能会展示多个表单项，如果其中一个表单项的描述说明文字过长的话一行可能展示不下，希望在上下布局的情况下可以同时支持两种选择呢，一种就是直接展示出来，另外就是?问号图标这种

**Comment by FateRiddle** [comment]
1.7.0 增加 descType 字段，支持此功能
