### ISSUE TITLE
[BUG] 使用form.setValueByPath更新表单值，已有的报错提示不更新

### ISSUE THREAD

**Issue by hellopanpan** [alibaba/x-render#582]
复现demo [test](https://codesandbox.io/s/hopeful-feynman-wmq60?file=/App.jsx)
1，点击提交后，会出现报错提示
2，点击第二行复选框，更新第一行的input（使用form.setValueByPath更新表单值），报错提示依然在

**Comment by FateRiddle** [comment]
按你说的做了，没有复现你说的现象。
