### ISSUE TITLE
[BUG] 当字段id和bind为同一个字符的时候，setValues 赋值失败

### ISSUE THREAD

**Issue by killdada** [alibaba/x-render#584]
**1.依赖仓库的版本(Dependencies versions)**：

- react：
- form-render：
- antd：

**2.问题描述(Bug description)**：

 当字段id和bind为同一个字符的时候，setValues 赋值失败

**3.最小复现demo(Reproduction demo)**：

https://codesandbox.io/s/morning-currying-erc66?file=/App.jsx

**Comment by lifegit** [comment]
+1，请问解决了吗

**Comment by killdada** [comment]
> +1，请问解决了吗

没有再使用 bind字段，新增了数据绑定组件绑定自定义字段filed,等复制的时候从field映射到id即可
