### ISSUE TITLE
ts环境下，fr-generator的extraButtons类型声明错误

### ISSUE THREAD

**Issue by wushuxuan** [alibaba/x-render#587]
**1.依赖仓库的版本(Dependencies versions)**：

- react：17.x
- form-render：1.6.9
- fr-generator：2.5.8

**2.问题描述(Bug description)**：
fr-generator的extraButtons类型声明错误

**3.最小复现demo(Reproduction demo)**：

form-render demo https://codesandbox.io/s/unruffled-flower-jl78h
table-render demo https://codesandbox.io/s/sweet-euler-bdoty
fr-generator demo https://codesandbox.io/s/s13sh
复现地址： https://codesandbox.io/s/sharp-gates-mtzov?file=/App.jsx
项目类型报错截图：
![image](https://user-images.githubusercontent.com/30644407/138667137-4acb8fe0-5956-4c05-b0e8-cfa0d43c44c7.png)

**Comment by F-loat** [comment]
fr-generator@2.6.1 已修复
