### ISSUE TITLE
[BUG] 预览态列表里面的子组件默认值不生效

### ISSUE THREAD

**Issue by lwdgit** [alibaba/x-render#590]
**1.依赖仓库的版本(Dependencies versions)**：

- react：16.14.0
- form-render: 1.8.3
 - fr-generator: 2.6.0

**2.问题描述(Bug description)**：
预览模式下：列表里面添加的输入框（其它也可以），其默认值不生效。
**3.最小复现demo(Reproduction demo)**：

form-render demo https://codesandbox.io/s/unruffled-flower-jl78h
table-render demo https://codesandbox.io/s/sweet-euler-bdoty
fr-generator demo https://codesandbox.io/s/s13sh

编辑态：
![image](https://user-images.githubusercontent.com/5530205/138823819-c1a4552d-ee10-4903-a4b5-148bf1fbb51b.png)
预览态: 
![image](https://user-images.githubusercontent.com/5530205/138823851-f5b76d6b-40dc-430c-9896-24c4c3b252aa.png)

**Comment by F-loat** [comment]
fr-generator@2.6.1 已修复
