### ISSUE TITLE
如何传递@ant-design/icons给Input组件

### ISSUE THREAD

**Issue by 551685830** [alibaba/x-render#601]
### 期望的新功能 (describe the expected new feature)
![image](https://user-images.githubusercontent.com/6261789/141123135-019f538e-5b64-48d1-a2d9-0fff1a48a545.png)

### 简述一下使用场景，便于开发者更好理解新功能的必要性 (describe your scenario for us to understand the need)
``` js
  <Input
      prefix={<MobileTwoTone />}
      maxLength={11}
      required={true}
      value={value}
      onBlur={handleBlur}
      {...rest}
    />
  <Input.Password
      prefix={<LockOutlined />}
      autoComplete="off"
      iconRender={(visible) => (visible ? <EyeTwoTone /> : <EyeInvisibleOutlined />)}
      {...props}
    />
```

``` json
"string5": {
  "title": "手机号",
  "type": "string",
  "rules": [
	{
	  "pattern": "^[0-9]{11}$",
	  "message": "请输入正确的手机号"
	}
  ],
  "props": {
	"prefix": "{{<MobileOutlined />}}",
        "prefix": "{<MobileOutlined />}",
        "prefix": <MobileOutlined />,
  },
  "width": "50%"
},
```

如下面的截图所示，类似这种需要给文本框(type=string)传递prefix（图标组件），是语法不正确还是不支持？
![image](https://user-images.githubusercontent.com/6261789/141124319-492c3a84-6a2f-4557-adf7-948435915ede.png)

**我当前的作法是通过自定义组件来实现的，感觉只是为某个特性就自定义组件未免太。。。**

**Comment by siyi98** [comment]
`schema`的能力有限哦，目前仅用于描述表单如何渲染。
