### ISSUE TITLE
[BUG] setErrorFields 和 removeErrorFields 无法覆盖输入校验出来的错误

### ISSUE THREAD

**Issue by charleylla** [alibaba/x-render#606]
**1.依赖仓库的版本(Dependencies versions)**：

- react：
- form-render：
- antd：

**2.问题描述(Bug description)**：

**3.最小复现demo(Reproduction demo)**：

form-render demo https://codesandbox.io/s/biao-dan-ye-xiao-yan-wen-ti-forked-efjly?file=/App.jsx

![image](https://user-images.githubusercontent.com/16316329/142182900-d69d4f2e-30c1-4cd9-afca-0f3433b54d94.png)

**Comment by siyi98** [comment]
@charleylla form-render升级到1.9.0版本即可。
