### ISSUE TITLE
[Feature] type=boolean widget= checkbox 时期望设置的description展示出来

### ISSUE THREAD

**Issue by ms-qing** [alibaba/x-render#608]
### 期望的新功能 (describe the expected new feature)
type=boolean widget= checkbox 时期望设置的description 能展示出来

### 简述一下使用场景，便于开发者更好理解新功能的必要性 (describe your scenario for us to understand the need)
![image](https://user-images.githubusercontent.com/6777666/142336581-408c71b3-9a76-42be-b056-5b81ff6d5922.png)

**Comment by siyi98** [comment]
在codesandbox上给个复现的demo吧

**Comment by siyi98** [comment]
@ms-qing 有兴趣来个pr？
