### ISSUE TITLE
[BUG]schema-generator 最终展示后 改动默认值 不会即时显示

### ISSUE THREAD

**Issue by jiaqi1993** [alibaba/x-render#610]
**1.依赖仓库的版本(Dependencies versions)**：

schema-generator: 2.5.8

在本地测试，或使用官网的 Schema编辑器都会有相同问题
**2.问题描述(Bug description)**：
1. 添加输入框， 默认值 输入 abc, 这里会即时显示
2. 点击最终展示，再点击开始编辑
3. 此时在同样的输入框的默认值做更改， 内容不会被即时显示， 依旧只出现abc
![image](https://user-images.githubusercontent.com/13100799/143198821-530d891b-2af1-49ab-909d-40fa24cfc934.png)

**3.最小复现demo(Reproduction demo)**：
根据以上步骤可复现问题
以下有我具体的操作过程
[点击前往google drive下载](https://drive.google.com/file/d/115K6Qh8mXKce5yLM9dLCNT2mY15SCieA/view?usp=sharing)

链接: [百度盘链接](https://pan.baidu.com/s/1fDnCtyNbeoFCTELWt0-6RA) 提取码: qky5

**Comment by F-loat** [comment]
这个是正常的，这里配置的是默认值，一旦输入过就不会生效了

**Comment by jiaqi1993** [comment]
@F-loat 您好， 谢谢您的帮忙和回复
因为 "最终展示" 和 "开始编辑" 是可以实时切换的
这样的情况就造成了 其实只要是在点击"最终展示"一次后， 之后的更改就不会在编辑模式下显示出来
变得需要频繁切换最终展示来看效果

**Comment by siyi98** [comment]
@jiaqi1993 问题已解决，这个issue就先关啦
