### ISSUE TITLE
[Feature] 生成自定义的组件 ID 

### ISSUE THREAD

**Issue by hankouyu** [alibaba/x-render#616]
### 期望的新功能 (describe the expected new feature)
能自定义组件 ID 的生成规则； 目前的组件内部是使用  nanoid 来生成组件 ID 的， 用的是其默认规则，并且没有修改规则的接口

### 简述一下使用场景，便于开发者更好理解新功能的必要性 (describe your scenario for us to understand the need)
我所开发的一个项目中， 组件生成的标识符中不能含有短横线（短横线会被识别为“减号”）。本地项目中， 修改了源码， 让组件按照自定义的方式生成 ID， 方能正常工作， 但是这样对于项目的升级维护都带来了极大不便， 所以希望能有个能生成自定义的组件 ID 的功能

**Comment by F-loat** [comment]
fr-generator@2.6.2 已支持

``` jsx
<Generator getId={name => `${name}_new`} />
```
