### ISSUE TITLE
[BUG] generator 相同组件的不同的自定义setting  右侧组件渲染有误

### ISSUE THREAD

**Issue by EwanBerg** [alibaba/x-render#619]
**1.依赖仓库的版本(Dependencies versions)**：

- react：17.x
- fr-generator：2.6.3
- antd：4.16.13

**2.问题描述(Bug description)**：
fr-generator 相同组件的传入不同的自定义setting  右侧组件配置渲染有误，所有相同组件只渲染了第一个组件里的自定义setting项
**3.最小复现demo(Reproduction demo)**：

demo https://codesandbox.io/s/rough-resonance-1n18i?file=/App.jsx

**Comment by F-loat** [comment]
设计如此，建议通过不同的自定义组件来区分
