### ISSUE TITLE
[BUG]fr-tooltip-toggle当提示框内容特别长时，无法全部展示

### ISSUE THREAD

**Issue by uuzpid** [alibaba/x-render#628]
**1.依赖仓库的版本(Dependencies versions)**：

- react：16.13.1
- form-render：0.9.5
- antd：4.6.5

**2.问题描述(Bug description)**：
![image](https://user-images.githubusercontent.com/65710301/145156800-b2cc325f-665c-4703-b301-8c80d632dc7e.png)
form-render和fr-generator都有这个问题发生，当我升级到1.8.3的from-reder（其他依赖也相应升级）后还是会有这个问题
**3.最小复现demo(Reproduction demo)**：

form-render demo https://codesandbox.io/s/unruffled-flower-jl78h
table-render demo https://codesandbox.io/s/sweet-euler-bdoty
fr-generator demo https://codesandbox.io/s/s13sh

**Comment by philousWen** [comment]
您好，您发我的邮件我已收到，我会尽快回复的。谢谢。。。
