### ISSUE TITLE
[BUG]form.setSchemaByPath无法触发表单更新

### ISSUE THREAD

**Issue by nashang** [alibaba/x-render#629]
1.依赖版本
react 17.x    form-render 1.8.6-beta.0 antd 4.16.13

2.问题描述
我的应用场景是表单的相关联场景。比如选A之后才能选B。选完A之后, 我去通过form.setSchemaByPath修改B的配置项
![image](https://user-images.githubusercontent.com/23025501/145342732-5c298ad8-a41c-4130-9511-90af8b42d61f.png)

3.具体代码片段
![image](https://user-images.githubusercontent.com/23025501/145342970-fad57584-67e1-438c-bc6e-f096525929dd.png)
![image](https://user-images.githubusercontent.com/23025501/145343021-702b4bbe-57d9-4462-9b45-cb99bf6b51fd.png)
结果
![image](https://user-images.githubusercontent.com/23025501/145343095-903c7b57-deee-4525-9db0-119c47a9ad00.png)

**Comment by siyi98** [comment]
老哥写法有问题哦，`setSchemaByPath` 的第二个参数是Object，不是Function
