### ISSUE TITLE
请问贡献者视频是通过什么方式实现的呢？表示很感兴趣[Feature]

### ISSUE THREAD

**Issue by GTMDJAVA** [alibaba/x-render#632]
### 简述一下使用场景，便于开发者更好理解新功能的必要性 (describe your scenario for us to understand the need)

看了贡献者视频感觉做的非常好很直观的感受到各位贡献者的辛苦付出。

**Comment by F-loat** [comment]
https://zhuanlan.zhihu.com/p/377095521
