### ISSUE TITLE
[Feature]期望所有组件支持是否展示title配置

### ISSUE THREAD

**Issue by moling1234** [alibaba/x-render#633]
### 简述一下使用场景，便于开发者更好理解新功能的必要性 (describe your scenario for us to understand the need)

1: 期望对象组件支持布局配置，（一行一列，一行多列）；

2: 期望所有组件支持是否展示title配置，而不是通过title是否为空做判断
![image](https://user-images.githubusercontent.com/32126933/146347038-05722797-f2e1-49d8-bd72-bf9215e72dd7.png)

**Comment by siyi98** [comment]
1. 试试`column` 属性？
2. 这样的话，schema还要增加一个类似于 `showTitle` 的字段；

**Comment by charleylla** [comment]
2. 通过 title 为空判断是否展示更合理，没有 title 就不展示，如果再增加一个字段就显得很冗余，这个字段的作用只是用来控制是否展示 title，和使用空的 title 没有非常明显的区别？
