### ISSUE TITLE
[BUG]需要对 schema 对象里面的 rules 字段做类型校验，必须是数组

### ISSUE THREAD

**Issue by jianfenkezhan** [alibaba/x-render#636]
**1.依赖仓库的版本(Dependencies versions)**：

- react：16.9.0
- form-render：1.x
- antd：4.12.x

**2.问题描述(Bug description)**：
搭建场景，直接保存 schema ，form-render 渲染对 rules 类型未做处理，直接白屏报错。

**Comment by siyi98** [comment]
@jianfenkezhan 长时间未给复现demo，先关闭此issue。
