### ISSUE TITLE
[BUG] 自定义 object 类型的 widget，props.children 无法透传，导致无法自定义组件

### ISSUE THREAD

**Issue by zhaoo** [alibaba/x-render#639]
![自定义组件](https://user-images.githubusercontent.com/30286980/147030411-32cbe3b2-4b7b-4295-8deb-16d840409686.png)

![使用](https://user-images.githubusercontent.com/30286980/147030353-3f4564b0-cf00-437a-a8af-0c600db0832b.png)

![报错](https://user-images.githubusercontent.com/30286980/147030474-259e435b-d611-4220-911d-6c0c17ccbd44.png)

貌似是 schema 没有被解析

**Comment by moweiwei** [comment]
+1

**Comment by moweiwei** [comment]
请问有 workaround 方法么？

**Comment by zhaoo** [comment]
作者提供的思路：自定义 widget，内部使用 form-render 构建一套表单。通过 props 传入 schema 和 formData 渲染子组件，通过 getValue、setValue 绑定内外两套表单的状态，实现联动。

**Comment by zhaoo** [comment]
已通过该方式实现 modalForm、stepForm 自定义组件。

**Comment by moweiwei** [comment]
有 demo 可以参考下么？谢谢

**Comment by zhaoo** [comment]
明早发你


 
---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年12月24日 23:45:22
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [alibaba/x-render] [BUG] 自定义 object 类型的 widget，props.children 无法透传，导致无法自定义组件 (Issue #639)




 
有 demo 可以参考下么？谢谢

**Comment by moweiwei** [comment]
非常感谢您，邮箱：moweiwei6@gmail.com
