### ISSUE TITLE
[BUG]日期范围、时间范围只读模式显示问题

### ISSUE THREAD

**Issue by zhangxuanlin** [alibaba/x-render#642]
问题：日期范围、时间范围在只读模式下显示有问题
期望结果：只读模式下也能退正常显示
![image](https://user-images.githubusercontent.com/17699676/148029610-80586892-9db5-4f38-b3bc-2b29cdaf859e.png)

**Comment by siyi98** [comment]
在props里设置format属性试试？

**Comment by siyi98** [comment]
![image](https://user-images.githubusercontent.com/29126094/148317061-a07a9bce-327e-4809-ab4a-f13e50e1435f.png)

**Comment by zhangxuanlin** [comment]
不是这个问题，数据映射问题，我关闭这个issue
