### ISSUE TITLE
[BUG] form-render 多选项。定义key值为0时，被当作异常过滤掉了

### ISSUE THREAD

**Issue by yercc** [alibaba/x-render#645]
**1.依赖仓库的版本(Dependencies versions)**：

- react：^16.12.0
- form-render：^1.6.3
- antd：^4.16.3

**2.问题描述(Bug description)**：
多选项。提交时submitData，定义key值为0时，被当作异常过滤掉了
例子：
初始化 多选项 ['0', '1', '6']
没改动直接提交时 ['1', '6']

**Comment by siyi98** [comment]
@yercc 升级到最新版本试试。
