### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by gdc1998** [alibaba/x-render#646]
**1.依赖仓库的版本(Dependencies versions)**：

- react：
- form-render：
- antd：

**^1.8.5 远程加载schema 第一切换正常 之后通过setstate 更新不会重新渲染**：

**3.最小复现demo(Reproduction demo)**：

form-render demo https://codesandbox.io/s/unruffled-flower-jl78h
table-render demo https://codesandbox.io/s/sweet-euler-bdoty
fr-generator demo https://codesandbox.io/s/s13sh

**Comment by mawuyun** [comment]
你也发现了，切换成  1.6.4 就可以了

**Comment by siyi98** [comment]
form-render@1.9.0 版本已经修复此问题。
