### ISSUE TITLE
[BUG] setSchema无效的bug复现了

### ISSUE THREAD

**Issue by mawuyun** [alibaba/x-render#647]
**1.依赖仓库的版本(Dependencies versions)**：

- react：17.x
- form-render：^1.8.5
- antd：^4.16.13

**2.问题描述(Bug description)**： 

1.6.4版本修复的setSchema无效的bug复现了

**Comment by lyhper** [comment]
应该是1.8.8这个版本有问题，降级到1.8.5恢复了

**Comment by roytan883** [comment]
@lyhper 我今天刚刚开始试用这个库。兄弟，幸好看到你这个回复。刚刚搞了各种方法都没法动态改变schema，永远显示第一版的界面，普通的useState，直接调用form.setSchemaByPath，直接调用form.setSchema，全部无效。降级到1.8.5果然可以正常了。

这最新版1.8.8，官方发版本都不跑测试代码吗？动态schema功能全废了都没人知道，这品控。

刚刚又看了一下代码目录，压根没看到任何测试代码，这发版本稳定靠什么？有点劝退了

**Comment by siyi98** [comment]
- form-render@1.9.0版本已经修复，最近年底业务需求较多，非常抱歉给您带来了不便。
- 单测已经开始在写了，到时候测试用例也需要社区一起进来参与，非常感谢。
