### ISSUE TITLE
[Feature]希望支持简单数组功能和非对象根节点schema设置

### ISSUE THREAD

**Issue by Hellerz** [alibaba/x-render#649]
#### 简单数组：即支持生成的对像[123,456]或["上海","背景"]格式的schema
即支持解析schema：
`{
    "type": "object",
    "properties": {
        "citys": {
            "type": "array",
            "items": {
                "type": "integer"
            }
        },
        "cityNames": {
            "type": "array",
            "items": {
                "type": "string"
            }
        }
    }
}`
生成的数据为
`{
     "citys":[2,3,4],
     "cityNames":["上海","北京"]
}`

####支持非对象根：即支持解析如下schema
`{
    "type": "string"
}`
或
`{
    "type": "number"
}`
或
`{
    "type": "array",
    "items": {
        "type": "string"
    }
}`

生成的数据为：
`"上海"`
`2`
`["上海"]`
### 简述一下使用场景，便于开发者更好理解新功能的必要性 (describe your scenario for us to understand the need)

我们希望将这个组件用于提交数据时做校验，因此需要支持以上数据格式

**Comment by siyi98** [comment]
经内部讨论，建议自己从业务层面解决这个问题。

**Comment by harry91** [comment]
> 经内部讨论，建议自己从业务层面解决这个问题。

字符串数组的需求非常常见。

**Comment by wangzhenzhen111** [comment]
好坑，0.x版本不是支持这种么，这种需求很常见
