### ISSUE TITLE
(postcss plugin) Error: @import must precede all other statements (besides @charset)

### ISSUE THREAD

**Issue by wiwengweng** [alibaba/x-render#652]
**1.依赖仓库的版本(Dependencies versions)**：

- react： "~17.0.1"
- form-render："~1.8.8"
- antd："^4.18.3"

**2.问题描述(Bug description)**：
将form render编译到Mendix低代码平台的时候，遇到一个小问题
D:\Projects\projects\widget-dev\mendix-pluggable-widget-template\src\XRender.tsx → dist\tmp\widgets\mendixcn\xrender\XRender.js...
(postcss plugin) Error: @import must precede all other statements (besides @charset)

**3.最小复现demo(Reproduction demo)**：请查看附件，谢谢

form-render demo https://codesandbox.io/s/unruffled-flower-jl78h
table-render demo https://codesandbox.io/s/sweet-euler-bdoty
fr-generator demo https://codesandbox.io/s/s13sh
[mendix-pluggable-widget-template.zip](https://github.com/alibaba/x-render/files/7852646/mendix-pluggable-widget-template.zip)

demo里面我们提供了依赖的安装，build之后就能看到问题的出现。看起来像是postcss里面的@import导致的问题，但是我找不到具体的原因。烦请帮忙review一下问题，谢谢

**Comment by tw93** [comment]
貌似这个工具没有太好兼容到mac的系统，辛苦提供更全的信息
![image](https://user-images.githubusercontent.com/8736212/150260749-516514a3-0ed1-4278-91e5-dfd5ee095066.png)
可以按照这个检查一下你的代码：https://stackoverflow.com/questions/58004095/warning-import-must-precede-all-other-statements-besides-charset

**Comment by wiwengweng** [comment]
Hi, @tw93 谢谢你的回复。上面这个链接之前也搜到过，没能帮我解答问题。实际上我在编译这个组件的时候没有遇到问题，下面的截图，是引入Antd之后的编译结果，也OK，但是最后引入xrender之后就出现issue里面的报错信息。不知道对版本有没有什么要求，我更新到是最新版的1.8.8，还是这个问题。
![image](https://user-images.githubusercontent.com/1968042/150265420-1daf0cdd-b9e3-4f92-9116-98b31b784e34.png)

**Comment by tw93** [comment]
![image](https://user-images.githubusercontent.com/8736212/151119514-d0aad6b3-f987-445b-8655-182069449df2.png)

@wiwengweng 终于找到了，依赖在antd这里的 less 打包，你看看你这边低代码的平台能否加上less的编译
