### ISSUE TITLE
[Feature] Array 什么时候回支持string[]结构呢

### ISSUE THREAD

**Issue by gdc1998** [alibaba/x-render#653]
### 期望的新功能 (describe the expected new feature)
Array 支持string[]

**Comment by tw93** [comment]
```
const schema = {
  type: 'object',
  properties: {
    listName2: {
      title: '对象数组',
      type: 'array',
      widget: 'tableList',
      items: {
        type: 'object',
        properties: {
          input1: {
            type: 'string',
          }
        },
      },
    },
  },
};
```

用上面这个应该可以实现，效果如下：
![image](https://user-images.githubusercontent.com/8736212/151129469-b5f4314b-fd69-4667-8aea-16f98e004254.png)

此外Array支持string[]，看了下实现，比较麻烦，暂时请使用同学业务中转换下数据

**Comment by chenqien** [comment]
@tw93 请问这个有计划支持吗？感觉是非常普遍实用有价值的特性

**Comment by tw93** [comment]
@思翊
看看
