### ISSUE TITLE
[BUG] table-render的scheme中，无法clear掉select中设定的default的值

### ISSUE THREAD

**Issue by WaterHong** [alibaba/x-render#655]
- [x] I have searched the issues of this repository and believe that this is not a duplicate.

**1.依赖仓库的版本(Dependencies versions)**：

- react：12.0.2
- table-render：1.1.5
- antd：4.18.3

**2.问题描述(Bug description)**：
table-render 的schema中存在两个以上的selec时t，设置select的default和allowClear后，点击clear的icon后查询，default的值仍然存在

**3.最小复现demo(Reproduction demo)**：
https://codesandbox.io/s/festive-keldysh-j090i?file=/App.tsx

**Comment by siyi98** [comment]
form-render升级到1.9.0版本即可解决。
