### ISSUE TITLE
[BUG] readOnly模式下，所有列表组件，仍然显示了新增删除复制等功能按钮

### ISSUE THREAD

**Issue by missmess** [alibaba/x-render#664]
**1.依赖仓库的版本(Dependencies versions)**：

- react：17.0.0
- form-render：1.9.1
- antd：4.18.5

**2.问题描述(Bug description)**：
FormRender的readOnly模式下，所有列表组件，如cardList，simpleList，仍然存在新增、删除、复制、上移下移等操作按钮。
只读模式下，不应该有这些按钮。

**3.最小复现demo(Reproduction demo)**：
jsx代码:
```javascript
<FormRender
  form={form}
  schema={schema}
  readOnly
/>
```
schema:
```json
{
  "type": "object",
  "properties": {
    "list_EYXWCx": {
      "title": "数组",
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "input_k_nMM9": {
            "title": "输入框",
            "type": "string",
            "props": {}
          }
        }
      }
    }
  }
}
```

**Comment by siyi98** [comment]
设置readOnly的话，操作按钮区域展示出来也不会影响什么，考虑到可能有用户会希望保留这个操作栏，所以先不针对此做修改。

**Comment by missmess** [comment]
> 1.设置readOnly的话，操作按钮区域展示出来也不会影响什么，考虑到可能有用户会希望保留这个操作栏，所以先不针对此做修改。 2.业务侧可以先通过覆盖`fr-card-toolbar`的样式来达到隐藏工具栏的效果。

使用readonly模式，主要是用于表单的查看。但是现在readonly模式下array存在操作栏，导致array还是可以新建、删除和移动。从用户体验上来说根本不是只读呀。保留操作栏的目的是什么呢？

或者请问一下后期是否可以增加feat，schema上添加额外属性去掉操作栏

**Comment by F-loat** [comment]
@missmess 现在列表组件是有 hideAdd 之类的 props 控制按钮的，只是需要自行控制下，[列表属性](https://x-render.gitee.io/form-render/schema/props#list-%E5%88%97%E8%A1%A8)

**Comment by missmess** [comment]
> @missmess 现在列表组件是有 hideAdd 之类的 props 控制按钮的，只是需要自行控制下，[列表属性](https://x-render.gitee.io/form-render/schema/props#list-%E5%88%97%E8%A1%A8)

嗯嗯，我现在就是这么实现的。在查看页面给schema执行了补丁function，加了hideAdd这些属性，隐藏了操作按钮。
```
/**
 *
 * bug: form-render在readOnly模式下渲染所有的list组件，也会显示新增、删除、移动、复制这四个操作按钮
 * 官方目前没有解决，但是list支持schema里传入props。所以给schema打个补丁加上这些属性
 */
const schemaPatchFix = (schema: any) => {
  // 不是object或者没有后代，退出处理
  if (
    typeof schema !== 'object' ||
    schema.type !== 'object' ||
    !Object.prototype.hasOwnProperty.call(schema, 'properties') ||
    typeof schema.properties !== 'object'
  ) {
    return schema;
  }
  // 挨个处理object的child
  Object.keys(schema.properties).forEach((k) => {
    const childSchema = schema.properties[k];
    // 如果child是object
    if (childSchema.type === 'object') {
      // 递归处理child
      schemaPatchFix(childSchema);
    }
    // 如果是array，并且array的item是object类型，则代表是list其中之一
    if (childSchema.type === 'array' && childSchema.items && childSchema.items.type === 'object') {
      // 打上补丁
      childSchema.props = { ...childSchema.props, hideMove: true, hideAdd: true, hideCopy: true, hideDelete: true };
      // 递归处理array的item
      schemaPatchFix(childSchema.items);
    }
  });
  return schema;
};
```
不过还是希望官方可以支持。因为大部分情况下，同一个schema，希望它在编辑页面有操作按钮，在查看页面没有操作按钮。都是通过readOnly来控制的。
