### ISSUE TITLE
[BUG]number类型，设置默认值，提交的时候验证失败

### ISSUE THREAD

**Issue by yangxiaoqiao2016** [alibaba/x-render#666]
**1.依赖仓库的版本(Dependencies versions)**：

- react：17.0.2
- form-render：1.9.1
- antd：4.16.9

**2.问题描述(Bug description)**：
number类型的数据，设置默认值111，得到的schema如下 ，default是string类型，FormRender提交的时候，数字输入框的类型不是number
```
{
  "type": "object",
  "properties": {
    "number_N8ZgDE": {
      "title": "数字输入框",
      "type": "number",
      "default": "1111"
    }
  },
  "labelWidth": 120,
  "displayType": "row"
}
```
![06820a69e308b6f4a6ec747dd91c9d26](https://user-images.githubusercontent.com/20087598/153358771-3fb3ea65-dc05-4fe5-a2be-672ef852094a.jpg)

**3.最小复现demo(Reproduction demo)**：
codesandbox的demo打开不了

form-render demo https://codesandbox.io/s/unruffled-flower-jl78h
table-render demo https://codesandbox.io/s/sweet-euler-bdoty
fr-generator demo https://codesandbox.io/s/s13sh

**Comment by yangxiaoqiao2016** [comment]
> default为什么要设置'111'呢，肯定是要 设置成number类型的呀

你拖动数字输入框控件，输入默认值，导出来的schema的default值就是string类型

**Comment by yangxiaoqiao2016** [comment]
![image](https://user-images.githubusercontent.com/20087598/153414012-0f23ccd6-845c-4cdb-9f5a-dd01bd8a9706.png)

**Comment by yangxiaoqiao2016** [comment]
> > 你拖动数字输入框控件
> 
> 这句话是什么意思？数字输入框有拖动的特性？

![image](https://user-images.githubusercontent.com/20087598/153414101-8d44ad6b-5203-4eb5-8255-a84cfa487d0c.png)

**Comment by F-loat** [comment]
`fr-generator@2.7.5` 已修复，感谢反馈
