### ISSUE TITLE
select组件选中选项后，调用form.resetFields，UI不重置

### ISSUE THREAD

**Issue by Alexis374** [alibaba/x-render#671]
**1.依赖仓库的版本(Dependencies versions)**：

- react：17.0.2
- form-render：1.9.1
- antd：4.18.7

**2.问题描述(Bug description)**：
select组件选择选项之后，调用form.resetFields()，可以看到model的值被重置，但是select组件的UI还是停留在上次选择的选项，没有被重置为空。

**3.最小复现 demo(Reproduction demo)**：

https://codesandbox.io/s/icy-fire-k9qx4p?file=/App.tsx

**Comment by tw93** [comment]
升级到 1.9.2   OK
