### ISSUE TITLE
[BUG]列表中使用颜色选择器默认值不生效

### ISSUE THREAD

**Issue by summerboys** [alibaba/x-render#672]
---

**1.依赖仓库的版本(Dependencies versions)**：

- react：17.0.1
- form-render：1.9.1
- antd：4.1.0

**2.问题描述(Bug description)**：
列表中使用颜色选择器默认值不生效以下是配置schema
{
  "type": "object",
  "properties": {
    "list_osTgWv": {
      "title": "数组",
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "color_w6x4s1": {
            "title": "颜色选择",
            "type": "string",
            "format": "color",
            "default": "#2c2e3b"
          }
        }
      },
      "props": {}
    }
  },
  "labelWidth": 120,
  "displayType": "row"
}

**3.最小复现 demo(Reproduction demo)**：

form-render demo https://codesandbox.io/s/unruffled-flower-jl78h
table-render demo https://codesandbox.io/s/sweet-euler-bdoty
fr-generator demo https://codesandbox.io/s/s13sh

**Comment by F-loat** [comment]
目前确实不支持数组子项的默认值配置，后续在 #679 讨论吧
