### ISSUE TITLE
数组下面的子元素，设置default无效

### ISSUE THREAD

**Issue by missmess** [alibaba/x-render#675]
**1.依赖仓库的版本(Dependencies versions)**：

- react：17.0.0
- form-render：1.9.1
- antd：4.18.5

**2.问题描述(Bug description)**：

数组下面的子元素组件，比如输入框，数字选择条等等，设置的default都无效。

**3.最小复现 demo(Reproduction demo)**：

Schema:
```json
{
  "type": "object",
  "displayType": "row",
  "properties": {
    "domain": {
      "title": "域",
      "type": "string",
      "default": "xxxxxx"
    },
    "number2": {
      "title": "带滑动条",
      "type": "number",
      "default": 11,
      "widget": "slider"
    },
    "event": {
      "title": "事件列表内容",
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "domain": {
            "title": "域",
            "type": "string",
            "default": "HU_SocF"
          },
          "number2": {
            "title": "带滑动条",
            "type": "number",
            "default": 11,
            "widget": "slider"
          }
        }
      }
    }
  }
}
```

截图：
![image](https://user-images.githubusercontent.com/20296208/154929714-dd9568b0-9aee-4ee3-a027-e7ea848aff29.png)

**Comment by F-loat** [comment]
数组子项暂不支持默认设置，array 的初始值可以设置在 array 那个层级上 https://github.com/alibaba/x-render/issues/672

**Comment by missmess** [comment]
> 数组子项暂不支持默认设置，array 的初始值可以设置在 array 那个层级上 #672

请问有文档嘛，如何设置？

**Comment by missmess** [comment]
> 数组子项暂不支持默认设置，array 的初始值可以设置在 array 那个层级上 #672

放在array层级确实可以出来。
```
{
      "title": "事件列表内容",
      "type": "array",
      "default": [{ "domain": "HU_SocF" }],
      ......
```
但是我现在的需求是，这个数组下所有子元素的domain的输入框，都是固定的default值，并且是readonly。
改array层级的default值，不太现实吧

**Comment by F-loat** [comment]
数组子项的默认值会支持的，issue 关闭是因为提重复了

**Comment by missmess** [comment]
> 数组子项的默认值会支持的，issue 关闭是因为提重复了

好的，感谢您。请问大概什么时候能支持呢？
