### ISSUE TITLE
你好，如何在form-render展示，自定义的echarts图表组件，现在组件可以自定义。切换预览的时候展示不出来

### ISSUE THREAD

**Issue by tianyazjq** [alibaba/x-render#676]
### 简述一下使用场景，便于开发者更好理解新功能的必要性 (describe your scenario for us to understand the need)
![image](https://user-images.githubusercontent.com/5754329/155111997-e9a0ac27-f558-44e1-bd74-bb02f16b0d75.png)

切换成预览的时候就没有了

![image](https://user-images.githubusercontent.com/5754329/155112117-2b9e29e0-d945-4144-a944-a6126fc2c134.png)

**Comment by F-loat** [comment]
提供下简化的复现示例哈，我这边试了下自定义组件在预览模式也是生效的

**Comment by tianyazjq** [comment]
可以了谢谢大兄弟👬



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年2月25日(周五) 晚上6:26
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [alibaba/x-render] 你好，如何在form-render展示，自定义的echarts图表组件，现在组件可以自定义。切换预览的时候展示不出来 (Issue #676)




 
提供下简化的复现示例哈，我这边试了下自定义组件在预览模式也是生效的
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
