### ISSUE TITLE
【BUG】form-render 内置列表组件 drawerList 内使用自定义组件编辑报错

### ISSUE THREAD

**Issue by mianmabb1** [alibaba/x-render#680]
**1.依赖仓库的版本(Dependencies versions)**：

- react：16.14.0
- form-render：1.9.2
- antd：4.18.3

**2.问题描述(Bug description)**：
自定义组件 `dateRange`，其接收 object 类型为值，在内置列表组件 `drawerList` 内使用 ：

<img width="452" alt="image" src="https://user-images.githubusercontent.com/49062532/155277067-0be56a7c-12c6-4e39-9748-7a5b6ca9df55.png">

![image](https://user-images.githubusercontent.com/49062532/155277343-2b136a80-036f-46af-a49e-e632892f8336.png)

页面编辑时报错：`Uncaught Error: Objects are not valid as a React child (found: object with keys {end, start}). If you meant to render a collection of children, use an array instead.`

**初步排查**

![image](https://user-images.githubusercontent.com/49062532/155278506-18b98759-270a-4037-b08b-05b427cf66f3.png)

![image](https://user-images.githubusercontent.com/49062532/155279043-f0bcf5f3-3053-4f7f-97e6-23deef55ce3e.png)

**3.最小复现 demo(Reproduction demo)**：

https://codesandbox.io/s/upbeat-tesla-kiqcmi

**Comment by F-loat** [comment]
#673 已修复，另外日期区间的话 type 应该是 array

**Comment by F-loat** [comment]
懂你的意思了，我们这边优化下，不过你还需要额外指定下 readOnlyWidget，不然默认是下面这种效果
![image](https://user-images.githubusercontent.com/16759376/155473201-26c1d531-05e8-4568-9c46-40118256bda6.png)

**Comment by mianmabb1** [comment]
指定 readOnlyWidget 没有生效 @F-loat

**Comment by F-loat** [comment]
@mianmabb1 下一版本应该会支持了 https://github.com/alibaba/x-render/pull/693 ，之前加到别的 pr 里了
