### ISSUE TITLE
修改组件的key之后，data里原有的key的数据仍然存在

### ISSUE THREAD

**Issue by missmess** [alibaba/x-render#681]
**1.依赖仓库的版本(Dependencies versions)**：

- react：
- form-render：
- antd：

**2.问题描述(Bug description)**：
原有一个组件key为input，输入内容后，onChange回调的data中有input的数据项。
将该组件的key改为kk，输入内容后，onChange回调的data中有kk的数据项，但input的数据项也存在，但是表单中已经没有该key的组件。onChange回调的data中理应不出现该input的数据项

**3.最小复现 demo(Reproduction demo)**：
1. 原始schema，就一个输入框
```json
{
  "type": "object",
  "properties": {
    "input": {
      "title": "简单输入框",
      "type": "string"
    }
  }
}
```
2. 输入框中输入字符串'a'后：
![image](https://user-images.githubusercontent.com/20296208/155286054-00843b82-730e-4430-b1f7-d80a85ba00da.png)

3. 将input改成kk：
![image](https://user-images.githubusercontent.com/20296208/155287463-4f2b6c18-6b8e-4cec-b495-b4fde7adf7b1.png)

4. 输入框中输入字符串'bb'后：
![image](https://user-images.githubusercontent.com/20296208/155287487-519a580f-6b22-4687-96cd-7a7a8f9c1b59.png)

5. 预期值应该是：
```json
{
  "kk": "bb"
}
```

**Comment by missmess** [comment]
现在有一个属性removeHiddenData，是把schema表单中已经隐藏的字段，在getValues或提交时从数据中去除掉。
![image](https://user-images.githubusercontent.com/20296208/155303295-8be4b845-74d5-4a50-8e8f-da1e46ce6eda.png)

期望有一个属性比如叫做removeInvalidateData，将已经不在schema表单中的那些无效的字段，从数据中去除掉。

**Comment by siyi98** [comment]
这种场景不对见啊，你的schema是放到useState里面来控制了吧？把组件用`useMemo(()=>{},[schmea])`包裹一下再试试？

**Comment by chenqien** [comment]
@missmess 请问这个问题你解决了吗？我这边也有一样的困扰
