### ISSUE TITLE
【BUG】form-render 1.9.3 版本，onFinish 时必填校验未生效

### ISSUE THREAD

**Issue by mianmabb1** [alibaba/x-render#686]
**1.依赖仓库的版本(Dependencies versions)**：

- react：16.14.0
- form-render：1.9.3
- antd：4.18.3

**2.问题描述(Bug description)**：
form-render 升级至 1.9.3，onFinish 时必填校验未生效

**3.最小复现 demo(Reproduction demo)**：
https://codesandbox.io/s/jolly-jennings-fnirj1

**Comment by siyi98** [comment]
1.9.4版本已经修复。
