### ISSUE TITLE
tsx 中使用 fr-generator 浮窗例子报错

### ISSUE THREAD

**Issue by wuyangcherish** [alibaba/x-render#690]
---

**1.依赖仓库的版本(Dependencies versions)**：

"antd": "^4.18.9",
"fr-generator": "^2.7.7",
"react": "^17.0.2",

**2.问题描述(Bug description)**：

使用 fr-generator 的例子的时报错 提示 
![image](https://user-images.githubusercontent.com/11582854/156556823-ca60f665-24dc-487b-8a28-66fcfa91846e.png)

**3.最小复现 demo(Reproduction demo)**：

form-render demo https://codesandbox.io/s/unruffled-flower-jl78h
table-render demo https://codesandbox.io/s/sweet-euler-bdoty
fr-generator demo https://codesandbox.io/s/s13sh

**Comment by F-loat** [comment]
templates 已经废弃掉了，可以通过 settings 实现相关能力，文档我们更新下
