### ISSUE TITLE
联动赋值后的输入框的检验没有实时同步

### ISSUE THREAD

**Issue by killdada** [alibaba/x-render#694]
---

**1.依赖仓库的版本(Dependencies versions)**：

- react：17.x
- form-render：1.9.5
- antd：4.19.1

**2.问题描述(Bug description)**：

官方demo  https://x-render.gitee.io/form-render/advanced/watch 的基础上

```js
import React, { useEffect } from 'react';
import { Button } from 'antd';
import FormRender, { useForm } from 'form-render';

const schema = {
  type: 'object',
  properties: {
    input1: {
      title: '简单输入框',
      type: 'string',
      required: true,
      placeholder: '尝试在此输入',
    },
    input2: {
      title: '简单输入框2',
      type: 'string',
      required: true,
    },
  },
};

const Demo = () => {
  const form = useForm();

  const watch = {
    // # 为全局
    '#': val => {
      console.log('表单的时时数据为：', val);
    },
    input1: val => {
      form.setValueByPath('input2', val);
    },
  };

  return (
    <div>
      <FormRender
        onFinish={onFinish}
        form={form}
        schema={schema}
        watch={watch}
      />
      <Button type="primary" onClick={form.submit}>
        提交
      </Button>
    </div>
  );
};
```

1：直接点击提交按钮，检验全部组件，二个组件都提示必填
![image](https://user-images.githubusercontent.com/16487810/157581473-c54befd0-cd52-46b1-a6fb-5140a76ea309.png)

2：在输入框1输入文字，此时输入框检验通过，提示消失，因为有watch监听的原因，输入框1值改变输入框2的值也改变，但是输入框值2的改变没有触发检验，导致此时输入框2的检验提示不会实时消失

![4790B99A-6CE6-48dd-9A37-BC7F799C2D86](https://user-images.githubusercontent.com/16487810/157581598-bffc9f88-1317-4a91-aed0-de70f4acd071.png)

**3.最小复现 demo(Reproduction demo)**：
实在打不开codebox，打开codebox里面一直停留在解析module,本地跑官方的截图出来的，可以在官方的这个地址验证，加个提交按钮即可 https://x-render.gitee.io/form-render/advanced/watch

原因分析，从那个版本开始以后，useForm.js 值得改变不再触发检验，只在submit触发一次全部检验，然后页面组件在onchange的时候触发一次检验当前组件

因为onchange监听的是当前输入框手动输入改变才会触发新的检验，watch设置的值并不会触发检验，然后useForm也没有对这种情况处理

所以如何折中优化？还是考虑性能不管这种联动输入框值改变的检验实时显示？

**Comment by siyi98** [comment]
可以先用`setErrorFields`手动处理一下

**Comment by siyi98** [comment]
watch中触发实时校验的话，性能会有些差。
