### ISSUE TITLE
Global CSS cannot be imported from within node_modules.

### ISSUE THREAD

**Issue by yetingmao** [alibaba/x-render#695]
--- 

**1.依赖仓库的版本(Dependencies versions)**：

- "next": "12.0.4",
 "fr-generator": "^2.7.7",
 "antd": "^4.17.2",

**2.问题描述(Bug description)**：
![image](https://user-images.githubusercontent.com/20633411/157582733-27e5b59c-9b13-41aa-97d4-37c46a01c132.png)

**Comment by siyi98** [comment]
什么场景？

**Comment by yetingmao** [comment]
![image](https://user-images.githubusercontent.com/20633411/157596466-742bb3bb-ccaa-4008-b65b-40dd8a0155e7.png)
引入之后，自动更新页面就直接报错了

**Comment by yetingmao** [comment]
https://nextjs.org/docs/messages/css-npm

**Comment by AntoninSorrento** [comment]
+1

**Comment by siyi98** [comment]
貌似是next.js的问题：https://github.com/vercel/next.js/discussions/27953

**Comment by tw93** [comment]
手动引入一下atom.css这个文件在你的组件中
https://www.google.com/search?q=Global+CSS+cannot+be+imported+from+within+node_modules&oq=Global+CSS+cannot+be+imported+from+within+node_modules&aqs=edge..69i57j69i61.656j0j1&sourceid=chrome&ie=UTF-8
