### ISSUE TITLE
移动端展示支持计划

### ISSUE THREAD

**Issue by dengyao** [alibaba/x-render#696]
请问下有没有计划支持移动端的计划，通过设计器生成的json文件，通过antd-mobile 展示移动端页面

**Comment by siyi98** [comment]
已经在计划中了，FR2.x会支持，时间大概在今年5，6月份左右。

**Comment by siyi98** [comment]
可以移步至这里：https://github.com/alibaba/x-render/discussions/699

**Comment by maxiangsai** [comment]
> 

你好，现在好像还不支持antd-mobile吧
