### ISSUE TITLE
支持Fusion组件(alibaba/next)

### ISSUE THREAD

**Issue by HengzheLi** [alibaba/x-render#697]
### 期望的新功能 (describe the expected new feature)
支持Fusion组件

### 简述一下使用场景，便于开发者更好理解新功能的必要性 (describe your scenario for us to understand the need)
现在开发的UI已经在使用Fusion组件了，希望X-render能支持在Antd和Fusion之间切换

**Comment by siyi98** [comment]
FR1.x目前与antd强耦合，不支持其他的组件库；
之后的FR2.x会将core抽离出来，大概会在5-6月份左右。
