### ISSUE TITLE
form-render支持指定渲染顺序

### ISSUE THREAD

**Issue by ghostjzf** [alibaba/x-render#702]

**Comment by siyi98** [comment]
有几个点需要讨论一下：
1. 如果有的`schema`字段没有设置`order`，那这个字段应该放在排序队列之前还是之后；
2. 如果开发者给两个`schema`设置了一样的`order`，那如何处理；

**Comment by ghostjzf** [comment]
> 有几个点需要讨论一下：
> 
> 1. 如果有的`schema`字段没有设置`order`，那这个字段应该放在排序队列之前还是之后；
> 2. 如果开发者给两个`schema`设置了一样的`order`，那如何处理；

我这么认为：

1. 没有设置order字段的应该放在设置order的字段之后
2. 如果存在两个同样的order则相同order按照传入顺序排序

**Comment by chenliangngng** [comment]
这个功能搞了吗，没搞到话给我，我最近要整这个了 @siyi98 
再顺便问下，改完后大概发版什么时候

**Comment by siyi98** [comment]
form-render@1.10.0 版本已支持
