### ISSUE TITLE
fr-generator 的"编辑框"，高度设置不生效

### ISSUE THREAD

**Issue by h184242597** [alibaba/x-render#703]
**fr-generator 表单设计器的"编辑框‘"，设置高度不生效**

- 问题1：编辑框组件的属性配置 row 貌似不对，应该是 rows 
- 问题2：在渲染“编辑框”时，设置的高度（rows）不生效，被 标签上的 style 覆盖了

**Comment by siyi98** [comment]
antd的  TextArea组件是不支持传入rows参数的：https://ant-design.gitee.io/components/input-cn/#Input.TextArea ，我们这边改一下
