### ISSUE TITLE
组件为hidden状态，onFinish仍会拿到值

### ISSUE THREAD

**Issue by gdc1998** [alibaba/x-render#704]
**1.依赖仓库的版本(Dependencies versions)**：

- react：17.0.40
- form-render：1.9.5
- antd：4.19.2

**2.问题描述(Bug description)**：
组件为hidden状态，onFinish仍会拿到值

**3.最小复现 demo(Reproduction demo)**：
{
    type: "object",
    properties: {
      inputName: {
        title: "简单输入框",
        type: "string",
      },
      input_swXrDH: {
        title: "输入框",
        type: "string",
        required: true,
        props: {},
        hidden: "{{formData.inputName.length}}",
      },
    },
    labelWidth: 120,
    displayType: "row",
  }

https://codesandbox.io/s/peaceful-sound-xdk9s8?file=/App.jsx

**Comment by siyi98** [comment]
`<FormRender removeHiddenData form={form} schema={schema} onFinish={onFinish} />`
组件要设置 `removeHiddenData` 属性哦
