### ISSUE TITLE
form-render 渲染简单数组时失败

### ISSUE THREAD

**Issue by fengomgod** [alibaba/x-render#705]
**1.依赖仓库的版本(Dependencies versions)**：

- react：17.0.0
- form-render：1.9.2
- table-render: 
- antd：

**2.问题描述(Bug description)**：
使用 form-render 渲染数组时， items如果是个简单数据类型（例如 string）， 此输入框就不展示了

**3.最小复现 demo(Reproduction demo)**：

将这段 schema 传入 FormRender 即可复现
{
  title: "测试",
  type: "object",
  properties: {
    id: {
      $id: "#/properties/id",
      description: "这是id",
      title: "id",
      type: "integer"
    },
    array: {
      $id: "#/properties/array",
      description: "这是array",
      title: "array",
      type: "array",
      items: {
        $id: "#/properties/array/items",
        type: "string",
        title: "item"
      }
    }
  }
}

form-render demo https://codesandbox.io/s/unruffled-flower-jl78h
table-render demo https://codesandbox.io/s/sweet-euler-bdoty
fr-generator demo https://codesandbox.io/s/s13sh

**Comment by siyi98** [comment]
schmea 写的有问题，参考这里：http://localhost:8080/form-render/advanced/list-display

**Comment by fengomgod** [comment]
这个链接是你的本地链接啊， 外链是哪个？

**Comment by fengomgod** [comment]
https://x-render.gitee.io/form-render/advanced/list-display/ 这个链接中的每一个例子的 items 都是一个 object ， 如果我希望生成的数据是 [1, 2, 3, 4, 5] 这种的话 schema 应该是什么样的？并且上面写到的例子的格式也是符合规范的啊。。。

**Comment by fengomgod** [comment]
@siyi98  麻烦帮忙看一下

**Comment by siyi98** [comment]
> https://x-render.gitee.io/form-render/advanced/list-display/ 这个链接中的每一个例子的 items 都是一个 object ， 如果我希望生成的数据是 [1, 2, 3, 4, 5] 这种的话 schema 应该是什么样的？并且上面写到的例子的格式也是符合规范的啊。。。

- 你写的items是不对的哦，schema的规范可以参考这里：https://x-render.gitee.io/form-render/schema/schema；
- 可以生成  [ {x:''}, {y:''} , z:'' }] 这样的数据，[1,2,3,4,5]这样的数据目前只有`select`多选模式是可以的
