### ISSUE TITLE
radio和数组长度联动

### ISSUE THREAD

**Issue by gonglixin980926** [alibaba/x-render#708]
### 增加一个control radio，即为通过该radio 来改变其他radio或数组

**Comment by siyi98** [comment]
额...这个场景没太看懂...能截个图描述一下吗👀

**Comment by gonglixin980926** [comment]
![image](https://user-images.githubusercontent.com/40887236/159651370-82bba4a1-f4fc-41af-a73e-181684a452bc.png)

**Comment by gonglixin980926** [comment]
> 额...这个场景没太看懂...能截个图描述一下吗👀

就是上面的图的使用方式

**Comment by siyi98** [comment]
有这种业务场景？

**Comment by siyi98** [comment]
用表达式可以实现吧

**Comment by gonglixin980926** [comment]
> 有这种业务场景？

有的

**Comment by gonglixin980926** [comment]
>

**Comment by gonglixin980926** [comment]
> 用表达式可以实现吧

我使用了自定义组件，通过使用， "dependencies": ["optionsCount"], 在自定义组件里拿到这个值，然后重新设置数组组件的值就OK了，不过这样实现每次输入，这个自定义的组件每次都会更新一遍。

**Comment by gonglixin980926** [comment]
> 用表达式可以实现吧

https://github.com/gonglixin980926/my-app
这是我写的自定义组件，可以看下，

**Comment by siyi98** [comment]
设置了dependencies的话，组件在监听的数据变化后是会重新渲染的。
