### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'schema')

### ISSUE THREAD

**Issue by gonglixin980926** [alibaba/x-render#709]
**1.依赖仓库的版本(Dependencies versions)**：

- react："^17.0.2"
- form-render："^1.9.5"
- table-render: 
- antd："^4.19.3"

**2.问题描述(Bug description)**：
TypeError: Cannot read properties of undefined (reading 'schema')
    at Object.getSchemaByPath (useForm.js:333:1)
    at optionsCount (index.tsx:57:1)
    at runWatcher (Watcher.js:16:1)
    at Watcher.js:36:1
    at invokePassiveEffectCreate (react-dom.development.js:23487:1)
    at HTMLUnknownElement.callCallback (react-dom.development.js:3945:1)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:3994:1)
    at invokeGuardedCallback (react-dom.development.js:4056:1)
    at flushPassiveEffectsImpl (react-dom.development.js:23574:1)
    at unstable_runWithPriority (scheduler.development.js:468:1) 'getSchemaByPath'
**3.最小复现 demo(Reproduction demo)**：
import FormRender, { useForm } from 'form-render';
import { useEffect, useRef, useState } from 'react';

const schema = {
    "type": "object",
    "properties": {
      "optionsCount": {
        "title": "单选",
        "type": "string",
        "enum": [
          "1",
          "2",
          "3"
        ],
        "enumNames": [
          "1",
          "2",
          "3"
        ],
        "widget": "radio",
        "default": "3"
      },
      "options": {
        "title": "数组",
        "type": "array",
        "items": {
          "type": "object",
          "properties": {
            "text": {
              "title": "输入框",
              "type": "string",
              "props": {}
            }
          }
        },
        "props": {
          "hideAdd": "true"
        },
        "displayType": "row",
        "default": "[{text: \"\"}]"
      }
    },
    "column": 1,
    "labelWidth": 120,
    "displayType": "row"
  }

const CustomFrom = () => {
    const form = useForm();
    const defaultOptions = schema.properties.options.default

    const watch = {
      "optionsCount": val => {
          form.setValueByPath('options',new Array(Number(val || 1)).fill(defaultOptions))
          console.log(form.getSchemaByPath('options'))
      },
    }
    return <FormRender form={form} schema={schema as any} watch={watch}/>;
}

export default CustomFrom

form-render demo https://codesandbox.io/s/unruffled-flower-jl78h
table-render demo https://codesandbox.io/s/sweet-euler-bdoty
fr-generator demo https://codesandbox.io/s/s13sh

**Comment by siyi98** [comment]
`form.getSchemaByPath('options[].text')`

**Comment by gonglixin980926** [comment]
> `form.getSchemaByPath('options[].text')`

这个是不能输出一个引用值么
