### ISSUE TITLE
form-render 渲染数组表单新增条目、 删除条目、 调整顺序 时均无法触发 onChange 事件

### ISSUE THREAD

**Issue by fengomgod** [alibaba/x-render#713]
**1.依赖仓库的版本(Dependencies versions)**：

- react：17
- form-render：1.9.2
- table-render: 
- antd：

**2.问题描述(Bug description)**：
form-render 渲染数组表单新增条目、 删除条目、 调整顺序 时均无法触发 onChange 事件， 但修改数组某一项的值的时候是可以触发的

**3.最小复现 demo(Reproduction demo)**：

* 使用这段 schema 数据渲染表单
const demoSchema = {
  title: "demo",
  type: "object",
  properties: {
    list: {
      type: "array",
      title: "数组",
      widget: "virtualList",
      items: {
        type: "object",
        title: "数组条目",
        properties: {
          formRenderItem: {
            type: "string",
            title: "名称"
          }
        }
      }
    }
  }
}
* 在 onchange 事件内随便打印一个值
* 在表单中点击新增条目
* 可以看到控制台并未打印对应更改

form-render demo https://codesandbox.io/s/unruffled-flower-jl78h
table-render demo https://codesandbox.io/s/sweet-euler-bdoty
fr-generator demo https://codesandbox.io/s/s13sh

**Comment by siyi98** [comment]
onchange事件写在哪里了

**Comment by siyi98** [comment]
form-render没有对外暴露onchange事件诶

**Comment by fengomgod** [comment]
onValueChange 事件， 上面的描述写错了

**Comment by siyi98** [comment]
@fengomgod 也没有对外暴露 onValueChange 方法呀，你的demo里面也没看到 onValueChange

**Comment by xiaorong61** [comment]
> form-render没有对外暴露onchange事件诶

http://x-components.gitee.io/form-render/config/props

这里有的
