### ISSUE TITLE
希望代码能真正完全开源

### ISSUE THREAD

**Issue by taoqf** [alibaba/x-render#715]
### 期望的新功能 (describe the expected new feature)

完全不依赖antd.即使使用antd,也可以通过设置widgets的方式来。
这样可以方便产品解偶。也更灵活。

### 简述一下使用场景，便于开发者更好理解新功能的必要性 (describe your scenario for us to understand the need)

antd有可能存在一些问题（至少我遇上了）。在集成的时候会有障碍，如果能完全分离，那是最好了。

我试着查看修改源码剖离它们，发现似乎不是全部的源码。

**Comment by siyi98** [comment]
XRender 2.0 会将 core 抽离出来，目前可以试试form-render的mapping：https://x-render.gitee.io/form-render/advanced/mapping

**Comment by taoqf** [comment]
我还是真心期待2.0，mapping我用不了，我现在项目中有东西与antd冲突，因为现在1.0里直接有antd的引用，所以我无论如何都用不了。
可否透露一下2.0的计划在什么时候？
