### ISSUE TITLE
文档 playground 页面现在什么内容都没有

### ISSUE THREAD

**Issue by wjkang** [alibaba/x-render#719]
**1.依赖仓库的版本(Dependencies versions)**：

- form-render：1

**2.问题描述(Bug description)**：

playground 现在什么内容都没有

这是旧版的

[![qcVHa9.jpg](https://s1.ax1x.com/2022/03/29/qcVHa9.jpg)](https://imgtu.com/i/qcVHa9)

**3.最小复现 demo(Reproduction demo)**：

https://x-render.gitee.io/playground/

**Comment by siyi98** [comment]
已经修复
