### ISSUE TITLE
使用fr-generator时，如何实现某一个表单项不可删除且ID不可修改

### ISSUE THREAD

**Issue by LMLGM** [alibaba/x-render#720]
![image](https://user-images.githubusercontent.com/58587791/160745943-1b8692eb-20cd-496f-9862-5039f5571295.png)
目前已经实现默认的defalutValue不可删除，但是ID怎么实现不可以编辑，但是新增的是可以编辑的

**Comment by F-loat** [comment]
id 不可编辑建议通过动态设置 settings 里 id 对应的项为隐藏/只读，或者通过自定义组件实现，id 默认使用 idInput 组件
