### ISSUE TITLE
下拉框里的值通过配置的接口动态获取

### ISSUE THREAD

**Issue by Y-G-H** [alibaba/x-render#722]
### 期望的新功能 (describe the expected new feature)

下拉框单选/多选之类的这种组件选项，能不能支持通过接口动态渲染呢。
简单点就比如通过约定接口回参格式，或者麻烦点更通用一点也可以做成前端通过类似jsonpath这样子的语法来提取k/v

### 简述一下使用场景，便于开发者更好理解新功能的必要性 (describe your scenario for us to understand the need)

这个场景应该很常见，大多数时候都无法预测下拉框中的选项值或者难以在配置中去维护，我看现在的使用是通过表单配置选项这样很呆

**Comment by siyi98** [comment]
用 `form.setSchemaByPath`：https://x-render.gitee.io/form-render/advanced/form-methods

**Comment by zwmmm** [comment]
form.setSchemaByPath 会触发 watch 死循环
