### ISSUE TITLE
select 单选模式下。onSearch 事件 不执行

### ISSUE THREAD

**Issue by gdc1998** [alibaba/x-render#725]
**1.依赖仓库的版本(Dependencies versions)**：

- react：17.0.4
- form-render：1.9.5
- table-render: 
- antd：4.19.2

**2.问题描述(Bug description)**：

**3.最小复现 demo(Reproduction demo)**：

form-render demo https://codesandbox.io/s/unruffled-flower-jl78h
table-render demo https://codesandbox.io/s/sweet-euler-bdoty
fr-generator demo https://codesandbox.io/s/s13sh

**Comment by siyi98** [comment]
贴下代码吧

**Comment by gdc1998** [comment]
https://codesandbox.io/s/unruffled-flower-jl78h?file=/App.jsx

**Comment by gdc1998** [comment]
我看codesandbox 跑不起来。把schema 写进去了 麻烦看下 哈 https://codesandbox.io/s/unruffled-flower-jl78h?file=/App.jsx

**Comment by gdc1998** [comment]
https://codesandbox.io/s/musing-butterfly-4vw6wd 
codesandbox 我看跑不起来 写了个简单的schema 麻烦看下哈

**Comment by siyi98** [comment]
![image](https://user-images.githubusercontent.com/29126094/162110290-e84ceb6a-98df-46c6-bf96-7f5cb8f33758.png)
XRender劫持了Select组件的onSearch函数，可以参考上图中的写法，文档我稍后补充一下。
