### ISSUE TITLE
单独暴露FRCore

### ISSUE THREAD

**Issue by lhz960904** [alibaba/x-render#727]
### 期望的新功能 (describe the expected new feature)
单独暴露 FRCore
### 简述一下使用场景，便于开发者更好理解新功能的必要性 (describe your scenario for us to understand the need)
我在使用nextjs，配合scss，不想使用antd组件库，以及引入antd只能入口引入样式文件。所以想单独使用FRCore组件，自己定制一套组件widget

### 附nextjs 使用 form-render 提示的报错

<img width="985" alt="image" src="https://user-images.githubusercontent.com/29157111/161559500-47d9f0e2-cac3-4690-9e07-be0d0e9b3c3b.png">

**Comment by siyi98** [comment]
这个会在XRender2.0支持，预计6月发布

**Comment by cyberbear181** [comment]
2.0在哪
