### ISSUE TITLE
form.setValueByPath更新特定的表单项后，提交时数据并没有生效更新

### ISSUE THREAD

**Issue by slodreamer** [alibaba/x-render#728]
**1.依赖仓库的版本(Dependencies versions)**：

- react：
- form-render：
- table-render: 
- antd：

**2.问题描述(Bug description)**：

form.setValueByPath更新特定的表单项后，提交时数据并没有生效更新

**3.最小复现 demo(Reproduction demo)**：

form-render demo https://codesandbox.io/s/relaxed-pine-u4u2my

**Comment by siyi98** [comment]
你的用法有问题：`form.setValueByPath(path,value)`

**Comment by siyi98** [comment]
`form.setValueByPath('hospitalLabel', tags)`

**Comment by slodreamer** [comment]
没有问题的，因为我是尝试着改了hospitalLabel这个path没生效，tags是我传过去的value，我重新设置了一个特定title的值也没有生效

**Comment by siyi98** [comment]
你的form-render是什么版本，我这里没有复现你的问题诶...

**Comment by slodreamer** [comment]
1.9.9

**Comment by siyi98** [comment]
看下你的自定义组件内部是怎么写的

**Comment by slodreamer** [comment]
我直接设置也没有起作用呢
<img width="626" alt="image" src="https://user-images.githubusercontent.com/15122540/162113561-2334108c-da4b-4118-9443-e2548c71b998.png">

**Comment by siyi98** [comment]
> 我直接设置也没有起作用呢 <img alt="image" width="626" src="https://user-images.githubusercontent.com/15122540/162113561-2334108c-da4b-4118-9443-e2548c71b998.png">

不能这样写，应该是 `form.setValueByPath('title','测试')`

**Comment by slodreamer** [comment]
谢谢大佬的回复，问题已解决
