### ISSUE TITLE
提交前校验所有 required 为 true 属性

### ISSUE THREAD

**Issue by gonglixin980926** [alibaba/x-render#731]
### 简述一下使用场景，便于开发者更好理解新功能的必要性 (describe your scenario for us to understand the need)
提交前校验所有 required 为 true 属性，并将校验结果作为参数传递给 onFinish

**Comment by siyi98** [comment]
onFinish的第二个参数就是校验结果呀

**Comment by gonglixin980926** [comment]
> 

提交校验，不会把错误的字段显示在表单上面
我这样用了下 `const { errors } = await form.submit()` 就可以了
