### ISSUE TITLE
数组/对象已经被隐藏了，但数组/对象的子元素依然会被校验

### ISSUE THREAD

**Issue by gonglixin980926** [alibaba/x-render#732]
**1.依赖仓库的版本(Dependencies versions)**：

- react：^17.0.2
- form-render：^1.9.9
- table-render: 
- antd：

**2.问题描述(Bug description)**：
数组/对象已经被隐藏了，但数组/对象的子元素依然会被校验
**3.最小复现 demo(Reproduction demo)**：
codesandbox:
https://codesandbox.io/s/keen-engelbart-wg9oin?file=/src/index.tsx
github:
https://github.com/gonglixin980926/my-app

form-render demo https://codesandbox.io/s/unruffled-flower-jl78h
table-render demo https://codesandbox.io/s/sweet-euler-bdoty
fr-generator demo https://codesandbox.io/s/s13sh

@siyi98 希望大佬尽快回复下～

**Comment by siyi98** [comment]
1.9.3-beta.1 版本已修复，明天发正式版。

**Comment by RoxanneCIA** [comment]
@siyi98 校验确实已解决，但是再次显示对象的时候，对象下的表单还是隐藏状态。。
