### ISSUE TITLE
drawerList第二页排序操作无效【官方示例同样有问题】

### ISSUE THREAD

**Issue by chenqien** [alibaba/x-render#733]
**1.依赖仓库的版本(Dependencies versions)**：

- react：
- form-render：1.9.11
- table-render: 
- antd：

**2.问题描述(Bug description)**：
<img width="1389" alt="image" src="https://user-images.githubusercontent.com/32092235/162665143-705bb6e1-380f-4a85-806a-03352ce75e7a.png">

**3.最小复现 demo(Reproduction demo)**：

form-render demo https://codesandbox.io/s/unruffled-flower-jl78h
table-render demo https://codesandbox.io/s/sweet-euler-bdoty
fr-generator demo https://codesandbox.io/s/s13sh

**Comment by chenqien** [comment]
@siyi98 大佬啥时候有时间修复呢？ 感谢感谢~

**Comment by tw93** [comment]
已修复，最近的版本会发布

**Comment by tw93** [comment]
已修复，请用1.9.12最新版本
