### ISSUE TITLE
watch immediate 不生效bug

### ISSUE THREAD

**Issue by lida1984** [alibaba/x-render#734]
源码的 useForm 对外取消了firstMount 属性。导致watch 中 immediate无法生效。
本人把这个放开，同时改造了下 watcher 组件：

const Watcher = ({ watchKey, watch, formData, firstMount }) => {
  const value = getValueByPath(formData, watchKey);
  const watchObj = watch[watchKey];
  const [isWatched, setIsWatched] = useState(false);

  useEffect(() => {
    const runWatcher = () => {
      if (typeof watchObj === 'function') {
        try {
          watchObj(value);
        } catch (error) {
          console.log(`${watchKey}对应的watch函数执行报错：`, error);
        }
      } else if (watchObj && typeof watchObj.handler === 'function') {
        try {
          watchObj.handler(value);
        } catch (error) {
          console.log(`${watchKey}对应的watch函数执行报错：`, error);
        }
      }
    };
    if (!firstMount) {
      // useForm 渲染完成，完成form 的 finalFlatten
      if (!isWatched) {
        if (typeof watchObj === 'function') { 
          runWatcher();
        } else {
          const immediate = watchObj && watchObj.immediate;
          if (immediate) {
            runWatcher();
          }
        }
        setIsWatched(true)
      } else {
        runWatcher();
      }
    }
  }, [JSON.stringify(value), firstMount]);
  return null;
};

**Comment by siyi98** [comment]
可以提个pr

**Comment by tw93** [comment]
一个月没有反馈，有新的pr可以提交过来即可
