### ISSUE TITLE
Object  那个折叠框是否可以禁止折叠

### ISSUE THREAD

**Issue by tanchang123** [alibaba/x-render#737]
Object  那个折叠框是否可以禁止折叠 @siyi98

**Comment by leeguooooo** [comment]
用 Mapping 覆盖 Object, 因为他本来的样式就比较丑。

可以看下我覆盖的 Object,  参考文档 ： https://x-render.gitee.io/form-render/advanced/mapping
<img width="1460" alt="image" src="https://user-images.githubusercontent.com/9278645/163298743-5537682d-3818-48f0-9a7b-357fc75ab928.png">

**Comment by tanchang123** [comment]
> 



> 可以用 Mapping 覆盖 Object, 因为他本来的样式就比较丑。 参考文档 ： https://x-render.gitee.io/form-render/advanced/mapping
> 
> 可以看下我覆盖的 Object：
> 
> <img alt="图片" width="1460" src="https://user-images.githubusercontent.com/9278645/163298743-5537682d-3818-48f0-9a7b-357fc75ab928.png">

方便上一下mapping那一块的代码吗

**Comment by leeguooooo** [comment]
> 

其实就跟文档上的例子差不多

**Comment by tanchang123** [comment]
> > 
> 
> 其实就跟文档上的例子差不多
如图所以，在mapping自定义的组件里面拿不到自己添加的属性collapsed，可以问一下，怎么才能在props里面拿个自定义的collapsed属性吗
![mapping](https://user-images.githubusercontent.com/51226567/163321007-43964d66-bf9c-4644-a800-4864c5b0e7c1.PNG)
![disabled](https://user-images.githubusercontent.com/51226567/163321024-243e94f7-c63c-4482-8ef9-54db674b3fa1.PNG)
@leeguooooo
