### ISSUE TITLE
表单设计器支持顶部底部组件固定

### ISSUE THREAD

**Issue by ViaLee** [alibaba/x-render#743]
### 期望的新功能 (describe the expected new feature)
对于拖入的最外层组件(包括自定义widget)，希望能提供是否固定在顶部或底部等相关配置项 ，或希望提供hideCopy、hideDelete、hideMove配置属性禁止删除、移动、复制
### 简述一下使用场景，便于开发者更好理解新功能的必要性 (describe your scenario for us to understand the need)
类似模板表单：希望初始化时顶部底部有固定的类似页眉页脚或标题的自定义组件，不可删除修改，中间部分为自定义表单设计

**Comment by F-loat** [comment]
复制和删除按钮可以通过 controlButton 属性控制的
