### ISSUE TITLE
typescript使用导出的Schema构建时会失败，需要export RuleItem和SchemaBase

### ISSUE THREAD

**Issue by Qlly-web** [alibaba/x-render#749]
### 期望的新功能 (describe the expected new feature)
export RuleItem和SchemaBase
### 简述一下使用场景，便于开发者更好理解新功能的必要性 (describe your scenario for us to understand the need)
尝试手动export RuleItem和SchemaBase构建成功，辛苦大佬看看
构建时需要生成声明文件

**Comment by siyi98** [comment]
有空提个pr吗

**Comment by Qlly-web** [comment]
好的

**Comment by siyi98** [comment]
https://github.com/alibaba/x-render/pull/756/files
