### ISSUE TITLE
当外层 required 包含一个对象的 key 值时， 对应对象内的 required 就不生效了

### ISSUE THREAD

**Issue by fengomgod** [alibaba/x-render#750]
**1.依赖仓库的版本(Dependencies versions)**：

- react：17
- form-render：1.9.11
- table-render: 
- antd：4.20.0

**2.问题描述(Bug description)**：
当外层 required 包含一个对象property时， 这个对象内的 required 就不生效了， 如果删掉外层 required 中的 object1， 那么 objcet1 中的 required 就会生效

**3.最小复现 demo(Reproduction demo)**：
const jsonSchema = {
    "$id":"http://example.com/root.json",
    "$schema":"http://json-schema.org/draft-07/schema#",
    "type":"object",
    "properties":{
        "id":{
            "$id":"#/properties/id",
            "type":"integer",
            "title":"id",
            "description":"这是id"
        },
        "object1":{
            "type":"object",
            "properties":{
                "key":{
                    "type":"string",
                    "title":"key值",
                    "widget":"stringInput"
                },
                "id":{
                    "type":"integer",
                    "title":"id"
                },
                "name":{
                    "type":"string",
                    "title":"名字",
                    "format":"imageInput",
                    "widget":"imageInput",
                    "rules":[
                        {
                            "message":"请输入一个图片地址"
                        }
                    ]
                },
                "time":{
                    "type":"string",
                    "title":"时间",
                    "format":"dateTime",
                    "widget":"date",
                    "rules":[
                        {
                            "message":"请选择一个日期时间"
                        }
                    ]
                }
            },
            "title":"第一个对象",
            "$id":"#/properties/object1",
            "collapsed":true,
            "required":[
                "key",
                "id",
                "name",
                "time"
            ]
        }
    },
    "title":"测试配置",
    "required":[
        "id",
        "object1"
    ]
}

form-render demo https://codesandbox.io/s/unruffled-flower-jl78h
table-render demo https://codesandbox.io/s/sweet-euler-bdoty
fr-generator demo https://codesandbox.io/s/s13sh

**Comment by tw93** [comment]
object对象直接required，其实是不支持的，建议放里面即可
