### ISSUE TITLE
TableRender中，想要修改seachApi中的url，请问如何修改？

### ISSUE THREAD

**Issue by caimingyi484** [alibaba/x-render#751]
想要修改seachApi中的url，请问如何修改？
使用useState无效；
```
const searchApi = params => {
    // console.log('params >>> ', params);
    console.log(schema,'========');
    const url = 'https://www.fastmock.site/mock/62ab96ff94bc013592db1f67667e9c76/getTableList/api/basic';
    return request(url, {
        method: 'GET',
        params: { ...params }
      }).then(res => {
        // console.log('response:', res);
        if (res && res.data) {
          return {
            rows: res.data,
            total: res.data.length,
            extraData: res.status,
          }; // 注意一定要返回 rows 和 total
        }
      })
      .catch(e => console.log('Oops, error', e));
  };
  const [searchApii, setSearchApii] = useState({searchApi:searchApi});

useEffect(() => {
...
       const searchApi1 = params => {
              // console.log('params >>> ', params);
              console.log(schema,'111111111');
              // url的地址不一样
              const url = 'https://www.fastmock.site/mock/62ab96ff94bc013592db1f67667e9c76/getTableList/api/get';
              return request(url, {
                  method: 'GET',
                  params: { ...params }
                }).then(res => {
                  // console.log('response:', res);
                  if (res && res.data) {
                    return {
                      rows: res.data,
                      total: res.data.length,
                      extraData: res.status,
                    }; // 注意一定要返回 rows 和 total
                  }
                })
                .catch(e => console.log('Oops, error', e));
            };
            setSearchApii({searchApi:searchApi1});
...
});

return (
<Search
          schema={schema}
          onSearch={onSearch}
          // afterSearch={afterSearch}
          api={searchApii.searchApi}
        />
...
);
```
请指教！

**Comment by siyi98** [comment]
用useRef试试

**Comment by caimingyi484** [comment]
> 用useRef试试

可以使用，谢谢了
...
  const url = 'https://www.fastmock.site/mock/62ab96ff94bc013592db1f67667e9c76/getTableList/api/basic';
  const urlRef = useRef(url);
...
 const searchApi = params => {
    // console.log('params >>> ', params);
    console.log(schema,'========');
    // const url = 'https://www.fastmock.site/mock/62ab96ff94bc013592db1f67667e9c76/getTableList/api/basic';
    const url = urlRef.current;
    return request(url, {
        method: 'GET',
        params: { ...params }
      }).then(res => {
        // console.log('response:', res);
        if (res && res.data) {
          return {
            rows: res.data,
            total: res.data.length,
            extraData: res.status,
          }; // 注意一定要返回 rows 和 total
        }
      })
      .catch(e => console.log('Oops, error', e));
  };

 useEffect(() => {
        ...
        urlRef.current = 'https://www.fastmock.site/mock/62ab96ff94bc013592db1f67667e9c76/getTableList/api/basic?id=1';
        refresh(null, { extra: 1 });
        ...
  });

  return (
    <Search
          schema={schema}
          onSearch={onSearch}
          // afterSearch={afterSearch}
          api={searchApi}
          searchOnMount={false}
        />
     ...
   );
