### ISSUE TITLE
支持自定义组件能力增强

### ISSUE THREAD

**Issue by loo100** [alibaba/x-render#759]
### 期望的新功能
希望 schema type 增加一个 func 类型，用于传入 React Component (虽然这样有点违背 json schema ）
### 简述一下使用场景，便于开发者更好理解新功能的必要性
场景： 填写大段配置表单项中，中间有可能插入一个特殊的组件。有简单交互，点击或者发个请求显示一下。这种用 widget 写一个自定义组件有点不灵活。

**Comment by siyi98** [comment]
这种形式我们内部也讨论过，最后还是决定不对`JSON Schema`做过多扩展。

**Comment by loo100** [comment]
> 这种形式我们内部也讨论过，最后还是决定不对`JSON Schema`做过多扩展。

那现在有什么比较优雅的办法么，就是想在一堆表单项目（通过json配置）中间插一个稍微复杂点的组件如我们现在配合自己公司内部的UI框架，做了一个层适配层，全局注册的，使用 widget 和 mapping 的方式，但是现在不想把一些偏业务的组件也用这种方式来做，这种有点臃肿。

**Comment by loo100** [comment]
> 这种形式我们内部也讨论过，最后还是决定不对`JSON Schema`做过多扩展。

甚至有一个比较愚蠢的做法，自定义一个空的占位组件（自定义宽，高）。这样x-render渲染的时候出来一个空的区域，直接讲组件插进去。
比较棘手的问题，可能这个自定义的组件需要使用 formdata 里面的数据，或者是 formdata的数据影响了这个自定义组件。类似这种，你们现在有什么好的办法么。

**Comment by BeanWei** [comment]
如果成本允许的话，可以考虑换个方案，[formily](https://github.com/alibaba/formily)  相比之下 formily 更具优势

**Comment by loo100** [comment]
> 如果成本允许的话，可以考虑换个方案，[formily](https://github.com/alibaba/formily) 相比之下 formily 更具优势。
> 
> x-render 和 formily 都十分优秀。x-render 适合简单的，formily 自身比较复杂但是更能打更能应对复杂的业务需求

 formily  就不考虑了

**Comment by tw93** [comment]
@loo100 好问题，可以一起讨论下
看问题描述，我可以理解成让 from-render 支持自定义组件的描述吗？我在想类似vue那种slot思路有没有办法json描述
cc @siyi98

**Comment by loo100** [comment]
> @loo100 好问题，可以一起讨论下 看问题描述，我可以理解成让 from-render 支持自定义组件的描述吗？我在想类似vue那种slot思路有没有办法json描述 cc @siyi98

对，就是这个意思
