### ISSUE TITLE
fr-generator在 react18.0.0中无法正常使用。会不停重置。

### ISSUE THREAD

**Issue by FEyudong** [alibaba/x-render#762]
**1.依赖仓库的版本(Dependencies versions)**：

- react：18.0.0

**2.问题描述(Bug description)**：
拖拽一个组件到画布，会不停重置画布。
**3.最小复现 demo(Reproduction demo)**：

form-render demo https://codesandbox.io/s/unruffled-flower-jl78h
table-render demo https://codesandbox.io/s/sweet-euler-bdoty
fr-generator demo https://codesandbox.io/s/s13sh

**Comment by FEyudong** [comment]
降级到17就好了

**Comment by siyi98** [comment]
https://github.com/react-dnd/react-dnd/issues/3416

**Comment by siyi98** [comment]
@FEyudong 方便给个demo仓库地址看看么

**Comment by F-loat** [comment]
2.8.0-beta.0 已优化，可以用更新试下

**Comment by zwmmm** [comment]
> 

2.8.0-beta.0 未发布到npm公网上 麻烦发下好么

**Comment by siyi98** [comment]
v2.8.0 版本发布

**Comment by BLJJ-DBLD** [comment]
![image](https://user-images.githubusercontent.com/70953752/191882598-f0fb4b3b-7098-471c-9971-087aa08f9112.png)
本人使用 v2.8.0 版本，编写默认 demo 还是会有首次闪屏失效 bug

**Comment by BLJJ-DBLD** [comment]
![image](https://user-images.githubusercontent.com/70953752/191882662-648016f9-2768-469b-adc6-ed67b81f980c.png)
我这边在使用 v2.8.0 版本下，默认 demo 还是会在第一次拖拽时出现闪屏和失效BUG

**Comment by BLJJ-DBLD** [comment]
> v2.8.0 版本发布

我使用 v2.8.0 版本后还是会出现该 BUG

**Comment by BLJJ-DBLD** [comment]
> v2.8.0 版本发布

老哥，我使用 v2.8.0 版本发布 并没有效果。但是使用了 tag 中的 2.8.0-beta.0 却有效。
