### ISSUE TITLE
可以实现表格内每一行都自定义列数和列宽吗

### ISSUE THREAD

**Issue by LELOG** [alibaba/x-render#769]
类似这种：
按照一行分为24的布局，我可以定义每一行显示几列，每一列占x/24(x为所占比)，貌似现在x-render我只看到一个最外层的属性column统一定义全部行的列数，不能自定义每一行。请问有什么属性可以实现，还是目前暂不支持

**Comment by F-loat** [comment]
暂不支持特定行指定列数，但是每个组件都可以通过 `width` 属性指定宽度的
