### ISSUE TITLE
generator右侧setting希望能支持动态配置

### ISSUE THREAD

**Issue by ViaLee** [alibaba/x-render#773]
### 期望的新功能 (describe the expected new feature)
generator右侧setting希望能支持动态配置，且随组件数据联动，也就是支持相同组件由于数据不同settings不同。

### 简述一下使用场景，便于开发者更好理解新功能的必要性 (describe your scenario for us to understand the need)
有的自定义组件的settings需要和自定义组件的数据进行联动，组件数据改变时希望能及时更新settings。
目前settings作为generator的属性如果修改会导致generator重新渲染，能否支持仅修改当前渲染settings的form的schema，比如通过ref可获取这个form实例，去修改其schema。
或者有其他实现方法吗，求教Thanks♪(･ω･)ﾉ

**Comment by F-loat** [comment]
目前可以通过 `ref.getSettingsForm()` 获取到配置表单实例，可以看下能否满足需求

**Comment by ViaLee** [comment]
> 

使用ref.getSettingsForm()可以取到右侧表单实例，但是调用它的setSchemaByPath和setSchema方法，没法新增表单项，仅对已有的表单项修改部分属性有效果，比如title有效，type无效
<img width="527" alt="image" src="https://user-images.githubusercontent.com/35186077/168515332-7fe308e6-ac73-4c18-bea9-df883ff507d5.png">
<img width="273" alt="image" src="https://user-images.githubusercontent.com/35186077/168515398-31e5912f-e6c7-4ad1-af64-0a08e8bf59bb.png">

**Comment by F-loat** [comment]
你描述个具体的场景吧，我们看看怎么实现更合适些

**Comment by F-loat** [comment]
你描述个具体的场景吧，我们看看怎么实现更合适些

**Comment by ViaLee** [comment]
> 你描述个具体的场景吧，我们看看怎么实现更合适些

好的~ 场景其实很简单：
使用自定义组件实现的单选题配置，右侧setting希望根据选项数联动分数配置项，新增或删除一个选项，setting的分数项也新增或删除一个。
<img width="846" alt="image" src="https://user-images.githubusercontent.com/35186077/168717651-3a0ab21f-3930-4931-bbd6-e8c0ceba1507.png">

**Comment by F-loat** [comment]
@ViaLee 还是有点奇怪，相当于是配表单的默认值嘛，你们这个表单配置出来的效果是什么，选项还能让用户修改吗

**Comment by ViaLee** [comment]
> @ViaLee 还是有点奇怪，相当于是配表单的默认值嘛，你们这个表单配置出来的效果是什么，选项还能让用户修改吗

是的，是创建问卷界面，拖入的是题型，有的题型是需要配置选项内容和每项的属性
