### ISSUE TITLE
自定义列表组件的时候 props里面的schema拿不到items里面的properties 返回的是个空对象

### ISSUE THREAD

**Issue by ErnestWangZuNian** [alibaba/x-render#774]
**1.依赖仓库的版本(Dependencies versions)**：

- react：17.x
- form-render：1.9.0
- table-render: 
- antd：

**2.问题描述(Bug description)**：
自定义列表组件的时候 props里面的schema拿不到items里面的properties 返回的是个空对象
**3.最小复现 demo(Reproduction demo)**：
`import { Button } from 'antd';
import FormRender, { useForm } from 'form-render';

import CardList  from './cardlist';

const schema = {
  type: 'object',
  properties: {
    listName2: {
      title: '对象数组',
      description: '对象数组嵌套功能',
      type: 'array',
      widget: 'cardList',
      items: {
        type: 'object',
        properties: {
          input1: {
            title: '简单输入框',
            type: 'string',
            required: true,
          },
          select1: {
            title: '单选',
            type: 'string',
            enum: ['a', 'b', 'c'],
            enumNames: ['早', '中', '晚'],
            default: 'a',
          },
          obj: {
            title: '对象',
            type: 'object',
            properties: {
              input1: {
                title: '简单输入框',
                type: 'string',
                required: true,
                default: '卡片列表',
              },
              select1: {
                title: '单选',
                type: 'string',
                enum: ['a', 'b', 'c'],
                enumNames: ['早', '中', '晚'],
              },
            },
          },
        },
      },
    },
  },
};

const Demo = () => {
  const form = useForm();
  const onFinish = (formData, errors) => {
    console.log('formData:', formData, 'errors', errors);
  };
  return (
    <div>
      <FormRender form={form} schema={schema} onFinish={onFinish} widgets={{cardList: CardList}} />
      <Button type="primary" onClick={form.submit}>
        提交
      </Button>
    </div>
  );
};

export default Demo;
`
// CardList组件
`const NewCardList = (props) => {
  const { schema, addons, children } = props;

  const { getSchemaByPath, dataPath } = addons;

  console.log(schema, '3333');

  console.log(schema, addons, props);
  return <div>1111</div>;
};

export default NewCardList;`
// 打印结果
<img width="503" alt="image" src="https://user-images.githubusercontent.com/11648360/168454964-759b7ab9-c7bf-4705-9cfa-2d515e7d90fd.png">

**Comment by ErnestWangZuNian** [comment]
[https://codesandbox.io/s/jolly-wave-dbsd7k?file=/App.jsx](url)

最小复现demo

**Comment by siyi98** [comment]
@ErnestWangZuNian 递归解析schema的时候，`properties`会被重置，这是上一个维护者写的逻辑，这个逻辑去掉的话我不确定会不会有坑。
源码地址：https://github.com/alibaba/x-render/blob/master/packages/form-render/src/form-render-core/src/utils.js#L143

**Comment by ErnestWangZuNian** [comment]
您好，我已收到邮件，我会尽快处理的。。。

**Comment by siyi98** [comment]
你要获取properties的目的是什么，我们换种思路看看？

**Comment by ErnestWangZuNian** [comment]
就是你在自定义对象形式的组件的时候 你需要拿到schema 中的type去渲染对应的组件类型
  现在拿不到schema有个最简单的bug就是 你有个对象schmema 你想获取描述信息都获取不到 只能拿到title

**Comment by siyi98** [comment]
@ErnestWangZuNian 换种思路，你可以直接用原来的schema来写？不需要从props里获取。

**Comment by zjyfantasy** [comment]
这个问题解决了吗，我也有需求要配置array里item子组件的属性，但是获取不到

**Comment by ErnestWangZuNian** [comment]
您好，我已收到邮件，我会尽快处理的。。。
