### ISSUE TITLE
hidden类型检验错误，fr-generator 无法选中已添加的组件

### ISSUE THREAD

**Issue by donghainan** [alibaba/x-render#781]
**1.依赖仓库的版本(Dependencies versions)**：

- react：17.0.2
- form-render：1.9.12
- fr-generator: 2.7.8
- table-render: 
- antd：4.20.4

**2.问题描述(Bug description)**：
组件hidden属性设置 hidden: "{{rootValue.input === '1'}}" , hidden类型检验错误，导致fr-generator 无法选中已添加的组件
**3.最小复现 demo(Reproduction demo)**：

form-render demo https://codesandbox.io/s/unruffled-flower-jl78h
table-render demo https://codesandbox.io/s/sweet-euler-bdoty
fr-generator demo https://codesandbox.io/s/s13sh

**Comment by F-loat** [comment]
可以先设置 validation={false} 来跳过配置表单校验
