### ISSUE TITLE
组件类型切换为object后样式在creater中样式错误

### ISSUE THREAD

**Issue by mylesshie** [alibaba/x-render#783]
**1.依赖仓库的版本(Dependencies versions)**：

- react：16.8
- form-render：1.9.9
- table-render: 
- antd：3.26.x

**2.问题描述(Bug description)**：
在fr-generator的时候，我这边做了一个自定义组件如图：
这是组件type为string的展示方式：
<img width="808" alt="image" src="https://user-images.githubusercontent.com/4142212/170015654-f0340dd5-7656-4865-a10d-2bd43a92cbd8.png">

这是组件type为object时的展示方式：
<img width="801" alt="image" src="https://user-images.githubusercontent.com/4142212/170016947-93ce7546-7ffe-4784-8665-b7bfc2e6fd85.png">

我的诉求是type为object时候也像string一样的展示，该如何设置呢？因为展示为object时会误导用户
如下是schema配置：
`{
      text: 'Treaty列表',
      name: 'Treaty',
      schema: {
        title: 'Treaty列表',
        type: 'object',
        widget: 'CustomSelect'
      },
      setting: {
        default: {
          title: 'defaultValue',
          type: 'string'
        }
      }
    }`

**3.最小复现 demo(Reproduction demo)**：

form-render demo https://codesandbox.io/s/unruffled-flower-jl78h
table-render demo https://codesandbox.io/s/sweet-euler-bdoty
fr-generator demo https://codesandbox.io/s/s13sh

**Comment by siyi98** [comment]
为什么要把`type:"string"`改到`type:"object"`呢，这两个类型都是有内置的样式的

**Comment by siyi98** [comment]
如果要覆盖默认的样式，可以看文档：https://xrender.fun/form-render/advanced/mapping
如果是为了改变formData的结构，可以看文档这里的`bind`示例：https://xrender.fun/form-render/advanced/form-methods
