### ISSUE TITLE
增加表格编辑的示例

### ISSUE THREAD

**Issue by mraiguo** [alibaba/x-render#785]
### 期望的新功能 (describe the expected new feature)
内置或者在示例中增加表格编辑的demo（包括行内编辑，弹窗编辑）
### 简述一下使用场景，便于开发者更好理解新功能的必要性 (describe your scenario for us to understand the need)
表格编辑是一个非常常用的需求，而如果使用antd原生的方法操作会非常繁琐，提供这个特性能大大减少开发者的样板代码工作量

**Comment by siyi98** [comment]
你要的是「筛选+编辑表格」，还是只要「编辑表格」？
如果是只要编辑表格，可以看看tableList：https://xrender.fun/form-render/advanced/list-display

**Comment by mraiguo** [comment]
> 你要的是「筛选+编辑表格」，还是只要「编辑表格」？ 如果是只要编辑表格，可以看看tableList：https://xrender.fun/form-render/advanced/list-display

https://ant.design/components/table-cn/#components-table-demo-edit-row.  想要的是类似这种效果的，应该是所说的 「筛选+编辑表格」吧
