### ISSUE TITLE
官网例子报错

### ISSUE THREAD

**Issue by xu-Aurora** [alibaba/x-render#790]
<img width="892" alt="image" src="https://user-images.githubusercontent.com/35291465/171337242-c8ddbd58-17c8-426d-a5ef-1b0e1616a41d.png">

https://xrender.fun/table-render#search使用官网的这个例子，全部复制下来的，没有改动一个，启动项目报上面那个错误

**Comment by xu-Aurora** [comment]
使用table-render会造成我原本的组件样式错乱。
<img width="405" alt="image" src="https://user-images.githubusercontent.com/35291465/171339126-a8c1ebc7-f42b-4742-9f14-190df074a9ef.png">

**Comment by siyi98** [comment]
贴代码，一张截图什么也看不出来

**Comment by siyi98** [comment]
你先自己排查一下，目前还没人遇到过这样的问题，先看看是不是antd版本不一致。
