### ISSUE TITLE
一个页面多个form时，切换form显隐时form的事件执行有bug

### ISSUE THREAD

**Issue by mylesshie** [alibaba/x-render#795]
问题描述：
当一个页面有多个formrender组件时，他们共用一个form对象，在切换表单显隐时候，watch方法执行会有bug
<img width="1275" alt="image" src="https://user-images.githubusercontent.com/4142212/172089682-34d04a04-95f8-40c6-a64f-2a08df742199.png">

测试代码仓库：https://github.com/mylesshie/test-form-render

**Comment by siyi98** [comment]
有没有试过用两个form实例呢

**Comment by siyi98** [comment]
其实可以写两个form的

**Comment by Echonessy** [comment]
是不是后面的form实例把前面的form实例覆盖了
