### ISSUE TITLE
update Xrender.mp4 on the Readme page

### ISSUE THREAD

**Issue by GOWxx** [alibaba/x-render#798]
readme 页面底部的视频 [Xrender.mp4](https://user-images.githubusercontent.com/8736212/123383626-ff187a80-d5c5-11eb-803f-296762fe72d0.mp4)
最后停在的时间是2021年5月28日，已经过去一年啦，期望可以更新～

**Comment by siyi98** [comment]
收到，这周末更新一下。

**Comment by naah69** [comment]
想问下这个视频是怎么生成的啊
