### ISSUE TITLE
【form-render】1.10.0版本表单提交前的校验逻辑存在undefine的bug

### ISSUE THREAD

**Issue by chenqien** [alibaba/x-render#799]
**1.依赖仓库的版本(Dependencies versions)**：

- react：
- form-render：
- table-render: 
- antd：

**2.问题描述(Bug description)**：
bug代码路径：packages/form-render/src/form-render-core/src/validator.js
<img width="773" alt="image" src="https://user-images.githubusercontent.com/32092235/172900473-62091a61-01a6-4d7d-8364-03816286a3ea.png">

当schema中存在数组时，表单校验这里会出错

**3.最小复现 demo(Reproduction demo)**：

form-render demo https://codesandbox.io/s/unruffled-flower-jl78h
table-render demo https://codesandbox.io/s/sweet-euler-bdoty
fr-generator demo https://codesandbox.io/s/s13sh

**Comment by siyi98** [comment]
发下你的schema看看

**Comment by sunbowq** [comment]
{
    type: 'object',
    properties: {
      list_7iN75b: {
        title: '数组',
        type: 'array',
        items: {
          type: 'object',
          properties: {
            input_5vWjGQ: {
              title: '输入框',
              type: 'string',
              props: {},
            },
            input_gYQO4r: {
              title: '输入框',
              type: 'string',
              props: {},
            },
          },
        },
        props: {},
      },
    },
    labelWidth: 120,
    displayType: 'row',
  }

**Comment by sunbowq** [comment]
> 发下你的schema看看
{
    type: 'object',
    properties: {
      list_7iN75b: {
        title: '数组',
        type: 'array',
        items: {
          type: 'object',
          properties: {
            input_5vWjGQ: {
              title: '输入框',
              type: 'string',
              props: {},
            },
            input_gYQO4r: {
              title: '输入框',
              type: 'string',
              props: {},
            },
          },
        },
        props: {},
      },
    },
    labelWidth: 120,
    displayType: 'row',
  }

**Comment by sunbowq** [comment]
我改了 好几个版本都不行

**Comment by sunbowq** [comment]
![10669db07d1d375b5bafc6301bcbc86](https://user-images.githubusercontent.com/57241855/173184639-71722b0c-7845-4941-8365-5012cdaeeeb9.png)
![48e086afe91e4ce5ab46f730a040436](https://user-images.githubusercontent.com/57241855/173184644-5389528a-f7f9-4097-a695-4e9fed765842.png)

js Object[key]方法 的key值少个[] 所以取不到值

**Comment by chenqien** [comment]
@siyi98 
我这的问题跟 @sunbowq 描述的是一样，目前是降级到1.9.13才没问题。

**Comment by siyi98** [comment]
@chenqien @sunbowq 1.11.3版本已解决

**Comment by sunbowq** [comment]
好的 谢谢 辛苦



在 2022-06-13 17:26:01，"思翊" ***@***.***> 写道：

@***@***.*** 1.11.3版本已解决
