### ISSUE TITLE
table-rander全屏后，表格密度按钮点击无效

### ISSUE THREAD

**Issue by Jarod-Xie** [alibaba/x-render#802]
**1.依赖仓库的版本(Dependencies versions)**：
官网table 演示案例https://xrender.fun/table-render/demo

**2.问题描述(Bug description)**：
在官网table演示案例，点击右上角全屏，全屏后表格密度按钮点击没反应

**3.最小复现 demo(Reproduction demo)**：
https://xrender.fun/table-render/demo

**Comment by siyi98** [comment]
table-render@1.3.5 版本已修复
