### ISSUE TITLE
闪屏/form项点击消失

### ISSUE THREAD

**Issue by zhangfengchao** [alibaba/x-render#803]
**1.依赖仓库的版本(Dependencies versions)**：

    "antd": "^4.21.0",
    "fr-generator": "^2.7.8",
    "react": "^18.1.0",

**2.问题描述(Bug description)**：拖动闪屏并且有几率已有的form项自己消失

**3.最小复现 demo(Reproduction demo)**：

form-render demo https://codesandbox.io/s/unruffled-flower-jl78h
table-render demo https://codesandbox.io/s/sweet-euler-bdoty
fr-generator demo https://codesandbox.io/s/s13sh

**Comment by siyi98** [comment]
先降到react17

**Comment by xiaorong61** [comment]
Duplicate of #762
