### ISSUE TITLE
一个页面多个表格，下面的表格右上角的表格密度按钮点击无效

### ISSUE THREAD

**Issue by Jarod-Xie** [alibaba/x-render#804]
**1.依赖仓库的版本(Dependencies versions)**：
官网表格 demo
**2.问题描述(Bug description)**：
![image](https://user-images.githubusercontent.com/27668637/173474507-773949eb-a6a5-4596-8841-f1d8fe733ff9.png)

**3.最小复现 demo(Reproduction demo)**：
https://xrender.fun/table-render/demo

**Comment by siyi98** [comment]
emmm...昨天解全屏模式的那个bug，Dropdown用了getPopupContainer的属性，导致所有的`密度设置`都挂载在id为'tr-table'的元素上了，所以才出现了这个情况，我下午改一下

**Comment by Jarod-Xie** [comment]
> emmm...昨天解全屏模式的那个bug，Dropdown用了getPopupContainer的属性，导致所有的`密度设置`都挂载在id为'tr-table'的元素上了，所以才出现了这个情况，我下午改一下

提了个pr，大佬看下啊

**Comment by siyi98** [comment]
fixed
