### ISSUE TITLE
希望字段描述(description)能够收缩

### ISSUE THREAD

**Issue by hes-zhu** [alibaba/x-render#807]
### 希望字段描述(description)能够收缩，类似antd formItem tooltip的提示
当前，描述过多很难看，有点喧兵夺主
![image](https://user-images.githubusercontent.com/40056535/173557693-11cd014b-2cbe-4915-8001-9fdfb1486f31.png)
希望变更
![image](https://user-images.githubusercontent.com/40056535/173557848-7f67b03b-d637-41af-b955-65d465e3dde0.png)

**Comment by hes-zhu** [comment]
enen...看啦下源码，已经有参数(descType)控制啦，回去翻了下文档找到了相关描述，😮‍💨看文档不仔细，打扰啦

```js
switch (displayType) {
  case 'row':
    return (
      <Tooltip title={description}>
        <i className="fr-tooltip-icon" />
      </Tooltip>
    );
  case 'inline':
    return null;
  default:
    if (descType === 'icon') {
      return (
        <Tooltip title={description}>
          <i className="fr-tooltip-icon" />
        </Tooltip>
      );
    }

    return <span className="fr-desc ml2">{`( ${description} )`}</span>;
}
```

![image](https://user-images.githubusercontent.com/40056535/174271491-c02d5bf6-c608-45ad-84c8-e8bd346a2563.png)

**Comment by xdd-lisa** [comment]
希望字段描述(description)能够支持自定义组件，比如按钮，或者a标签一类

**Comment by xdd-lisa** [comment]
![image](https://user-images.githubusercontent.com/32589018/185926877-aa419e50-9bd1-4909-baed-6be88be91f5e.png)
