### ISSUE TITLE
自定义组件通过Props无法获取addons

### ISSUE THREAD

**Issue by hes-zhu** [alibaba/x-render#808]
**1.依赖仓库的版本(Dependencies versions)**：

- react：^17.0.2
- fr-generator：^2.7.8

**2.问题描述(Bug description)**：
自定义组件通过Props无法获取addons，addons的值是undefined
![image](https://user-images.githubusercontent.com/40056535/173558176-9a65ad82-34db-4275-b870-9dbf691107a2.png)
```js
import _ from 'lodash';
import { FC, ReactNode, useEffect, useState } from 'react';
import { queryDatapkgsAsync } from '@mdtBsServices/datapkgs';
import Select, { SelectProps } from '@mdtDesign/select';
import Spin from '@mdtDesign/spin';
import { IDatapkg, IDatapkgsQuery, ILabelValue } from '@mdtProComm/interfaces';
import useTokenRequest from '../../hooks/useTokenRequest';

interface IFrSelectProps extends SelectProps {
  style: any;
  value: any;
  onChange: any;
  addons: any;
}
// 已删除多余代码
const SelectDatapkg: FC<IFrSelectProps> = ({ style, value, onChange, addons, ...rest }) => {
  // addons -> undefined
  console.log('addons: ', addons);
  // const { dependValues = null } = addons;
  // console.log(dependValues);
  const [search, setSearch] = useState<string>();
  const [notFound, setNotFound] = useState<ReactNode>(<span>无</span>);
  const [pkgs, setPkgs] = useState<IDatapkg[]>([]);

  const finalProps = {
    options,
    showSearch: true,
    // onSearch: onPkgNameSearch,
    // onClear: () => setOptions([]),
    notFoundContent: notFound,
    value,
    style: { width: '100%', ...style },
    onChange: handleChange,
    ...rest,
  };

  return <Select defaultValue={value} {...finalProps} />;
};

export default SelectDatapkg;
```

**Comment by siyi98** [comment]
我这里无法复现

**Comment by hes-zhu** [comment]
@siyi98 有点诡异的是，如果有意覆盖了库里重名的组件，addons会有值，但是自定义的组件且不与库里组件重名，则addons仍然没有值，我不确定这是否是一个正常的行为，以下链接是我的demo代码，烦请看一看（我没有引入样式文件，对于样式不必在意）：
https://codesandbox.io/s/red-rgb-jirg1y?file=/src/widgets/index.js

**Comment by siyi98** [comment]
你用的不是ant design的组件吗

**Comment by hes-zhu** [comment]
嗯嗯，和组件无关的，我排查过，用antd一样的，addons仍然没有值

**Comment by hes-zhu** [comment]
@siyi98 怎么样啦，关于此问题，有什么进展吗？

**Comment by siyi98** [comment]
@hes-zhu 最近业务有点忙，今晚帮你看看。

**Comment by siyi98** [comment]
你有空的话，可以帮忙给这个issue提个pr：https://github.com/alibaba/x-render/issues/807

**Comment by hes-zhu** [comment]
嗯嗯，好的👌

**Comment by hes-zhu** [comment]
@siyi98 
看啦下form-render、fr-generator源码，这个我也不清楚到底属不属于一个bug，详情看下面分析

原因是自定义组件必须注入form-render才能挂载addons，我的自定义组件是在fr-generator编辑使用，渲染的时候widgets还在fr-generator上，还没有进入form-render，点击最终展示按钮(preview 控制的form-render渲染)，这个时候wigetProps才挂载addons，自定义组件才拿到addons的值。

自定义组件这个时候拿不到addons的值：
![image](https://user-images.githubusercontent.com/40056535/174282683-7956f013-fbf5-4b5f-91be-e802c6c9cf36.png)

点击展示后能获取到addons的值：
![image](https://user-images.githubusercontent.com/40056535/174282953-8582b7b9-6929-4b36-9e84-e31ceef8a3d3.png)

再看一种情况，如果用自定义组件去覆盖默认组件，则会直接打印出addons:
![image](https://user-images.githubusercontent.com/40056535/174285018-0aaf4874-9a55-44b3-91d5-e53e60126ed3.png)
这里可以把打印拆分为初次渲染的前三次打印，拖入节点后的打印，拖入节点后的打印又分为有值和无值的打印
前三个打印是初次加载默认重名组件时候的打印，`socket连接成功`下面的打印是拖入节点后的打印，可以拆解成有值和无值的打印，我猜测有值的是form-render那边渲染组件的打印，无值的是fr-generator渲染组件的打印（这个时候没有点击展示按钮，符合上述分析）
【关于打印次数的问题，不用纠结，这是React dev开发时的问题，会多次渲染，prod不会，详情官方文档有描述】
点击最终展示：
![image](https://user-images.githubusercontent.com/40056535/174291100-325765f7-37f3-4e17-ac2a-1b92cc8d6ccb.png)


```js
// fr-generator Provider文件
import {
  widgets as defaultWidgets,
} from 'form-render';

const _widgets = { ...defaultWidgets, ...widgets, list };
// defaultWidgets 是form-render 直接引入的默认组件
// widgets是我们的自定义组件
```
猜测结果：自定义组件覆盖默认组件后会在form-render、fr-generator都渲染，不覆盖默认组件的自定义组件只会在fr-generator渲染

令我困惑的是这张图，在最终展示下，我点击了没有覆盖默认组件的自定义组件：
结果，没有覆盖默认组件的自定义组件正常打印没问(selectDatapkg.tsx)，但是为什么那个覆盖默认组件的自定义组件(select.tsx)也在打印，我没有对他进行渲染操作，它好像不应该渲染。

时间原因，我后面再看看为什么...

期待：
1. 自定义组件和默认组件的行为能保持一致(不知道从你们的角度看，它们是否应该行为保持一致)
2. 那个渲染问题很诡异，从我使用的角度来看，它似乎不应该在那个时机触发渲染打印
