### ISSUE TITLE
《表单设计器》如何在组件配置中获取表单配置的某一项的值

### ISSUE THREAD

**Issue by z2131023** [alibaba/x-render#813]
### 期望的新功能 (describe the expected new feature)
![image](https://user-images.githubusercontent.com/22854141/174204676-b2ec9c58-2384-47bd-a870-8ee01e7563f1.png)
![image](https://user-images.githubusercontent.com/22854141/174204687-aa4826a4-862e-4254-a871-6e9c4b355a84.png)

### 简述一下使用场景，便于开发者更好理解新功能的必要性 (describe your scenario for us to understand the need)
在组件配置中的《请选择长度》自定义下拉组件的选项要依赖于表单配置中的《整体布局》组件的选项值，如《整体布局》选中一行三列，那么《请选择长度》的值为 【1，2，3】 即 占整行长度的x分之一，我可以通过schema的width属性实现，但是现在不知道怎么在组件配置中获取表单配置中的值

**Comment by siyi98** [comment]
「组件配置」和「表单配置」是两个独立的 `FormRender`  实例，目前是拿不到的

**Comment by lhbxs** [comment]
老的设计器已经不在迭代了，有兴趣的话，可以关注一下讨论组，关于新设计器的迭代和进展，同时也欢迎在讨论里面提想法！

**Comment by liyuyu0929** [comment]
> 老的设计器已经不在迭代了，有兴趣的话，可以关注一下讨论组，关于新设计器的迭代和进展，同时也欢迎在讨论里面提想法！

加不进去群啊
