### ISSUE TITLE
自定义的组件的setting中，增加了一些配置项，如果让配置项相互联动？

### ISSUE THREAD

**Issue by wangmhaha** [alibaba/x-render#816]
我这里有一个需求，我需要开发一个自定义获取数据源的的组件，她的配置项中有几项自定义配置
<img width="933" alt="image" src="https://user-images.githubusercontent.com/23375506/174579525-0e8fd6f6-5678-4ceb-b29c-4154b1d20fa8.png">
这两个下拉的选项都是需要通过请求获取动态的数据，且下面的元数据选择项是需要根据上面的数据源选择结果来获取的。
怎么动态的修改setting中的配置项？在自定义的组件中我也不能获取到schema

**Comment by laosandegudai** [comment]
初始化的时候给数据源赋值，两个组件得联动了。

**Comment by wangmhaha** [comment]
我已在初始化的时候赋值了，但是下面这个元数据的下拉框的数据是要依赖上面选择的的数据源的，数据源onChange时去请求元数据的数据，但是拿的到数据我怎么赋值进去呢，我已经尝试了很多方法了，感觉没有太好的办法

**Comment by laosandegudai** [comment]
跟你初始化赋值一样，绑定一个state，更新这个state就行了。

**Comment by laosandegudai** [comment]
是的。其实可以透传props。

**Comment by wangmhaha** [comment]
<img width="787" alt="image" src="https://user-images.githubusercontent.com/23375506/174612639-16d84fe6-d0bd-49ae-97c8-706fa08fbd60.png">
这种方法不行，onChange的时候我去获取tableData的值，更新state，一是数据这个时候加载不了，二是会导致整个组件重渲染，之前拖入的表单项也全部没有了，又变成了一个初始化空的编辑器

**Comment by laosandegudai** [comment]
你试试表单透传进去，用依赖处理试试。

**Comment by wangmhaha** [comment]
我有点不是太明白你的意思，能详细一点吗？谢谢

**Comment by laosandegudai** [comment]
> 不行的，我在这里都拿不到addons, 是undefined

可以的，你看看自定义组件的文档，
![image](https://user-images.githubusercontent.com/17979159/174736800-b763dc6c-f3a0-4231-82e2-957b13dacf25.png)

**Comment by wangmhaha** [comment]
能贴一下你的代码吗？我在自定义的组件中的addons一直是undefined

**Comment by laosandegudai** [comment]
看这里https://xrender.fun/form-render/advanced/widget
![image](https://user-images.githubusercontent.com/17979159/174743469-15afa703-6a31-4cb6-aeb8-7f4d6fd3e492.png)
k框里面有你想要的所有数据。

**Comment by wangmhaha** [comment]
文档我都看了 ，我这里是在具体的配置表单项里的setting里，我看了源码，配置这里确实也是通过FormRender来生成的
我的问题是：
 在自定义的组件中我拿不到addons，是undefined,  也就没有办法使用addons上的方法，例如setSchemaByPath等。
<img width="709" alt="image" src="https://user-images.githubusercontent.com/23375506/174744882-f92a2033-d000-4e78-9edc-eea59cbb0018.png">
<img width="1124" alt="image" src="https://user-images.githubusercontent.com/23375506/174745071-73ac8eab-a5c3-404d-91a4-ab80d5a40699.png">

**Comment by laosandegudai** [comment]
> 文档我都看了 ，我这里是在具体的配置表单项里的setting里，我看了源码，配置这里确实也是通过FormRender来生成的 我的问题是： 在自定义的组件中我拿不到addons，是undefined, 也就没有办法使用addons上的方法，例如setSchemaByPath等。 <img alt="image" width="709" src="https://user-images.githubusercontent.com/23375506/174744882-f92a2033-d000-4e78-9edc-eea59cbb0018.png"> <img alt="image" width="1124" src="https://user-images.githubusercontent.com/23375506/174745071-73ac8eab-a5c3-404d-91a4-ab80d5a40699.png">

不知道你咋搞的，如果你拿不到addons，说明这个组件你那里不正常，可能是你写的有问题。

**Comment by siyi98** [comment]
> 问题

你的form-render是什么版本？
