### ISSUE TITLE
Generator  Settings 能否扩展？

### ISSUE THREAD

**Issue by laosandegudai** [alibaba/x-render#817]
### 期望的新功能 (describe the expected new feature)
目前当一些默认组件的右侧设置不能满足时，是否能扩展而不是替代，发现写了自己的后默认的就没了。

### 简述一下使用场景，便于开发者更好理解新功能的必要性 (describe your scenario for us to understand the need)
是否能扩展settings而不是写了自己的就把默认的替代了。

**Comment by sunbowq** [comment]
@laosandegudai 可以扩展的
![image](https://user-images.githubusercontent.com/57241855/174606892-0596754e-dfd3-4234-aa3c-a683bc15bae2.png)

**Comment by laosandegudai** [comment]
> @laosandegudai 可以扩展的 ![image](https://user-images.githubusercontent.com/57241855/174606892-0596754e-dfd3-4234-aa3c-a683bc15bae2.png)

如何操作的？自己扩展会覆盖默认的设置，泥土里面也时一样的。
