### ISSUE TITLE
 希望支持json schema 草案4中 additionalproperties属性

### ISSUE THREAD

**Issue by hedyma86** [alibaba/x-render#820]
### 期望的新功能 (describe the expected new feature)
期望支持 json schema 草案4中 additionalproperties属性

### 简述一下使用场景，便于开发者更好理解新功能的必要性 (describe your scenario for us to understand the need)

场景是：需要用户自定义一些k-v字段。
比如需求的model json是{
 name:xxx,
 age:xxx,
custom:{
  key1:value1,
 keyx:valuex
....
}
}
其中custorm内的字段是需要用户自定义的。

参考 https://rjsf-team.github.io/react-jsonschema-form/ 中 additionalProperties 的效果。

**Comment by siyi98** [comment]
需求场景能再详细点吗

**Comment by hmzzrcs** [comment]
对后端来说，是map类型，例如 map<string,string> , map<string,object>

**Comment by siyi98** [comment]
用来做什么呢，说个场景看看

**Comment by hmzzrcs** [comment]
go:map[string]string
java: map<string,string>

{
   "name1":"value1","name2":"value2"
}

go: map[string]struct
java: map<string,class>

{
 "name1":{...},"name2":{...}
}

**Comment by hmzzrcs** [comment]
> `additionalProperties`这个属性用来做什么，给后端传递数据？修改表单样式？

指定 map[string]struct 里，这个struct的结构

**Comment by siyi98** [comment]
> > `additionalProperties`这个属性用来做什么，给后端传递数据？修改表单样式？
> 
> 指定 map[string]struct 里，这个struct的结构

laigePR？

**Comment by hmzzrcs** [comment]
https://rjsf-team.github.io/react-jsonschema-form/

**Comment by siyi98** [comment]
> https://rjsf-team.github.io/react-jsonschema-form/

看了下这个效果，感觉和form-render内置的list很像啊

**Comment by siyi98** [comment]
归档到这里： #770
