### ISSUE TITLE
locale=‘en’ 无效

### ISSUE THREAD

**Issue by hedyma86** [alibaba/x-render#822]
**1.依赖仓库的版本(Dependencies versions)**：

- react：17.0.0
- antd：4.14.0
- "form-render": "^1.13.7-beta.0"

**2.问题描述(Bug description)**：

**3.最小复现 demo(Reproduction demo)**：
import enUS from 'antd/lib/locale/en_US';

<
                    form={form}
                    schema={schema}
                    onFinish={onFinish}
                    configProvider={{locale:enUS}}
                />

直接设置 locale=“en'不生效 ，用configProvider生效了。但对象数组中的”新增一条“按钮还是中文，应该怎么解？

**Comment by siyi98** [comment]
原因：目前ConfigProvider影响的是antd组件的设置，“新增一条”属于FormRender内部的文案，目前不受ConfigProvider的影响。
action：我下周发个版，支持下FR内部的国际化。

**Comment by siyi98** [comment]
v1.13.14 版本，可以通过修改 `schema` 中的`props`，透传文案。
