### ISSUE TITLE
tabslist draggable 传入无效

### ISSUE THREAD

**Issue by gdc1998** [alibaba/x-render#833]
**1.依赖仓库的版本(Dependencies versions)**：

- react：
- form-render：1.13.8
- table-render: 
- antd：

**2.问题描述(Bug description)**：
tabslist draggable 传入无效 发现源码里并未用到draggable 字段

**3.最小复现 demo(Reproduction demo)**：

form-render demo https://codesandbox.io/s/unruffled-flower-jl78h
table-render demo https://codesandbox.io/s/sweet-euler-bdoty
fr-generator demo https://codesandbox.io/s/s13sh

**Comment by siyi98** [comment]
之前加了有点问题，暂时注释掉了
