### ISSUE TITLE
希望tableList columns支持width配置

### ISSUE THREAD

**Issue by gdc1998** [alibaba/x-render#835]
### 期望的新功能 (describe the expected new feature)
希望tableList columns支持width配置
### 简述一下使用场景，便于开发者更好理解新功能的必要性 (describe your scenario for us to understand the need)
如最左侧id的展示/或拖拽排序自定义组件希望固定为30px 
最小改动 如下 
 width: schema.width || FIELD_LENGTH,

**Comment by siyi98** [comment]
这么简单的改动，来个PR吧，勇士
