### ISSUE TITLE
表单设计器中的getId，大佬们是怎么保证最后排序的顺序的

### ISSUE THREAD

**Issue by gepeng123** [alibaba/x-render#836]
### 简述一下使用场景，便于开发者更好理解新功能的必要性 (describe your scenario for us to understand the need)
我使用getId，默认的是name => ${name}_${nanoid(6)}生成的ID，因为是随机生成的，所以在保存时会时乱序的，大佬们都是怎么处理这个问题的呢

**Comment by F-loat** [comment]
对象 key 的顺序一般是可以保证的，可以看下是不是服务端保存的问题，特殊场景可以使用 order 属性额外进行顺序控制
