### ISSUE TITLE
schema修改后，FormData已删除组件数据残留

### ISSUE THREAD

**Issue by hedyma86** [alibaba/x-render#838]
**1.依赖仓库的版本(Dependencies versions)**：

- react：
- form-render：
- table-render: 
- antd：

**2.问题描述(Bug description)**：

schema修改后，用form.setValues({})后，查看form.getValues()是正确的，但onfinish提交获取的formData还是有之前数据。求解。

**3.最小复现 demo(Reproduction demo)**：

https://xrender.fun/playground在官网中可重现。
官网：最简样例中。
1、简单输入框中输入1，查看Data
{
  "input": "1",
  "listName2": []
}
2、切换到schema删除简单输入框字段
3、切换回Data修改其他数据，Data中 input:"1"始终存在。

**Comment by siyi98** [comment]
用 `removeHiddenData` 属性删除：https://xrender.fun/form-render/api/props
