### ISSUE TITLE
form-render checkbox设置default不生效

### ISSUE THREAD

**Issue by xiaohutongxue2** [alibaba/x-render#853]
**1.依赖仓库的版本(Dependencies versions)**：

- react：
- form-render：
- antd：

**2.问题描述(Bug description)**：
checkbox设置default后没有默认选中

**3.最小复现 demo(Reproduction demo)**：
配置
![image](https://user-images.githubusercontent.com/22583322/178646119-5d1e73a7-c2bb-478e-a8e7-a6f3e9393f2b.png)

展示
![image](https://user-images.githubusercontent.com/22583322/178646185-7f8dd113-ae57-46c9-bc35-ca03923cbe98.png)

**Comment by psycholali** [comment]
你好 我这边没有复现这个问题 请问你formrender用的哪个版本？你试试我的schema看看？
{
    "title": "对象",
    "type": "object",
    "displayType": "row",
    "properties": {
        "check": {
            "title": "多选",
            "type": "array",
            "items": {
                "type": "string"
            },
            "enum": [
                "a",
                "b"
            ],
            "enumNames": [
                "wordingA",
                "wordingB"
            ],
            "default": ["a"]
        }
    }
}
![image](https://user-images.githubusercontent.com/9802379/178976892-756afbed-b833-4c44-9362-6ccc5bcb6001.png)
