### ISSUE TITLE
渲染问题，表单在线上/预发环境输入明显卡顿 ，代理到本地资源卡顿消失

### ISSUE THREAD

**Issue by gdc1998** [alibaba/x-render#854]
**1.依赖仓库的版本(Dependencies versions)**：

- react：17.0.47
- form-render：1.9.13
- table-render: 
- antd：4.21.5

**2.问题描述(Bug description)**：
1. 表单改变一次，form 实例所在的组件会render3次
2. 当表单有array结构时，线上预发输入明显卡顿  fr自带的list组件 与自定义的都有同样的问题 ，资源代理到本地卡顿会消失

**3.最小复现 demo(Reproduction demo)**：

form-render demo https://codesandbox.io/s/unruffled-flower-jl78h
table-render demo https://codesandbox.io/s/sweet-euler-bdoty
fr-generator demo https://codesandbox.io/s/s13sh

**Comment by siyi98** [comment]
贴下代码？

**Comment by chenqien** [comment]
同样有这个问题，官方示例也是一样的。

**Comment by gdc1998** [comment]
> 以官网demo列表的展示 对象数组为例。 当数据增加至20条左右input长按输入/删除 有明显卡顿 ，若为两个list结构 没10条就会出现卡顿 （本地复现）

自定义为例
https://codesandbox.io/s/peaceful-driscoll-b9nick?file=/src/App.js
list数据增加至10条左右 第一个输入框输入长按删除 明显卡顿（预发复现，本地未卡顿）

**Comment by siyi98** [comment]
重复渲染的次数太多了...本地也能复现...目前设计上存在一些问题，是想在XRender2.0解决的

**Comment by StrongerD** [comment]
> 重复渲染的次数太多了...本地也能复现...目前设计上存在一些问题，是想在XRender2.0解决的，我先归档到discussion里： #770

这个问题目前解决了吗 为什么form-render某个组件的onChange 会导致整个表单重新渲染呢
