### ISSUE TITLE
通过 form-render生成的schema提交的数据，如何在服务端进行校验？

### ISSUE THREAD

**Issue by lys623** [alibaba/x-render#857]
### 期望的新功能 (describe the expected new feature)
通过 form-render生成的schema，如何在用户提交数据的时候在服务端进行校验？没看到相关资料
### 简述一下使用场景，便于开发者更好理解新功能的必要性 (describe your scenario for us to understand the need)
如题，生成的表单一般是to c的，暴露给用户，在服务端是否可以对前端提交上来的数据进行校验？

使用阿里的formily生成的schemaData ，是可以在后端nodejs进行检验的；
![image](https://user-images.githubusercontent.com/4364314/180194986-d21b3f8e-dadb-487b-92c2-1f368130155d.png)

![image](https://user-images.githubusercontent.com/4364314/180195545-0bb9b0cb-2050-4ac9-8981-809fb17e4a49.png)

**Comment by siyi98** [comment]
没明白，什么叫「在用户提交数据的时候在服务端进行校验」

**Comment by lys623** [comment]
也就是一份schema 和一份valueData，是否支持使用nodejs在服务器端进行检验，valueData是否符合schema设置的检验规则；

**Comment by siyi98** [comment]
暂不支持这样的能力

**Comment by wangxinyu666666** [comment]
> ### 期望的新功能 (describe the expected new feature)
> 通过 form-render生成的schema，如何在用户提交数据的时候在服务端进行校验？没看到相关资料
> 
> ### 简述一下使用场景，便于开发者更好理解新功能的必要性 (describe your scenario for us to understand the need)
> 如题，生成的表单一般是to c的，暴露给用户，在服务端是否可以对前端提交上来的数据进行校验？
> 
> 使用阿里的formily生成的schemaData ，是可以在后端nodejs进行检验的； ![image](https://user-images.githubusercontent.com/4364314/180194986-d21b3f8e-dadb-487b-92c2-1f368130155d.png)
> 
> ![image](https://user-images.githubusercontent.com/4364314/180195545-0bb9b0cb-2050-4ac9-8981-809fb17e4a49.png)

你好，我和你遇到了一样的问题，请问您是怎么通过formily在服务端进行校验的？
