### ISSUE TITLE
能否支持remix

### ISSUE THREAD

**Issue by tingfeng-key** [alibaba/x-render#859]
### 期望的新功能 (describe the expected new feature)
可以在remix中使用x-render

**Comment by siyi98** [comment]
现在出了什么问题？

**Comment by tingfeng-key** [comment]
报错提示：不能引入less

**Comment by siyi98** [comment]
emmm...XRender没有单独引入antd.less

**Comment by siyi98** [comment]
@tingfeng-key 貌似官方给出了解决方案：https://remix.run/docs/en/v1/guides/styling#css-preprocessors

**Comment by tingfeng-key** [comment]
好的，我会试试这种方案

**Comment by siyi98** [comment]
或者使用 `Umi` or `Vite`，社区更成熟一些，哈哈
