### ISSUE TITLE
将必填项删除, 然后切换到最终展示模式, 再切回到编辑模式, 所有的在编辑组件不能选中, 整个编辑器呈现一种卡死状态

### ISSUE THREAD

**Issue by jisao** [alibaba/x-render#864]
![6F94E206-8C2B-405D-9439-5A83008C1BDA](https://user-images.githubusercontent.com/27863425/182778173-53d0f1b6-7ff2-4886-bca6-e74a2b8cc066.png)
![8096ECDD-8814-4CAF-A12C-9AC8C6E7AB99](https://user-images.githubusercontent.com/27863425/182778192-0e4ebc57-45ad-4b2a-8f43-317ba1965bcf.png)
提一个建议, 能不能给个方法, 统一来获取最终导出的schema哪些必填字段没有填写, 现在编辑器是, 只要必填字段没填, 就不能插入新的组件

**Comment by F-loat** [comment]
暂时可以通过 validation={false} 禁用表单校验，但需要手动保证 schema 的完整性
