### ISSUE TITLE
样式相关

### ISSUE THREAD

**Issue by jile1997** [alibaba/x-render#867]
### 期望的新功能 每个组件可否添加一个样式配置  整个schema可以支持layout布局

![image](https://user-images.githubusercontent.com/58684242/183590366-5edbf3d6-4608-43f6-b273-8c1318015d83.png)
![image](https://user-images.githubusercontent.com/58684242/183590503-8649cd87-6618-4e49-ac08-b6cf0c3e0bc0.png)
像这样多一个style的配置项,这样可以灵活的布局这个对象

用表单编辑器的时候，可以和栅格系统结合吗
像这个网站https://react-grid-layout.github.io/react-grid-layout/examples/0-showcase.html
上面这个效果是https://github.com/react-grid-layout/react-grid-layout
像这样一样，这样排版好，用表单编辑器导出的时候带上布局的样式
![image](https://user-images.githubusercontent.com/58684242/183591399-962042a4-20cb-46da-b7cc-07bfd3c77dbd.png)

**Comment by siyi98** [comment]
支持填写  `className`  的
