### ISSUE TITLE
upload 组件其他属性无法使用

### ISSUE THREAD

**Issue by bingege12138** [alibaba/x-render#870]
**1.依赖仓库的版本(Dependencies versions)**：

- react："^16.7.0"
- form-render："^1.13.11"
- table-render: 
- antd：^4.16.6

**2.问题描述(Bug description)**： upload 无法使用antd 自带的其他属性

代码  const elements = [
  {
    text: '附件',
    name: 'UploadFile',
    schema: {
      title: '附件',
      type: 'string',
      widget: "UploadFile",
      props: {
        action: '/api/v1/appraisal/settlement_order/uploadReceipt',
        headers: { Authorization: window.localStorage.Authorization || "" },
      }
    },
    setting: {
    },
  },
];

form-render demo https://codesandbox.io/s/unruffled-flower-jl78h
table-render demo https://codesandbox.io/s/sweet-euler-bdoty
fr-generator demo https://codesandbox.io/s/s13sh

**Comment by shinneyou** [comment]
可以自己基于upload组件外面包裹一层，通过schema的props把需要的属性传进去，然后解析出来挂载upload组件上
```javascript
const uploadWrap = (props) => {
    {onchange, ...otherProps} = props;
    <Upload {...otherProps}/>
}
```

**Comment by bingege12138** [comment]
好的谢谢

**Comment by iceberg211** [comment]
@shinneyou  这个包装的组件是作为自定义组件加在widgets属性中吗?怎么去使用呢?
