### ISSUE TITLE
希望form-render可以暴露出校验api 供手动调用

### ISSUE THREAD

**Issue by Jocelyn329** [alibaba/x-render#876]
简述一下使用场景：
 比如：当组件的必填变为非必填的时候 由于未进行校验 页面仍然会存在之前的校验信息
尝试使用 setErrorFields 以及 removeErrorField手动清理 但是并未生效
希望可以暴露出validate api  方便在动态修改组件schema的时候 可以手动调用api进行form校验 而不是必须在submit的时候才能整体校验

**Comment by siyi98** [comment]
手动触发校验？

**Comment by Jocelyn329** [comment]
> 手动触发校验？

是的呀 因为这边有动态修改schema的情况 但是使用 setErrorFields 以及 removeErrorField手动清理 未生效 所有希望可以暴露出valid的api 在我schema 修改的时候 手动触发一遍校验规则

**Comment by siyi98** [comment]
这里：https://xrender.fun/form-render/api/props#validatefields

**Comment by Siri-yxw** [comment]
> @Jocelyn329 这里：https://xrender.fun/form-render/api/props#validatefields

![image](https://github.com/alibaba/x-render/assets/44385227/5ba2efb5-8849-4237-85bf-6b6e9fc848a9)

**Comment by Siri-yxw** [comment]
> 简述一下使用场景： 比如：当组件的必填变为非必填的时候 由于未进行校验 页面仍然会存在之前的校验信息 尝试使用 setErrorFields 以及 removeErrorField手动清理 但是并未生效 希望可以暴露出validate api 方便在动态修改组件schema的时候 可以手动调用api进行form校验 而不是必须在submit的时候才能

> 简述一下使用场景： 比如：当组件的必填变为非必填的时候 由于未进行校验 页面仍然会存在之前的校验信息 尝试使用 setErrorFields 以及 removeErrorField手动清理 但是并未生效 希望可以暴露出validate api 方便在动态修改组件schema的时候 可以手动调用api进行form校验 而不是必须在submit的时候才能整体校验

解决了吗，我也需要这个，请问怎么解决的呢

**Comment by Siri-yxw** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
