### ISSUE TITLE
hidden 中同时使用 rootValue 和 formData 时会报错

### ISSUE THREAD

**Issue by fengomgod** [alibaba/x-render#877]
**1.依赖仓库的版本(Dependencies versions)**：

- react：
- form-render：
- table-render: 
- antd：

**2.问题描述(Bug description)**：
在 array 的子属性中使用 hidden 属性来控制列表中组件的联动时， 如果在语句中同时使用了 rootValue 和 formData 时控制台会报错， 并且语句也无法正常生效， 但单独使用 rootValue 或者 formData 时都是没有问题的

**3.最小复现 demo(Reproduction demo)**：
可以在 formRender 的 playGround 里使用这段 schema
**最下方**的 hidden 条件中同时使用了 rootValue 和 formData ， 此时控制台会报错， 且语句也会失效
{
  "type": "object",
  "properties": {
    "case1": {
      "title": "整体隐藏",
      "type": "object",
      "properties": {
        "showMore": {
          "title": "显示更多",
          "type": "boolean"
        },
        "x1": {
          "title": "输入框1",
          "type": "string",
          "hidden": "{{!rootValue.showMore}}"
        },
        "x2": {
          "title": "输入框2",
          "type": "string",
          "hidden": "{{!rootValue.showMore}}"
        }
      }
    },
    "case2": {
      "title": "选项联动",
      "type": "object",
      "properties": {
        "bi": {
          "title": "汇款币种",
          "type": "string",
          "enum": [
            "rmb",
            "dollar"
          ],
          "enumNames": [
            "人民币",
            "美元"
          ]
        },
        "inputName": {
          "title": "金额",
          "description": "{{rootValue.bi === 'dollar' ? '一次汇款不超过150美元':'一次汇款不超过1000元'}}",
          "type": "string",
          "props": {
            "addonBefore": "{{rootValue.bi === 'dollar'? '$':'￥'}}",
            "addonAfter": "{{rootValue.bi === 'dollar'? '美元':'元'}}"
          }
        }
      }
    },
    "case3": {
      "title": "列表/显示不同组件",
      "type": "object",
      "properties": {
        "ruleList": {
          "title": "球员筛选",
          "type": "array",
          "items": {
            "type": "object",
            "properties": {
              "attr": {
                "title": "标准",
                "type": "string",
                "widget": "select",
                "enum": [
                  "goal",
                  "league"
                ],
                "enumNames": [
                  "入球数",
                  "所在联盟"
                ],
                "width": "40%"
              },
              "relation": {
                "title": "关系",
                "type": "string",
                "enum": [
                  ">",
                  "<",
                  "="
                ],
                "widget": "select",
                "hidden": "{{rootValue.attr === 'league'}}",
                "width": "20%"
              },
              "goal": {
                "title": "入球数",
                "type": "string",
                "rules": [
                  {
                    "pattern": "^[0-9]+$",
                    "message": "输入正确得分"
                  }
                ],
                "hidden": "{{rootValue.attr === 'league'}}",
                "width": "40%"
              },
              "league": {
                "title": "名称",
                "type": "string",
                "enum": [
                  "a",
                  "b",
                  "c"
                ],
                "enumNames": [
                  "西甲",
                  "英超",
                  "中超"
                ],
                "widget": "select",
                "hidden": "{{formData.case1.showMore || rootValue.attr !== 'league'}}",
                "width": "40%"
              }
            }
          }
        }
      }
    }
  }
}

**Comment by siyi98** [comment]
统一用`formData`吧
