### ISSUE TITLE
widgets挂载完之后不更新数据

### ISSUE THREAD

**Issue by xiaomonvguoguo** [alibaba/x-render#878]
自定义了一个组件，并且需要通过widget给自定义的组件传值，页面刚进去的时候需要传的接口还没加载完，但是组件已经挂载完，穿过去的数据是空，等数据有的时候，值并不会更新
外面传值的代码：需要把recycleLinkCode传过去，在自定义组件里面调用
    widgets={{ map: (mapProps: any) => <MapModel {...{ isHiddeModal: true, ...mapProps }} />,
            CloseConfiguration: (mapProps: any) => <CloseConfiguration {...{ recycleLinkCode: detail?.baseDataVo?.recycleLinkCode, ...mapProps }} /> 
          }}
自定义组件的代码
 useEffect(() => {
    const {api} = schema;
    if (api == 'recyclingLinkStatus') {
      recyclingLinkStatus({ linkCode: recycleLinkCode}).then((res) => {
        const enums = []
        const enumNames = []
        res.map((item) => {
          enums.push(item.code)
          enumNames.push(item.name)
        })
        if (Array.isArray(enums)) {
          const enumsOptions = enums.map((item, inde) => {
            let label = enumNames && Array.isArray(enumNames) ? enumNames[inde] : item
            const isHtml = typeof label === 'string' && label[0] === '<'
            if (isHtml) {
              label = <span dangerouslySetInnerHTML={{ __html: label }} />
            }
            return { label:`${label}(${item})`, value: item }
          })
          setOptions(enumsOptions || [])
        }
      })
    }
    const $value = toObject(value)
    setSelectVal($value)
    setTimeOptions($value?.selectObj)
  }, [value,recycleLinkCode])

**Comment by siyi98** [comment]
1.`formData`的更新才会触发表单的重新渲染，但是`recycleLinkCode`不是表单值，所以不能用`form.setValues`和`form.setValueByPath`来修改表单值；
2. 触发组件重新渲染，可以试试这样写：  `useMemo(()=><CloseConfiguration recycleLinkCode={recycleLinkCode}  />,[recycleLinkCode])`

**Comment by xiaomonvguoguo** [comment]
1.我想用form render的watch也不可以么？
另一种情况我用watch是起作用的，如下。
 <FormRender
          schema={
            type === 'resolve'
              ? {
                ...propertiesType,
                properties: propertiesAuditModal
              }
              : propertiesType
          }
          form={formModal}
          widgets={{ businessTypeId: RecycleBusinessTypeList, recyclingLink: recyclingLinkList }}
          watch={{
            businessTypeId: (val: any) => {
              fetchBusinessDimensionList(val || mergeResultModal?.businessTypeId)
              // 切换业务线类型，重置维度信息
              if (val && val != mergeResultModal?.businessTypeId) {
                // firstResetModalIndex += 1
                // 切换业务线类型，重置维度信息
                Object.entries(resetDimen).forEach(([key]) => {    
                  formModal.setValueByPath(key, [])
                })
              }
            }
          }}
          beforeFinish={beforeFinish}
        />

**Comment by xiaomonvguoguo** [comment]
1.我想用form render的watch也不可以么？
另一种情况我用watch是起作用的，如下。
 <FormRender
          schema={
            type === 'resolve'
              ? {
                ...propertiesType,
                properties: propertiesAuditModal
              }
              : propertiesType
          }
          form={formModal}
          widgets={{ businessTypeId: RecycleBusinessTypeList, recyclingLink: recyclingLinkList }}
          watch={{
            businessTypeId: (val: any) => {
              fetchBusinessDimensionList(val || mergeResultModal?.businessTypeId)
              // 切换业务线类型，重置维度信息
              if (val && val != mergeResultModal?.businessTypeId) {
                // firstResetModalIndex += 1
                // 切换业务线类型，重置维度信息
                Object.entries(resetDimen).forEach(([key]) => {    
                  formModal.setValueByPath(key, [])
                })
              }
            }
          }}
          beforeFinish={beforeFinish}
        />

**Comment by siyi98** [comment]
如果watch能解决你的问题，也可以

**Comment by xiaomonvguoguo** [comment]
谢谢了，我研究一下
