### ISSUE TITLE
官网链接挂了，有人处理吗

### ISSUE THREAD

**Issue by lys623** [alibaba/x-render#879]
![image](https://user-images.githubusercontent.com/4364314/185829910-03cf40e0-bbeb-4124-ad29-6deab5222d57.png)

**Comment by siyi98** [comment]
没挂呀

**Comment by siyi98** [comment]
打不开的话访问这个：https://xrender.vercel.app/

**Comment by lys623** [comment]
> 打不开的话访问这个：https://xrender.vercel.app/

这个也打不开 ；

https://x-render.gitee.io/table-render 这个可以打开，但是会重定向到https://xrender.fun/ ，然后 https://xrender.fun/打不开，能否取消重定向？ @siyi98
