### ISSUE TITLE
vscode 表单设计工具无法更改ID

### ISSUE THREAD

**Issue by garfeng** [alibaba/x-render#882]
**1.依赖仓库的版本(Dependencies versions)**：

- react：
- form-render： https://marketplace.visualstudio.com/items?itemName=F-loat.vscode-plugin-fr-schema
- table-render: 
- antd：
- vscode:  1.70.2(user setup)
![image](https://user-images.githubusercontent.com/19792314/186085157-4b6053da-b0d7-47aa-91e1-e8c941b2c1c8.png)

**2.问题描述(Bug description)**：

vscode 表单设计工具中的ID无法更改. 

![1661235570893](https://user-images.githubusercontent.com/19792314/186084814-e3773562-5c27-4c44-b0dc-af53584c8718.png)

**3.最小复现 demo(Reproduction demo)**：

无

**Comment by F-loat** [comment]
新版插件已修复，vscode 拓展管理中更新即可
