### ISSUE TITLE
能够生成一个像antd中tabs切换的组件吗

### ISSUE THREAD

**Issue by bartflyian** [alibaba/x-render#889]
### 期望的新功能 (describe the expected new feature)
生成一个像antd中tabs切换的组件
### 简述一下使用场景，便于开发者更好理解新功能的必要性 (describe your scenario for us to understand the need)
生成一个像antd中tabs切换的组件

**Comment by siyi98** [comment]
和表单相关的还是 协议驱动渲染的tabs？

**Comment by bartflyian** [comment]
协议驱动渲染的,每个tab可以承载不同的表单或组件

**Comment by siyi98** [comment]
看看这个 `tabList`  是不是满足你的需求：https://xrender.fun/form-render/advanced/list-display

**Comment by LilianShi** [comment]
所以，初步生成一个antd tabs的数据应该是啥样的呀？楼主弄出来了吗
