### ISSUE TITLE
按照如下图示点击组件出现白屏，影响界面使用

### ISSUE THREAD

**Issue by guoyuanYYDS** [alibaba/x-render#890]
【必现】按照图中顺序点击输入出现白屏
![企业微信截图_16615086109706](https://user-images.githubusercontent.com/54087726/186881729-c2a5418f-ea4c-4801-abf9-a409845ea63d.png)
![图片](https://user-images.githubusercontent.com/54087726/186881829-a14e10ad-7671-4cd3-866c-51823093a4d5.png)

**Comment by siyi98** [comment]
react什么版本

**Comment by guoyuanYYDS** [comment]
这个是在你们的官网操作也是白屏

**Comment by siyi98** [comment]
感谢反馈，已修复。
