### ISSUE TITLE
Warning: React does not recognize the `dataPath` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `datapath` instead. If you accidentally passed it from a parent component, remove it from the DOM element.

### ISSUE THREAD

**Issue by hhbusui** [alibaba/x-render#891]
**1.依赖仓库的版本(Dependencies versions)**：

![image](https://user-images.githubusercontent.com/43135111/187025279-00e61406-cf9c-4c78-87bd-e60488cb2930.png)

**2.问题描述(Bug description)**：
控制台报错：

react_devtools_backend.js:4026 Warning: React does not recognize the `dataPath` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `datapath` instead. If you accidentally passed it from a parent component, remove it from the DOM element.

![image](https://user-images.githubusercontent.com/43135111/187025335-df170f13-4900-46ff-984e-ce8201e587cc.png)

**3.最小复现 demo(Reproduction demo)**：
![image](https://user-images.githubusercontent.com/43135111/187025312-a08c11cb-a7e8-4328-9f7b-e23f6868cd58.png)

**Comment by siyi98** [comment]
现在还没兼容react18

**Comment by hhbusui** [comment]
> 现在玩游戏react18

好的 谢谢

**Comment by Veinvirus** [comment]
> 现在还没兼容react18

react17也出现了这个问题
