### ISSUE TITLE
fr-generator 什么时候正式支持react18？

### ISSUE THREAD

**Issue by zwmmm** [alibaba/x-render#894]
**1.依赖仓库的版本(Dependencies versions)**：

- react：18
- fr-generator: 2.8.0-beta.0

**2.问题描述(Bug description)**：
目前稳定版不支持 react18，beta版本虽然支持18，但是缺少部分功能，比如隐藏[表单配置](https://github.com/alibaba/x-render/blob/master/tools/schema-generator/src/components/Settings/index.jsx#L65)

希望稳定版本能支持下react18，或者beta版能支持下隐藏表单配置的功能

**Comment by siyi98** [comment]
v2.8.0 版本已支持

**Comment by zwmmm** [comment]
> v2.8.0 版本已支持

栓Q
