### ISSUE TITLE
官网经常打不开

### ISSUE THREAD

**Issue by loo100** [alibaba/x-render#896]
**1.依赖仓库的版本(Dependencies versions)**：

- react：
- form-render：
- table-render: 
- antd：

**2.问题描述(Bug description)**：

**3.最小复现 demo(Reproduction demo)**：

form-render demo https://codesandbox.io/s/unruffled-flower-jl78h
table-render demo https://codesandbox.io/s/sweet-euler-bdoty
fr-generator demo https://codesandbox.io/s/s13sh

**Comment by siyi98** [comment]
科学上网一下，或者访问这个：https://alibaba.github.io/x-render/
