### ISSUE TITLE
descWidget 传入 schema.description

### ISSUE THREAD

**Issue by lucifan** [alibaba/x-render#898]
### 期望的新功能 (describe the expected new feature)

使用自定义组件将 schema.description 的内容通过额外的交互展示给用户

### 简述一下使用场景，便于开发者更好理解新功能的必要性 (describe your scenario for us to understand the need)

看到新版本（v1.13.14）支持设置 `descWidget`，但是没有给 `descWidget` 传入任何 props（至少传入 `schema.description`），这样 `descWidget` 没办法根据 schema 进行动态渲染

https://github.com/alibaba/x-render/blob/master/packages/form-render/src/form-render-core/src/core/RenderField/Title.js

```
  const RenderDesc = () => {
    const Widget = widgets[schema.descWidget];
    if (Widget) {
      return <Widget />;
    }
    return null;
  };
```

我的 schema 内容

```
{
  "type": "object",
  "properties": {
    "PATH_1": {
      "id": "PATH_1",
      "title": "PATH_1",
      "widget": "keyValue",
      "placeholder": {},
      "type": "array",
      "rules": [{}],
      "description": "test_description",
      "descType": "widget",
      "descWidget": "help"
    }
  }
}
```

我理解这样只能把 description 的内容写在 descWidget 对应的组件里面了，是功能问题还是我的用法不对，求解答

**Comment by siyi98** [comment]
v1.13.15-beta.0  版本，可从`props`中获取整个schema

**Comment by lucifan** [comment]
> 更新至 v1.13.15-beta.0 版本，可从`props`中获取整个schema

已确认可用，感谢

**Comment by siyi98** [comment]
周四会发布 1.13.15  正式版
