### ISSUE TITLE
能暴露下 utils 下的方法么

### ISSUE THREAD

**Issue by zwmmm** [alibaba/x-render#902]
### 期望的新功能 (describe the expected new feature)

form-render 下的[removeHiddenFromResult](https://github.com/alibaba/x-render/blob/09009a74c10e9da851791866f13bdc6a2255755a/packages/form-render/src/form-render-core/src/utils.js) 希望能暴露出来

### 简述一下使用场景，便于开发者更好理解新功能的必要性 (describe your scenario for us to understand the need)
场景是这样的，我既要获取所有的信息，还要获取一份移除隐藏属性的内容，看到 utils 下有这个方法，所以希望能把这些方法导出给开发者使用，希望能够得到回复

**Comment by siyi98** [comment]
版本：form-render@1.13.15-beta.2
调用方法：form.getHiddenValues()
