### ISSUE TITLE
form-render无法获取到隐藏表单项的值

### ISSUE THREAD

**Issue by wangmhaha** [alibaba/x-render#903]
**1.依赖仓库的版本(Dependencies versions)**：

- react：
- form-render：
- table-render: 
- antd：

**2.问题描述(Bug description)**：

**3.最小复现 demo(Reproduction demo)**：

form-render demo https://codesandbox.io/s/unruffled-flower-jl78h
table-render demo https://codesandbox.io/s/sweet-euler-bdoty
fr-generator demo https://codesandbox.io/s/s13sh

**Comment by wangmhaha** [comment]
我使用的是form-reader的版本是1.13.7，fr-generator2.7.8
<img width="1051" alt="image" src="https://user-images.githubusercontent.com/23375506/189260135-0fb25222-d1bb-413e-92ae-9df458c1055d.png">
在fr-generator中配置了表单项并隐藏了其中两项，但是在form-reader渲染之后，提交表单的值时，确无法获取到隐藏表单项的值，在之前的版本上是可以的。我查看了源码发现在coreReader方法中 有一个判断
<img width="409" alt="image" src="https://user-images.githubusercontent.com/23375506/189260856-36d71a0f-0d2d-4ed8-b8c7-d3fd98c69cb7.png">
当是hidden时，就不进行渲染。这个是为什么呢？有可能确实有些表单项是需要隐藏的

**Comment by siyi98** [comment]
你的需求是：表单项隐藏，表单值保留？

**Comment by wangmhaha** [comment]
是的，表单项隐藏，但是能获取到表单的值。我个人觉的这个场景在实际开发中其实经常会遇见

**Comment by siyi98** [comment]
默认行为就是不删除隐藏表单项的值，你是不是配置了`removeHiddenData`

**Comment by wangmhaha** [comment]
我没有配置的

**Comment by siyi98** [comment]
给个demo仓库吧

**Comment by siyi98** [comment]
@wangmhaha 老哥有空的时候给个demo仓库吧，方便排查问题

**Comment by wangmhaha** [comment]
嗯，好的，我弄个demo仓库，然后做一个demo。这两天有点忙，我弄好了我发出来
