### ISSUE TITLE
不能 treeshaking

### ISSUE THREAD

**Issue by zwmmm** [alibaba/x-render#907]
**1.依赖仓库的版本(Dependencies versions)**：

- react：18
- form-render：1.13.14
- antd：4.23.1

**2.问题描述(Bug description)**：

引入 form-render 包不会自动 treeshaking，并且会导致antd、lodash-es 等都全量加载

<img width="852" alt="image" src="https://user-images.githubusercontent.com/30194521/190335412-3251f0c5-a22a-47d4-a24b-77c46588ef47.png">

**3.最小复现 demo(Reproduction demo)**：
https://github.com/zwmmm/form-render-test
直接npm run build 查看打包后文件

**Comment by siyi98** [comment]
配置 `babel-plugin-import` 试试：https://github.com/umijs/babel-plugin-import

**Comment by zwmmm** [comment]
是让我用 babel-plugin-import 解决 antd 的问题 还是说 form-render 也支持配置 babel-plugin-import

**Comment by siyi98** [comment]
用babel-plugin-import 解决  lodash和antd的打包问题

**Comment by siyi98** [comment]
你装 form-render@1.13.15-beta.1  版本试试，体积应该小了很多

**Comment by zwmmm** [comment]
没有任何区别

**Comment by siyi98** [comment]
年后会上线一个性能优化之后的版本，可以等一等。
