### ISSUE TITLE
复杂表格列表的多选组件值不能显示在列表中吗

### ISSUE THREAD

**Issue by lintingjie** [alibaba/x-render#908]
**1.依赖仓库的版本(Dependencies versions)**：

- react：
- form-render：
- table-render: 
- antd：

**2.问题描述(Bug description)**：
![image](https://user-images.githubusercontent.com/19299121/191447728-3a5b58d7-6541-4329-af3e-4a2d39a25281.png)

**3.最小复现 demo(Reproduction demo)**：

form-render demo https://codesandbox.io/s/unruffled-flower-jl78h
table-render demo https://codesandbox.io/s/sweet-euler-bdoty
fr-generator demo https://codesandbox.io/s/s13sh

**Comment by lintingjie** [comment]
你好，请问这个bug什么时候能解决呢，急需这个功能

**Comment by lhbxs** [comment]
1.14.13-beta.1
比较复杂的还可以通过配置 readOnlyWidget 来解决
