### ISSUE TITLE
https://alibaba.github.io/x-render/ 访问不了，麻烦修复下

### ISSUE THREAD

**Issue by lys623** [alibaba/x-render#912]
如题，
我们这边 https://xrender.fun/form-render 也访问不了；

**Comment by siyi98** [comment]
https://xrender.fun  已经做了优化处理了，你那边还不行吗？

**Comment by siyi98** [comment]
再试试：https://alibaba.github.io/x-render

**Comment by lys623** [comment]
> https://xrender.fun 已经做了优化处理了，你那边还不行吗？

不行，现在 https://alibaba.github.io/x-render/ 可以了
