### ISSUE TITLE
为什么通过mappting可以覆盖默认Object, 而通过widget不可以

### ISSUE THREAD

**Issue by lilili001** [alibaba/x-render#915]
### 期望的新功能 (describe the expected new feature)
期望widget也可以重写Object
### 简述一下使用场景，便于开发者更好理解新功能的必要性 (describe your scenario for us to understand the need)
通常业务中有些通用模块 类似卡片,  该模块头可设置标题, 描述, 展开收缩, 按钮等, 该模块内容区可放任意控件
现有的Object无法满足需求

**Comment by siyi98** [comment]
覆盖widget没有太大意义诶，相当自己写一个自定义组件了...

**Comment by lilili001** [comment]
close
