### ISSUE TITLE
为什么fr-generator使用模版填充的时候多了一个外层框？是否可以去掉

### ISSUE THREAD

**Issue by lys623** [alibaba/x-render#917]
**1.依赖仓库的版本(Dependencies versions)**：

- react：
- form-render：
- table-render: 
- antd：

**2.问题描述(Bug description)**：

如下图，模版渲染的时候，应该和我当前拼凑选得组件一样吧？这里多了一层
![image](https://user-images.githubusercontent.com/4364314/192231057-388d67af-250b-42e7-9db1-91724ae9327e.png)

**3.最小复现 demo(Reproduction demo)**：

form-render demo https://codesandbox.io/s/unruffled-flower-jl78h
table-render demo https://codesandbox.io/s/sweet-euler-bdoty
fr-generator demo https://codesandbox.io/s/s13sh

**Comment by siyi98** [comment]
这个有什么问题吗，点击「最终展示」就能看到效果

**Comment by lys623** [comment]
我理解模版应该是包括多个组件的schema？渲染的时候和我手选多个组件是一样的，现在编辑态下渲染不一样，虽然最终态是一样得，看着不舒服

**Comment by siyi98** [comment]
这个模板已经很久了，确实可以优化一下，好兄弟有什么想法，来个PR？

**Comment by lys623** [comment]
等我先熟悉xrender的源码，有设计文档什么的学习吗？ @siyi98
