### ISSUE TITLE
fr-generator优化建议

### ISSUE THREAD

**Issue by lys623** [alibaba/x-render#918]
### 期望的新功能 (describe the expected new feature)
以为是本人体验了[表单设计器](https://alibaba.github.io/x-render/generator/playground)后，发现缺失的功能或交互，记录下：
- [ ] 不支持快捷键操作，如cmd+a全选，delete删除选中的组件；
- [ ] 缺少undoredo功能；
- [ ] 缺少编辑schema的模式
- [ ] 缺少所见即所的模式（要点击“最终展示”按钮来回切换），可以搞个浮窗（或者找地方）实时显示，一般研发都有两个显示屏；

可能功能已经存在？我没有发现，欢迎指导；

**Comment by lhbxs** [comment]
当前设计器不在迭代了，后面会推出新版设计器
