### ISSUE TITLE
fr-generator  randombytes 不能解析

### ISSUE THREAD

**Issue by vicykie** [alibaba/x-render#919]
**1.依赖仓库的版本(Dependencies versions)**：

- react：>=16.8.0 || >=17.0.0
- form-render：1.13.14
- fr-generator: 2.8.0
- antd：4.23.0

**2.问题描述(Bug description)**：

Could not resolve "randombytes"
    node_modules/fr-generator/dist/index.esm.js:5763:26:
      5763 │ var randomBytes = require('randombytes'); // Generate an internal UID to make the regexp pattern harder to guess.
           ╵                           ~~~~~~~~~~~~~

  You can mark the path "randombytes" as external to exclude it from the bundle, which will remove
  this error. You can also surround this "require" call with a try/catch block to handle this
  failure at run-time instead of bundle-time.

**Comment by siyi98** [comment]
安装最新版本，已经修复了
