### ISSUE TITLE
所以colon应该怎么用呢, 在表单设计器中设置 `colon:false`  没生效:

### ISSUE THREAD

**Issue by lilili001** [alibaba/x-render#921]
所以colon应该怎么用呢, 在表单设计器中设置 `colon:false`  没生效:
![image](https://user-images.githubusercontent.com/8953052/192745438-717e27d1-923c-4fc5-a815-89bd1b4ff5a8.png)
![image](https://user-images.githubusercontent.com/8953052/192745600-7406a0c1-eab1-466e-80a9-a6b71277e632.png)
![image](https://user-images.githubusercontent.com/8953052/192745981-c487c0ef-967c-43aa-a88f-40346c62fdfb.png)

_Originally posted by @lilili001 in https://github.com/alibaba/x-render/issues/784#issuecomment-1260650157_

**Comment by lhbxs** [comment]
<FormRender
      form={form}
      colon={false}
      schema={schema}
  />
  
 目前可以全局设置，你还有单独设置的场景？
