### ISSUE TITLE
bool类型复选框为什么不显示label

### ISSUE THREAD

**Issue by lilili001** [alibaba/x-render#922]
### 期望的新功能 (describe the expected new feature)
bool类型的复选框可以显示label
### 简述一下使用场景，便于开发者更好理解新功能的必要性 (describe your scenario for us to understand the need)
业务中 复选框是和其他控件类似, 参与布局, 有时候可能一行几个控件, label不显示 会很奇怪

`{
        text: '复选框',
        name: 'checkbox',
        schema: {
            title: '复选',
            type: 'boolean',
        }
    }`

**Comment by siyi98** [comment]
应该是   `title:'复选框'`  吧

**Comment by siyi98** [comment]
有label的，感觉你的schema有问题吧，截个图看看

**Comment by siyi98** [comment]
发下你完整的schema
