### ISSUE TITLE
渲染type=block类型的时候子元素宽度达不到100%

### ISSUE THREAD

**Issue by lys623** [alibaba/x-render#928]
**1.依赖仓库的版本(Dependencies versions)**：

- react：
- form-render：
- table-render: 
- antd：

**2.问题描述(Bug description)**：
渲染type=block类型的时候，标签上需要加上class为fr-content，要不是的话里面的元素达不到100%宽度，如下图；
![image](https://user-images.githubusercontent.com/4364314/194702126-eb085401-cf52-48f8-9995-89402949fc21.png)

代码修改：
packages/form-render/src/form-render-core/src/core/RenderField/index.js:234

**3.最小复现 demo(Reproduction demo)**：

form-render demo https://codesandbox.io/s/unruffled-flower-jl78h
table-render demo https://codesandbox.io/s/sweet-euler-bdoty
fr-generator demo https://codesandbox.io/s/s13sh

**Comment by lys623** [comment]
我发现type:html的功能是包含了type:block的功能的，所以type:block是用来干嘛的？

**Comment by siyi98** [comment]
可以看看文档里的解释：http://localhost:8080/form-render/api/schema#type-1
