### ISSUE TITLE
formRender的1.13.15-beta.4 版本缺少type：block的类型定义

### ISSUE THREAD

**Issue by lys623** [alibaba/x-render#929]
**1.依赖仓库的版本(Dependencies versions)**：

- react：
- form-render：
- table-render: 
- antd：

**2.问题描述(Bug description)**：

如题；
代码位置：packages/form-render/src/index.d.ts:5

**3.最小复现 demo(Reproduction demo)**：

form-render demo https://codesandbox.io/s/unruffled-flower-jl78h
table-render demo https://codesandbox.io/s/sweet-euler-bdoty
fr-generator demo https://codesandbox.io/s/s13sh

**Comment by siyi98** [comment]
1.13.15-beta.5 补上了
