### ISSUE TITLE
表单设计器自定义组件dependencies联动

### ISSUE THREAD

**Issue by lfnealc** [alibaba/x-render#933]
<img width="536" alt="image" src="https://user-images.githubusercontent.com/16184492/194876222-c64dda50-4aac-4d97-9cd8-a930752f762d.png">

想问一下，在设计器的schema中想要使用自定义组件的联动功能，但是object类型的父组件id如果不修改getId()，id的后6位是随机生成的，在dependencies中如何能得到父组件的id。

如果修改了getId为name => ${name}，在设计器中相同的组件不能修改组件id。修改id后添加相同的组件id会被修改回去，相同的组件就只能保留一个。

form-render：1.13.14
fr-generator：2.8.0

**Comment by lhbxs** [comment]
老的设计器已经不在迭代了，有兴趣的话，可以关注一下讨论组，关于新设计器的迭代和进展，同时也欢迎在讨论里面提想法！
