### ISSUE TITLE
打包时报错 ./node_modules/antd/es/style/default.less

### ISSUE THREAD

**Issue by wx9999** [alibaba/x-render#935]
**1.依赖仓库的版本(Dependencies versions)**：

- react：17.0.0
- form-render：
- table-render: 
- antd：4.20.2
- fr-generator: 2.8.0
**2.问题描述(Bug description)**：
引用 import Generator from 'fr-generator'; 之后，项目打包失败。
 ./node_modules/antd/es/style/default.less
TypeError: this[MODULE_TYPE] is not a function
    at runMicrotasks (<anonymous>)
**3.最小复现 demo(Reproduction demo)**：

form-render demo https://codesandbox.io/s/unruffled-flower-jl78h
table-render demo https://codesandbox.io/s/sweet-euler-bdoty
fr-generator demo https://codesandbox.io/s/s13sh

**Comment by siyi98** [comment]
给个仓库地址
