### ISSUE TITLE
ExtendedWidget 去掉 areEqual之后 导致组件反复渲染

### ISSUE THREAD

**Issue by Jocelyn329** [alibaba/x-render#938]
今天更新了一下xrender 发现 form-render ExtendedWidget 里面  去掉了 areEqual的处理 导致页面上有些hook的监听（比如针对数组 或者对象的监听） 会进入死循环，针对这部分  为什么要注释掉呢

**Comment by siyi98** [comment]
那块的`areEqual`的处理逻辑写的不是很好，v1.13.18 版本加回来。

**Comment by siyi98** [comment]
form-render@1.13.18-beta.0
下周四发正式版

**Comment by Jocelyn329** [comment]
emmm 等待
