### ISSUE TITLE
【问卷】XRender 使用场景

### ISSUE THREAD

**Issue by FateRiddle** [alibaba/x-render#94]
<img src=https://qpluspicture.oss-cn-beijing.aliyuncs.com/Gto163/编组.png width=200/>

如果您和您的公司或组织使用了xRender ，非常感谢您的支持，欢迎留下公司或产品名，您的回复将成为维护者、社区用户和观望者的信心来源。

> 在不泄露信息的前提下，建议把截图晒一晒~
> 无关回复将会定期删除

推荐回复格式：

```
- 产品：
- 公司或组织：（如果可以）
- 链接：（如果可以）
- 截图：（如果可以）
```

**Comment by bingyingao** [comment]
- 产品：淘宝洋淘/躺平/闲鱼鱼塘
- 公司或组织：淘宝-社交平台-船坞投放后台
- 链接：（如果可以）
- 截图：（如果可以）

**Comment by philousWen** [comment]
- 产品：页匠
- 公司或组织：飞猪-营销-搭建投放系统

**Comment by byc233518** [comment]
- 产品：精工云MES
- 公司或组织：广东精工智能系统有限公司
- 链接：https://gd.jgyun.cn/login

**Comment by chenxiaolei** [comment]
产品：工作流表单设计器
公司或组织：中国铁塔
产品图片：
![工作流](https://user-images.githubusercontent.com/7622085/83861834-afb1a300-a753-11ea-9633-be4e66ec3a42.png)
![工作流2](https://user-images.githubusercontent.com/7622085/83862020-f7d0c580-a753-11ea-9695-5e29a2dfeee6.png)
![工作流3](https://user-images.githubusercontent.com/7622085/83862028-f99a8900-a753-11ea-92a4-ea1954baf4c6.png)

**Comment by YiuTerran** [comment]
我们有个项目在选型中，贵司的formily和formRender是两个团队的作品么？为啥没有合力一处，而在重复造轮子？

**Comment by tw93** [comment]
@YiuTerran 
> https://juejin.im/post/5ed7c39cf265da76ee1f5727   
> form-render 是 2 年多前，贴合飞猪运营平台场景，沉淀出的一套表单解决方案，和 formily 算是相对独立，各自有各自的场景。最近我们也和 formily 团队在包括协议和编辑器上进行共建。未来有望提供方便的转换函数，实现两侧协议的互通。schema 编辑器与集团合作，打算实现统一的 schema 生产工具。

**Comment by zhousufa** [comment]
- 产品：数政搭投平台
- 公司或组织：数字政务中台

- 截图：
![image](https://user-images.githubusercontent.com/3891137/83990913-bae81700-a97d-11ea-92b4-bd75387c3a8a.png)

**Comment by tw93** [comment]
![image](https://user-images.githubusercontent.com/8736212/85942342-2b6dcc80-b95b-11ea-942d-cdb3d394cae6.png)

**Comment by Aaron52077** [comment]
> * 产品：数据可视化datav-pro
> * 公司或组织：可视化项目大屏
> * 链接：https://wuli-admin.gitee.io/react-wuli-admin/#/dashboard

**Comment by pkaq** [comment]
> > * 产品：数据可视化datav-pro
> > * 公司或组织：可视化项目大屏
> > * 链接：https://wuli-admin.gitee.io/react-wuli-admin/#/dashboard
> 
> ![QQ图片20201214103222](https://user-images.githubusercontent.com/20987715/102034022-f44f8280-3df7-11eb-9e31-721332917614.png)
> ![QQ图片20201214103303](https://user-images.githubusercontent.com/20987715/102034025-f6b1dc80-3df7-11eb-9d99-3fd32a5cc017.png)

开源吗 兄弟

**Comment by PathFun** [comment]
产品：showData
公司或组织：自己
链接：http://withwide.com/bigScreen/index.html
![Uploading image.png…]()

**Comment by aqqwiyth** [comment]
目前钉钉的宜搭是基于form-render么

**Comment by Turkyden** [comment]
产品：watermark-pro
简介：最安全，最快速的纯前端图片加水印，拒绝上传保证个人信息安全。
公司或组织：自己
链接：https://github.com/Turkyden/watermark-pro

[: : : Live Demo : : :](https://watermark-pro.vercel.app/)

![image](https://user-images.githubusercontent.com/24560160/116022944-cae41480-a67d-11eb-89f6-8ca76670e0ad.png)

**Comment by lx544690189** [comment]
产品：H5可视化搭建平台
链接：
- GitHub：https://github.com/lx544690189/scorpio-h5-design
- 演示地址：https://scorpio-design.lxzyl.cn
![demot](https://www.hualigs.cn/image/608a855abb8ff.jpg)

**Comment by shanxiaohan** [comment]
#### 产品：Pickup Editor
#### 公司或组织：蚂蚁金服
####  截图
<img width="919" alt="BE7DA2A5-AFFD-45F9-A568-68E59F17709E" src="https://user-images.githubusercontent.com/11870702/117633114-4f6f8080-b1b0-11eb-9d7e-66f57ed33f97.png">

**Comment by Aaron52077** [comment]
> > > * 产品：数据可视化datav-pro
> > > * 公司或组织：可视化项目大屏
> > > * 链接：https://wuli-admin.gitee.io/react-wuli-admin/#/dashboard
> > 
> > 
> > ![QQ图片20201214103222](https://user-images.githubusercontent.com/20987715/102034022-f44f8280-3df7-11eb-9e31-721332917614.png)
> > ![QQ图片20201214103303](https://user-images.githubusercontent.com/20987715/102034025-f6b1dc80-3df7-11eb-9d99-3fd32a5cc017.png)
> 
> 开源吗 兄弟

> > > * 链接：https://github.com/Aaron52077/react-visual-data 开源拉~

**Comment by killdada** [comment]
- 产品： 内部erp表单 (基于公司内部已有的erp表单业务进行重构 )
- 链接 https://github.com/killdada/you-can-form-render

![image](https://user-images.githubusercontent.com/16487810/129175640-e57683bf-6923-4c11-9bd0-603639123b79.png)
![image](https://user-images.githubusercontent.com/16487810/129175801-248e7e21-9c21-4531-a31d-d609d51552e1.png)


[demo](http://ycid-form-render.yenmysoft.com.cn/#/demo)

**Comment by hand-dot** [comment]
您好，
XRender是一个非常出色的库，非常感谢你们的辛勤工作。

我正在一个开源PDF创建库的wysiwyg编辑器中使用它，所以我想分享一下。

- 产品：pdfme
- 公司或组织（如果可能）：pdfme
- 链接（如果可能）：
  - GitHub Repo：https://github.com/pdfme/pdfme
  - Demo：https://pdfme.com/template-design
- 截图（如果可能）：
![CleanShot 2024-01-03 at 16 58 33@2x](https://github.com/alibaba/x-render/assets/24843808/82a8c956-f2f5-4290-bfe1-7309d3406798)

---

translated by ChatGPT
