### ISSUE TITLE
select 支持空状态

### ISSUE THREAD

**Issue by shaodahong** [alibaba/x-render#943]
如果 value 这里不填的话再次进来这个全部选项会消失，想要支持 `{label: '全部', value: ''}` 的选项

<img width="924" alt="image" src="https://user-images.githubusercontent.com/14831261/196615896-a5a2a048-9c74-443e-8786-44d5347d5717.png">

**Comment by siyi98** [comment]
这种设计不合理吧...`全部`作为一个选项，应该有自己的枚举值吧

**Comment by shaodahong** [comment]
> 这种设计不合理吧...`全部`作为一个选项，应该有自己的枚举值吧

默认的枚举值机时候 `''`，但是我看 xrender 好像会重置掉

**Comment by lhbxs** [comment]
这种不适合做在x-render里面，太定制化了。业务上你可以通过给 select 的 option 增加一条。 例如：{ label: '全部', value: 'all'}
onFinish 的时候进行数据剔除
