### ISSUE TITLE
ErrorSchema 能否支持自定义

### ISSUE THREAD

**Issue by airsky0605** [alibaba/x-render#944]
### 期望的新功能 (describe the expected new feature)
ErrorSchema 自定义

### 简述一下使用场景，便于开发者更好理解新功能的必要性 (describe your scenario for us to understand the need)
现有的场景限定了ErrorSchema的展示，希望能支持自定义UI

**Comment by airsky0605** [comment]
![image](https://user-images.githubusercontent.com/41507410/196914767-6908c41e-7a17-4442-a7f2-d68efa7cdfb2.png)

**Comment by siyi98** [comment]
比如想展示成什么样子的呢

**Comment by airsky0605** [comment]
> 你的自定义 `ErrorSchema` 是什么样子的呢

比如 
 <div class="ErrorSchema">
      <div class="ErrorSchema-content">数据尚未同步</div>
    </div>

一个reactNode节点

**Comment by lhbxs** [comment]
我理解是不是在 widgets 里面传人一个ErrorSchema 自定义渲染组件，然后异常的时候我们渲染这个组件就OK了。

**Comment by lhbxs** [comment]
1.14.9-beta.1, 传一个errorSchemaWidget组件






if (!widgetName) {
    const CustomErrorSchema = widgets['errorSchemaWidget'];
    if (CustomErrorSchema) {
      return <CustomErrorSchema schema={schema} />;
    }
    widgetName = 'input';
    return <ErrorSchema schema={schema} />;
  }
