### ISSUE TITLE
tableList里的元素，schema加了default属性，tableList默认带出来一条 是正常的吗

### ISSUE THREAD

**Issue by Jocelyn329** [alibaba/x-render#947]

**Comment by siyi98** [comment]
设置了默认值，肯定会有数据的呀

**Comment by Jocelyn329** [comment]
> 设置了默认值，肯定会有数据的呀

我们目前基于你们代码的基础上做了二次封装，希望呈现的效果是 
初始化的时候 带出来的是子表的默认值（一个对象数组）， 可能有多条；
点击新增的时候  新增的这一条 带出来的是子表内相应的表单设置的默认值；
请问我们需要做怎样的调整才能符合这种需求呢？
emm  不知道我这样说 你们可否明白

**Comment by Jocelyn329** [comment]
> > 设置了默认值，肯定会有数据的呀
> 
> 我说的子表 就是 table的概念

**Comment by lhbxs** [comment]
尝试下2.x，2.x 支持此功能
