### ISSUE TITLE
fr-generator 的依赖randombytes在Chrome和Firefox都报错

### ISSUE THREAD

**Issue by ilovelll** [alibaba/x-render#948]
**1.依赖仓库的版本(Dependencies versions)**：

- react：18.2
- form-render：1.13.16
- fr-generator:  2.8.2
- antd：4.23.6

**2.问题描述(Bug description)**：
fr-generator 的依赖randombytes有一个子依赖safe-buffer报错，
`Module "buffer" has been externalized for browser compatibility. Cannot access "buffer.Buffer" in client code.`

**3.最小复现 demo(Reproduction demo)**：

**Comment by siyi98** [comment]
v2.8.3
