### ISSUE TITLE
请问下ExtendedWidget的memo，后续版本会加回来吗

### ISSUE THREAD

**Issue by QiaoQt** [alibaba/x-render#953]
![image](https://user-images.githubusercontent.com/63537017/199442250-01b008ee-5ee9-4185-9932-2f931a86aceb.png)

**Comment by siyi98** [comment]
现在遇到什么问题了吗

**Comment by QiaoQt** [comment]
是的，我们在项目里升级了新的版本，发现去掉memo之后，很多表单页有卡死的情况。

**Comment by QiaoQt** [comment]
> 现在遇到什么问题了吗


是的，我们在项目里升级了新的版本，发现去掉memo之后，很多表单页有卡死的情况。

**Comment by siyi98** [comment]
最新版本已经有了
