### ISSUE TITLE
form-render 子组件的onChange事件导致表单内其他组件重新渲染

### ISSUE THREAD

**Issue by StrongerD** [alibaba/x-render#962]
**1.依赖仓库的版本(Dependencies versions)**：

- react：17.x
- form-render：1.9.2
- antd：4.18.7

**2.问题描述(Bug description)**：
form render中的子组件触发onChange事件，会导致其他表单组件重新渲染，在表单中存在大量组件的情况下（比如表单存在50+以上的组件），在连续快速输入的情况下，性能会出现问题cpu 直接吃满，在windows等性能差的电脑，会出现明显的卡顿。同时在表单初始化渲染的时候，子组件会重复渲染三次，onChange事件触发也会造成同样的问题，强烈要求针对form单个组件进行重新渲染。不要无脑去修改覆盖 data.current

**3.最小复现 demo(Reproduction demo)**：

form-render demo https://codesandbox.io/s/unruffled-flower-jl78h

**Comment by siyi98** [comment]
内部已经在升级了，大概年后会发一个性能优化的版本，可以等一等。

**Comment by StrongerD** [comment]
> 内部已经在针对性能问题进行升级改造了，大概年后会发一个性能优化的版本，可以等一等。

预计在什么时候 可以发布这个优化的版本呢
