### ISSUE TITLE
提供api接口，可以不通过formRender组件渲染就可以判断当前数据是否合法

### ISSUE THREAD

**Issue by wangxinyu666666** [alibaba/x-render#963]
### 期望的新功能 (describe the expected new feature)
提供api接口，可以不通过formRender组件UI渲染就可以判断当前数据是否合法
### 简述一下使用场景，便于开发者更好理解新功能的必要性 (describe your scenario for us to understand the need)
const schema = {
  "type": "object",
  "properties": {
    "input": {
      "title": "简单输入框",
      "type": "string",
      "min": 6,
      "rules": [
        {
          "pattern": "^[A-Za-z0-9]+$",
          "message": "只允许填写英文字母和数字"
        }
      ]
    },
    "select": {
      "title": "单选",
      "type": "string",
      "enum": [
        "a",
        "b",
        "c"
      ],
      "enumNames": [
        "选项1",
        "选项2",
        "选项3"
      ],
      "widget": "radio"
    }
  }
}

比如现在有个JSON：
const data = {
	"input": "用户输入",
	"select": "a"
}

能否提供一个api，不用UI渲染，就可以直接看data是否符合schema~

**Comment by siyi98** [comment]
这个在业务侧自己写一个就好了，没必要让form-render导出这个吧。

**Comment by wangxinyu666666** [comment]
> 这个在业务侧自己写一个就好了，没必要让form-render导出这个吧。

业务里的schema很复杂并且不确定，required和hidden字段之类的都有函数表达式，字段嵌套比较深，校验起来比较复杂，所以就想问一下formrender有没有现成的

**Comment by siyi98** [comment]
建议业务侧自行处理~
