### ISSUE TITLE
版本1.14.0版本 样式错乱

### ISSUE THREAD

**Issue by 21haoxingxiu** [alibaba/x-render#967]
**1.依赖仓库的版本(Dependencies versions)**：

- react：
- form-render：
- table-render: 
- antd：

**2.问题描述(Bug description)**：
table-render 依赖 form-render  1.x 版本 升级后 表单样式错乱

**3.最小复现 demo(Reproduction demo)**：

form-render demo https://codesandbox.io/s/unruffled-flower-jl78h
table-render demo https://codesandbox.io/s/sweet-euler-bdoty
fr-generator demo https://codesandbox.io/s/s13sh

**Comment by siyi98** [comment]
解法：form-render 的 latest 版本已经回到 1.13.7，删掉 node_modules 重新安装依赖 即可修复。
