### ISSUE TITLE
watch在onMount前和onMount时各触发了一次

### ISSUE THREAD

**Issue by vision-ken** [alibaba/x-render#969]
**1.依赖仓库的版本(Dependencies versions)**：

    "react": ">=16.8.0",
    "form-render": "1.14.2",
    "antd": "4.x",
    "react-dom": ">=16.8.0"

**2.问题描述(Bug description)**：

表单值formData来自后端，在onMount通过form.setValues(formData)设置表单初始值，并且实时监听表单的值。

但是watch在onMount前和onMount时各触发了一次。如下图
<img width="1671" alt="image" src="https://user-images.githubusercontent.com/24715266/203696912-e5d0b6f4-d36c-449d-be14-332e2b0417ed.png">

期望结果：watch在onMount前和onMount时都不应该触发，onMount后如果字段值发生变更时才需要触发watch事件。

**最小复现 demo(Reproduction demo)**：
https://codesandbox.io/s/damp-star-mdvgre

**Comment by lhbxs** [comment]
欢迎尝试升级 2.x，2.x 不会有此类的问题。
