### ISSUE TITLE
debug 错误调试模式，表单数据信息能否在log中体现

### ISSUE THREAD

**Issue by 21haoxingxiu** [alibaba/x-render#972]
### 期望的新功能 (describe the expected new feature)
json和表单在同一个页面，json变化导致页面跳动，不好操作，而且页面很长 无法展示完整页面
### 简述一下使用场景，便于开发者更好理解新功能的必要性 (describe your scenario for us to understand the need)
![image](https://user-images.githubusercontent.com/20453074/204425797-ba2de1db-503e-48f4-a2aa-cc11ae2b5e2a.png)

**Comment by siyi98** [comment]
可以加参数控制一下，有兴趣来个PR吗？

**Comment by Jesslynwong** [comment]
> 可以加参数控制一下，有兴趣来个PR吗？

我尝试添加参数，coonsole.log出结果，但添加修改后的代码不奏效
【主要做法】利用yalc发布至本地，项目中引入该库
【尝试解决如下】
    1. 排除包更新问题。检查过项目中的lib 和 es都被替换成了最新的修改后的代码
    2. 排除编译器缓存。项目以及项目编译器关掉重新开启，都不奏效
    3. 排除文件运行问题。 项目中的 'pre' '_debug_from_' 参数只有一处使用。我直接在那个文件中修改参数为'pr'，还是不奏效。
【求助】
还会是什么原因呢？

**Comment by lhbxs** [comment]
默认在控制台也同步打印出来了。1.14.10-beta.1
