### ISSUE TITLE
hidden字段的引发的联动 如何实现呢？

### ISSUE THREAD

**Issue by Jocelyn329** [alibaba/x-render#975]
hidden字段的引发的联动 如何实现呢？

场景：
A字段 影响 B隐藏字段，
 B隐藏字段 影响 C字段

在B中写了方法监听变化 改变C 但是B被hidden了  导致Dom不在 代码不会执行

所以我目前将下面两个地方做了调整  目测是可以了 但这是否会有什么别的影响呢  之前你们是基于什么做的调整？

![image](https://user-images.githubusercontent.com/29472840/204519571-131e004c-6653-4397-b4c1-ebbbd9859458.png)
![image](https://user-images.githubusercontent.com/29472840/204680094-ad848ee1-d105-4d61-86d1-2f07805afa7b.png)

**Comment by lhbxs** [comment]
1.x 不在迭代新功能了，可以升级2.x 试试
