### ISSUE TITLE
希望fr-generator能支持下设置antd的prefixCls

### ISSUE THREAD

**Issue by BingruLin** [alibaba/x-render#977]
### 同学你好，我们这边也想把自己的schema2form升级成form-render。但我们的老工程是antd3的，为了能使用必须antd4的form-render，我们通过重命名antd4包；webpack loader和业务层改prefixCls的方式来兼容，现在form-render样式没问题了。

但是，我们在用fr-generator的时候发现，它不支持调用方设置prefixCls，导致表单生成器的样式还是用的antd3的，希望帮忙透传下prefixCls的值。

**Comment by BingruLin** [comment]
所以大哥们什么时候加下呢~

**Comment by siyi98** [comment]
@BingruLin  
- 版本：`fr-generator@2.8.5-beta.3`
- 用法：`<Generator configProvider={{prefixCls:''}} />`
