### ISSUE TITLE
form-render中数组设置为可折叠后无效

### ISSUE THREAD

**Issue by BingruLin** [alibaba/x-render#979]
<img width="1084" alt="image" src="https://user-images.githubusercontent.com/32869377/205540393-aaccaed8-d5d4-4ddd-badc-1e94da3903c9.png">

如图所示，给数组设置为可折叠后，在最终展示功能页调试发现数组没有展开和收缩按钮，看着感觉数组不具备展开和收缩能力。

<img width="1127" alt="image" src="https://user-images.githubusercontent.com/32869377/205540842-6afe2dc9-57de-49e0-8462-8cdbd7f74fa2.png">

**Comment by siyi98** [comment]
这个数组用的是 `simpleList` 组件，是不能折叠的，右侧配置不应该透出这个配置，我改下。

**Comment by BingruLin** [comment]
好的

**Comment by siyi98** [comment]
@BingruLin 
`fr-generator@2.8.5-beta.2`
