### ISSUE TITLE
为什么校验后input不变红色啊？正确输入后反而变红了

### ISSUE THREAD

**Issue by Hokkaii** [alibaba/x-render#980]
**1.依赖仓库的版本(Dependencies versions)**：

- react：17
- form-render：1.14.3
- table-render:
- antd：4

**2.问题描述(Bug description)**：

**3.最小复现 demo(Reproduction demo)**：

form-render demo https://codesandbox.io/s/unruffled-flower-jl78h
table-render demo https://codesandbox.io/s/sweet-euler-bdoty
fr-generator demo https://codesandbox.io/s/s13sh

**Comment by weissha** [comment]
我也发现了，排查一圈发现是这个库的问题，降级到低版本1.4.0也存在这个问题

**Comment by siyi98** [comment]
@Hokkaii 把你的Schema贴出来看看？我们这边没复现

**Comment by siyi98** [comment]
@Hokkaii @weissha 
感谢反馈！`form-render@1.14.6` 已修复

**Comment by Hokkaii** [comment]
> 我也发现了，排查一圈发现是这个库的问题，降级到低版本1.4.0也存在这个问题

我也是，差点给我整吐了

**Comment by Hokkaii** [comment]
> @Hokkaii @weissha 感谢反馈！`form-render@1.14.6` 已修复

感恩！
