### ISSUE TITLE
希望fr-generator能支持下多选组件的枚举可以调位置

### ISSUE THREAD

**Issue by BingruLin** [alibaba/x-render#982]
### 简述一下使用场景，便于开发者更好理解新功能的必要性 (describe your scenario for us to understand the need)
忠实粉丝又来提建议了。对于选项类组件，有时希望运营在使用过程中能先看到被选择频率高的选项在前，因此有个调整枚举位置的小需求，希望大佬们能考虑下

**Comment by siyi98** [comment]
截个图看看？

**Comment by lhbxs** [comment]
当前设计器不在迭代了，后面会推出新版设计器
