### ISSUE TITLE
1.14.3版本按文档demo启动有问题

### ISSUE THREAD

**Issue by sky-admin** [alibaba/x-render#983]
**1.依赖仓库的版本(Dependencies versions)**：

- react：18.2
- form-render：1.14.3
- table-render:无
- antd：4.x

**2.问题描述(Bug description)**：

用CRA生成一个项目，按官网文档 安装antd@4和最新的form-render后启动报错。
报错如下：
![image](https://user-images.githubusercontent.com/6292668/206107243-53d832a9-fac6-4390-95a0-bc2bbed9116d.png)

检查文件发现，在 es/index.js 里试图 export {connectForm} from './form-render-core/src'
但 form-render-core/src 中并未 export 出 connectForm（dts文件里倒是声明应该导出它来着）。

切换成1.14.2后发现有导出。

**3.最小复现 demo(Reproduction demo)**：

如描述。
更换成1.14.2后问题消失。

**Comment by siyi98** [comment]
form-render@1.14.4 版本已修复
