### ISSUE TITLE
有答疑微信群吗

### ISSUE THREAD

**Issue by 21haoxingxiu** [alibaba/x-render#985]
**1.依赖仓库的版本(Dependencies versions)**：

- react：
- form-render：
- table-render:
- antd：

**2.问题描述(Bug description)**：

我看之前的钉钉群号失效了， 可以在文档里贴下最新的二维码

**3.最小复现 demo(Reproduction demo)**：

form-render demo https://codesandbox.io/s/unruffled-flower-jl78h
table-render demo https://codesandbox.io/s/sweet-euler-bdoty
fr-generator demo https://codesandbox.io/s/s13sh

**Comment by siyi98** [comment]
有什么问题可以直接在 issue 中提问哦。
