### ISSUE TITLE
fr-generator的右侧“表单配置”版块的数据变化不会触发onSchemaChange

### ISSUE THREAD

**Issue by BingruLin** [alibaba/x-render#987]
**1.依赖仓库的版本(Dependencies versions)**：

- react：18.0.26
- form-render：2.8.4
- antd：4.24.4

**2.问题描述(Bug description)**：
fr-generator的右侧“表单配置”版块的数据变化不会触发onSchemaChange

**3.最小复现 demo(Reproduction demo)**：
<img width="1270" alt="image" src="https://user-images.githubusercontent.com/32869377/207497120-d8097464-7b5d-4744-a67f-a37a56bfb717.png">

例如整体布局：一行二列这个设置，改成一行三列后没有触发onSchemaChange

**Comment by HeiCodeBoy** [comment]
组件配置里面的**默认值**也**仅触发一次**，之后的修改不触发

**Comment by smile2014** [comment]
fr-generator 只开放使用对吧，没有源码

**Comment by lhbxs** [comment]
老的设计器已经不在迭代了，有兴趣的话，可以关注一下讨论组，关于新设计器的迭代和进展，同时也欢迎在讨论里面提想法！
