### ISSUE TITLE
允许 `hideLabel` schema 来隐藏form label

### ISSUE THREAD

**Issue by xiaohao9006** [alibaba/x-render#989]
### 期望的新功能 (describe the expected new feature)
我们的一些custom widget，会在widget里面显示`title` schema value，但是因为默认form render会用`title` schema value来显示form label，我们的custom widget就会出现两个重复的title。所以希望能有一个`hideLabel` schema能让我们把form render default的form label隐藏掉，但是`title` value依然存在。

我可以做个PR。

**Comment by lhbxs** [comment]
不是很明白，可以截下效果图同时把schema发出来看看

**Comment by lhbxs** [comment]
如果是单纯的输入控件，不要在组件里面去定义title。欢迎升级 2.x，2.x 的 formItem label 支持自定义函数
