### ISSUE TITLE
tableList 添加或删除 tableItem 时不会触发 validator

### ISSUE THREAD

**Issue by zibiaowu** [alibaba/x-render#991]
https://github.com/alibaba/x-render/blob/master/packages/form-render/src/form-render-core/src/core/RenderChildren/RenderList/index.js#L69

![image](https://user-images.githubusercontent.com/18088464/208037456-e189d498-84fe-4170-9ca7-cdfe0bbca872.png)

这个 TODO 有计划什么时候修复吗？或者现在有啥 workaround 可以解决？

简单点是不是允许传入一个 onDeleteItemCallback 就可以了？

**Comment by lhbxs** [comment]
欢迎尝试升级 2.x，2.x 不会有诸如此类的问题。
