### ISSUE TITLE
upload组件必填校验状态无法清除

### ISSUE THREAD

**Issue by HeiCodeBoy** [alibaba/x-render#994]
**1.依赖仓库的版本(Dependencies versions)**：

- react：17.0.1
- form-render：1.14.7
- antd：4.17.0

**2.问题描述(Bug description)**：
**问题1**：使用FormRender 提供的upload组件虽然可以上传，但是无法使用其他props。比如多选的参数multiple，headers等，使用“ui:options”也无效；

const schema = {
  type: 'object',
  properties: {
    upload_7vP75a: {
      title: '文件上传',
      type: 'string',
      format: 'upload'
      props: {
         action: '/upload',
         multiple: true
      },
      'ui:options':{
         multiple: true
      },
      required: true,
    }
  },
  labelWidth: 120,
  displayType: 'row'
};

**问题2**：使用自定义Upload组件，虽然能解决传参的问题，但是在必填条件下，无法重置表单状态，比如：删除附件后，点击提交form.validateFields().then((res) => {}) 方式，表单便不会再校验了，但是在render里面使用按钮的方式
<Button onClick={() => form.setValues({ upload_7vP75a: undefined })}>重置</Button> 进行重置，再点提交，校验功能便正常了

// 删除操作后，addons内的方法均未起到清空或重置的作用，但是通过按钮事件，form实例的setValues方法却是可以
const schema = {
  type: 'object',
  properties: {
    upload_7vP75a: {
      title: '文件上传',
      type: 'object',
      // format: 'upload',
      props: {},
      required: true,
      widget: 'uploadM'
    }
  },
  labelWidth: 120,
  displayType: 'row'
};

const uploadFile = (props) => {
  const onRemove = (file) => {
    let value = props.value;
    if (value) {
      let fileList = value.fileList.filter((v) => v.uid !== file.uid);
      if (fileList?.length === 0) {
      **// 以下addons方法均不能正常清空或者重置表单状态**
      //  props.addons.formData = {};
      //  props.addons.setValues({ upload_7vP75a: {} });
        // console.log('进入addons');
        // props.addons.removeErrorField(props.addons.dataPath);
        // props.addons.setValueByPath(props.addons.dataPath, undefined);
        // props.value = undefined;
      }
    }
  };

  const newProps = {
    action: `/upload`,
    headers: { Authorization: ‘123 || '' },
    multiple: true,
    onRemove: onRemove,
    ...props,
    fileList: props.value?.fileList
  };
  return (
    <Upload {...newProps}>
      <Button>上传</Button>
    </Upload>
  );
};

<FormRender form={form} schema={schema} debug widgets={{ uploadM: uploadFile }} />

**3.最小复现 demo(Reproduction demo)**：

form-render demo https://codesandbox.io/s/modest-gagarin-9qsc1n?file=/App.jsx

**Comment by lhbxs** [comment]
props.addons.setValues({ upload_7vP75a: '' });    或者是 props.onChange('');
