### ISSUE TITLE
请问有适配移动端的计划吗？

### ISSUE THREAD

**Issue by syguan95** [alibaba/x-render#995]
请问还有适配移动端的计划吗？之前看知乎上说计划2022年中旬完成2.0版本的开发，会支持移动端的antd-mobile。这个啥时候会发布呢？

**Comment by lhbxs** [comment]
暂时没有

**Comment by lhbxs** [comment]
目前在做 form-render 升级改造，升级之后会解决性能瓶颈等问题。后面才会去考虑 移动端场景的问题
