### ISSUE TITLE
form-render@2.0.0-rc.0ss

### ISSUE THREAD

**Issue by ponkans** [alibaba/x-render#996]
For [form-render@2.0.0-rc.0ss](mailto:form-render@2.0.0-rc.0ss) version：
 If the schema is set to default or form.setvalues, then the set form item will not work and will appear to have no updated state internally. For example: https://codesandbox.io/s/silly-feynman-fx6qsr

**Comment by lhbxs** [comment]
1.0 版本不再继续增加新功能，如果需要适配 antd V5 请升级 2.x 版本

**Comment by lhbxs** [comment]
New functions are no longer added in version 1.0. If antd V5 needs to be adapted, please upgrade to version 2.x
