### ISSUE TITLE
fr-generator 怎样自定义一个表格组件？

### ISSUE THREAD

**Issue by hongyu2016** [alibaba/x-render#997]
fr-generator 和form-item 里面的tableList 不符合使用要求，以及在fr-generator画布中无法禁止拖入相同的表格组件。
1：请问怎样完全自定义一个表格组件呢？
2：自定义的表格组件中如何做到不能再拖入这个相同的表格组件呢？

**Comment by lhbxs** [comment]
老的设计器已经不在迭代了，有兴趣的话，可以关注一下讨论组，关于新设计器的迭代和进展，同时也欢迎在讨论里面提想法！
