### ISSUE TITLE
CardList 的 上移，下移，复制，新增，删除 操作都不会触发 form 的 onValuesChange 方法

### ISSUE THREAD

**Issue by Dearest** [alibaba/x-render#998]
**1.依赖仓库的版本(Dependencies versions)**：

- react：17.0.2
- form-render：1.14.7
- table-render:
- antd：^4.24.4

**2.问题描述(Bug description)**：

CardList 的 上移，下移，复制，新增，删除 操作都不会触发 form 的 onValuesChange 方法

**3.最小复现 demo(Reproduction demo)**：

**Comment by lhbxs** [comment]
请使用 watch 监听
const watch = {
    '#': (data,) => {
    
    },
    'listName': (data) => {
      
    }
  }
